import type { ManagementProtocol } from '../types.js';

export const endocrineProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'thyroid_nodule_benign',
    icd10Prefixes: ['D34'],
    label: 'Benign Thyroid Nodule',
    keyPoints: [
      'Most thyroid nodules are benign; risk of malignancy ~5–15% in solitary nodules — ultrasound and FNAC are gold standard.',
      'TIRADS score guides FNAC indication; nodules <1 cm with benign features may be observed.',
      'TSH suppression with levothyroxine is no longer recommended routinely.',
    ],
    redFlags: [
      'Rapid growth or fixation to surrounding structures',
      'Hoarseness, dysphagia, or stridor suggesting recurrent laryngeal nerve involvement',
      'Hard, irregular nodule with cervical lymphadenopathy',
      'FNAC result: suspicious or malignant (Bethesda IV–VI)',
    ],
    investigations: [
      { label: 'Thyroid function tests (TSH, fT4)', urgency: 'routine' },
      { label: 'Neck ultrasound with TIRADS scoring', urgency: 'routine' },
      { label: 'FNAC if TIRADS ≥3 or nodule ≥1 cm', urgency: 'routine' },
      { label: 'Calcium, PTH (if parathyroid pathology suspected)', urgency: 'routine' },
      { label: 'Vocal cord assessment (indirect laryngoscopy) if hoarse', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Ensure euthyroid state; no treatment required for benign FNAC (Bethesda II).' },
      { phase: 'conservative', step: 'Surveillance ultrasound at 12 months; repeat FNAC only if significant growth (>20% in two dimensions).' },
      { phase: 'conservative', step: 'Counsel patient regarding benign nature; advise return if new symptoms develop.' },
      { phase: 'surgical', step: 'Hemithyroidectomy if nodule >4 cm, compressive symptoms, or patient preference despite benign FNAC.' },
      { phase: 'followup', step: 'Annual TSH post-operatively; thyroid hormone replacement if total thyroidectomy performed.' },
    ],
    referral: 'Endocrinology or Endocrine Surgery for TIRADS ≥4, FNAC Bethesda III–VI, or compressive symptoms.',
  },

  {
    diseaseId: 'thyroid_carcinoma',
    icd10Prefixes: ['C73'],
    label: 'Thyroid Carcinoma',
    keyPoints: [
      'Papillary thyroid carcinoma is the most common type (~80%); generally excellent prognosis with 10-year survival >95% for low-risk disease.',
      'FNAC Bethesda V–VI confirms malignancy; molecular markers (BRAF, RAS) may aid indeterminate cases.',
      'Total thyroidectomy ± central neck dissection is standard; radioiodine ablation reserved for intermediate/high-risk disease.',
    ],
    redFlags: [
      'Locally invasive tumour causing stridor, dysphagia, or haemoptysis',
      'Rapidly enlarging neck mass with systemic symptoms',
      'Medullary carcinoma — check serum calcitonin and CEA; exclude MEN2',
      'Haemodynamic compromise from large tumour burden',
    ],
    investigations: [
      { label: 'TSH, fT4, fT3', urgency: 'routine' },
      { label: 'Serum calcitonin, CEA (if medullary suspected)', urgency: 'urgent' },
      { label: 'Neck ultrasound with lymph node mapping', urgency: 'urgent' },
      { label: 'FNAC of primary nodule and suspicious lymph nodes', urgency: 'urgent' },
      { label: 'CT neck/chest (staging — if locally advanced or suspicious nodes)', urgency: 'urgent' },
      { label: 'RET proto-oncogene mutation (if medullary carcinoma)', urgency: 'routine' },
      { label: 'Calcium, PTH (pre-operative baseline)', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Confirm diagnosis with FNAC; stage with ultrasound and CT if locally advanced.' },
      { phase: 'surgical', step: 'Total thyroidectomy ± central compartment neck dissection (level VI) for papillary/follicular carcinoma.' },
      { phase: 'surgical', step: 'Lateral neck dissection (levels II–V) if lateral node involvement confirmed.' },
      { phase: 'conservative', step: 'Radioiodine (I-131) ablation for intermediate/high-risk differentiated thyroid cancer post-operatively.' },
      { phase: 'conservative', step: 'TSH suppression with levothyroxine (target TSH <0.1 mU/L for high-risk; 0.1–0.5 for low-risk).' },
      { phase: 'followup', step: 'Thyroglobulin and anti-thyroglobulin antibodies at 6–12 months post-ablation; neck ultrasound annually.' },
      { phase: 'followup', step: 'Refer for targeted therapy (lenvatinib, sorafenib) if radioiodine-refractory.' },
    ],
    referral: 'Urgent Endocrine Surgery; MDT involving Oncology and Nuclear Medicine for high-risk or advanced disease.',
  },

  {
    diseaseId: 'hyperthyroidism',
    icd10Prefixes: ['E05'],
    label: 'Hyperthyroidism',
    keyPoints: [
      'Graves\' disease accounts for ~70–80% of cases; TSH receptor antibodies (TRAb) are diagnostic.',
      'Toxic multinodular goitre and toxic adenoma are common in iodine-deficient regions.',
      'Thyroid storm is a medical emergency: HR >140, hyperpyrexia, altered sensorium — treat with propranolol, PTU, iodine, and dexamethasone.',
    ],
    redFlags: [
      'Thyroid storm: hyperpyrexia >38.5 °C, HR >140, agitation, vomiting — immediate ICU transfer',
      'New-onset atrial fibrillation or heart failure',
      'Severe ophthalmopathy with corneal exposure or optic nerve compression',
      'Haemodynamic instability',
    ],
    investigations: [
      { label: 'TSH (suppressed), fT4, fT3', urgency: 'urgent' },
      { label: 'TRAb (TSH receptor antibodies)', urgency: 'routine' },
      { label: 'Thyroid peroxidase antibodies (TPO Ab)', urgency: 'routine' },
      { label: 'Thyroid ultrasound ± Doppler (increased flow in Graves\')', urgency: 'routine' },
      { label: 'Technetium-99m thyroid scan (if toxic nodule/TMNG suspected)', urgency: 'routine' },
      { label: 'FBC, LFTs (baseline before antithyroid drugs)', urgency: 'routine' },
      { label: 'ECG (exclude AF)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Symptom control with propranolol 40 mg TDS (or atenolol) for tremor and palpitations.' },
      { phase: 'conservative', step: 'Antithyroid drugs: carbimazole 20–40 mg/day or propylthiouracil 300–400 mg/day; titrate to TFTs.' },
      { phase: 'conservative', step: 'Titration or block-and-replace regimen over 12–18 months for Graves\' disease.' },
      { phase: 'conservative', step: 'Radioiodine I-131 ablation if antithyroid drugs fail, patient declines surgery, or toxic nodule.' },
      { phase: 'surgical', step: 'Total thyroidectomy for large goitre, compression, ophthalmopathy, or patient preference.' },
      { phase: 'followup', step: 'Monitor TFTs 6-weekly until euthyroid; then 3-monthly; lifelong thyroid replacement post-ablation/surgery.' },
    ],
    referral: 'Endocrinology for management; Endocrine Surgery if thyroidectomy planned; Ophthalmology if Graves\' orbitopathy present.',
  },

  {
    diseaseId: 'hashimoto_thyroiditis',
    icd10Prefixes: ['E06.3'],
    label: 'Hashimoto Thyroiditis',
    keyPoints: [
      'Most common cause of hypothyroidism in iodine-sufficient regions; TPO antibodies positive in >95%.',
      'May present with transient hyperthyroidism (hashitoxicosis) early in disease course.',
      'Small increased risk of thyroid lymphoma — new rapid enlargement warrants urgent evaluation.',
    ],
    redFlags: [
      'Rapid goitre growth suggesting lymphoma or carcinoma',
      'Myxoedema coma: hypothermia, bradycardia, altered consciousness — immediate admission',
      'Airway compromise from large goitre',
    ],
    investigations: [
      { label: 'TSH, fT4', urgency: 'routine' },
      { label: 'TPO antibodies, thyroglobulin antibodies', urgency: 'routine' },
      { label: 'Thyroid ultrasound (heterogeneous echotexture)', urgency: 'routine' },
      { label: 'FBC (exclude anaemia)', urgency: 'routine' },
      { label: 'Lipid profile (hypothyroidism elevates LDL)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Levothyroxine when TSH >10 mU/L or TSH 4–10 mU/L with symptoms; start 25–50 mcg/day.' },
      { phase: 'conservative', step: 'Titrate levothyroxine to maintain TSH 0.5–2.5 mU/L; recheck TFTs 6–8 weeks after dose change.' },
      { phase: 'conservative', step: 'No specific treatment needed if euthyroid — monitor annually.' },
      { phase: 'followup', step: 'Annual TFTs and clinical review; monitor for progression to hypothyroidism.' },
    ],
    referral: 'Endocrinology if difficulty achieving euthyroid state; Endocrine Surgery if compressive goitre or rapid enlargement.',
  },

  {
    diseaseId: 'primary_hyperparathyroidism',
    icd10Prefixes: ['E21.0'],
    label: 'Primary Hyperparathyroidism',
    keyPoints: [
      'Most commonly caused by single parathyroid adenoma (~85%); presents with hypercalcaemia, often incidentally discovered.',
      'Classic mnemonic "bones, stones, groans, psychic moans": osteoporosis, renal stones, constipation, depression/fatigue.',
      'Surgical cure rate >95% with minimally invasive parathyroidectomy guided by pre-operative localisation.',
    ],
    redFlags: [
      'Severe hypercalcaemia (>3.5 mmol/L): polyuria, polydipsia, confusion, cardiac arrhythmia',
      'Hypercalcaemic crisis: nausea, vomiting, obtundation — IV saline and bisphosphonates urgently',
      'Nephrolithiasis with acute renal impairment',
    ],
    investigations: [
      { label: 'Serum calcium (adjusted/ionised), phosphate, albumin', urgency: 'urgent' },
      { label: 'Intact PTH', urgency: 'urgent' },
      { label: 'Renal function, eGFR', urgency: 'urgent' },
      { label: '24-hour urinary calcium excretion (exclude FHH)', urgency: 'routine' },
      { label: 'Sestamibi parathyroid scan + neck ultrasound for localisation', urgency: 'routine' },
      { label: 'DEXA bone mineral density (osteoporosis assessment)', urgency: 'routine' },
      { label: 'Renal ultrasound (nephrolithiasis)', urgency: 'routine' },
      { label: 'Vitamin D 25-OH level', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'IV 0.9% saline 200–300 mL/hr if hypercalcaemia >3.0 mmol/L; furosemide after adequate rehydration.' },
      { phase: 'conservative', step: 'Bisphosphonates (zoledronic acid 4 mg IV) for acute hypercalcaemia >3.5 mmol/L or symptoms.' },
      { phase: 'conservative', step: 'Ensure adequate hydration; avoid thiazide diuretics and calcium supplements.' },
      { phase: 'surgical', step: 'Minimally invasive parathyroidectomy (MIP) with intra-operative PTH monitoring is definitive treatment.' },
      { phase: 'surgical', step: 'Bilateral neck exploration if localisation fails or multiglandular disease suspected (MEN1/MEN2A).' },
      { phase: 'followup', step: 'Post-operative calcium and PTH at 24 h; monitor for hungry bone syndrome in severe disease.' },
      { phase: 'followup', step: 'Annual calcium, creatinine, DEXA if managed conservatively (asymptomatic mild disease).' },
    ],
    referral: 'Endocrine Surgery for parathyroidectomy; Endocrinology for ongoing medical management; Nephrology if renal calculi.',
  },

  {
    diseaseId: 'parathyroid_adenoma',
    icd10Prefixes: ['D35.1'],
    label: 'Parathyroid Adenoma',
    keyPoints: [
      'Single adenoma accounts for 85% of primary hyperparathyroidism; multiglandular disease in MEN syndromes.',
      'Pre-operative localisation with sestamibi scan and ultrasound guides minimally invasive approach.',
      'Intra-operative PTH drop >50% from pre-excision baseline confirms adequate resection.',
    ],
    redFlags: [
      'Hypercalcaemia >3.5 mmol/L with symptoms',
      'Associated MEN1 or MEN2A syndrome — screen family members',
      'Parathyroid carcinoma (hard mass, very high PTH, calcium >3.5 mmol/L)',
    ],
    investigations: [
      { label: 'Serum calcium (adjusted), PTH', urgency: 'urgent' },
      { label: 'Sestamibi (Tc-99m) parathyroid scan', urgency: 'routine' },
      { label: 'Neck ultrasound (complementary localisation)', urgency: 'routine' },
      { label: '4D-CT neck (if sestamibi negative or multiglandular disease)', urgency: 'routine' },
      { label: 'MEN1 gene mutation testing if family history', urgency: 'routine' },
      { label: 'Intra-operative PTH assay (sent during surgery)', urgency: 'stat' },
    ],
    management: [
      { phase: 'surgical', step: 'Minimally invasive parathyroidectomy under general anaesthesia with real-time PTH monitoring.' },
      { phase: 'surgical', step: 'Convert to four-gland exploration if PTH fails to drop >50% within 10 minutes post-excision.' },
      { phase: 'followup', step: 'Calcium and PTH at 24 hours; supplement calcium/vitamin D for 2–4 weeks post-operatively.' },
      { phase: 'followup', step: 'Annual calcium measurement; re-evaluate if hypercalcaemia recurs (persistent/recurrent disease).' },
    ],
    referral: 'Endocrine Surgery; Endocrinology for MEN syndrome workup if multiglandular disease found.',
  },

  {
    diseaseId: 'adrenal_incidentaloma',
    icd10Prefixes: ['D44.1'],
    label: 'Adrenal Incidentaloma',
    keyPoints: [
      'Found in ~4% of abdominal CT scans; majority are non-functioning cortical adenomas.',
      'Biochemical screen for hormonal excess (phaeochromocytoma, Cushing\'s, Conn\'s) is mandatory before surgery.',
      'CT attenuation <10 HU and washout >60% strongly suggests benign lipid-rich adenoma.',
    ],
    redFlags: [
      'Phaeochromocytoma features: hypertensive crisis, palpitations, diaphoresis — alpha-blockade before any intervention',
      'CT features of malignancy: size >4 cm, irregular borders, heterogeneous, HU >10',
      'Rapid size growth on surveillance imaging',
    ],
    investigations: [
      { label: 'Overnight 1 mg dexamethasone suppression test (Cushing\'s screen)', urgency: 'routine' },
      { label: '24-hour urinary catecholamines / plasma metanephrines (phaeochromocytoma)', urgency: 'routine' },
      { label: 'Aldosterone:renin ratio (if hypertensive — Conn\'s syndrome)', urgency: 'routine' },
      { label: 'Adrenal CT protocol with washout (10 min delayed enhancement)', urgency: 'routine' },
      { label: 'MRI adrenal (if indeterminate on CT)', urgency: 'routine' },
      { label: 'FDG-PET (if malignancy strongly suspected)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Biochemical evaluation completed before any surgical decision.' },
      { phase: 'conservative', step: 'Non-functioning adenoma <4 cm with benign CT features: surveillance CT at 6–12 months; repeat biochemistry annually for 4 years.' },
      { phase: 'surgical', step: 'Laparoscopic adrenalectomy for: phaeochromocytoma, Conn\'s adenoma, Cushing\'s adenoma, or size >4 cm / growth >1 cm/year.' },
      { phase: 'surgical', step: 'Pre-operative alpha-blockade (phenoxybenzamine 10 mg BD, titrate up) for 2 weeks minimum before phaeochromocytoma surgery.' },
      { phase: 'followup', step: 'Post-adrenalectomy cortisol replacement if contralateral suppression; taper over months.' },
    ],
    referral: 'Endocrinology for biochemical workup; Endocrine Surgery for resection; Oncology if adrenocortical carcinoma suspected.',
  },

  {
    diseaseId: 'neck_lymphadenopathy',
    icd10Prefixes: ['R59.9'],
    label: 'Neck Lymphadenopathy',
    keyPoints: [
      'Most cervical lymphadenopathy is reactive (viral/bacterial); persistent nodes >6 weeks without infectious cause require further evaluation.',
      'Hard, fixed, non-tender nodes in a patient >40 years with smoking/alcohol history — consider squamous cell carcinoma until proven otherwise.',
      'Level I–II nodes often from oropharyngeal primaries; level III–IV from hypopharynx/larynx; level V from nasopharynx; supraclavicular from thoracic/abdominal malignancy.',
    ],
    redFlags: [
      'Node >2 cm, hard, fixed, or with skin involvement',
      'Systemic B symptoms: drenching night sweats, unexplained fever, >10% weight loss in 6 months (lymphoma)',
      'Supraclavicular node (Virchow\'s) — strong association with thoracic/abdominal malignancy',
      'Rapid growth over days (abscess) or progressive growth over weeks without infection',
    ],
    investigations: [
      { label: 'FBC, ESR, CRP, LDH', urgency: 'urgent' },
      { label: 'Monospot test / EBV serology (if young patient)', urgency: 'routine' },
      { label: 'Chest X-ray (hilar adenopathy, TB, lymphoma)', urgency: 'urgent' },
      { label: 'Neck ultrasound with Doppler', urgency: 'urgent' },
      { label: 'CT neck/chest/abdomen/pelvis if malignancy suspected', urgency: 'urgent' },
      { label: 'FNAC of the largest/most accessible node', urgency: 'urgent' },
      { label: 'Excision biopsy if FNAC non-diagnostic and malignancy remains suspected', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'If infectious cause (tender, fluctuant, fever): antibiotics (amoxicillin-clavulanate); incision and drainage if abscess.' },
      { phase: 'conservative', step: 'Reactive lymphadenopathy: watchful waiting 4–6 weeks with review; treat underlying infection.' },
      { phase: 'conservative', step: 'If no resolution at 6 weeks or malignancy suspected: urgent FNAC and imaging.' },
      { phase: 'surgical', step: 'Excision biopsy under GA for definitive histology if FNAC inconclusive.' },
      { phase: 'followup', step: 'Oncology MDT referral for lymphoma or metastatic disease; ENT for head and neck primary.' },
    ],
    referral: 'ENT/Head and Neck Surgery if primary malignancy suspected; Haematology/Oncology for lymphoma; ID if TB or atypical mycobacteria.',
  },

  {
    diseaseId: 'salivary_gland_mass',
    icd10Prefixes: ['D11.9'],
    label: 'Salivary Gland Mass',
    keyPoints: [
      'Parotid mass: 80% of salivary gland tumours; 80% are benign (pleomorphic adenoma most common).',
      'Facial nerve palsy associated with a parotid mass is strongly suggestive of malignancy.',
      'Warthin\'s tumour: bilateral in 10%, common in older male smokers, hot on Tc-99m scan.',
    ],
    redFlags: [
      'Facial nerve weakness (VII palsy) — malignancy until proven otherwise',
      'Skin involvement, fixation, cervical lymphadenopathy',
      'Rapid growth or pain in a previously stable lump',
      'Trismus suggesting deep lobe or infratemporal fossa extension',
    ],
    investigations: [
      { label: 'Ultrasound of salivary gland mass', urgency: 'routine' },
      { label: 'FNAC (USS-guided) of the mass', urgency: 'routine' },
      { label: 'MRI face/neck (preferred for parotid deep lobe or submandibular extension)', urgency: 'routine' },
      { label: 'CT neck with contrast if malignancy suspected (nodal staging)', urgency: 'urgent' },
      { label: 'Facial nerve assessment (clinical grading — House-Brackmann)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Reactive salivary gland enlargement (sialadenitis): hydration, sialagogues, antibiotics for bacterial infection, warm compresses.' },
      { phase: 'surgical', step: 'Pleomorphic adenoma: superficial parotidectomy with facial nerve preservation; recurrence risk high with enucleation alone.' },
      { phase: 'surgical', step: 'Warthin\'s tumour: surgery if symptomatic or diagnostic uncertainty.' },
      { phase: 'surgical', step: 'Malignant parotid tumour: total parotidectomy ± neck dissection ± post-operative radiotherapy.' },
      { phase: 'followup', step: 'Long-term surveillance for pleomorphic adenoma (risk of malignant transformation — carcinoma ex-pleomorphic ~5%).' },
    ],
    referral: 'ENT/Head and Neck Surgery for all salivary gland masses; MDT with Oncology if malignancy confirmed.',
  },

  {
    diseaseId: 'branchial_cyst',
    icd10Prefixes: ['Q18.0'],
    label: 'Branchial Cyst',
    keyPoints: [
      'Second branchial arch cyst is most common: smooth, fluctuant, anterior to sternocleidomastoid at the junction of upper and middle thirds.',
      'Typically presents in young adults; can become inflamed and mimic a neck abscess.',
      'Important to exclude cystic nodal metastasis from head and neck squamous cell carcinoma in adults >40 years — "cystic SCC node" can mimic branchial cyst.',
    ],
    redFlags: [
      'Patient >40 years with a "cystic" neck mass — exclude cystic SCC nodal metastasis',
      'Rapidly enlarging or acutely inflamed cyst with systemic sepsis',
      'Fistula with persistent discharge — may indicate branchial fistula with internal opening',
    ],
    investigations: [
      { label: 'Neck ultrasound (cystic thin-walled mass anterior to SCM)', urgency: 'routine' },
      { label: 'MRI neck (delineate extent; relationship to carotid sheath)', urgency: 'routine' },
      { label: 'FNAC (cholesterol crystals + lymphoid tissue on aspirate confirm branchial cyst)', urgency: 'routine' },
      { label: 'Panendoscopy (exclude pharyngeal fistula opening) if recurrent', urgency: 'routine' },
      { label: 'CT neck/chest/panendoscopy to exclude occult primary if >40 years', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Antibiotics for acute infection; defer definitive surgery until inflammation resolves (4–6 weeks).' },
      { phase: 'surgical', step: 'Excision of cyst with its tract under GA; step-ladder cervical incisions for extensive tracts.' },
      { phase: 'surgical', step: 'Complete excision essential to prevent recurrence; partial excision leads to high recurrence rates.' },
      { phase: 'followup', step: 'Histological confirmation post-operatively; review if any atypical features warrant further investigation.' },
    ],
    referral: 'ENT/Head and Neck Surgery; Oncology workup if cystic SCC node cannot be excluded.',
  },
];
