import type { ManagementProtocol } from '../types.js';

export const generalSurgeryProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'appendicitis',
    icd10Prefixes: ['K35'],
    label: 'Acute Appendicitis',
    keyPoints: [
      'Alvarado score ≥7 warrants surgical consultation regardless of imaging.',
      'CT is gold standard in adults; USS preferred in children and pregnant women.',
      'Perforation risk rises sharply after 36–72 h from symptom onset.',
    ],
    redFlags: [
      'Peritonism / guarding — likely perforation; immediate surgical review.',
      'Haemodynamic instability — initiate sepsis-6 protocol.',
      'Paediatric or elderly — atypical signs; low threshold for imaging.',
    ],
    investigations: [
      { label: 'FBC + differential (WBC, neutrophilia)', urgency: 'urgent' },
      { label: 'CRP', urgency: 'urgent' },
      { label: 'USS abdomen ± CT abdomen/pelvis with IV contrast', urgency: 'urgent' },
      { label: 'Urine dipstick / βhCG — exclude ectopic pregnancy (females of reproductive age)', urgency: 'urgent' },
      { label: 'Group & save', urgency: 'urgent' },
      { label: 'U&E, LFTs, amylase (exclude differentials)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access, adequate analgesia (IV morphine titrated), NBM.' },
      { phase: 'immediate', step: 'IV crystalloid resuscitation (Hartmann\'s or 0.9% NaCl).' },
      { phase: 'immediate', step: 'IV antibiotics: co-amoxiclav 1.2 g TDS or cefuroxime 750 mg TDS + metronidazole 500 mg TDS.' },
      { phase: 'surgical', step: 'Laparoscopic appendicectomy (gold standard; reduces wound infection and LOS).' },
      { phase: 'surgical', step: 'Open appendicectomy via Lanz incision if laparoscopy unavailable or mass present.' },
      { phase: 'conservative', step: 'Appendix mass: non-operative management with IV antibiotics; interval appendicectomy at 6–8 weeks.' },
      { phase: 'followup', step: 'Histopathology of specimen — exclude carcinoid tumour or appendiceal mucocoele.' },
      { phase: 'followup', step: 'Wound review at 1–2 weeks; safety-net for ileus, collection, or stump leak.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia — titrate to pain score', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '1.2 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24–48 h', indication: 'Antibiotics — first line', phase: 'immediate' },
      { drugName: 'Cefuroxime', dose: '750 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24–48 h', indication: 'Antibiotics — alternative to co-amoxiclav', phase: 'immediate', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Metronidazole', dose: '500 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24–48 h', indication: 'Anaerobic cover (use with cefuroxime)', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid resuscitation', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', duration: '48–72 h', indication: 'Multimodal analgesia (with morphine)', phase: 'immediate' },
    ],
    referral: 'Surgical on-call — same day.',
  },
  {
    diseaseId: 'cholecystitis',
    icd10Prefixes: ['K81'],
    label: 'Acute Cholecystitis',
    keyPoints: [
      "Murphy's sign has sensitivity 65% and specificity 87% for acute cholecystitis.",
      'Tokyo Guidelines (TG18) grade severity: Grade I mild, II moderate, III severe with organ dysfunction.',
      'Early laparoscopic cholecystectomy (within 72 h) reduces complications vs interval surgery.',
    ],
    redFlags: [
      'Fever >39°C with rigors — consider cholangitis (Charcot\'s triad).',
      'Jaundice + RUQ pain — biliary obstruction; urgent ERCP or surgical decompression.',
      'Peritonism — gallbladder perforation; emergency laparotomy.',
    ],
    investigations: [
      { label: 'FBC, CRP', urgency: 'urgent' },
      { label: 'LFTs, bilirubin, ALP, GGT', urgency: 'urgent' },
      { label: 'USS abdomen (gallstones, wall thickening, pericholecystic fluid)', urgency: 'urgent' },
      { label: 'Blood cultures (if febrile)', urgency: 'urgent' },
      { label: 'Amylase / lipase (exclude pancreatitis)', urgency: 'urgent' },
      { label: 'MRCP or CT if CBD dilation or jaundice', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'NBM, IV analgesia (morphine + antiemetic), IV fluids.' },
      { phase: 'immediate', step: 'IV antibiotics: co-amoxiclav 1.2 g TDS or piperacillin-tazobactam for severe.' },
      { phase: 'surgical', step: 'Early laparoscopic cholecystectomy within 72 h (Grade I–II).' },
      { phase: 'surgical', step: 'Delayed cholecystectomy 6–8 weeks if patient unfit for early surgery.' },
      { phase: 'conservative', step: 'Percutaneous cholecystostomy if Grade III or unfit for surgery.' },
      { phase: 'followup', step: 'Ensure histology of gallbladder specimen reviewed.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '1.2 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — Grade I–II', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — Grade III / severe', phase: 'immediate', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid maintenance', phase: 'immediate' },
    ],
    referral: 'Surgical team — same day admission.',
  },
  {
    diseaseId: 'peptic_ulcer',
    icd10Prefixes: ['K25', 'K26', 'K27'],
    label: 'Peptic Ulcer Disease',
    keyPoints: [
      'Test for H. pylori (CLO test, urea breath test, or stool antigen) — eradication reduces recurrence by >80%.',
      'NSAIDs are the second commonest cause; stop or switch to a COX-2 inhibitor + PPI.',
      'Rockford-score ≥6 (Blatchford for bleeding) predicts need for urgent endoscopy.',
    ],
    redFlags: [
      'Haematemesis or melaena — GI bleed; urgent upper GI endoscopy within 24 h.',
      'Peritonism / board-like rigidity — perforated ulcer; emergency laparotomy.',
      'Haemodynamic instability — resuscitate and activate surgical emergency team.',
    ],
    investigations: [
      { label: 'FBC, U&E, LFTs, coagulation', urgency: 'urgent' },
      { label: 'Group & save (crossmatch if bleeding)', urgency: 'urgent' },
      { label: 'H. pylori testing (urea breath test or stool antigen)', urgency: 'routine' },
      { label: 'Upper GI endoscopy (OGD)', urgency: 'urgent' },
      { label: 'Erect CXR / AXR (if perforation suspected — free air)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'PPI: omeprazole 40 mg BD (IV if haemorrhage).' },
      { phase: 'conservative', step: 'H. pylori eradication: triple therapy (PPI + amoxicillin + clarithromycin × 7–14 days).' },
      { phase: 'conservative', step: 'Stop NSAIDs; switch to paracetamol ± low-dose COX-2 inhibitor + PPI.' },
      { phase: 'conservative', step: 'Lifestyle: avoid alcohol, smoking cessation, small frequent meals.' },
      { phase: 'surgical', step: 'Perforated ulcer: laparoscopic omental patch repair (Graham patch).' },
      { phase: 'surgical', step: 'Haemorrhage not controlled endoscopically: under-running of bleeding vessel.' },
      { phase: 'followup', step: 'Repeat OGD at 8 weeks for gastric ulcers (to exclude malignancy).' },
      { phase: 'followup', step: 'Confirm H. pylori eradication at 4 weeks post-treatment.' },
    ],
    medications: [
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'BD (twice daily)', route: 'IV (intravenous)', indication: 'PPI — IV if haemorrhage or NBM', phase: 'immediate' },
      { drugName: 'Omeprazole', dose: '20 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'PPI — maintenance (oral)', phase: 'conservative', alternativeTo: 'Omeprazole IV' },
      { drugName: 'Amoxicillin', dose: '1 g', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7–14 days', indication: 'H. pylori eradication — triple therapy', phase: 'conservative' },
      { drugName: 'Clarithromycin', dose: '500 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7–14 days', indication: 'H. pylori eradication — triple therapy', phase: 'conservative' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Analgesia — avoid NSAIDs', phase: 'immediate' },
    ],
    referral: 'Gastroenterology / general surgery depending on severity.',
  },
  {
    diseaseId: 'pancreatitis',
    icd10Prefixes: ['K85'],
    label: 'Acute Pancreatitis',
    keyPoints: [
      'BISAP or modified Glasgow score at 48 h predicts severity; Ranson criteria at 48 h.',
      'Gallstones (40%) and alcohol (35%) account for 75% of cases in surgical OPD.',
      'CT with IV contrast (CECT) at 48–72 h if no improvement — assess for necrosis.',
    ],
    redFlags: [
      'SIRS criteria met — severe pancreatitis; HDU/ICU admission.',
      'Haemodynamic instability or AKI — aggressive resuscitation, senior review.',
      'Peritonitis — consider haemorrhagic pancreatitis or visceral perforation.',
    ],
    investigations: [
      { label: 'Serum amylase or lipase (>3× ULN diagnostic)', urgency: 'stat' },
      { label: 'FBC, CRP (at 48 h for severity scoring)', urgency: 'urgent' },
      { label: 'U&E, LFTs, calcium, glucose, albumin', urgency: 'urgent' },
      { label: 'USS abdomen (gallstones, CBD dilation)', urgency: 'urgent' },
      { label: 'ABG (PaO₂ <8 kPa = severe)', urgency: 'urgent' },
      { label: 'CECT abdomen at 48–72 h if severe / not improving', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Aggressive IV fluid resuscitation (Hartmann\'s 250–500 ml/h initial).' },
      { phase: 'immediate', step: 'Analgesia: IV morphine or pethidine; antiemetics.' },
      { phase: 'immediate', step: 'NBM — enteral feeding via NG/NJ if not tolerating PO at 48 h.' },
      { phase: 'conservative', step: 'Gallstone pancreatitis: ERCP within 72 h if cholangitis; cholecystectomy in same admission if mild.' },
      { phase: 'conservative', step: 'Alcohol cessation support and referral.' },
      { phase: 'surgical', step: 'Infected necrosis (CECT confirmed): step-up approach — percutaneous drain → video-assisted retroperitoneal debridement (VARD).' },
      { phase: 'followup', step: 'Interval cholecystectomy for gallstone aetiology if not done in-patient.' },
      { phase: 'followup', step: 'Pancreatic function testing (exocrine / endocrine) after severe episode.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia — titrate to pain score', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '500 ml', frequency: 'Q2H (every 2 hours) initially', route: 'IV (intravenous)', indication: 'Aggressive fluid resuscitation (250–500 ml/h)', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', duration: '48–72 h', indication: 'Multimodal analgesia', phase: 'immediate' },
    ],
    referral: 'General surgery + gastroenterology; ITU if BISAP ≥3.',
  },
  {
    diseaseId: 'cholangitis',
    icd10Prefixes: ['K83.0'],
    label: 'Acute Cholangitis',
    keyPoints: [
      "Charcot's triad (RUQ pain, fever, jaundice) present in 50–70%; Reynolds' pentad adds confusion and hypotension.",
      'Tokyo Guidelines TG18 severity grading guides timing of biliary decompression.',
      'Blood cultures positive in 20–30%; anaerobic cover essential.',
    ],
    redFlags: [
      "Reynolds' pentad (confusion + hypotension) — septic shock; emergency biliary decompression.",
      'Bilirubin rapidly rising or >200 µmol/L — imminent hepatic failure.',
      'Failure to improve within 12–24 h of antibiotics — Grade II/III; escalate to ERCP.',
    ],
    investigations: [
      { label: 'FBC, CRP', urgency: 'stat' },
      { label: 'LFTs, bilirubin, ALP, GGT', urgency: 'stat' },
      { label: 'Blood cultures × 2 (before antibiotics)', urgency: 'stat' },
      { label: 'USS abdomen (CBD dilation, stones)', urgency: 'urgent' },
      { label: 'MRCP or CT cholangiogram', urgency: 'urgent' },
      { label: 'Coagulation, U&E, glucose', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access × 2, fluid resuscitation, catheter (urine output monitoring).' },
      { phase: 'immediate', step: 'IV antibiotics: piperacillin-tazobactam 4.5 g TDS or meropenem 1 g TDS if severe.' },
      { phase: 'immediate', step: 'Analgesia and antiemetics IV.' },
      { phase: 'surgical', step: 'Endoscopic biliary decompression (ERCP + sphincterotomy ± stent) — within 24–48 h (Grade I–II) or emergency (Grade III).' },
      { phase: 'surgical', step: 'Percutaneous transhepatic cholangiogram (PTC) if ERCP fails or not available.' },
      { phase: 'followup', step: 'Interval cholecystectomy after recovery from biliary sepsis.' },
      { phase: 'followup', step: 'LFTs and USS at 6 weeks to confirm resolution.' },
    ],
    medications: [
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antibiotics — Grade I–II / first line', phase: 'immediate' },
      { drugName: 'Meropenem', dose: '1 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antibiotics — Grade III / septic shock', phase: 'immediate', alternativeTo: 'Piperacillin-tazobactam (Tazocin)' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid resuscitation', phase: 'immediate' },
    ],
    referral: 'Surgical / gastroenterology emergency — same day.',
  },
  {
    diseaseId: 'gord',
    icd10Prefixes: ['K21'],
    label: 'GORD / Reflux Oesophagitis',
    keyPoints: [
      'Diagnosis is clinical; OGD indicated for alarm features, failure of PPI trial, or age >55.',
      "Los Angeles classification grades oesophagitis (A–D); Barrett's oesophagus requires surveillance.",
      '24-h pH-impedance monitoring is gold standard when diagnosis uncertain.',
    ],
    redFlags: [
      'Dysphagia to solids — progressive, suggests stricture or malignancy; urgent OGD.',
      'Haematemesis or unexplained weight loss — upper GI malignancy must be excluded.',
      'Alarm features (anaemia, weight loss, dysphagia, vomiting) — OGD within 2 weeks.',
    ],
    investigations: [
      { label: 'OGD (if alarm features or PPI failure)', urgency: 'urgent' },
      { label: 'H. pylori testing (stool antigen or urea breath test)', urgency: 'routine' },
      { label: 'FBC (exclude anaemia)', urgency: 'routine' },
      { label: '24-h pH impedance monitoring (if unclear diagnosis)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Lifestyle: head-of-bed elevation, avoid late meals, reduce alcohol and caffeine, weight loss.' },
      { phase: 'conservative', step: 'PPI: omeprazole 20–40 mg OD, 30 min before breakfast; 4–8-week course.' },
      { phase: 'conservative', step: 'Step-down to lowest effective dose or H₂ antagonist (ranitidine/famotidine).' },
      { phase: 'conservative', step: 'H. pylori eradication if positive (may worsen GORD but reduces cancer risk).' },
      { phase: 'surgical', step: 'Laparoscopic Nissen fundoplication for confirmed GORD refractory to PPIs or patient preference.' },
      { phase: 'followup', step: "Barrett's oesophagus (low-grade dysplasia): surveillance OGD every 3–5 years." },
    ],
    medications: [
      { drugName: 'Omeprazole', dose: '20 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'PPI — initial therapy, 30 min before breakfast', phase: 'conservative' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'PPI — escalated dose if 20 mg insufficient', phase: 'conservative', alternativeTo: 'Omeprazole 20 mg' },
      { drugName: 'Gaviscon Advance', dose: '10 ml', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Alginate — post-meals and bedtime', phase: 'conservative' },
      { drugName: 'Famotidine', dose: '20 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'H₂ blocker — alternative or breakthrough GORD', phase: 'conservative' },
    ],
    referral: 'Gastroenterology for persistent or complicated GORD.',
  },
  {
    diseaseId: 'diverticulitis',
    icd10Prefixes: ['K57'],
    label: 'Acute Diverticulitis',
    keyPoints: [
      'Hinchey classification grades severity (I = pericolic abscess → IV = faeculent peritonitis).',
      'CT abdomen/pelvis with IV contrast is the diagnostic imaging of choice.',
      'Uncomplicated (Hinchey I–II) can be managed as outpatient with oral antibiotics.',
    ],
    redFlags: [
      'Peritonism / free air on AXR — Hinchey III/IV; emergency laparotomy.',
      'Abscess >4 cm — CT-guided percutaneous drainage.',
      'Failure to settle on antibiotics at 48 h — reassess, consider CT-guided drain.',
    ],
    investigations: [
      { label: 'FBC, CRP, U&E', urgency: 'urgent' },
      { label: 'CT abdomen/pelvis with IV contrast', urgency: 'urgent' },
      { label: 'Blood cultures (if febrile)', urgency: 'urgent' },
      { label: 'Urine dipstick (exclude UTI)', urgency: 'urgent' },
      { label: 'Colonoscopy at 6–8 weeks post-recovery (exclude malignancy)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Uncomplicated: oral co-amoxiclav 625 mg TDS for 5–7 days; liquid diet.' },
      { phase: 'immediate', step: 'Complicated: NBM, IV co-amoxiclav or piperacillin-tazobactam, IV fluids.' },
      { phase: 'surgical', step: 'Abscess: CT-guided percutaneous drainage (preferred for >4 cm).' },
      { phase: 'surgical', step: 'Hinchey III/IV: emergency Hartmann\'s procedure (sigmoid colectomy + end colostomy) or primary anastomosis.' },
      { phase: 'followup', step: 'High-fibre diet after resolution; colonoscopy at 6–8 weeks.' },
      { phase: 'followup', step: 'Elective sigmoid colectomy after ≥2 episodes — discuss with patient.' },
    ],
    medications: [
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Antibiotics — uncomplicated outpatient', phase: 'conservative' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '1.2 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — complicated inpatient', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — severe / Hinchey III–IV', phase: 'immediate', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid maintenance', phase: 'immediate' },
    ],
    referral: 'Surgical for complicated or Hinchey ≥II disease.',
  },
  {
    diseaseId: 'inguinal_hernia',
    icd10Prefixes: ['K40'],
    label: 'Inguinal / Femoral Hernia',
    keyPoints: [
      'Indirect inguinal hernia is the commonest hernia type (M:F ≈ 8:1 for inguinal; femoral M:F = 1:4).',
      'Femoral hernias have higher strangulation risk — elective repair recommended regardless of symptoms.',
      'Lichtenstein tension-free mesh repair is gold standard; laparoscopic (TEP/TAPP) equivalent outcomes.',
    ],
    redFlags: [
      'Irreducible hernia with pain — strangulation risk; emergency surgery within 4–6 h.',
      'Obstructive symptoms (vomiting, distension) — bowel obstruction secondary to hernia.',
      'Erythema / skin changes overlying hernia — strangulation progressing.',
    ],
    investigations: [
      { label: 'Clinical diagnosis sufficient for uncomplicated cases', urgency: 'routine' },
      { label: 'USS if diagnosis unclear (esp. occult hernia)', urgency: 'routine' },
      { label: 'FBC, U&E if emergency repair planned', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Elective: Lichtenstein mesh herniorrhaphy (local or GA) or laparoscopic TEP/TAPP.' },
      { phase: 'surgical', step: 'Emergency strangulated hernia: resuscitate, IV antibiotics, prompt surgery; bowel resection if non-viable.' },
      { phase: 'conservative', step: 'Truss may be offered for unfit patients declining surgery — monitor for strangulation.' },
      { phase: 'followup', step: 'Review wound at 2 weeks; counsel on recurrence risk and mesh awareness.' },
    ],
    referral: 'General surgery — elective or emergency depending on presentation.',
  },
  {
    diseaseId: 'colorectal_cancer',
    icd10Prefixes: ['C18', 'C19', 'C20'],
    label: 'Colorectal Cancer',
    keyPoints: [
      'Colonoscopy is the gold standard for diagnosis and biopsy — also therapeutic for early lesions.',
      'CEA not diagnostic but useful as a baseline for surveillance after resection.',
      'Staging by CT chest/abdomen/pelvis determines resectability; MRI rectum for rectal cancers.',
    ],
    redFlags: [
      'Obstruction (absolute constipation, distension) — emergency stenting or Hartmann\'s.',
      'PR haemorrhage with haemodynamic instability — emergency resuscitation + endoscopy.',
      'Liver or lung metastases — discuss at colorectal MDT; may still be resectable.',
    ],
    investigations: [
      { label: 'Colonoscopy + biopsy', urgency: 'urgent' },
      { label: 'FBC (exclude iron-deficiency anaemia)', urgency: 'urgent' },
      { label: 'CEA baseline', urgency: 'routine' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'MRI pelvis (rectal cancer staging, CRM assessment)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Colon cancer: laparoscopic or open hemicolectomy / sigmoid colectomy with D3 lymphadenectomy.' },
      { phase: 'surgical', step: 'Rectal cancer: anterior resection (or APR for low tumours); TEMS / TEM for T1 disease.' },
      { phase: 'conservative', step: 'Neoadjuvant chemoradiotherapy for T3/T4 or N+ rectal cancers before surgery.' },
      { phase: 'conservative', step: 'Adjuvant chemotherapy (CAPOX or FOLFOX) for Stage III colon cancer.' },
      { phase: 'followup', step: 'Surveillance colonoscopy at 1 year, then 3-yearly; CEA + CT at 6-monthly intervals × 3 years.' },
    ],
    referral: 'Colorectal MDT — urgent 2-week wait referral.',
  },
  {
    diseaseId: 'bowel_obstruction',
    icd10Prefixes: ['K56'],
    label: 'Bowel Obstruction',
    keyPoints: [
      'Adhesions (60%) and hernias (20%) account for 80% of small bowel obstruction.',
      'CT abdomen/pelvis identifies level, cause, and ischaemia — gold standard.',
      '"Drip and suck" (IV fluids + NG tube) resolves 70–80% of adhesive SBO conservatively.',
    ],
    redFlags: [
      'Peritonism or clinical deterioration — strangulation; emergency surgery.',
      'Closed-loop obstruction on CT — high ischaemia risk; urgent surgery.',
      'Failure to resolve at 48 h of conservative management — reassess and consider surgery.',
    ],
    investigations: [
      { label: 'AXR (dilated loops, air-fluid levels)', urgency: 'urgent' },
      { label: 'CT abdomen/pelvis with IV contrast (level + cause + ischaemia)', urgency: 'urgent' },
      { label: 'FBC, U&E, lactate', urgency: 'urgent' },
      { label: 'Group & save', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access, IV fluids (correct dehydration and electrolytes), catheter.' },
      { phase: 'immediate', step: 'NG tube insertion — "drip and suck" decompression.' },
      { phase: 'immediate', step: 'Analgesia, antiemetics.' },
      { phase: 'conservative', step: 'Adhesive SBO: conservative 48 h trial if no peritonism; water-soluble contrast study at 24 h.' },
      { phase: 'surgical', step: 'Strangulation, failure to resolve, hernia as cause, or large bowel obstruction — operative intervention.' },
      { phase: 'surgical', step: 'Large bowel obstruction with cancer: colonic stenting (bridge to surgery) or emergency Hartmann\'s.' },
      { phase: 'followup', step: 'Elective laparoscopic adhesiolysis for recurrent adhesive obstruction.' },
    ],
    referral: 'Emergency surgical admission.',
  },
];
