import type { ManagementProtocol } from '../types.js';
import { INTRA_ABDOMINAL_PENICILLIN_ALTERNATIVE } from './shared.js';

export const generalSurgeryProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'appendicitis',
    icd10Prefixes: ['K35', 'K36', 'K37'],
    label: 'Acute Appendicitis',
    guidelines: ['WSES Jerusalem guidelines 2020 (acute appendicitis)', 'CODA trial 2020 (antibiotics-first)', 'ACR Appropriateness Criteria 2018 (imaging in pregnancy / children)'],
    allergyAlternatives: { penicillin: INTRA_ABDOMINAL_PENICILLIN_ALTERNATIVE },
    keyPoints: [
      'Alvarado score ≥7 warrants surgical consultation regardless of imaging.',
      'CT is the reference test in adults; ultrasound first in children and pregnancy, then MRI in pregnancy if ultrasound is non-diagnostic (WSES 2020).',
      'Perforation risk rises sharply after 36–72 h from symptom onset.',
    ],
    redFlags: [
      'Peritonism / guarding — likely perforation; immediate surgical review.',
      'Haemodynamic instability — initiate sepsis-6 protocol.',
      'Paediatric or elderly — atypical signs; low threshold for imaging.',
    ],
    investigations: [
      { label: 'FBC + differential (WBC, neutrophilia)', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 2.5 },
      { label: 'CRP', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 3.0 },
      { label: 'U&E, LFTs, amylase (exclude differentials)', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'Group & save', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'Urine dipstick', urgency: 'urgent', tier: 1, category: 'bedside' },
      { label: 'βhCG (females of reproductive age — exclude ectopic)', urgency: 'urgent', tier: 1, category: 'bedside' },
      { label: 'USS abdomen — RIF (appendix, free fluid)', urgency: 'urgent', tier: 2, category: 'imaging-uss', lrPos: 7.5 },
      { label: 'CT abdomen/pelvis with IV contrast (adults, not pregnant — MRI in pregnancy) — if ultrasound is inconclusive', urgency: 'urgent', tier: 3, category: 'imaging-ct', lrPos: 13.0, conditional: 'If USS inconclusive or high clinical suspicion', onlyIf: 'not-pregnant' },
      { label: 'MRI abdomen/pelvis (non-contrast) if ultrasound is non-diagnostic — pregnancy (WSES 2020; ACR 2018)', urgency: 'urgent', tier: 3, category: 'imaging-mri', onlyIf: 'pregnant' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access, adequate analgesia (IV morphine titrated), NBM.' },
      { phase: 'immediate', step: 'IV crystalloid resuscitation (Hartmann\'s or 0.9% NaCl).' },
      { phase: 'immediate', step: 'IV antibiotics: co-amoxiclav 1.2 g TDS or cefuroxime 750 mg TDS + metronidazole 500 mg TDS.' },
      { phase: 'surgical', step: 'Laparoscopic appendicectomy (gold standard; reduces wound infection and LOS).' },
      { phase: 'surgical', step: 'Open appendicectomy via Lanz incision if laparoscopy unavailable or mass present.' },
      { phase: 'conservative', step: 'Appendix mass: non-operative management with IV antibiotics; interval appendicectomy at 6–8 weeks.' },
      { phase: 'conservative', step: 'Uncomplicated appendicitis on imaging: antibiotics-first non-operative management is an option for selected adults after shared decision-making (WSES 2020; CODA 2020) — an appendicolith predicts antibiotic failure and complications, so surgery is preferred when one is present.' },
      { phase: 'followup', step: 'Histopathology of specimen — exclude carcinoid tumour or appendiceal mucocoele.' },
      { phase: 'followup', step: 'Wound review at 1–2 weeks; safety-net for ileus, collection, or stump leak. No routine post-operative antibiotics after simple appendicitis (WSES 2020).' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia — titrate to pain score', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '1.2 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24–48 h', indication: 'Antibiotics — first line', phase: 'immediate' },
      { drugName: 'Cefuroxime', dose: '750 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24–48 h', indication: 'Antibiotics — alternative to co-amoxiclav', phase: 'immediate', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Metronidazole', dose: '500 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24–48 h', indication: 'Anaerobic cover (use with cefuroxime)', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid resuscitation', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', duration: '48–72 h', indication: 'Multimodal analgesia (with morphine)', phase: 'immediate' },
    ],
    referral: 'Surgical on-call — same day.',
  },
  {
    diseaseId: 'cholecystitis',
    icd10Prefixes: ['K81', 'K80.0', 'K80.1', 'K80.4', 'K82.2', 'K82.1'],
    label: 'Acute Cholecystitis',
    guidelines: ['Tokyo Guidelines 2018 (TG18) acute cholecystitis', 'WSES 2020 acute calculous cholecystitis'],
    allergyAlternatives: { penicillin: INTRA_ABDOMINAL_PENICILLIN_ALTERNATIVE },
    keyPoints: [
      "Murphy's sign has sensitivity 65% and specificity 87% for acute cholecystitis.",
      'Tokyo Guidelines (TG18) grade severity: Grade I mild, II moderate, III severe with organ dysfunction.',
      'Grade I–II: early laparoscopic cholecystectomy (within 72 h of admission, up to 7 days of symptoms) if fit (CCI/ASA-PS); Grade III: early surgery only in a favourable patient at an advanced centre, otherwise gallbladder drainage and delayed cholecystectomy when stable (TG18).',
    ],
    redFlags: [
      'Fever >39°C with rigors — consider cholangitis (Charcot\'s triad).',
      'Jaundice + RUQ pain — biliary obstruction; urgent ERCP or surgical decompression.',
      'Peritonism — gallbladder perforation; emergency laparotomy.',
    ],
    investigations: [
      { label: 'FBC, CRP', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 2.0 },
      { label: 'LFTs, bilirubin, ALP, GGT', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 3.5, rationale: 'Cholestatic pattern + elevated bilirubin suggests CBD involvement' },
      { label: 'Amylase / lipase (exclude pancreatitis)', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'Blood cultures × 2 (before antibiotics)', urgency: 'urgent', tier: 1, category: 'microbiology', conditional: 'If febrile or Grade II–III' },
      { label: 'USS abdomen (gallstones, wall thickening, pericholecystic fluid)', urgency: 'urgent', tier: 2, category: 'imaging-uss', lrPos: 8.5 },
      { label: 'MRCP if the CBD is dilated or the patient is jaundiced', urgency: 'urgent', tier: 3, category: 'imaging-mri', lrPos: 15.0, conditional: 'If CBD dilation or jaundice on USS' },
      { label: 'CT abdomen (if MRCP unavailable or to assess complications)', urgency: 'urgent', tier: 3, category: 'imaging-ct', lrPos: 5.0, conditional: 'If MRCP unavailable' },
    ],
    management: [
      { phase: 'immediate', step: 'NBM, IV analgesia (morphine + antiemetic), IV fluids.' },
      { phase: 'immediate', step: 'IV antibiotics: co-amoxiclav 1.2 g TDS or piperacillin-tazobactam for severe.' },
      { phase: 'surgical', step: 'Early laparoscopic cholecystectomy within 72 h for Grade I–II if fit (low CCI / ASA-PS — TG18).' },
      { phase: 'surgical', step: 'Gallbladder drainage (percutaneous cholecystostomy / PTGBD) for Grade III, or Grade II unfit for surgery (high CCI / ASA-PS) — TG18.' },
      { phase: 'surgical', step: 'Delayed cholecystectomy 6–8 weeks after drainage or recovery if the patient was unfit for early surgery.' },
      { phase: 'followup', step: 'Ensure histology of gallbladder specimen reviewed.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '1.2 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — Grade I–II', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — Grade III / severe', phase: 'immediate', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid maintenance', phase: 'immediate' },
    ],
    referral: 'Surgical team — same day admission.',
  },
  {
    diseaseId: 'peptic_ulcer',
    icd10Prefixes: ['K25', 'K26', 'K27', 'K28'],
    label: 'Peptic Ulcer Disease',
    guidelines: ['NICE CG184 (2014, updated 2019) dyspepsia and GORD', 'Maastricht VI/Florence consensus (2022) H. pylori', 'WSES 2020 perforated/bleeding peptic ulcer'],
    allergyAlternatives: {
      penicillin: 'Penicillin allergy: bismuth quadruple therapy for 14 days — PPI + bismuth + tetracycline + metronidazole (Maastricht VI 2022); or PPI + clarithromycin + metronidazole for 7 days (NICE CG184) if no recent macrolide exposure.',
    },
    keyPoints: [
      'Test for H. pylori (CLO test, urea breath test, or stool antigen) — eradication reduces recurrence by >80%.',
      'NSAIDs are the second commonest cause; stop or switch to a COX-2 inhibitor + PPI.',
      'Glasgow-Blatchford score guides the need for admission and endoscopy in bleeding; Rockall after endoscopy predicts rebleeding and mortality.',
    ],
    redFlags: [
      'Haematemesis or melaena — GI bleed; urgent upper GI endoscopy within 24 h.',
      'Peritonism / board-like rigidity — perforated ulcer; emergency laparotomy.',
      'Haemodynamic instability — resuscitate and activate surgical emergency team.',
    ],
    investigations: [
      { label: 'FBC, U&E, LFTs, coagulation', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'Group & save (crossmatch if actively bleeding)', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'H. pylori (urea breath test or stool antigen)', urgency: 'routine', tier: 1, category: 'other', lrPos: 3.0 },
      { label: 'Erect CXR (free air under diaphragm)', urgency: 'urgent', tier: 2, category: 'imaging-xr', lrPos: 5.5, conditional: 'If perforation suspected' },
      { label: 'Upper GI endoscopy (OGD) — for bleeding or dyspepsia; not in suspected perforation (CT first)', urgency: 'urgent', tier: 3, category: 'endoscopy', lrPos: 20.0, rationale: 'Diagnostic and therapeutic for haemorrhage' },
      { label: 'CT abdomen/pelvis if perforation suspected and erect CXR is non-diagnostic', urgency: 'urgent', tier: 3, category: 'imaging-ct', conditional: 'Suspected perforation' },
    ],
    management: [
      { phase: 'immediate', step: 'PPI: omeprazole 40 mg BD (IV if haemorrhage).' },
      { phase: 'conservative', step: 'H. pylori eradication: PPI + amoxicillin + clarithromycin (or metronidazole) for 7 days (NICE CG184); where clarithromycin resistance is high, 14-day bismuth quadruple therapy (Maastricht VI 2022).' },
      { phase: 'conservative', step: 'Gastric or duodenal ulcer: full-dose PPI for 8 weeks (NICE CG184); gastric ulcer — repeat OGD at 6–8 weeks to confirm healing and exclude malignancy.' },
      { phase: 'conservative', step: 'Stop NSAIDs; switch to paracetamol ± low-dose COX-2 inhibitor + PPI.' },
      { phase: 'conservative', step: 'Lifestyle: avoid alcohol, smoking cessation, small frequent meals.' },
      { phase: 'surgical', step: 'Perforated ulcer: laparoscopic omental patch repair (Graham patch).' },
      { phase: 'surgical', step: 'Haemorrhage not controlled endoscopically: under-running of bleeding vessel.' },
      { phase: 'followup', step: 'Repeat OGD at 8 weeks for gastric ulcers (to exclude malignancy).' },
      { phase: 'followup', step: 'Confirm H. pylori eradication at 4 weeks post-treatment.' },
    ],
    medications: [
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'BD (twice daily)', route: 'IV (intravenous)', indication: 'PPI — IV if haemorrhage or NBM', phase: 'immediate' },
      { drugName: 'Omeprazole', dose: '20 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'PPI — maintenance (oral)', phase: 'conservative', alternativeTo: 'Omeprazole IV' },
      { drugName: 'Amoxicillin', dose: '1 g', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7–14 days', indication: 'H. pylori eradication — triple therapy', phase: 'conservative' },
      { drugName: 'Clarithromycin', dose: '500 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7–14 days', indication: 'H. pylori eradication — triple therapy', phase: 'conservative' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Analgesia — avoid NSAIDs', phase: 'immediate' },
    ],
    referral: 'Gastroenterology / general surgery depending on severity.',
  },
  {
    diseaseId: 'pancreatitis',
    icd10Prefixes: ['K85'],
    label: 'Acute Pancreatitis',
    guidelines: ['ACG 2024 management of acute pancreatitis', 'WATERFALL trial 2022 (fluid resuscitation)', 'IAP/APA 2013 evidence-based guidelines', 'Revised Atlanta classification 2012'],
    keyPoints: [
      'Moderate, goal-directed fluids — high-volume fluid resuscitation increases fluid overload without benefit (WATERFALL 2022; ACG 2024); smaller volumes with heart failure or CKD.',
      'No prophylactic antibiotics: antibiotics only for documented or strongly suspected infection (infected necrosis, cholangitis, other source) — ACG 2024; IAP/APA 2013.',
      'Early oral feeding (within 24 h as tolerated); enteral rather than parenteral nutrition if oral intake fails.',
      'Find the cause: gallstones (ultrasound), alcohol, triglycerides, calcium, drugs (e.g. azathioprine), or a recent ERCP if one was done.',
    ],
    redFlags: [
      'Persistent organ failure (> 48 h), SIRS, rising urea or creatinine — severe pancreatitis; HDU/ICU.',
      'Cholangitis (fever, jaundice, rising bilirubin) — ERCP within 24 h.',
      'Triglycerides > 11.3 mmol/L (hypertriglyceridaemia) — cause-specific treatment.',
      'Haemodynamic instability or AKI — goal-directed resuscitation, senior review.',
    ],
    investigations: [
      { label: 'Serum amylase or lipase (>3× ULN diagnostic)', urgency: 'stat', tier: 1, category: 'bloods', lrPos: 25.0 },
      { label: 'FBC, CRP (at 48 h for severity scoring)', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'U&E, LFTs, calcium, glucose, albumin, triglycerides', urgency: 'urgent', tier: 1, category: 'bloods', rationale: 'LFTs suggest gallstone aetiology; triglycerides and calcium identify metabolic causes' },
      { label: 'Blood gas if hypoxic or unwell (PaO₂ <8 kPa = severe)', urgency: 'urgent', tier: 1, category: 'bedside', lrPos: 3.5 },
      { label: 'USS abdomen (gallstones, CBD dilation)', urgency: 'urgent', tier: 2, category: 'imaging-uss', lrPos: 5.0, rationale: 'First-line to identify gallstone aetiology' },
      { label: 'CECT abdomen — only if the diagnosis is uncertain, or at 72–96 h if not improving (necrosis, collections); not routinely at admission', urgency: 'urgent', tier: 3, category: 'imaging-ct', lrPos: 18.0, conditional: 'Diagnosis uncertain, or not improving after 72 h' },
    ],
    management: [
      { phase: 'immediate', step: 'Moderate goal-directed IV fluids with lactated Ringer\'s / Hartmann\'s: 10 mL/kg bolus only if hypovolaemic, then 1.5 mL/kg/h, reassessed at 12, 24 and 48 h — avoid aggressive fluids (WATERFALL 2022; ACG 2024); reduce with heart failure or CKD.' },
      { phase: 'immediate', step: 'Analgesia: IV opioid (morphine) with antiemetic; paracetamol.' },
      { phase: 'immediate', step: 'Early oral feeding within 24 h as tolerated (low-fat solid diet); enteral (NG/NJ) feeding if oral intake is not tolerated — not parenteral (ACG 2024).' },
      { phase: 'immediate', step: 'No prophylactic antibiotics; antibiotics only for documented or strongly suspected infection (infected necrosis, cholangitis, pneumonia, UTI) — ACG 2024.' },
      { phase: 'conservative', step: 'Biliary pancreatitis with cholangitis: ERCP within 24 h (ACG 2024; TG18); ERCP is not routine without cholangitis or persistent biliary obstruction.' },
      { phase: 'conservative', step: 'Mild biliary pancreatitis: laparoscopic cholecystectomy for gallstones during the same admission (ACG 2024); with peripancreatic collections or necrosis, defer cholecystectomy until collections resolve or beyond 6 weeks (IAP/APA 2013).' },
      { phase: 'conservative', step: 'Alcohol-related: thiamine (IV Pabrinex or oral) and alcohol-withdrawal assessment and treatment per local protocol (e.g. CIWA-Ar-guided chlordiazepoxide); alcohol cessation support.' },
      { phase: 'conservative', step: 'Drug-induced (e.g. azathioprine): stop the causative drug and record it as an adverse reaction; do not rechallenge.' },
      { phase: 'conservative', step: 'Hypertriglyceridaemia (> 11.3 mmol/L): specialist management (insulin–glucose infusion; plasmapheresis in selected cases), then triglyceride-lowering therapy; no cholecystectomy unless gallstones are present.' },
      { phase: 'conservative', step: 'Severe disease: HDU/ICU; monitor intra-abdominal (bladder) pressure for abdominal compartment syndrome.' },
      { phase: 'surgical', step: 'Infected necrosis (CECT gas or FNA confirmed): step-up approach — percutaneous or endoscopic drainage → minimally invasive necrosectomy, delayed ≥ 4 weeks until walled off.' },
      { phase: 'followup', step: 'Interval cholecystectomy for gallstone aetiology if not done in-patient (after collections resolve).' },
      { phase: 'followup', step: 'Pancreatic function testing (exocrine / endocrine) after severe episode.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia — titrate to pain score', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1.5 mL/kg/h (after a 10 mL/kg bolus only if hypovolaemic)', frequency: 'Continuous, reassess at 12/24/48 h', route: 'IV (intravenous)', indication: 'Moderate goal-directed fluid resuscitation (WATERFALL 2022)', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', duration: '48–72 h', indication: 'Multimodal analgesia', phase: 'immediate' },
    ],
    referral: 'General surgery + gastroenterology; HDU/ICU for organ failure.',
  },
  {
    diseaseId: 'cholangitis',
    icd10Prefixes: ['K83.0', 'K80.3'],
    label: 'Acute Cholangitis',
    guidelines: ['Tokyo Guidelines 2018 (TG18) acute cholangitis', 'ACG 2024 / ASGE 2019 choledocholithiasis'],
    allergyAlternatives: { penicillin: INTRA_ABDOMINAL_PENICILLIN_ALTERNATIVE },
    keyPoints: [
      "Charcot's triad (RUQ pain, fever, jaundice) present in 50–70%; Reynolds' pentad adds confusion and hypotension.",
      'Tokyo Guidelines TG18 severity grading guides timing of biliary decompression.',
      'Blood cultures positive in 20–30%; anaerobic cover essential.',
    ],
    redFlags: [
      "Reynolds' pentad (confusion + hypotension) — septic shock; emergency biliary decompression.",
      'Bilirubin rapidly rising or >200 µmol/L — imminent hepatic failure.',
      'Failure to improve within 12–24 h of antibiotics — Grade II/III; escalate to ERCP.',
    ],
    investigations: [
      { label: 'FBC, CRP', urgency: 'stat', tier: 1, category: 'bloods', lrPos: 2.5 },
      { label: 'LFTs, bilirubin, ALP, GGT', urgency: 'stat', tier: 1, category: 'bloods', lrPos: 4.0, rationale: 'Cholestatic pattern supports biliary obstruction' },
      { label: 'Blood cultures × 2 (before antibiotics)', urgency: 'stat', tier: 1, category: 'microbiology', lrPos: 2.0 },
      { label: 'Coagulation, U&E, glucose', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'USS abdomen (CBD dilation, stones)', urgency: 'urgent', tier: 2, category: 'imaging-uss', lrPos: 6.5 },
      { label: 'MRCP (CBD stones, stricture)', urgency: 'urgent', tier: 3, category: 'imaging-mri', lrPos: 18.0, conditional: 'After USS — confirms stone vs stricture before ERCP' },
      { label: 'CT cholangiogram (if MRCP unavailable)', urgency: 'urgent', tier: 3, category: 'imaging-ct', conditional: 'If MRCP unavailable' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access × 2, fluid resuscitation, catheter (urine output monitoring).' },
      { phase: 'immediate', step: 'IV antibiotics: piperacillin-tazobactam 4.5 g TDS or meropenem 1 g TDS if severe.' },
      { phase: 'immediate', step: 'Analgesia and antiemetics IV.' },
      { phase: 'surgical', step: 'Biliary drainage by ERCP (sphincterotomy ± stone extraction ± stent): Grade III — urgent, as soon as organ support allows; Grade II — early, within 24 h; Grade I — if there is no response to antibiotics within 24 h (TG18; ACG 2024).' },
      { phase: 'surgical', step: 'Percutaneous transhepatic cholangiogram (PTC) if ERCP fails or not available.' },
      { phase: 'followup', step: 'Interval cholecystectomy after recovery from biliary sepsis.' },
      { phase: 'followup', step: 'LFTs and USS at 6 weeks to confirm resolution.' },
    ],
    medications: [
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antibiotics — Grade I–II / first line', phase: 'immediate' },
      { drugName: 'Meropenem', dose: '1 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antibiotics — Grade III / septic shock', phase: 'immediate', alternativeTo: 'Piperacillin-tazobactam (Tazocin)' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid resuscitation', phase: 'immediate' },
    ],
    referral: 'Surgical / gastroenterology emergency — same day.',
  },
  {
    diseaseId: 'gord',
    icd10Prefixes: ['K21'],
    label: 'GORD / Reflux Oesophagitis',
    keyPoints: [
      'Diagnosis is clinical; OGD indicated for alarm features, failure of PPI trial, or age >55.',
      "Los Angeles classification grades oesophagitis (A–D); Barrett's oesophagus requires surveillance.",
      '24-h pH-impedance monitoring is gold standard when diagnosis uncertain.',
    ],
    redFlags: [
      'Dysphagia to solids — progressive, suggests stricture or malignancy; urgent OGD.',
      'Haematemesis or unexplained weight loss — upper GI malignancy must be excluded.',
      'Alarm features (anaemia, weight loss, dysphagia, vomiting) — OGD within 2 weeks.',
    ],
    investigations: [
      { label: 'FBC (exclude anaemia)', urgency: 'routine', tier: 1, category: 'bloods' },
      { label: 'H. pylori (stool antigen or urea breath test)', urgency: 'routine', tier: 1, category: 'other', lrPos: 2.5 },
      { label: 'OGD (alarm features or PPI failure)', urgency: 'urgent', tier: 3, category: 'endoscopy', lrPos: 8.0, conditional: 'Alarm features, age >55, or 4-week PPI trial failed' },
      { label: '24-h pH impedance monitoring', urgency: 'routine', tier: 3, category: 'other', lrPos: 15.0, conditional: 'If diagnosis uncertain after OGD' },
    ],
    management: [
      { phase: 'immediate', step: 'Age ≥ 55 with weight loss and reflux, dyspepsia or upper abdominal pain, or any dysphagia: suspected cancer pathway — urgent OGD within 2 weeks (NICE NG12).' },
      { phase: 'conservative', step: 'Lifestyle: head-of-bed elevation, avoid late meals, reduce alcohol and caffeine, weight loss.' },
      { phase: 'conservative', step: 'PPI: omeprazole 20–40 mg OD, 30 min before breakfast; 4–8-week course.' },
      { phase: 'conservative', step: 'Step-down to lowest effective dose or H₂ antagonist (ranitidine/famotidine).' },
      { phase: 'conservative', step: 'H. pylori eradication if positive (may worsen GORD but reduces cancer risk).' },
      { phase: 'surgical', step: 'Laparoscopic Nissen fundoplication for confirmed GORD refractory to PPIs or patient preference.' },
      { phase: 'followup', step: "Barrett's oesophagus (low-grade dysplasia): surveillance OGD every 3–5 years." },
    ],
    medications: [
      { drugName: 'Omeprazole', dose: '20 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'PPI — initial therapy, 30 min before breakfast', phase: 'conservative' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'PPI — escalated dose if 20 mg insufficient', phase: 'conservative', alternativeTo: 'Omeprazole 20 mg' },
      { drugName: 'Gaviscon Advance', dose: '10 ml', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Alginate — post-meals and bedtime', phase: 'conservative' },
      { drugName: 'Famotidine', dose: '20 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '4–8 weeks', indication: 'H₂ blocker — alternative or breakthrough GORD', phase: 'conservative' },
    ],
    referral: 'Gastroenterology for persistent or complicated GORD.',
  },
  {
    diseaseId: 'diverticulitis',
    icd10Prefixes: ['K57.0', 'K57.12', 'K57.13', 'K57.2', 'K57.32', 'K57.33', 'K57.4', 'K57.52', 'K57.53', 'K57.8', 'K57.92', 'K57.93'],
    label: 'Acute Diverticulitis',
    guidelines: ['NICE NG147 (2019) diverticular disease', 'WSES 2020 acute left-sided colonic diverticulitis', 'NICE NG125 (2019) surgical site infection'],
    allergyAlternatives: { penicillin: INTRA_ABDOMINAL_PENICILLIN_ALTERNATIVE },
    keyPoints: [
      'Hinchey classification grades severity (I = pericolic abscess → IV = faeculent peritonitis).',
      'CT abdomen/pelvis with IV contrast is the diagnostic imaging of choice.',
      'Uncomplicated diverticulitis: antibiotics are not routinely required in immunocompetent, systemically well patients (NICE NG147; WSES 2020) — outpatient observation with analgesia and safety-netting.',
      'Immunosuppressed patients: fewer signs, higher perforation risk — lower threshold for CT, admission, antibiotics and surgery.',
    ],
    redFlags: [
      'Peritonism / free air on AXR — Hinchey III/IV; emergency laparotomy.',
      'Abscess >4 cm — CT-guided percutaneous drainage.',
      'Failure to settle on antibiotics at 48 h — reassess, consider CT-guided drain.',
    ],
    investigations: [
      { label: 'FBC, CRP, U&E', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 2.5 },
      { label: 'Urine dipstick (exclude UTI)', urgency: 'urgent', tier: 1, category: 'bedside' },
      { label: 'Blood cultures × 2 (if febrile)', urgency: 'urgent', tier: 1, category: 'microbiology', conditional: 'If febrile >38°C' },
      { label: 'CT abdomen/pelvis with IV contrast', urgency: 'urgent', tier: 3, category: 'imaging-ct', lrPos: 22.0, rationale: 'Gold standard — confirms diagnosis, grades Hinchey, detects abscess' },
      { label: 'Colonoscopy (6–8 weeks post-recovery)', urgency: 'routine', tier: 3, category: 'endoscopy', conditional: 'After acute episode resolves — exclude malignancy' },
    ],
    management: [
      { phase: 'conservative', step: 'Uncomplicated, immunocompetent and systemically well: antibiotics not routinely required (not for immunosuppressed patients) — analgesia (paracetamol; avoid NSAIDs and opioids where possible), clear fluids, review within 48 h; if systemically unwell, immunocompromised or with significant comorbidity: oral co-amoxiclav 500/125 mg three times daily for 5 days (NICE NG147).' },
      { phase: 'immediate', step: 'Complicated: NBM, IV co-amoxiclav or piperacillin-tazobactam, IV fluids.' },
      { phase: 'surgical', step: 'Abscess: CT-guided percutaneous drainage (preferred for >4 cm).' },
      { phase: 'surgical', step: 'Hinchey III/IV: emergency Hartmann\'s procedure (sigmoid colectomy + end colostomy) or primary anastomosis.' },
      { phase: 'followup', step: 'High-fibre diet after resolution; colonoscopy at 6–8 weeks.' },
      { phase: 'followup', step: 'Elective sigmoid colectomy is individualised (complicated disease, persistent symptoms, immunosuppression), not automatic after two episodes (WSES 2020; NICE NG147); antibiotic prophylaxis as a single IV dose at induction, within 60 minutes before incision (NICE NG125).' },
    ],
    medications: [
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '500/125 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5 days', indication: 'Uncomplicated — only if systemically unwell, immunocompromised or significant comorbidity (NICE NG147)', phase: 'conservative' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '1.2 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — complicated inpatient', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '5 days', indication: 'Antibiotics — severe / Hinchey III–IV', phase: 'immediate', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'Q8H (every 8 hours)', route: 'IV (intravenous)', indication: 'IV fluid maintenance', phase: 'immediate' },
    ],
    referral: 'Surgical for complicated or Hinchey ≥II disease.',
  },
  {
    diseaseId: 'inguinal_hernia',
    icd10Prefixes: ['K40'],
    label: 'Inguinal / Femoral Hernia',
    guidelines: ['HerniaSurge international guidelines for groin hernia management (2018)', 'WSES 2017 emergency repair of complicated abdominal wall hernias'],
    keyPoints: [
      'Indirect inguinal hernia is the commonest hernia type (M:F ≈ 8:1 for inguinal; femoral M:F = 1:4).',
      'Femoral hernias have higher strangulation risk — repair recommended regardless of symptoms; exclude an occult femoral hernia in women.',
      'Adults: Lichtenstein tension-free mesh repair or laparoscopic TEP/TAPP (HerniaSurge 2018); minimally symptomatic men who decline or are unfit for repair may choose watchful waiting.',
    ],
    redFlags: [
      'Irreducible hernia with pain — strangulation risk; emergency surgery within 4–6 h.',
      'Obstructive symptoms (vomiting, distension) — bowel obstruction secondary to hernia.',
      'Erythema / skin changes overlying the hernia, peritonism, fever or raised lactate — strangulation; do not attempt reduction.',
    ],
    investigations: [
      { label: 'Clinical diagnosis (sufficient for uncomplicated hernia)', urgency: 'routine', tier: 1, category: 'other' },
      { label: 'FBC, U&E, CRP, lactate (irreducible or tender hernia — strangulation markers)', urgency: 'urgent', tier: 1, category: 'bloods', conditional: 'Irreducible / tender hernia or emergency repair' },
      { label: 'USS (if diagnosis unclear or occult hernia)', urgency: 'routine', tier: 2, category: 'imaging-uss', lrPos: 7.5, conditional: 'Diagnosis uncertain on clinical examination' },
    ],
    management: [
      { phase: 'immediate', step: 'Irreducible, tender hernia: nil by mouth, IV fluids and analgesia; assess for strangulation (skin changes, peritonism, systemic toxicity, raised lactate) — WSES 2017.' },
      { phase: 'conservative', step: 'Incarcerated without any sign of strangulation: a single gentle reduction by an experienced surgeon with analgesia may be considered; do not attempt reduction if strangulation is suspected (WSES 2017). If reduced, admit and repair on the same admission.' },
      { phase: 'surgical', step: 'Emergency repair if strangulation is suspected: resuscitate, IV antibiotics, emergency surgery; assess bowel viability and resect non-viable bowel (WSES 2017).' },
      { phase: 'surgical', step: 'Elective: Lichtenstein mesh herniorrhaphy (local or GA) or laparoscopic TEP/TAPP.' },
      { phase: 'conservative', step: 'Minimally symptomatic, reducible inguinal hernia in men who decline or are unfit for repair: watchful waiting after discussion — not for women (femoral hernia risk) or an irreducible hernia; most eventually choose repair (HerniaSurge 2018).', onlyIf: 'adult' },
      { phase: 'followup', step: 'Review wound at 2 weeks; counsel on recurrence risk and mesh awareness.' },
    ],
    referral: 'General surgery — elective or emergency depending on presentation; paediatric surgery for children.',
  },
  {
    diseaseId: 'colorectal_cancer',
    icd10Prefixes: ['C18', 'C19'],
    label: 'Colorectal Cancer',
    cancer: true,
    guidelines: ['NICE NG151 (2020) colorectal cancer', 'WSES 2018 obstructive left colon carcinoma', 'ESGE 2020 colonic stenting', 'CPOC 2021 frailty', 'BSG 2021 iron deficiency anaemia'],
    keyPoints: [
      'Colonoscopy is the gold standard for diagnosis and biopsy — also therapeutic for early lesions.',
      'CEA not diagnostic but useful as a baseline for surveillance after resection.',
      'Staging by CT chest/abdomen/pelvis determines resectability; MRI rectum for rectal cancers.',
    ],
    redFlags: [
      'Obstruction (absolute constipation, distension) — stenting is contraindicated with perforation, impending caecal perforation or peritonitis; left-sided lesions: resection, Hartmann\'s or stent bridge; right-sided: hemicolectomy.',
      'PR haemorrhage with haemodynamic instability — emergency resuscitation + endoscopy.',
      'Liver or lung metastases — discuss at colorectal MDT; may still be resectable.',
    ],
    investigations: [
      { label: 'FBC (exclude iron-deficiency anaemia)', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 3.0 },
      { label: 'CEA baseline', urgency: 'routine', tier: 1, category: 'bloods' },
      { label: 'Colonoscopy + biopsy', urgency: 'urgent', tier: 3, category: 'endoscopy', lrPos: 30.0, rationale: 'Gold standard — diagnostic and therapeutic for early lesions' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent', tier: 3, category: 'imaging-ct', lrPos: 8.0, conditional: 'After confirmed histological diagnosis' },
      { label: 'Pre-operative: ferritin / iron studies (treat iron deficiency), BNP if RCRI ≥ 1 or age ≥ 65 (ESC/ESAIC 2022), echocardiography if murmur or heart failure, functional capacity', urgency: 'routine', tier: 1, category: 'bloods', conditional: 'Before major resection' },
      { label: 'MRI pelvis (rectal cancer — CRM and T-stage)', urgency: 'urgent', tier: 3, category: 'imaging-mri', lrPos: 12.0, conditional: 'Rectal cancer only' },
    ],
    management: [
      { phase: 'surgical', step: 'Colon cancer: laparoscopic or open resection by tumour site with D3 lymphadenectomy — right (or extended right) hemicolectomy for right-sided tumours; left hemicolectomy or sigmoid colectomy if left-sided.' },
      { phase: 'surgical', step: 'Obstructing right-sided or transverse cancer: right (or extended right) hemicolectomy with primary ileocolic anastomosis in most patients (WSES 2018).' },
      { phase: 'surgical', step: 'Obstructing left-sided cancer: resection with anastomosis ± defunctioning stoma, Hartmann\'s procedure, or a colonic stent (SEMS) as a bridge — stenting is contraindicated with perforation, impending caecal perforation (tender caecum, ischaemia) or peritonitis (WSES 2018; ESGE 2020).' },
      { phase: 'conservative', step: 'Iron-deficiency anaemia before surgery: iron replacement (IV iron if surgery is within weeks) — BSG 2021.' },
      { phase: 'conservative', step: 'Older or frail patients: comprehensive geriatric assessment, delirium risk and prevention, and shared decision-making on goals of care before major surgery (CPOC 2021).' },
      { phase: 'surgical', step: 'Rectal cancer: anterior resection (or APR for low tumours); TEMS / TEM for T1 disease.' },
      { phase: 'conservative', step: 'Neoadjuvant chemoradiotherapy for T3/T4 or N+ rectal cancers before surgery.' },
      { phase: 'conservative', step: 'Adjuvant chemotherapy (CAPOX or FOLFOX) for Stage III colon cancer.' },
      { phase: 'followup', step: 'Surveillance colonoscopy at 1 year, then 3-yearly; CEA + CT at 6-monthly intervals × 3 years.' },
    ],
    referral: 'Colorectal MDT — urgent 2-week wait referral.',
  },
  {
    diseaseId: 'bowel_obstruction',
    icd10Prefixes: ['K56'],
    label: 'Bowel Obstruction',
    guidelines: ['WSES 2017 Bologna guidelines (adhesive SBO)', 'ASCRS 2021 colonic volvulus and acute colonic pseudo-obstruction', 'WSES 2018 obstructive left colon carcinoma', 'ESGE 2020 colonic stenting'],
    keyPoints: [
      'Adhesions (60%) and hernias (20%) account for 80% of small bowel obstruction; in a virgin abdomen look for a hernia or tumour.',
      'CT abdomen/pelvis identifies level, cause, and ischaemia — gold standard.',
      'Non-operative management resolves most adhesive SBO without strangulation; a water-soluble contrast challenge predicts resolution (WSES 2017).',
    ],
    redFlags: [
      'Peritonism or clinical deterioration — strangulation; emergency surgery.',
      'Closed-loop obstruction on CT — high ischaemia risk; urgent surgery.',
      'Caecal diameter ≥ 12 cm, caecal tenderness or ischaemia — impending perforation; no stent, urgent surgery.',
      'Failure to resolve within 72 h of non-operative management — surgery.',
    ],
    investigations: [
      { label: 'FBC, U&E (potassium), lactate', urgency: 'urgent', tier: 1, category: 'bloods', lrPos: 3.0, rationale: 'Lactate >2 mmol/L suggests bowel ischaemia' },
      { label: 'Group & save', urgency: 'urgent', tier: 1, category: 'bloods' },
      { label: 'AXR (dilated loops, air-fluid levels, coffee-bean sign)', urgency: 'urgent', tier: 2, category: 'imaging-xr', lrPos: 3.5 },
      { label: 'CT abdomen/pelvis with IV contrast (level, cause, ischaemia) — in pregnancy MRI / ultrasound first where they answer the question', urgency: 'urgent', tier: 3, category: 'imaging-ct', lrPos: 18.0, rationale: 'Gold standard — identifies level, aetiology, ischaemia, and closed loop' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access, IV fluid resuscitation; correct electrolytes (potassium, magnesium); urinary catheter and fluid balance.' },
      { phase: 'immediate', step: 'NG tube decompression; analgesia, antiemetics.' },
      { phase: 'conservative', step: 'SBO without strangulation (e.g. adhesions): non-operative management with NG decompression and IV fluids, plus a water-soluble contrast (Gastrografin) challenge — contrast reaching the colon within 24 h predicts resolution (WSES 2017); if not resolved by 72 h, or any deterioration → laparotomy / laparoscopic adhesiolysis.' },
      { phase: 'surgical', step: 'If strangulation, a closed loop, peritonism or a hernia is the cause: emergency laparotomy / laparoscopy; resect non-viable bowel.' },
      { phase: 'surgical', step: 'Sigmoid volvulus — only if no peritonitis, ischaemia or perforation: endoscopic decompression (flexible sigmoidoscopy with a flatus / rectal tube), then sigmoid colectomy on the same admission if fit (ASCRS 2021). Ischaemia or perforation: emergency sigmoid resection.' },
      { phase: 'surgical', step: 'Caecal volvulus: endoscopic decompression is not recommended (avoid) — urgent right hemicolectomy / ileocaecal resection (ASCRS 2021).' },
      { phase: 'surgical', step: 'Left-sided malignant large bowel obstruction: resection or Hartmann\'s procedure, or a colonic stent (SEMS) as a bridge — stenting is contraindicated with perforation, impending caecal perforation, ischaemia or a closed loop (WSES 2018; ESGE 2020). Right-sided lesions: right hemicolectomy.' },
      { phase: 'conservative', step: 'Malignant obstruction (e.g. peritoneal carcinomatosis): MDT / palliative care discussion of goals of care; medical management (octreotide, hyoscine butylbromide, dexamethasone, venting gastrostomy) when surgery is not appropriate.' },
      { phase: 'followup', step: 'Elective laparoscopic adhesiolysis for recurrent adhesive obstruction.' },
    ],
    referral: 'Emergency surgical admission.',
  },
];
