import type { ManagementProtocol } from '../types.js';

export const gynaecologyProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'ectopic_pregnancy',
    icd10Prefixes: ['O00.9'],
    label: 'Ectopic Pregnancy',
    keyPoints: [
      'Classic triad: amenorrhoea, lower abdominal pain, and vaginal bleeding — but only 50% present classically.',
      'Positive β-hCG with empty uterus on transvaginal ultrasound (TVUS) = ectopic until proven otherwise.',
      'Ruptured ectopic is a life-threatening emergency: shoulder-tip pain from diaphragmatic irritation, haemodynamic collapse.',
    ],
    redFlags: [
      'Haemodynamic instability (hypotension, tachycardia) — ruptured ectopic; immediate resuscitation and emergency surgery',
      'Peritonism or board-like rigidity — haemoperitoneum',
      'β-hCG rising >63% in 48 h with no intrauterine gestational sac — high suspicion',
      'Syncope or shoulder-tip pain in a woman of reproductive age',
    ],
    investigations: [
      { label: 'Serum β-hCG (quantitative)', urgency: 'stat' },
      { label: 'Transvaginal ultrasound (TVUS) — adnexal mass, free fluid', urgency: 'stat' },
      { label: 'FBC, group and crossmatch, coagulation', urgency: 'stat' },
      { label: 'Serum β-hCG at 48 hours (discriminatory zone approach)', urgency: 'urgent' },
      { label: 'Progesterone level (low in failing pregnancies)', urgency: 'urgent' },
      { label: 'Renal function, LFTs (methotrexate suitability)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Resuscitation: two large-bore IV cannulae; IV fluids; O2; crossmatch; urgent gynaecology review.' },
      { phase: 'surgical', step: 'Ruptured/haemodynamically unstable: emergency laparoscopy (salpingectomy); laparotomy if unstable.' },
      { phase: 'surgical', step: 'Unruptured ectopic with haemodynamic stability: laparoscopic salpingectomy (preferred) or salpingostomy (if contralateral tube damaged).' },
      { phase: 'conservative', step: 'Medical management with methotrexate (50 mg/m²) for selected unruptured ectopics: β-hCG <5000 IU/L, no cardiac activity, haemodynamically stable.' },
      { phase: 'conservative', step: 'Expectant management only for very low/falling β-hCG (<1500 IU/L) in truly asymptomatic patients under close surveillance.' },
      { phase: 'followup', step: 'Serial β-hCG until undetectable (<5 IU/L) after medical/surgical management; anti-D 250 IU IM if Rh negative.' },
    ],
    referral: 'Gynaecology immediately for all suspected ectopic pregnancies; Emergency Surgery if haemodynamically unstable and gynaecology unavailable.',
  },

  {
    diseaseId: 'ovarian_torsion',
    icd10Prefixes: ['N83.5'],
    label: 'Ovarian Torsion',
    keyPoints: [
      'Twisting of the ovary on its pedicle causes ischaemia; most common in women with ovarian cysts or hyperstimulation.',
      'Sudden onset severe unilateral pelvic pain, often with nausea/vomiting; may have intermittent (partial) torsion history.',
      'Colour Doppler absence does NOT exclude torsion — diagnosis is clinical and surgical; delay causes irreversible necrosis.',
    ],
    redFlags: [
      'Sudden severe unilateral pelvic pain with nausea/vomiting — presumed torsion until laparoscopy proves otherwise',
      'Haemodynamic instability or peritonism — consider concurrent haemoperitoneum or ruptured cyst',
      'Symptoms persisting >24 hours without surgery — high risk of ovarian necrosis',
    ],
    investigations: [
      { label: 'Serum β-hCG (exclude ectopic pregnancy)', urgency: 'stat' },
      { label: 'Transvaginal/pelvic ultrasound with Doppler', urgency: 'stat' },
      { label: 'FBC, CRP, LFTs', urgency: 'urgent' },
      { label: 'Serum CA-125 (if ovarian mass — baseline for malignancy)', urgency: 'urgent' },
      { label: 'MRI pelvis (if USS equivocal and patient stable)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia (IV opioids); nil by mouth; IV access; gynaecology review urgently.' },
      { phase: 'surgical', step: 'Emergency diagnostic laparoscopy: detorsion of the ovary and ovarian cystectomy if cyst present; aim to preserve ovarian tissue even if appears dusky.' },
      { phase: 'surgical', step: 'Oophoropexy of the contralateral ovary in young patients with no underlying pathology to prevent future torsion.' },
      { phase: 'surgical', step: 'Salpingo-oophorectomy only if ovary is frankly gangrenous (black, non-viable after detorsion).' },
      { phase: 'followup', step: 'Repeat ultrasound at 6 weeks to confirm preserved ovarian function; recurrence monitoring.' },
    ],
    referral: 'Emergency Gynaecology — ovarian torsion is a surgical emergency.',
  },

  {
    diseaseId: 'pelvic_inflammatory_disease',
    icd10Prefixes: ['N73.9'],
    label: 'Pelvic Inflammatory Disease',
    keyPoints: [
      'Polymicrobial ascending infection (Chlamydia, Gonorrhoea, anaerobes); most common in sexually active women <25 years.',
      'Chandelier sign: marked cervical excitation pain on bimanual examination.',
      'Complications: Fitz-Hugh-Curtis syndrome (perihepatitis), tubo-ovarian abscess, infertility, ectopic pregnancy risk.',
    ],
    redFlags: [
      'Tubo-ovarian abscess >4 cm on ultrasound — requires IV antibiotics ± drainage',
      'Peritonism or systemic sepsis — admit for IV treatment',
      'Failure to improve after 72 hours of oral antibiotics',
      'Rupture of tubo-ovarian abscess — surgical emergency',
    ],
    investigations: [
      { label: 'High vaginal swab and endocervical swabs (NAAT for Chlamydia/Gonorrhoea)', urgency: 'urgent' },
      { label: 'FBC, CRP, ESR', urgency: 'urgent' },
      { label: 'β-hCG (exclude ectopic pregnancy)', urgency: 'stat' },
      { label: 'Transvaginal ultrasound (tubo-ovarian abscess, free fluid)', urgency: 'urgent' },
      { label: 'HIV, syphilis, hepatitis B screen (co-infection)', urgency: 'routine' },
      { label: 'Urine dipstick/MSU (exclude UTI)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia; advise abstinence from sexual intercourse; partner notification and treatment.' },
      { phase: 'conservative', step: 'Mild-moderate PID (oral regimen): doxycycline 100 mg BD + metronidazole 400 mg BD × 14 days; add IM ceftriaxone 500 mg single dose.' },
      { phase: 'conservative', step: 'Severe PID or hospitalisation required: IV cefoxitin 2 g QDS + IV doxycycline 100 mg BD; switch to oral after 24 h clinical improvement.' },
      { phase: 'conservative', step: 'Tubo-ovarian abscess: IV antibiotics; drain under ultrasound guidance if >4 cm or no clinical improvement after 48–72 h.' },
      { phase: 'surgical', step: 'Laparoscopic drainage for ruptured or persistent tubo-ovarian abscess.' },
      { phase: 'followup', step: 'Review at 72 hours; test of cure for gonorrhoea at 2 weeks; advise regarding long-term fertility risk.' },
    ],
    referral: 'Gynaecology for severe PID or tubo-ovarian abscess; Sexual Health clinic for STI contact tracing and management.',
  },

  {
    diseaseId: 'ovarian_cyst',
    icd10Prefixes: ['N83.2'],
    label: 'Ovarian Cyst',
    keyPoints: [
      'Most ovarian cysts in premenopausal women are functional (follicular, corpus luteum) and resolve within 2–3 menstrual cycles.',
      'RMI (Risk of Malignancy Index) = ultrasound score × menopausal status × CA-125; RMI >200 warrants oncology review.',
      'IOTA simple rules on ultrasound guide benign vs malignant classification for pre-operative assessment.',
    ],
    redFlags: [
      'Acute severe pain: suspect torsion or rupture — urgent surgical assessment',
      'Solid/mixed morphology, bilateral, ascites, papillary projections — high risk of malignancy',
      'CA-125 markedly elevated in postmenopausal woman',
      'Postmenopausal woman with any complex cyst >1 cm',
    ],
    investigations: [
      { label: 'Pelvic ultrasound (transvaginal preferred)', urgency: 'routine' },
      { label: 'CA-125 (premenopausal: limited specificity; essential for postmenopausal)', urgency: 'routine' },
      { label: 'β-hCG (reproductive age — exclude ectopic/pregnancy)', urgency: 'urgent' },
      { label: 'CEA, CA19-9 (if mucinous characteristics on USS)', urgency: 'routine' },
      { label: 'HE4 (human epididymis protein 4) if available — ROMA score', urgency: 'routine' },
      { label: 'MRI pelvis if USS indeterminate', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Simple cyst <5 cm in premenopausal woman: no intervention; repeat USS in 2–3 months.' },
      { phase: 'conservative', step: 'Simple cyst 5–7 cm: annual surveillance ultrasound; regression expected in premenopausal women.' },
      { phase: 'surgical', step: 'Laparoscopic cystectomy for: cyst >7 cm, complex features, symptoms, or failure to resolve.' },
      { phase: 'surgical', step: 'Postmenopausal woman with any persistent cyst: discuss with Gynaecology; strong consideration for surgical removal.' },
      { phase: 'surgical', step: 'Suspected malignancy: staging laparotomy with frozen section by Gynaecological Oncologist.' },
      { phase: 'followup', step: 'Post-cystectomy histology review; endocrine function monitoring if significant ovarian tissue removed.' },
    ],
    referral: 'Gynaecology for complex/persistent cysts; Gynaecological Oncology if RMI >200 or malignancy suspected.',
  },

  {
    diseaseId: 'endometriosis',
    icd10Prefixes: ['N80.9'],
    label: 'Endometriosis',
    keyPoints: [
      'Average diagnostic delay of 7–10 years; classic symptoms: dysmenorrhoea, deep dyspareunia, chronic pelvic pain, cyclical bowel/bladder symptoms.',
      'Laparoscopy with histological confirmation remains the gold standard for diagnosis; USS can suggest endometrioma but not peritoneal disease.',
      'Medical management suppresses disease but is not curative; definitive surgical treatment depends on symptoms, location, and fertility wishes.',
    ],
    redFlags: [
      'Acute severe pelvic pain: suspect ruptured endometrioma or torsion',
      'Ureteric or bowel endometriosis causing obstruction — specialist multidisciplinary surgery required',
      'Infertility in known endometriosis — early referral to reproductive medicine',
    ],
    investigations: [
      { label: 'Transvaginal ultrasound (homogeneous "ground-glass" endometrioma)', urgency: 'routine' },
      { label: 'MRI pelvis (deep infiltrating endometriosis — bowel, bladder, parametria)', urgency: 'routine' },
      { label: 'CA-125 (non-specific; may be mildly elevated)', urgency: 'routine' },
      { label: 'Laparoscopy with biopsy (definitive diagnosis)', urgency: 'routine' },
      { label: 'Renal ultrasound (if ureteric involvement suspected)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'First-line hormonal suppression: combined oral contraceptive pill (continuous), progestogen (norethisterone, desogestrel), or LNG-IUS.' },
      { phase: 'conservative', step: 'Second-line: GnRH analogues (leuprorelin, goserelin) for 6 months ± add-back oestrogen; danazol now rarely used.' },
      { phase: 'conservative', step: 'NSAIDs for dysmenorrhoea; paracetamol and opioids for breakthrough pain.' },
      { phase: 'surgical', step: 'Laparoscopic excision or ablation of endometriotic deposits; ovarian cystectomy for endometrioma (not drainage alone).' },
      { phase: 'surgical', step: 'Deep infiltrating endometriosis: multidisciplinary surgery involving colorectal surgery, urology, and specialist gynaecology.' },
      { phase: 'followup', step: 'Long-term hormonal suppression after surgery to reduce recurrence; reproductive medicine referral for fertility concerns.' },
    ],
    referral: 'Gynaecology; Endometriosis specialist centre for deep infiltrating disease; Reproductive Medicine for fertility.',
  },

  {
    diseaseId: 'uterine_fibroids',
    icd10Prefixes: ['D25.9'],
    label: 'Uterine Fibroids (Leiomyomata)',
    keyPoints: [
      'Most common pelvic tumour in women (up to 70% by age 50); more prevalent and symptomatic in Afro-Caribbean women.',
      'Submucosal fibroids cause heavy menstrual bleeding and infertility disproportionate to their size.',
      'Hysterectomy is the only definitive cure; fertility-preserving options include myomectomy, uterine artery embolisation (UAE), and MRI-guided focused ultrasound.',
    ],
    redFlags: [
      'Severe anaemia from acute haemorrhage — IV iron infusion, transfusion, and urgent haemostasis',
      'Rapid uterine growth in peri/postmenopausal woman — exclude uterine sarcoma',
      'Urinary retention or hydronephrosis from compressive fibroid',
      'Red degeneration in pregnancy: severe localised uterine pain with fever — supportive management',
    ],
    investigations: [
      { label: 'Pelvic ultrasound (transabdominal + transvaginal)', urgency: 'routine' },
      { label: 'FBC (exclude iron-deficiency anaemia from HMB)', urgency: 'routine' },
      { label: 'Ferritin, iron studies', urgency: 'routine' },
      { label: 'MRI pelvis (pre-operative mapping, UAE planning, adenomyosis assessment)', urgency: 'routine' },
      { label: 'Endometrial biopsy if abnormal uterine bleeding (exclude endometrial pathology)', urgency: 'urgent' },
      { label: 'Hysteroscopy (submucosal fibroid assessment)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Heavy menstrual bleeding: tranexamic acid 1 g QDS during menses; NSAIDs.' },
      { phase: 'conservative', step: 'Hormonal: LNG-IUS (if uterine cavity not distorted), combined OCP, or progestogens for HMB control.' },
      { phase: 'conservative', step: 'GnRH analogues (ulipristal acetate where available) pre-operatively to shrink fibroids and correct anaemia.' },
      { phase: 'conservative', step: 'Uterine artery embolisation (UAE): effective for bulk symptoms; not ideal for fertility preservation.' },
      { phase: 'surgical', step: 'Hysteroscopic myomectomy for submucosal fibroids; laparoscopic/open myomectomy for intramural/subserosal (fertility-preserving).' },
      { phase: 'surgical', step: 'Hysterectomy (abdominal, laparoscopic, or vaginal) for definitive treatment in women who have completed childbearing.' },
      { phase: 'followup', step: 'Post-UAE/myomectomy: MRI at 3 months to assess response; haematological review for anaemia.' },
    ],
    referral: 'Gynaecology; Interventional Radiology for UAE; Reproductive Medicine if fertility is a concern.',
  },

  {
    diseaseId: 'cervical_carcinoma',
    icd10Prefixes: ['C53.9'],
    label: 'Cervical Carcinoma',
    keyPoints: [
      'HPV types 16 and 18 cause ~70% of cervical cancers; squamous cell carcinoma most common histology.',
      'Early disease (Stage IA–IIA): treated with radical hysterectomy + pelvic lymph node dissection or definitive chemoradiotherapy.',
      'FIGO staging is clinical; MRI pelvis is essential for local staging before treatment planning.',
    ],
    redFlags: [
      'Postcoital or irregular vaginal bleeding — colposcopy urgently if CIN3/cancer suspected',
      'Advanced disease: haematuria, rectal bleeding, leg oedema from lymph node or ureteric involvement',
      'Cervical mass visible on speculum examination — urgent gynaecology oncology referral',
    ],
    investigations: [
      { label: 'Cervical biopsy (under colposcopy)', urgency: 'urgent' },
      { label: 'MRI pelvis (local staging — parametrial involvement)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (distant metastasis staging)', urgency: 'urgent' },
      { label: 'FBC, renal function (ureteric obstruction)', urgency: 'urgent' },
      { label: 'HPV genotyping (type 16/18 associated with higher risk)', urgency: 'routine' },
      { label: 'PET-CT (lymph node and distant disease — where available)', urgency: 'routine' },
      { label: 'SCC antigen (squamous cell carcinoma antigen) — tumour marker', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Acute haemorrhage: vaginal packing; transfusion; haemostatic radiotherapy urgently.' },
      { phase: 'surgical', step: 'Stage IA1: cone biopsy (fertility-sparing) or simple hysterectomy.' },
      { phase: 'surgical', step: 'Stage IA2–IIA: radical hysterectomy (Wertheim\'s) + bilateral pelvic lymphadenectomy; or definitive chemoradiotherapy — equivalent outcomes.' },
      { phase: 'conservative', step: 'Stage IIB–IVA: concurrent platinum-based chemoradiotherapy + brachytherapy (definitive).' },
      { phase: 'conservative', step: 'Recurrent/metastatic: pembrolizumab (PD-L1 positive) + chemotherapy (bevacizumab + carboplatin + paclitaxel).' },
      { phase: 'followup', step: 'Clinical review every 3 months for 2 years, then 6-monthly; vault smear if radiotherapy; MRI for local recurrence.' },
    ],
    referral: 'Urgent Gynaecological Oncology; Radiation Oncology; MDT review before treatment decision.',
  },

  {
    diseaseId: 'ovarian_carcinoma',
    icd10Prefixes: ['C56.9'],
    label: 'Ovarian Carcinoma',
    keyPoints: [
      '70% present at advanced stage (III–IV) due to non-specific symptoms; CA-125 and pelvic USS are initial investigations.',
      'High-grade serous carcinoma is the most common and aggressive histotype; BRCA1/2 mutations confer increased risk.',
      'Primary debulking surgery (PDS) to no residual disease improves survival; neoadjuvant chemotherapy considered if PDS not achievable.',
    ],
    redFlags: [
      'Ascites with pelvic mass — ovarian carcinoma until proven otherwise',
      'CA-125 >500 U/mL in postmenopausal woman',
      'Bowel obstruction from peritoneal disease',
      'Deep vein thrombosis in a woman with pelvic mass (Trousseau\'s syndrome)',
    ],
    investigations: [
      { label: 'CA-125, HE4, ROMA score', urgency: 'urgent' },
      { label: 'Pelvic ultrasound (transvaginal)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'FBC, renal function, LFTs, coagulation', urgency: 'urgent' },
      { label: 'BRCA1/2 germline testing (all high-grade serous carcinomas)', urgency: 'routine' },
      { label: 'PET-CT (if CT equivocal for staging)', urgency: 'routine' },
      { label: 'Ascites cytology (paracentesis if large volume)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Primary debulking surgery (PDS): total abdominal hysterectomy, bilateral salpingo-oophorectomy, omentectomy, appendicectomy, pelvic/para-aortic lymphadenectomy.' },
      { phase: 'conservative', step: 'Neoadjuvant chemotherapy (carboplatin + paclitaxel × 3 cycles) if PDS upfront not achievable; interval debulking surgery after 3 cycles.' },
      { phase: 'conservative', step: 'Adjuvant chemotherapy: carboplatin + paclitaxel × 6 cycles for FIGO stage IC and above.' },
      { phase: 'conservative', step: 'PARP inhibitor maintenance (olaparib/niraparib) after platinum-sensitive first relapse, especially if BRCA mutated.' },
      { phase: 'followup', step: 'CA-125 and clinical review 3-monthly × 2 years; CT if CA-125 rising.' },
    ],
    referral: 'Urgent Gynaecological Oncology; MDT with Oncology, Radiology, Pathology.',
  },

  {
    diseaseId: 'uterine_carcinoma',
    icd10Prefixes: ['C54.1'],
    label: 'Uterine (Endometrial) Carcinoma',
    keyPoints: [
      'Most common gynaecological malignancy in high-income countries; 90% present with postmenopausal bleeding — a red flag symptom.',
      'Risk factors: obesity, nulliparity, late menopause, oestrogen-only HRT, tamoxifen, diabetes, PCOS.',
      'Endometrial biopsy (Pipelle) or hysteroscopy + biopsy is diagnostic; MRI for staging.',
    ],
    redFlags: [
      'Postmenopausal bleeding — endometrial carcinoma until excluded by biopsy',
      'Abnormal uterine bleeding in high-risk premenopausal women (obesity, PCOS, tamoxifen use)',
      'Pyometra in postmenopausal woman — carcinoma must be excluded',
    ],
    investigations: [
      { label: 'Endometrial biopsy (Pipelle) or hysteroscopy + biopsy', urgency: 'urgent' },
      { label: 'Transvaginal ultrasound (endometrial thickness; >4 mm in PMB is significant)', urgency: 'urgent' },
      { label: 'MRI pelvis (myometrial invasion depth, cervical extension — FIGO staging)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (lymph node and metastatic staging)', urgency: 'urgent' },
      { label: 'CA-125 (elevated in advanced/serous histotype)', urgency: 'routine' },
      { label: 'Mismatch repair (MMR) IHC / Lynch syndrome testing (all endometrial cancers)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Total hysterectomy + bilateral salpingo-oophorectomy (TH+BSO) ± pelvic/para-aortic lymphadenectomy — laparoscopic preferred.' },
      { phase: 'surgical', step: 'Sentinel lymph node mapping increasingly used for low-intermediate risk disease.' },
      { phase: 'conservative', step: 'Adjuvant radiotherapy (external beam pelvic RT ± vaginal vault brachytherapy) for intermediate/high-risk disease.' },
      { phase: 'conservative', step: 'Progestin therapy (medroxyprogesterone acetate 160 mg OD) for Grade 1 disease confined to endometrium in women wishing to preserve fertility — close surveillance mandatory.' },
      { phase: 'conservative', step: 'Chemotherapy (carboplatin + paclitaxel) for high-grade serous or advanced/recurrent disease; pembrolizumab for MMR-deficient recurrent disease.' },
      { phase: 'followup', step: 'Clinical review 3-monthly × 2 years; TVS and MRI for symptomatic recurrence.' },
    ],
    referral: 'Gynaecological Oncology; MDT review mandatory before treatment.',
  },

  {
    diseaseId: 'bartholin_abscess',
    icd10Prefixes: ['N75.1'],
    label: 'Bartholin\'s Abscess',
    keyPoints: [
      'Bartholin\'s glands (greater vestibular glands) drain at 4 and 8 o\'clock positions of the vaginal introitus; obstruction leads to cyst, infection causes abscess.',
      'Word catheter insertion or marsupialization is preferred over simple incision and drainage (high recurrence).',
      'In women >40 years, excision biopsy of the gland should be considered to exclude Bartholin\'s gland carcinoma.',
    ],
    redFlags: [
      'Systemic sepsis from ascending infection — IV antibiotics and urgent drainage',
      'Bartholin\'s gland mass in postmenopausal woman — carcinoma must be excluded by biopsy',
      'Rapidly enlarging or necrotising infection',
    ],
    investigations: [
      { label: 'Swab of abscess contents (NAAT for Gonorrhoea, Chlamydia; culture)', urgency: 'urgent' },
      { label: 'FBC, CRP (if systemic sepsis suspected)', urgency: 'urgent' },
      { label: 'β-hCG (reproductive-age women)', urgency: 'routine' },
      { label: 'Histology of excised Bartholin\'s gland tissue (women >40 years)', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia; consider sitz baths for comfort; antibiotics (co-amoxiclav or doxycycline + metronidazole) if systemic features.' },
      { phase: 'surgical', step: 'Word catheter insertion: stab incision into abscess at mucosal surface; insert balloon catheter; inflate with 2–3 mL saline; leave 4–6 weeks for epithelialisation.' },
      { phase: 'surgical', step: 'Marsupialization under LA/GA: elliptical excision of abscess wall; suture edges to vaginal mucosa creating permanent ostium.' },
      { phase: 'surgical', step: 'Bartholin\'s gland excision: for recurrent disease, persistent cyst, or postmenopausal women (to exclude carcinoma).' },
      { phase: 'followup', step: 'Review at 6 weeks for Word catheter removal; assess for recurrence; treat sexual partner if STI isolated.' },
    ],
    referral: 'Gynaecology for marsupialization or excision; Sexual Health for STI contact tracing if gonorrhoea or chlamydia isolated.',
  },
];
