import type { ManagementProtocol } from '../types.js';

export const gynaecologyProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'ectopic_pregnancy',
    icd10Prefixes: ['O00.9'],
    label: 'Ectopic Pregnancy',
    keyPoints: [
      'Classic triad: amenorrhoea, lower abdominal pain, and vaginal bleeding — but only 50% present classically.',
      'Positive β-hCG with empty uterus on transvaginal ultrasound (TVUS) = ectopic until proven otherwise.',
      'Ruptured ectopic is a life-threatening emergency: shoulder-tip pain from diaphragmatic irritation, haemodynamic collapse.',
    ],
    redFlags: [
      'Haemodynamic instability (hypotension, tachycardia) — ruptured ectopic; immediate resuscitation and emergency surgery',
      'Peritonism or board-like rigidity — haemoperitoneum',
      'β-hCG rising >63% in 48 h with no intrauterine gestational sac — high suspicion',
      'Syncope or shoulder-tip pain in a woman of reproductive age',
    ],
    investigations: [
      { label: 'Serum β-hCG (quantitative)', urgency: 'stat' },
      { label: 'Transvaginal ultrasound (TVUS) — adnexal mass, free fluid', urgency: 'stat' },
      { label: 'FBC, group and crossmatch, coagulation', urgency: 'stat' },
      { label: 'Serum β-hCG at 48 hours (discriminatory zone approach)', urgency: 'urgent' },
      { label: 'Progesterone level (low in failing pregnancies)', urgency: 'urgent' },
      { label: 'Renal function, LFTs (methotrexate suitability)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Resuscitation: two large-bore IV cannulae; IV fluids; O2; crossmatch; urgent gynaecology review.' },
      { phase: 'surgical', step: 'Ruptured/haemodynamically unstable: emergency laparoscopy (salpingectomy); laparotomy if unstable.' },
      { phase: 'surgical', step: 'Unruptured ectopic with haemodynamic stability: laparoscopic salpingectomy (preferred) or salpingostomy (if contralateral tube damaged).' },
      { phase: 'conservative', step: 'Medical management with methotrexate (50 mg/m²) for selected unruptured ectopics: β-hCG <5000 IU/L, no cardiac activity, haemodynamically stable.' },
      { phase: 'conservative', step: 'Expectant management only for very low/falling β-hCG (<1500 IU/L) in truly asymptomatic patients under close surveillance.' },
      { phase: 'followup', step: 'Serial β-hCG until undetectable (<5 IU/L) after medical/surgical management; anti-D 250 IU IM if Rh negative.' },
    ],
    medications: [
      { drugName: 'Methotrexate', dose: '50 mg/m²', frequency: 'Single dose', route: 'IM (intramuscular)', indication: 'Medical management — β-hCG <5000 IU/L, no cardiac activity, haemodynamically stable; folic acid antagonist', phase: 'immediate' },
      { drugName: 'Anti-D immunoglobulin', dose: '250 IU', frequency: 'Single dose', route: 'IM (intramuscular)', indication: 'Rh-negative patients — prevents Rh sensitisation', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia — pre-surgery or during expectant monitoring', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic — post-methotrexate', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia post-procedure', phase: 'discharge' },
    ],
    referral: 'Gynaecology immediately for all suspected ectopic pregnancies; Emergency Surgery if haemodynamically unstable and gynaecology unavailable.',
  },

  {
    diseaseId: 'ovarian_torsion',
    icd10Prefixes: ['N83.5'],
    label: 'Ovarian Torsion',
    keyPoints: [
      'Twisting of the ovary on its pedicle causes ischaemia; most common in women with ovarian cysts or hyperstimulation.',
      'Sudden onset severe unilateral pelvic pain, often with nausea/vomiting; may have intermittent (partial) torsion history.',
      'Colour Doppler absence does NOT exclude torsion — diagnosis is clinical and surgical; delay causes irreversible necrosis.',
    ],
    redFlags: [
      'Sudden severe unilateral pelvic pain with nausea/vomiting — presumed torsion until laparoscopy proves otherwise',
      'Haemodynamic instability or peritonism — consider concurrent haemoperitoneum or ruptured cyst',
      'Symptoms persisting >24 hours without surgery — high risk of ovarian necrosis',
    ],
    investigations: [
      { label: 'Serum β-hCG (exclude ectopic pregnancy)', urgency: 'stat' },
      { label: 'Transvaginal/pelvic ultrasound with Doppler', urgency: 'stat' },
      { label: 'FBC, CRP, LFTs', urgency: 'urgent' },
      { label: 'Serum CA-125 (if ovarian mass — baseline for malignancy)', urgency: 'urgent' },
      { label: 'MRI pelvis (if USS equivocal and patient stable)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia (IV opioids); nil by mouth; IV access; gynaecology review urgently.' },
      { phase: 'surgical', step: 'Emergency diagnostic laparoscopy: detorsion of the ovary and ovarian cystectomy if cyst present; aim to preserve ovarian tissue even if appears dusky.' },
      { phase: 'surgical', step: 'Oophoropexy of the contralateral ovary in young patients with no underlying pathology to prevent future torsion.' },
      { phase: 'surgical', step: 'Salpingo-oophorectomy only if ovary is frankly gangrenous (black, non-viable after detorsion).' },
      { phase: 'followup', step: 'Repeat ultrasound at 6 weeks to confirm preserved ovarian function; recurrence monitoring.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Pre-operative analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: "Hartmann's solution", dose: '1 L', frequency: 'Over 4 hours', route: 'IV (intravenous)', indication: 'IV fluid resuscitation', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV/PO (intravenous/oral)', indication: 'Post-operative multimodal analgesia', phase: 'immediate' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5 days', indication: 'Anti-inflammatory — post-discharge', phase: 'discharge' },
    ],
    referral: 'Emergency Gynaecology — ovarian torsion is a surgical emergency.',
  },

  {
    diseaseId: 'pelvic_inflammatory_disease',
    icd10Prefixes: ['N73.9'],
    label: 'Pelvic Inflammatory Disease',
    keyPoints: [
      'Polymicrobial ascending infection (Chlamydia, Gonorrhoea, anaerobes); most common in sexually active women <25 years.',
      'Chandelier sign: marked cervical excitation pain on bimanual examination.',
      'Complications: Fitz-Hugh-Curtis syndrome (perihepatitis), tubo-ovarian abscess, infertility, ectopic pregnancy risk.',
    ],
    redFlags: [
      'Tubo-ovarian abscess >4 cm on ultrasound — requires IV antibiotics ± drainage',
      'Peritonism or systemic sepsis — admit for IV treatment',
      'Failure to improve after 72 hours of oral antibiotics',
      'Rupture of tubo-ovarian abscess — surgical emergency',
    ],
    investigations: [
      { label: 'High vaginal swab and endocervical swabs (NAAT for Chlamydia/Gonorrhoea)', urgency: 'urgent' },
      { label: 'FBC, CRP, ESR', urgency: 'urgent' },
      { label: 'β-hCG (exclude ectopic pregnancy)', urgency: 'stat' },
      { label: 'Transvaginal ultrasound (tubo-ovarian abscess, free fluid)', urgency: 'urgent' },
      { label: 'HIV, syphilis, hepatitis B screen (co-infection)', urgency: 'routine' },
      { label: 'Urine dipstick/MSU (exclude UTI)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia; advise abstinence from sexual intercourse; partner notification and treatment.' },
      { phase: 'conservative', step: 'Mild-moderate PID (oral regimen): doxycycline 100 mg BD + metronidazole 400 mg BD × 14 days; add IM ceftriaxone 500 mg single dose.' },
      { phase: 'conservative', step: 'Severe PID or hospitalisation required: IV cefoxitin 2 g QDS + IV doxycycline 100 mg BD; switch to oral after 24 h clinical improvement.' },
      { phase: 'conservative', step: 'Tubo-ovarian abscess: IV antibiotics; drain under ultrasound guidance if >4 cm or no clinical improvement after 48–72 h.' },
      { phase: 'surgical', step: 'Laparoscopic drainage for ruptured or persistent tubo-ovarian abscess.' },
      { phase: 'followup', step: 'Review at 72 hours; test of cure for gonorrhoea at 2 weeks; advise regarding long-term fertility risk.' },
    ],
    medications: [
      { drugName: 'Ceftriaxone', dose: '500 mg', frequency: 'Single dose', route: 'IM (intramuscular)', indication: 'Gonorrhoea cover — required in all PID regimens', phase: 'immediate' },
      { drugName: 'Cefoxitin', dose: '2 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', indication: 'Severe or hospitalised PID — first-line inpatient', phase: 'immediate' },
      { drugName: 'Doxycycline', dose: '100 mg', frequency: 'BD (twice daily)', route: 'IV (intravenous)', indication: 'Severe PID inpatient — use together with cefoxitin', phase: 'immediate', alternativeTo: 'Cefoxitin — use together' },
      { drugName: 'Metronidazole', dose: '500 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Severe anaerobic cover — inpatient regimen', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO/IV (oral/intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Doxycycline', dose: '100 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '14 days', indication: 'Mild-moderate PID — oral outpatient or step-down after IV', phase: 'discharge' },
      { drugName: 'Metronidazole', dose: '400 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '14 days', indication: 'Anaerobic cover for mild-moderate PID — use with doxycycline', phase: 'discharge' },
    ],
    referral: 'Gynaecology for severe PID or tubo-ovarian abscess; Sexual Health clinic for STI contact tracing and management.',
  },

  {
    diseaseId: 'ovarian_cyst',
    icd10Prefixes: ['N83.2'],
    label: 'Ovarian Cyst',
    keyPoints: [
      'Most ovarian cysts in premenopausal women are functional (follicular, corpus luteum) and resolve within 2–3 menstrual cycles.',
      'RMI (Risk of Malignancy Index) = ultrasound score × menopausal status × CA-125; RMI >200 warrants oncology review.',
      'IOTA simple rules on ultrasound guide benign vs malignant classification for pre-operative assessment.',
    ],
    redFlags: [
      'Acute severe pain: suspect torsion or rupture — urgent surgical assessment',
      'Solid/mixed morphology, bilateral, ascites, papillary projections — high risk of malignancy',
      'CA-125 markedly elevated in postmenopausal woman',
      'Postmenopausal woman with any complex cyst >1 cm',
    ],
    investigations: [
      { label: 'Pelvic ultrasound (transvaginal preferred)', urgency: 'routine' },
      { label: 'CA-125 (premenopausal: limited specificity; essential for postmenopausal)', urgency: 'routine' },
      { label: 'β-hCG (reproductive age — exclude ectopic/pregnancy)', urgency: 'urgent' },
      { label: 'CEA, CA19-9 (if mucinous characteristics on USS)', urgency: 'routine' },
      { label: 'HE4 (human epididymis protein 4) if available — ROMA score', urgency: 'routine' },
      { label: 'MRI pelvis if USS indeterminate', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Simple cyst <5 cm in premenopausal woman: no intervention; repeat USS in 2–3 months.' },
      { phase: 'conservative', step: 'Simple cyst 5–7 cm: annual surveillance ultrasound; regression expected in premenopausal women.' },
      { phase: 'surgical', step: 'Laparoscopic cystectomy for: cyst >7 cm, complex features, symptoms, or failure to resolve.' },
      { phase: 'surgical', step: 'Postmenopausal woman with any persistent cyst: discuss with Gynaecology; strong consideration for surgical removal.' },
      { phase: 'surgical', step: 'Suspected malignancy: staging laparotomy with frozen section by Gynaecological Oncologist.' },
      { phase: 'followup', step: 'Post-cystectomy histology review; endocrine function monitoring if significant ovarian tissue removed.' },
    ],
    medications: [
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia for symptomatic cysts', phase: 'discharge' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily) with food', route: 'PO (oral)', indication: 'Anti-inflammatory for pain', phase: 'discharge' },
      { drugName: 'Combined oral contraceptive pill', dose: 'Per preparation', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Suppresses functional cyst recurrence — specific agent per gynaecology preference; no benefit for established cysts', phase: 'maintenance' },
    ],
    referral: 'Gynaecology for complex/persistent cysts; Gynaecological Oncology if RMI >200 or malignancy suspected.',
  },

  {
    diseaseId: 'endometriosis',
    icd10Prefixes: ['N80.9'],
    label: 'Endometriosis',
    keyPoints: [
      'Average diagnostic delay of 7–10 years; classic symptoms: dysmenorrhoea, deep dyspareunia, chronic pelvic pain, cyclical bowel/bladder symptoms.',
      'Laparoscopy with histological confirmation remains the gold standard for diagnosis; USS can suggest endometrioma but not peritoneal disease.',
      'Medical management suppresses disease but is not curative; definitive surgical treatment depends on symptoms, location, and fertility wishes.',
    ],
    redFlags: [
      'Acute severe pelvic pain: suspect ruptured endometrioma or torsion',
      'Ureteric or bowel endometriosis causing obstruction — specialist multidisciplinary surgery required',
      'Infertility in known endometriosis — early referral to reproductive medicine',
    ],
    investigations: [
      { label: 'Transvaginal ultrasound (homogeneous "ground-glass" endometrioma)', urgency: 'routine' },
      { label: 'MRI pelvis (deep infiltrating endometriosis — bowel, bladder, parametria)', urgency: 'routine' },
      { label: 'CA-125 (non-specific; may be mildly elevated)', urgency: 'routine' },
      { label: 'Laparoscopy with biopsy (definitive diagnosis)', urgency: 'routine' },
      { label: 'Renal ultrasound (if ureteric involvement suspected)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'First-line hormonal suppression: combined oral contraceptive pill (continuous), progestogen (norethisterone, desogestrel), or LNG-IUS.' },
      { phase: 'conservative', step: 'Second-line: GnRH analogues (leuprorelin, goserelin) for 6 months ± add-back oestrogen; danazol now rarely used.' },
      { phase: 'conservative', step: 'NSAIDs for dysmenorrhoea; paracetamol and opioids for breakthrough pain.' },
      { phase: 'surgical', step: 'Laparoscopic excision or ablation of endometriotic deposits; ovarian cystectomy for endometrioma (not drainage alone).' },
      { phase: 'surgical', step: 'Deep infiltrating endometriosis: multidisciplinary surgery involving colorectal surgery, urology, and specialist gynaecology.' },
      { phase: 'followup', step: 'Long-term hormonal suppression after surgery to reduce recurrence; reproductive medicine referral for fertility concerns.' },
    ],
    medications: [
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'First-line analgesia', phase: 'discharge' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'NSAID for dysmenorrhoea', phase: 'discharge' },
      { drugName: 'Norethisterone', dose: '5 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Progestogen — continuous use to suppress cycles and endometriosis activity', phase: 'maintenance' },
      { drugName: 'Levonorgestrel IUS (Mirena)', dose: '52 mg', frequency: 'Single device (5-year duration)', route: 'Intrauterine', indication: 'LNG-IUS — first-line hormonal management; reduces dysmenorrhoea and pelvic pain', phase: 'maintenance' },
      { drugName: 'Combined oral contraceptive pill', dose: 'Per preparation', frequency: 'OD (once daily) — continuous (no pill-free interval)', route: 'PO (oral)', indication: 'Continuous COCP — suppresses endometriosis activity; first-line hormonal therapy', phase: 'maintenance' },
      { drugName: 'Leuprorelin acetate', dose: '3.75 mg', frequency: 'Monthly', route: 'IM (intramuscular)', duration: 'Up to 6 months', indication: 'GnRH analogue — add-back oestrogen if course >3 months to reduce bone loss', phase: 'maintenance' },
      { drugName: 'Goserelin', dose: '3.6 mg', frequency: 'Monthly', route: 'SC (subcutaneous)', duration: 'Up to 6 months', indication: 'GnRH analogue — alternative to leuprorelin', phase: 'maintenance', alternativeTo: 'Leuprorelin acetate' },
      { drugName: 'Norethisterone', dose: '5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Add-back HRT — co-prescribe with GnRH analogues to reduce vasomotor symptoms and bone loss', phase: 'maintenance' },
    ],
    referral: 'Gynaecology; Endometriosis specialist centre for deep infiltrating disease; Reproductive Medicine for fertility.',
  },

  {
    diseaseId: 'uterine_fibroids',
    icd10Prefixes: ['D25.9'],
    label: 'Uterine Fibroids (Leiomyomata)',
    keyPoints: [
      'Most common pelvic tumour in women (up to 70% by age 50); more prevalent and symptomatic in Afro-Caribbean women.',
      'Submucosal fibroids cause heavy menstrual bleeding and infertility disproportionate to their size.',
      'Hysterectomy is the only definitive cure; fertility-preserving options include myomectomy, uterine artery embolisation (UAE), and MRI-guided focused ultrasound.',
    ],
    redFlags: [
      'Severe anaemia from acute haemorrhage — IV iron infusion, transfusion, and urgent haemostasis',
      'Rapid uterine growth in peri/postmenopausal woman — exclude uterine sarcoma',
      'Urinary retention or hydronephrosis from compressive fibroid',
      'Red degeneration in pregnancy: severe localised uterine pain with fever — supportive management',
    ],
    investigations: [
      { label: 'Pelvic ultrasound (transabdominal + transvaginal)', urgency: 'routine' },
      { label: 'FBC (exclude iron-deficiency anaemia from HMB)', urgency: 'routine' },
      { label: 'Ferritin, iron studies', urgency: 'routine' },
      { label: 'MRI pelvis (pre-operative mapping, UAE planning, adenomyosis assessment)', urgency: 'routine' },
      { label: 'Endometrial biopsy if abnormal uterine bleeding (exclude endometrial pathology)', urgency: 'urgent' },
      { label: 'Hysteroscopy (submucosal fibroid assessment)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Heavy menstrual bleeding: tranexamic acid 1 g QDS during menses; NSAIDs.' },
      { phase: 'conservative', step: 'Hormonal: LNG-IUS (if uterine cavity not distorted), combined OCP, or progestogens for HMB control.' },
      { phase: 'conservative', step: 'GnRH analogues (ulipristal acetate where available) pre-operatively to shrink fibroids and correct anaemia.' },
      { phase: 'conservative', step: 'Uterine artery embolisation (UAE): effective for bulk symptoms; not ideal for fertility preservation.' },
      { phase: 'surgical', step: 'Hysteroscopic myomectomy for submucosal fibroids; laparoscopic/open myomectomy for intramural/subserosal (fertility-preserving).' },
      { phase: 'surgical', step: 'Hysterectomy (abdominal, laparoscopic, or vaginal) for definitive treatment in women who have completed childbearing.' },
      { phase: 'followup', step: 'Post-UAE/myomectomy: MRI at 3 months to assess response; haematological review for anaemia.' },
    ],
    medications: [
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'QDS (four times daily) during menstruation', route: 'PO (oral)', duration: '5 days per cycle', indication: 'Antifibrinolytic — heavy menstrual bleeding', phase: 'discharge' },
      { drugName: 'Mefenamic acid', dose: '500 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'NSAID for menorrhagia ± dysmenorrhoea', phase: 'discharge' },
      { drugName: 'Levonorgestrel IUS (Mirena)', dose: '52 mg', frequency: 'Single device (5-year duration)', route: 'Intrauterine', indication: 'LNG-IUS — reduces HMB by up to 80%; only if uterine cavity not significantly distorted', phase: 'maintenance' },
      { drugName: 'Norethisterone', dose: '5 mg', frequency: 'TDS (three times daily) on days 5–26 of cycle', route: 'PO (oral)', indication: 'Cyclic progestogen — reduces heavy menstrual bleeding', phase: 'maintenance' },
      { drugName: 'Leuprorelin acetate', dose: '3.75 mg', frequency: 'Monthly', route: 'IM (intramuscular)', duration: '3–6 months pre-operatively', indication: 'GnRH analogue — pre-operative fibroid shrinkage and anaemia correction', phase: 'immediate' },
      { drugName: 'Ulipristal acetate', dose: '5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '3 months', indication: 'SPRM — pre-operative fibroid volume reduction; where available', phase: 'maintenance' },
      { drugName: 'Ferrous sulfate', dose: '200 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Iron supplementation for iron-deficiency anaemia from heavy menstrual bleeding', phase: 'discharge' },
    ],
    referral: 'Gynaecology; Interventional Radiology for UAE; Reproductive Medicine if fertility is a concern.',
  },

  {
    diseaseId: 'cervical_carcinoma',
    icd10Prefixes: ['C53.9'],
    label: 'Cervical Carcinoma',
    keyPoints: [
      'HPV types 16 and 18 cause ~70% of cervical cancers; squamous cell carcinoma most common histology.',
      'Early disease (Stage IA–IIA): treated with radical hysterectomy + pelvic lymph node dissection or definitive chemoradiotherapy.',
      'FIGO staging is clinical; MRI pelvis is essential for local staging before treatment planning.',
    ],
    redFlags: [
      'Postcoital or irregular vaginal bleeding — colposcopy urgently if CIN3/cancer suspected',
      'Advanced disease: haematuria, rectal bleeding, leg oedema from lymph node or ureteric involvement',
      'Cervical mass visible on speculum examination — urgent gynaecology oncology referral',
    ],
    investigations: [
      { label: 'Cervical biopsy (under colposcopy)', urgency: 'urgent' },
      { label: 'MRI pelvis (local staging — parametrial involvement)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (distant metastasis staging)', urgency: 'urgent' },
      { label: 'FBC, renal function (ureteric obstruction)', urgency: 'urgent' },
      { label: 'HPV genotyping (type 16/18 associated with higher risk)', urgency: 'routine' },
      { label: 'PET-CT (lymph node and distant disease — where available)', urgency: 'routine' },
      { label: 'SCC antigen (squamous cell carcinoma antigen) — tumour marker', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Acute haemorrhage: vaginal packing; transfusion; haemostatic radiotherapy urgently.' },
      { phase: 'surgical', step: 'Stage IA1: cone biopsy (fertility-sparing) or simple hysterectomy.' },
      { phase: 'surgical', step: "Stage IA2–IIA: radical hysterectomy (Wertheim's) + bilateral pelvic lymphadenectomy; or definitive chemoradiotherapy — equivalent outcomes." },
      { phase: 'conservative', step: 'Stage IIB–IVA: concurrent platinum-based chemoradiotherapy + brachytherapy (definitive).' },
      { phase: 'conservative', step: 'Recurrent/metastatic: pembrolizumab (PD-L1 positive) + chemotherapy (bevacizumab + carboplatin + paclitaxel).' },
      { phase: 'followup', step: 'Clinical review every 3 months for 2 years, then 6-monthly; vault smear if radiotherapy; MRI for local recurrence.' },
    ],
    medications: [
      { drugName: 'Cisplatin', dose: '40 mg/m²', frequency: 'Weekly', route: 'IV (intravenous)', indication: 'Concurrent with external beam radiotherapy — refer to oncology', phase: 'immediate' },
      { drugName: 'Carboplatin', dose: 'AUC5', frequency: 'Every 3–4 weeks', route: 'IV (intravenous)', indication: 'Alternative to cisplatin if renal impairment; recurrent or metastatic disease', phase: 'maintenance', alternativeTo: 'Cisplatin' },
      { drugName: 'Paclitaxel', dose: '175 mg/m²', frequency: 'Every 3 weeks', route: 'IV (intravenous)', indication: 'Combination with carboplatin for recurrent or metastatic disease', phase: 'maintenance' },
      { drugName: 'Bevacizumab', dose: '15 mg/kg', frequency: 'Every 3 weeks', route: 'IV (intravenous)', indication: 'VEGF inhibitor — recurrent or metastatic cervical carcinoma', phase: 'maintenance' },
      { drugName: 'Pembrolizumab', dose: '200 mg', frequency: 'Every 3 weeks', route: 'IV (intravenous)', indication: 'PD-L1 positive recurrent or metastatic disease — immunotherapy', phase: 'maintenance' },
      { drugName: 'Ondansetron', dose: '8 mg', frequency: 'TDS (three times daily)', route: 'IV/PO (intravenous/oral)', indication: 'Chemotherapy-induced nausea and vomiting', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO/IV (oral/intravenous)', indication: 'Analgesia', phase: 'immediate' },
    ],
    referral: 'Urgent Gynaecological Oncology; Radiation Oncology; MDT review before treatment decision.',
  },

  {
    diseaseId: 'ovarian_carcinoma',
    icd10Prefixes: ['C56.9'],
    label: 'Ovarian Carcinoma',
    keyPoints: [
      '70% present at advanced stage (III–IV) due to non-specific symptoms; CA-125 and pelvic USS are initial investigations.',
      'High-grade serous carcinoma is the most common and aggressive histotype; BRCA1/2 mutations confer increased risk.',
      'Primary debulking surgery (PDS) to no residual disease improves survival; neoadjuvant chemotherapy considered if PDS not achievable.',
    ],
    redFlags: [
      'Ascites with pelvic mass — ovarian carcinoma until proven otherwise',
      'CA-125 >500 U/mL in postmenopausal woman',
      'Bowel obstruction from peritoneal disease',
      "Deep vein thrombosis in a woman with pelvic mass (Trousseau's syndrome)",
    ],
    investigations: [
      { label: 'CA-125, HE4, ROMA score', urgency: 'urgent' },
      { label: 'Pelvic ultrasound (transvaginal)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'FBC, renal function, LFTs, coagulation', urgency: 'urgent' },
      { label: 'BRCA1/2 germline testing (all high-grade serous carcinomas)', urgency: 'routine' },
      { label: 'PET-CT (if CT equivocal for staging)', urgency: 'routine' },
      { label: 'Ascites cytology (paracentesis if large volume)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Primary debulking surgery (PDS): total abdominal hysterectomy, bilateral salpingo-oophorectomy, omentectomy, appendicectomy, pelvic/para-aortic lymphadenectomy.' },
      { phase: 'conservative', step: 'Neoadjuvant chemotherapy (carboplatin + paclitaxel × 3 cycles) if PDS upfront not achievable; interval debulking surgery after 3 cycles.' },
      { phase: 'conservative', step: 'Adjuvant chemotherapy: carboplatin + paclitaxel × 6 cycles for FIGO stage IC and above.' },
      { phase: 'conservative', step: 'PARP inhibitor maintenance (olaparib/niraparib) after platinum-sensitive first relapse, especially if BRCA mutated.' },
      { phase: 'followup', step: 'CA-125 and clinical review 3-monthly × 2 years; CT if CA-125 rising.' },
    ],
    medications: [
      { drugName: 'Carboplatin', dose: 'AUC5–6', frequency: 'Day 1 of each cycle (every 3 weeks)', route: 'IV (intravenous)', duration: '6 cycles', indication: 'First-line chemotherapy — refer to oncology', phase: 'immediate' },
      { drugName: 'Paclitaxel', dose: '175 mg/m²', frequency: 'Day 1 of each cycle (every 3 weeks)', route: 'IV (intravenous)', duration: '6 cycles', indication: 'First-line combination with carboplatin', phase: 'immediate' },
      { drugName: 'Bevacizumab', dose: '7.5 mg/kg', frequency: 'Every 3 weeks', route: 'IV (intravenous)', indication: 'VEGF inhibitor — added to first-line or second-line chemotherapy', phase: 'maintenance' },
      { drugName: 'Olaparib', dose: '300 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'PARP inhibitor — BRCA-mutated disease; maintenance after platinum-sensitive first-line chemotherapy', phase: 'maintenance' },
      { drugName: 'Niraparib', dose: '300 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'PARP inhibitor — maintenance therapy alternative to olaparib', phase: 'maintenance', alternativeTo: 'Olaparib' },
      { drugName: 'Ondansetron', dose: '8 mg', frequency: 'TDS (three times daily)', route: 'IV/PO (intravenous/oral)', indication: 'Chemotherapy-induced nausea and vomiting', phase: 'immediate' },
      { drugName: 'Dexamethasone', dose: '8 mg', frequency: 'Pre-chemotherapy (single dose)', route: 'IV (intravenous)', indication: 'Pre-chemotherapy antiemetic prophylaxis', phase: 'immediate' },
    ],
    referral: 'Urgent Gynaecological Oncology; MDT with Oncology, Radiology, Pathology.',
  },

  {
    diseaseId: 'uterine_carcinoma',
    icd10Prefixes: ['C54.1'],
    label: 'Uterine (Endometrial) Carcinoma',
    keyPoints: [
      'Most common gynaecological malignancy in high-income countries; 90% present with postmenopausal bleeding — a red flag symptom.',
      'Risk factors: obesity, nulliparity, late menopause, oestrogen-only HRT, tamoxifen, diabetes, PCOS.',
      'Endometrial biopsy (Pipelle) or hysteroscopy + biopsy is diagnostic; MRI for staging.',
    ],
    redFlags: [
      'Postmenopausal bleeding — endometrial carcinoma until excluded by biopsy',
      'Abnormal uterine bleeding in high-risk premenopausal women (obesity, PCOS, tamoxifen use)',
      'Pyometra in postmenopausal woman — carcinoma must be excluded',
    ],
    investigations: [
      { label: 'Endometrial biopsy (Pipelle) or hysteroscopy + biopsy', urgency: 'urgent' },
      { label: 'Transvaginal ultrasound (endometrial thickness; >4 mm in PMB is significant)', urgency: 'urgent' },
      { label: 'MRI pelvis (myometrial invasion depth, cervical extension — FIGO staging)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (lymph node and metastatic staging)', urgency: 'urgent' },
      { label: 'CA-125 (elevated in advanced/serous histotype)', urgency: 'routine' },
      { label: 'Mismatch repair (MMR) IHC / Lynch syndrome testing (all endometrial cancers)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Total hysterectomy + bilateral salpingo-oophorectomy (TH+BSO) ± pelvic/para-aortic lymphadenectomy — laparoscopic preferred.' },
      { phase: 'surgical', step: 'Sentinel lymph node mapping increasingly used for low-intermediate risk disease.' },
      { phase: 'conservative', step: 'Adjuvant radiotherapy (external beam pelvic RT ± vaginal vault brachytherapy) for intermediate/high-risk disease.' },
      { phase: 'conservative', step: 'Progestin therapy (medroxyprogesterone acetate 160 mg OD) for Grade 1 disease confined to endometrium in women wishing to preserve fertility — close surveillance mandatory.' },
      { phase: 'conservative', step: 'Chemotherapy (carboplatin + paclitaxel) for high-grade serous or advanced/recurrent disease; pembrolizumab for MMR-deficient recurrent disease.' },
      { phase: 'followup', step: 'Clinical review 3-monthly × 2 years; TVS and MRI for symptomatic recurrence.' },
    ],
    medications: [
      { drugName: 'Medroxyprogesterone acetate', dose: '160 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Fertility-sparing — Grade 1 endometrioid, progesterone receptor positive; close surveillance mandatory', phase: 'maintenance' },
      { drugName: 'Carboplatin', dose: 'AUC5', frequency: 'Every 3 weeks', route: 'IV (intravenous)', duration: '4–6 cycles', indication: 'Adjuvant or palliative chemotherapy — high-grade or advanced disease; refer to oncology', phase: 'maintenance' },
      { drugName: 'Paclitaxel', dose: '175 mg/m²', frequency: 'Every 3 weeks', route: 'IV (intravenous)', duration: '4–6 cycles', indication: 'Combination with carboplatin for high-grade or advanced disease', phase: 'maintenance' },
      { drugName: 'Pembrolizumab', dose: '200 mg', frequency: 'Every 3 weeks', route: 'IV (intravenous)', indication: 'MMR-deficient recurrent endometrial carcinoma — immunotherapy', phase: 'maintenance' },
      { drugName: 'Ondansetron', dose: '8 mg', frequency: 'TDS (three times daily)', route: 'IV/PO (intravenous/oral)', indication: 'Antiemetic — perioperative and during chemotherapy', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO/IV (oral/intravenous)', indication: 'Post-surgical analgesia', phase: 'immediate' },
    ],
    referral: 'Gynaecological Oncology; MDT review mandatory before treatment.',
  },

  {
    diseaseId: 'bartholin_abscess',
    icd10Prefixes: ['N75.1'],
    label: "Bartholin's Abscess",
    keyPoints: [
      "Bartholin's glands (greater vestibular glands) drain at 4 and 8 o'clock positions of the vaginal introitus; obstruction leads to cyst, infection causes abscess.",
      'Word catheter insertion or marsupialization is preferred over simple incision and drainage (high recurrence).',
      "In women >40 years, excision biopsy of the gland should be considered to exclude Bartholin's gland carcinoma.",
    ],
    redFlags: [
      'Systemic sepsis from ascending infection — IV antibiotics and urgent drainage',
      "Bartholin's gland mass in postmenopausal woman — carcinoma must be excluded by biopsy",
      'Rapidly enlarging or necrotising infection',
    ],
    investigations: [
      { label: 'Swab of abscess contents (NAAT for Gonorrhoea, Chlamydia; culture)', urgency: 'urgent' },
      { label: 'FBC, CRP (if systemic sepsis suspected)', urgency: 'urgent' },
      { label: 'β-hCG (reproductive-age women)', urgency: 'routine' },
      { label: "Histology of excised Bartholin's gland tissue (women >40 years)", urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia; consider sitz baths for comfort; antibiotics (co-amoxiclav or doxycycline + metronidazole) if systemic features.' },
      { phase: 'surgical', step: 'Word catheter insertion: stab incision into abscess at mucosal surface; insert balloon catheter; inflate with 2–3 mL saline; leave 4–6 weeks for epithelialisation.' },
      { phase: 'surgical', step: 'Marsupialization under LA/GA: elliptical excision of abscess wall; suture edges to vaginal mucosa creating permanent ostium.' },
      { phase: 'surgical', step: "Bartholin's gland excision: for recurrent disease, persistent cyst, or postmenopausal women (to exclude carcinoma)." },
      { phase: 'followup', step: 'Review at 6 weeks for Word catheter removal; assess for recurrence; treat sexual partner if STI isolated.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'As required', route: 'IV (intravenous)', indication: 'Severe pain — pre-procedure analgesia', phase: 'immediate' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Systemic features or surrounding cellulitis', phase: 'discharge' },
      { drugName: 'Doxycycline', dose: '100 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7 days', indication: 'STI-associated abscess — use with metronidazole; alternative to co-amoxiclav', phase: 'discharge', alternativeTo: 'Co-amoxiclav (Augmentin)' },
      { drugName: 'Metronidazole', dose: '400 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7 days', indication: 'STI-associated abscess — use with doxycycline', phase: 'discharge' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia', phase: 'discharge' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily) with food', route: 'PO (oral)', indication: 'Anti-inflammatory', phase: 'discharge' },
    ],
    referral: "Gynaecology for marsupialization or excision; Sexual Health for STI contact tracing if gonorrhoea or chlamydia isolated.",
  },
];
