import type { ManagementProtocol } from '../types.js';

export const hepatobiliaryProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'choledocholithiasis',
    icd10Prefixes: ['K80.5', 'K80.4', 'K80.3'],
    label: 'Choledocholithiasis',
    keyPoints: [
      'CBD stones cause 10–15% of all biliary colic presentations; risk rises with gallbladder stones.',
      'MRCP is gold standard non-invasive imaging (>95% sensitivity); USS CBD dilation suggests obstruction.',
      'ERCP is both diagnostic and therapeutic — sphincterotomy clears stones in 90%.',
    ],
    redFlags: [
      'Fever + jaundice + pain — acute cholangitis; urgent biliary decompression.',
      'Rising bilirubin despite antibiotics — escalate to ERCP within 24 h.',
      'Septic shock — emergency biliary decompression, HDU.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin (conjugated), ALP, GGT', urgency: 'urgent' },
      { label: 'USS abdomen (CBD dilation, stones)', urgency: 'urgent' },
      { label: 'MRCP (CBD stone confirmation)', urgency: 'urgent' },
      { label: 'FBC, CRP, blood cultures if febrile', urgency: 'urgent' },
      { label: 'Amylase (exclude pancreatitis)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV analgesia, antiemetics, IV fluids, NBM.' },
      { phase: 'surgical', step: 'ERCP + sphincterotomy and stone extraction.' },
      { phase: 'surgical', step: 'Laparoscopic cholecystectomy + intraoperative cholangiogram (same admission or elective after ERCP).' },
      { phase: 'followup', step: 'LFTs at 6 weeks to confirm resolution; repeat USS if not normalised.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Biliary colic analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '1 L', frequency: 'over 4–6 h', route: 'IV (intravenous)', indication: 'IV fluid resuscitation', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antibiotics if cholangitis — see cholangitis protocol', phase: 'immediate' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'IV (intravenous)', indication: 'Mucosal protection', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', indication: 'Multimodal analgesia', phase: 'immediate' },
    ],
    referral: 'Gastroenterology / HPB surgery for ERCP.',
  },
  {
    diseaseId: 'cholangiocarcinoma',
    icd10Prefixes: ['C22.1'],
    label: 'Cholangiocarcinoma',
    keyPoints: [
      'Klatskin tumour (hilar) is the commonest type — presents late with painless jaundice.',
      'CA 19-9 >100 U/ml has reasonable sensitivity in the context of biliary obstruction.',
      'Resectability assessed by dedicated HPB team — only 20–30% are resectable at presentation.',
    ],
    redFlags: [
      'Septic cholangitis on background of biliary stricture — emergency biliary decompression.',
      'Bilirubin >300 µmol/L — risk of hepatic failure; urgent drainage.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin, CA 19-9, CEA', urgency: 'urgent' },
      { label: 'MRCP (biliary anatomy, stricture level)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'Endoscopic USS (EUS) + brush cytology / biopsy', urgency: 'urgent' },
      { label: 'PET-CT (exclude distant metastases pre-resection)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Resectable hilar: extended hepatectomy + bile duct resection + lymphadenectomy.' },
      { phase: 'surgical', step: 'Distal CBD: pancreaticoduodenectomy (Whipple\'s procedure).' },
      { phase: 'conservative', step: 'Unresectable: biliary stenting (ERCP or PTC) for palliation.' },
      { phase: 'conservative', step: 'Palliative chemotherapy: gemcitabine + cisplatin ± durvalumab (TOPAZ-1 regimen).' },
      { phase: 'followup', step: 'MDT review; 3-monthly CT surveillance post-resection × 2 years.' },
    ],
    medications: [
      { drugName: 'Gemcitabine', dose: '1000 mg/m²', frequency: 'IV days 1 and 8 per 21-day cycle', route: 'IV (intravenous)', indication: 'Palliative first-line chemotherapy — refer oncology', phase: 'maintenance' },
      { drugName: 'Cisplatin', dose: '25 mg/m²', frequency: 'IV days 1 and 8 per 21-day cycle', route: 'IV (intravenous)', indication: 'Combination with gemcitabine — TOPAZ-1 regimen', phase: 'maintenance' },
      { drugName: 'Durvalumab', dose: '1500 mg', frequency: 'every 3 weeks', route: 'IV (intravenous)', indication: 'Add-on to gemcitabine-cisplatin per TOPAZ-1 — immunotherapy', phase: 'maintenance' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral) / IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '5–10 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous) / PO (oral)', indication: 'Biliary pain', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '8 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous) / PO (oral)', indication: 'Chemo nausea', phase: 'immediate' },
      { drugName: 'Cholestyramine', dose: '4 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Pruritus from cholestasis — bile acid sequestrant', phase: 'maintenance' },
      { drugName: 'Rifampicin', dose: '150–300 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Refractory pruritus', phase: 'maintenance', alternativeTo: 'Cholestyramine' },
    ],
    referral: 'Urgent HPB MDT referral.',
  },
  {
    diseaseId: 'pancreatic_carcinoma',
    icd10Prefixes: ['C25'],
    label: 'Pancreatic Carcinoma',
    keyPoints: [
      'Painless jaundice with palpable gallbladder = Courvoisier\'s law — pancreatic head mass until proven otherwise.',
      'CA 19-9 elevated in 70–80% but not specific; useful for monitoring after resection.',
      'Only 15–20% resectable at presentation; 5-year survival after Whipple\'s is 20–25%.',
    ],
    redFlags: [
      'New-onset diabetes + weight loss + epigastric pain in >50s — screen for pancreatic cancer.',
      'Obstructive jaundice with biliary sepsis — emergency biliary decompression.',
      'Haemodynamic instability — visceral vessel involvement.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin, CA 19-9', urgency: 'urgent' },
      { label: 'CT pancreas protocol (dual-phase)', urgency: 'urgent' },
      { label: 'MRCP / ERCP (biliary anatomy, brush cytology)', urgency: 'urgent' },
      { label: 'EUS + FNA for tissue diagnosis', urgency: 'urgent' },
      { label: 'PET-CT / CT thorax for staging', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Resectable head: Whipple\'s pancreaticoduodenectomy ± pylorus-preserving.' },
      { phase: 'surgical', step: 'Resectable body/tail: distal pancreatectomy + splenectomy.' },
      { phase: 'conservative', step: 'Borderline resectable: neoadjuvant chemotherapy (FOLFIRINOX or gemcitabine + nab-paclitaxel) then re-stage.' },
      { phase: 'conservative', step: 'Unresectable / metastatic: FOLFIRINOX or gemcitabine + nab-paclitaxel; biliary stenting for obstruction.' },
      { phase: 'followup', step: 'MDT surveillance; pain management and pancreatic enzyme replacement.' },
    ],
    medications: [
      { drugName: 'FOLFIRINOX (Oxaliplatin + Irinotecan + Leucovorin + Fluorouracil)', dose: 'Oxaliplatin 85 mg/m² + Irinotecan 180 mg/m² + Leucovorin 400 mg/m² + Fluorouracil 400 mg/m² bolus then 2400 mg/m² over 46 h', frequency: 'every 2 weeks', route: 'IV (intravenous)', indication: 'Neoadjuvant or palliative first-line chemotherapy — refer oncology', phase: 'maintenance' },
      { drugName: 'Gemcitabine + nab-Paclitaxel', dose: 'Gemcitabine 1000 mg/m² + nab-Paclitaxel 125 mg/m²', frequency: 'days 1, 8, 15 per 28-day cycle', route: 'IV (intravenous)', indication: 'Alternative first-line chemotherapy', phase: 'maintenance', alternativeTo: 'FOLFIRINOX (Oxaliplatin + Irinotecan + Leucovorin + Fluorouracil)' },
      { drugName: 'Creon (Pancreatin)', dose: '25,000 units', frequency: 'with each meal', route: 'PO (oral)', indication: 'Pancreatic exocrine insufficiency — PERT', phase: 'discharge' },
      { drugName: 'Ondansetron', dose: '8 mg', frequency: 'TDS (three times daily)', route: 'PO (oral) / IV (intravenous)', indication: 'Chemo nausea', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '5–10 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Severe abdominal / back pain', phase: 'immediate' },
      { drugName: 'Oxycodone MR', dose: '10–20 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Chronic pancreatic pain', phase: 'discharge' },
      { drugName: 'Dexamethasone', dose: '4 mg', frequency: 'pre-chemotherapy', route: 'IV (intravenous)', indication: 'Steroid anti-emetic pre-chemo', phase: 'immediate' },
      { drugName: 'Metformin (WITHHOLD)', dose: 'N/A — withhold', frequency: 'omit on day of contrast imaging', route: 'PO (oral)', indication: 'Stop before contrast for imaging — lactic acidosis risk', phase: 'immediate' },
    ],
    referral: 'Urgent HPB / oncology MDT.',
  },
  {
    diseaseId: 'hepatocellular_carcinoma',
    icd10Prefixes: ['C22.0'],
    label: 'Hepatocellular Carcinoma',
    keyPoints: [
      'AFP >400 ng/ml in cirrhosis is highly specific for HCC — but AFP-negative HCC exists.',
      'LI-RADS categorisation on multi-phase CT or MRI liver avoids biopsy in typical cases.',
      'Barcelona Clinic Liver Cancer (BCLC) staging guides treatment allocation.',
    ],
    redFlags: [
      'Haemoperitoneum (ruptured HCC) — emergency hepatic embolisation or surgery.',
      'Hepatic encephalopathy — acute liver failure; hepatology emergency.',
    ],
    investigations: [
      { label: 'AFP, LFTs, bilirubin, INR, albumin', urgency: 'urgent' },
      { label: 'Multi-phase CT liver or Gd-MRI liver (LI-RADS)', urgency: 'urgent' },
      { label: 'USS abdomen + Doppler (portal vein invasion)', urgency: 'urgent' },
      { label: 'Hepatitis B/C serology', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'BCLC 0/A (single ≤2 cm, no portal HTN): hepatic resection or ablation (RFA/MWA).' },
      { phase: 'surgical', step: 'BCLC B (multinodular): transarterial chemoembolisation (TACE).' },
      { phase: 'conservative', step: 'BCLC C (vascular invasion / metastases): sorafenib or lenvatinib.' },
      { phase: 'conservative', step: 'Liver transplantation for Milan-criteria tumours in compensated cirrhosis.' },
      { phase: 'followup', step: 'USS + AFP 3-monthly post-ablation/resection.' },
    ],
    medications: [
      { drugName: 'Sorafenib', dose: '400 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'BCLC stage C first-line TKI', phase: 'maintenance' },
      { drugName: 'Lenvatinib', dose: '12 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'First-line alternative to sorafenib for unresectable HCC', phase: 'maintenance', alternativeTo: 'Sorafenib' },
      { drugName: 'Regorafenib', dose: '160 mg', frequency: 'OD (once daily) days 1–21 of a 28-day cycle', route: 'PO (oral)', indication: 'Second-line post-sorafenib', phase: 'maintenance' },
      { drugName: 'Atezolizumab + Bevacizumab', dose: 'Atezolizumab 1200 mg + Bevacizumab 15 mg/kg', frequency: 'every 3 weeks', route: 'IV (intravenous)', indication: 'IMbrave150 — first-line immunotherapy combination', phase: 'maintenance' },
      { drugName: 'Propranolol', dose: '20–40 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Portal hypertension / varices prophylaxis', phase: 'maintenance' },
      { drugName: 'Spironolactone', dose: '100 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Ascites', phase: 'maintenance' },
      { drugName: 'Furosemide', dose: '40 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Ascites — add to spironolactone', phase: 'maintenance' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia — use with caution in cirrhosis; reduce dose as needed', phase: 'discharge' },
      { drugName: 'Lactulose', dose: '15–30 mL', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Hepatic encephalopathy prevention — target 2–3 soft stools/day', phase: 'maintenance' },
    ],
    referral: 'Hepatology / HPB MDT.',
  },
  {
    diseaseId: 'primary_sclerosing_cholangitis',
    icd10Prefixes: ['K83.01'],
    label: 'Primary Sclerosing Cholangitis',
    keyPoints: [
      'Associated with IBD in 70–80% (predominantly UC); conversely 5% of UC patients develop PSC.',
      'Multifocal biliary strictures on MRCP ("beads on a string") are characteristic.',
      'Lifetime risk of cholangiocarcinoma is 10–15%; annual MRCP + CA 19-9 surveillance required.',
    ],
    redFlags: [
      'Dominant biliary stricture with raised CA 19-9 — exclude cholangiocarcinoma urgently.',
      'Ascending cholangitis — IV antibiotics and urgent biliary decompression.',
    ],
    investigations: [
      { label: 'LFTs, GGT, ALP, bilirubin', urgency: 'urgent' },
      { label: 'MRCP (biliary tree characterisation)', urgency: 'urgent' },
      { label: 'CA 19-9, CEA (baseline)', urgency: 'routine' },
      { label: 'Colonoscopy (IBD assessment)', urgency: 'routine' },
      { label: 'Liver biopsy if parenchymal disease assessment needed', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'No disease-modifying therapy proven; ursodeoxycholic acid not routinely recommended at high doses.' },
      { phase: 'surgical', step: 'Dominant stricture: ERCP balloon dilation ± short-term stenting.' },
      { phase: 'conservative', step: 'Liver transplantation for end-stage liver disease or recurrent cholangitis — best curative option.' },
      { phase: 'followup', step: 'Annual MRCP, CA 19-9, colonoscopy (surveillance for CRC in IBD-PSC).' },
    ],
    medications: [
      { drugName: 'Piperacillin-tazobactam', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Acute cholangitis complication', phase: 'immediate' },
      { drugName: 'Co-amoxiclav', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Dominant stricture with cholangitis — oral step-down', phase: 'discharge' },
      { drugName: 'Ursodeoxycholic acid', dose: '13–15 mg/kg/day', frequency: 'OD (once daily) or in divided doses', route: 'PO (oral)', indication: 'Symptom management for fatigue / pruritus — low-to-moderate doses only; high doses NOT recommended', phase: 'maintenance' },
      { drugName: 'Cholestyramine', dose: '4 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Pruritus', phase: 'maintenance' },
      { drugName: 'Rifampicin', dose: '150–300 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Refractory pruritus', phase: 'maintenance', alternativeTo: 'Cholestyramine' },
    ],
    referral: 'Hepatology / transplant centre.',
  },
  {
    diseaseId: 'liver_abscess',
    icd10Prefixes: ['K75.0'],
    label: 'Liver Abscess',
    keyPoints: [
      'Pyogenic (E. coli, Klebsiella, Streptococcus) commonest in Caribbean; amoebic (E. histolytica) in travellers.',
      'Single right lobe abscess is typical; CT liver with contrast is the diagnostic standard.',
      'USS-guided percutaneous aspiration / drainage is the primary intervention.',
    ],
    redFlags: [
      'Septic shock — emergency resuscitation; percutaneous drainage without delay.',
      'Rupture into pleura or peritoneum — emergency surgical intervention.',
    ],
    investigations: [
      { label: 'FBC, CRP, blood cultures × 2', urgency: 'stat' },
      { label: 'LFTs, bilirubin', urgency: 'urgent' },
      { label: 'CT abdomen with IV contrast (abscess characteristics)', urgency: 'urgent' },
      { label: 'Amoebic serology (IHA / ELISA)', urgency: 'routine' },
      { label: 'Aspiration fluid C&S, AFB', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV broad-spectrum antibiotics: piperacillin-tazobactam + metronidazole.' },
      { phase: 'immediate', step: 'IV fluids, analgesia, antipyretics.' },
      { phase: 'surgical', step: 'USS-guided percutaneous aspiration / drain insertion (abscess >3 cm).' },
      { phase: 'conservative', step: 'Amoebic abscess: metronidazole 800 mg TDS × 10 days (often responds without drainage).' },
      { phase: 'followup', step: 'CT at 4–6 weeks to confirm resolution; prolonged oral antibiotics (4–6 weeks total).' },
    ],
    medications: [
      { drugName: 'Piperacillin-tazobactam', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Pyogenic liver abscess — empirical broad-spectrum antibiotics', phase: 'immediate' },
      { drugName: 'Metronidazole', dose: '500 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Amoebic abscess + anaerobic cover for pyogenic', phase: 'immediate' },
      { drugName: 'Metronidazole', dose: '800 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '10 days', indication: 'Amoebic abscess — often resolves without drainage', phase: 'discharge' },
      { drugName: 'Ceftriaxone', dose: '2 g', frequency: 'OD (once daily)', route: 'IV (intravenous)', indication: 'Pyogenic alternative if piperacillin-tazobactam unavailable', phase: 'immediate', alternativeTo: 'Piperacillin-tazobactam' },
      { drugName: 'Co-amoxiclav', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '4–6 weeks', indication: 'Oral step-down for pyogenic abscess post-drainage', phase: 'discharge' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral) / IV (intravenous)', indication: 'Fever and pain', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
    ],
    referral: 'General surgery / interventional radiology + infectious diseases.',
  },
  {
    diseaseId: 'acute_hepatitis',
    icd10Prefixes: ['B17', 'B16', 'B15', 'K72'],
    label: 'Acute Hepatitis',
    keyPoints: [
      'Hepatitis A and E are faeco-oral (epidemic in Caribbean); B and C are blood-borne.',
      'ALT >10× ULN indicates significant hepatocellular injury.',
      'Acute liver failure (INR >1.5 + encephalopathy): immediate transfer to hepatology/transplant centre.',
    ],
    redFlags: [
      'INR >1.5 + encephalopathy — acute liver failure; emergency hepatology referral.',
      'Bilirubin >300 µmol/L + rapidly falling transaminases — poor prognostic sign.',
    ],
    investigations: [
      { label: 'LFTs, ALT, AST, bilirubin, ALP', urgency: 'urgent' },
      { label: 'INR, albumin, glucose (synthetic function)', urgency: 'urgent' },
      { label: 'Viral hepatitis serology (A IgM, HBsAg, HBeAg, HCV PCR, HEV IgM)', urgency: 'urgent' },
      { label: 'Autoimmune screen (ANA, ASMA, AMA) if viral negative', urgency: 'routine' },
      { label: 'USS abdomen', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Supportive: IV fluids, rest, avoid hepatotoxic drugs / alcohol.' },
      { phase: 'conservative', step: 'Hepatitis B: nucleoside analogues (tenofovir / entecavir) if severe or fulminant.' },
      { phase: 'conservative', step: 'Hepatitis C: direct-acting antivirals (sofosbuvir-based) after acute phase.' },
      { phase: 'conservative', step: 'Autoimmune hepatitis: corticosteroids (prednisolone 40–60 mg/day).' },
      { phase: 'followup', step: 'LFTs monthly until normalised; screen household contacts for Hep A / B; vaccination.' },
    ],
    medications: [
      { drugName: 'Tenofovir disoproxil', dose: '300 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Severe / fulminant HBV hepatitis', phase: 'immediate' },
      { drugName: 'Entecavir', dose: '0.5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'HBV — alternative to tenofovir', phase: 'immediate', alternativeTo: 'Tenofovir disoproxil' },
      { drugName: 'Sofosbuvir + Velpatasvir', dose: 'Sofosbuvir 400 mg + Velpatasvir 100 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '12 weeks', indication: 'HCV direct-acting antivirals — refer hepatology', phase: 'maintenance' },
      { drugName: 'Prednisolone', dose: '40–60 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Autoimmune hepatitis — start after excluding viral causes', phase: 'immediate' },
      { drugName: 'Azathioprine', dose: '50 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Autoimmune hepatitis maintenance with prednisolone taper', phase: 'maintenance' },
      { drugName: 'N-acetylcysteine', dose: '150 mg/kg over 1 h, then 50 mg/kg over 4 h, then 100 mg/kg over 16 h', frequency: 'single continuous infusion course', route: 'IV (intravenous)', indication: 'Paracetamol-induced acute hepatic failure — within 24 h of overdose', phase: 'immediate' },
      { drugName: 'Lactulose', dose: '30 mL', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Hepatic encephalopathy', phase: 'immediate' },
      { drugName: 'Vitamin K', dose: '10 mg', frequency: 'single dose (repeat as needed)', route: 'IV (intravenous)', indication: 'Coagulopathy', phase: 'immediate' },
    ],
    referral: 'Hepatology; urgent transfer if acute liver failure.',
  },
  {
    diseaseId: 'gallbladder_carcinoma',
    icd10Prefixes: ['C23'],
    label: 'Gallbladder Carcinoma',
    keyPoints: [
      'Most incidentally discovered post-cholecystectomy (pT1a — no further surgery required).',
      'Porcelain gallbladder has lower carcinoma risk than historically reported.',
      'pT1b and above require re-resection with a 1 cm margin of liver bed ± lymphadenectomy.',
    ],
    redFlags: [
      'Jaundice with gallbladder mass — locally advanced disease; HPB MDT urgently.',
      'Peritoneal disease — unresectable; goals-of-care discussion.',
    ],
    investigations: [
      { label: 'LFTs, CA 19-9, CEA, AFP', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'MRI liver / MRCP (biliary involvement)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Incidental pT1a: simple cholecystectomy — curative.' },
      { phase: 'surgical', step: 'pT1b: radical cholecystectomy (liver segment IVb/V resection + lymphadenectomy).' },
      { phase: 'surgical', step: 'pT2/T3: extended resection ± bile duct resection — HPB centre.' },
      { phase: 'conservative', step: 'Unresectable: gemcitabine + cisplatin; biliary stenting for obstruction.' },
      { phase: 'followup', step: 'CT at 3-monthly intervals × 2 years; HPB MDT ongoing.' },
    ],
    medications: [
      { drugName: 'Gemcitabine', dose: '1000 mg/m²', frequency: 'IV days 1 and 8 per 21-day cycle', route: 'IV (intravenous)', indication: 'Palliative chemotherapy — refer oncology', phase: 'maintenance' },
      { drugName: 'Cisplatin', dose: '25 mg/m²', frequency: 'IV days 1 and 8 per 21-day cycle', route: 'IV (intravenous)', indication: 'Combination with gemcitabine', phase: 'maintenance' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral) / IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '5–10 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Biliary pain', phase: 'immediate' },
      { drugName: 'Cholestyramine', dose: '4 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Pruritus from obstructive jaundice', phase: 'maintenance' },
    ],
    referral: 'HPB MDT — urgent.',
  },
  {
    diseaseId: 'sphincter_oddi_dysfunction',
    icd10Prefixes: ['K83.4'],
    label: 'Sphincter of Oddi Dysfunction',
    keyPoints: [
      'Biliary SOD: biliary-type pain + abnormal LFTs or CBD dilation (Rome IV criteria).',
      'Pancreatic SOD: recurrent pancreatitis with no other cause — diagnosis of exclusion.',
      'Sphincterotomy benefits most patients with Type I / II SOD; manometry needed for Type III.',
    ],
    redFlags: [
      'Recurrent pancreatitis — exclude anatomical, genetic, and autoimmune causes first.',
    ],
    investigations: [
      { label: 'LFTs, amylase (during episode)', urgency: 'urgent' },
      { label: 'USS abdomen + MRCP (exclude stones, stricture)', urgency: 'urgent' },
      { label: 'ERCP with sphincter of Oddi manometry (specialist centres)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Calcium channel blockers or nitrates may reduce pain in Type III.' },
      { phase: 'surgical', step: 'Endoscopic biliary sphincterotomy (Type I/II).' },
      { phase: 'surgical', step: 'Pancreatic sphincterotomy if pancreatic-type SOD.' },
      { phase: 'followup', step: 'Symptom review at 6 weeks; repeat LFTs and amylase.' },
    ],
    medications: [
      { drugName: 'Glyceryl trinitrate', dose: '400 mcg', frequency: 'SL PRN (sublingual as needed) before meals', route: 'SL (sublingual)', indication: 'Smooth muscle relaxation — type II SOD', phase: 'maintenance' },
      { drugName: 'Nifedipine SR', dose: '10–20 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Calcium channel blocker for sphincter relaxation — type II SOD', phase: 'maintenance', alternativeTo: 'Glyceryl trinitrate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia — avoid NSAIDs (hepatotoxic risk)', phase: 'maintenance' },
      { drugName: 'Amitriptyline', dose: '10–25 mg', frequency: 'nocte (at night)', route: 'PO (oral)', indication: 'Neuromodulation for functional biliary pain — type III SOD', phase: 'maintenance' },
    ],
    referral: 'Gastroenterology / HPB for ERCP manometry.',
  },
  {
    diseaseId: 'biliary_stricture',
    icd10Prefixes: ['K83.1'],
    label: 'Biliary Stricture',
    keyPoints: [
      'Commonest causes: post-cholecystectomy (benign) or malignant (cholangiocarcinoma, pancreatic cancer).',
      'MRCP is first-line imaging; brush cytology at ERCP has low sensitivity (30–40%).',
      'Bismuth classification for hilar strictures guides surgical approach.',
    ],
    redFlags: [
      'Rising CA 19-9 with stricture — strong suspicion for cholangiocarcinoma; HPB MDT urgently.',
      'Cholangitis superimposed on stricture — emergency biliary decompression.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin, CA 19-9', urgency: 'urgent' },
      { label: 'MRCP (stricture morphology, level)', urgency: 'urgent' },
      { label: 'ERCP + brush cytology / biopsy', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging if malignant)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Benign: ERCP balloon dilation + stenting; repeat dilations q3 months × 1 year.' },
      { phase: 'surgical', step: 'Malignant resectable: oncological resection (Whipple\'s or extended hepatectomy).' },
      { phase: 'conservative', step: 'Malignant unresectable: metal biliary stent (SEMS) for palliation.' },
      { phase: 'followup', step: 'LFTs and imaging at 3-monthly intervals.' },
    ],
    medications: [
      { drugName: 'Piperacillin-tazobactam', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Superimposed cholangitis', phase: 'immediate' },
      { drugName: 'Co-amoxiclav', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Post-ERCP prophylaxis / oral step-down', phase: 'discharge' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Gastric acid suppression post-ERCP', phase: 'discharge' },
      { drugName: 'Ursodeoxycholic acid', dose: '500 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Post-anastomotic stricture biliary protection — limited evidence', phase: 'maintenance' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia', phase: 'discharge' },
      { drugName: 'Cholestyramine', dose: '4 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Pruritus from persistent obstruction', phase: 'maintenance' },
    ],
    referral: 'HPB surgery / gastroenterology.',
  },
];
