import type { ManagementProtocol } from '../types.js';

export const hepatobiliaryProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'choledocholithiasis',
    icd10Prefixes: ['K80.5', 'K80.4', 'K80.3'],
    label: 'Choledocholithiasis',
    keyPoints: [
      'CBD stones cause 10–15% of all biliary colic presentations; risk rises with gallbladder stones.',
      'MRCP is gold standard non-invasive imaging (>95% sensitivity); USS CBD dilation suggests obstruction.',
      'ERCP is both diagnostic and therapeutic — sphincterotomy clears stones in 90%.',
    ],
    redFlags: [
      'Fever + jaundice + pain — acute cholangitis; urgent biliary decompression.',
      'Rising bilirubin despite antibiotics — escalate to ERCP within 24 h.',
      'Septic shock — emergency biliary decompression, HDU.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin (conjugated), ALP, GGT', urgency: 'urgent' },
      { label: 'USS abdomen (CBD dilation, stones)', urgency: 'urgent' },
      { label: 'MRCP (CBD stone confirmation)', urgency: 'urgent' },
      { label: 'FBC, CRP, blood cultures if febrile', urgency: 'urgent' },
      { label: 'Amylase (exclude pancreatitis)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV analgesia, antiemetics, IV fluids, NBM.' },
      { phase: 'surgical', step: 'ERCP + sphincterotomy and stone extraction.' },
      { phase: 'surgical', step: 'Laparoscopic cholecystectomy + intraoperative cholangiogram (same admission or elective after ERCP).' },
      { phase: 'followup', step: 'LFTs at 6 weeks to confirm resolution; repeat USS if not normalised.' },
    ],
    referral: 'Gastroenterology / HPB surgery for ERCP.',
  },
  {
    diseaseId: 'cholangiocarcinoma',
    icd10Prefixes: ['C22.1'],
    label: 'Cholangiocarcinoma',
    keyPoints: [
      'Klatskin tumour (hilar) is the commonest type — presents late with painless jaundice.',
      'CA 19-9 >100 U/ml has reasonable sensitivity in the context of biliary obstruction.',
      'Resectability assessed by dedicated HPB team — only 20–30% are resectable at presentation.',
    ],
    redFlags: [
      'Septic cholangitis on background of biliary stricture — emergency biliary decompression.',
      'Bilirubin >300 µmol/L — risk of hepatic failure; urgent drainage.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin, CA 19-9, CEA', urgency: 'urgent' },
      { label: 'MRCP (biliary anatomy, stricture level)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'Endoscopic USS (EUS) + brush cytology / biopsy', urgency: 'urgent' },
      { label: 'PET-CT (exclude distant metastases pre-resection)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Resectable hilar: extended hepatectomy + bile duct resection + lymphadenectomy.' },
      { phase: 'surgical', step: 'Distal CBD: pancreaticoduodenectomy (Whipple\'s procedure).' },
      { phase: 'conservative', step: 'Unresectable: biliary stenting (ERCP or PTC) for palliation.' },
      { phase: 'conservative', step: 'Palliative chemotherapy: gemcitabine + cisplatin ± durvalumab (TOPAZ-1 regimen).' },
      { phase: 'followup', step: 'MDT review; 3-monthly CT surveillance post-resection × 2 years.' },
    ],
    referral: 'Urgent HPB MDT referral.',
  },
  {
    diseaseId: 'pancreatic_carcinoma',
    icd10Prefixes: ['C25'],
    label: 'Pancreatic Carcinoma',
    keyPoints: [
      'Painless jaundice with palpable gallbladder = Courvoisier\'s law — pancreatic head mass until proven otherwise.',
      'CA 19-9 elevated in 70–80% but not specific; useful for monitoring after resection.',
      'Only 15–20% resectable at presentation; 5-year survival after Whipple\'s is 20–25%.',
    ],
    redFlags: [
      'New-onset diabetes + weight loss + epigastric pain in >50s — screen for pancreatic cancer.',
      'Obstructive jaundice with biliary sepsis — emergency biliary decompression.',
      'Haemodynamic instability — visceral vessel involvement.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin, CA 19-9', urgency: 'urgent' },
      { label: 'CT pancreas protocol (dual-phase)', urgency: 'urgent' },
      { label: 'MRCP / ERCP (biliary anatomy, brush cytology)', urgency: 'urgent' },
      { label: 'EUS + FNA for tissue diagnosis', urgency: 'urgent' },
      { label: 'PET-CT / CT thorax for staging', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Resectable head: Whipple\'s pancreaticoduodenectomy ± pylorus-preserving.' },
      { phase: 'surgical', step: 'Resectable body/tail: distal pancreatectomy + splenectomy.' },
      { phase: 'conservative', step: 'Borderline resectable: neoadjuvant chemotherapy (FOLFIRINOX or gemcitabine + nab-paclitaxel) then re-stage.' },
      { phase: 'conservative', step: 'Unresectable / metastatic: FOLFIRINOX or gemcitabine + nab-paclitaxel; biliary stenting for obstruction.' },
      { phase: 'followup', step: 'MDT surveillance; pain management and pancreatic enzyme replacement.' },
    ],
    referral: 'Urgent HPB / oncology MDT.',
  },
  {
    diseaseId: 'hepatocellular_carcinoma',
    icd10Prefixes: ['C22.0'],
    label: 'Hepatocellular Carcinoma',
    keyPoints: [
      'AFP >400 ng/ml in cirrhosis is highly specific for HCC — but AFP-negative HCC exists.',
      'LI-RADS categorisation on multi-phase CT or MRI liver avoids biopsy in typical cases.',
      'Barcelona Clinic Liver Cancer (BCLC) staging guides treatment allocation.',
    ],
    redFlags: [
      'Haemoperitoneum (ruptured HCC) — emergency hepatic embolisation or surgery.',
      'Hepatic encephalopathy — acute liver failure; hepatology emergency.',
    ],
    investigations: [
      { label: 'AFP, LFTs, bilirubin, INR, albumin', urgency: 'urgent' },
      { label: 'Multi-phase CT liver or Gd-MRI liver (LI-RADS)', urgency: 'urgent' },
      { label: 'USS abdomen + Doppler (portal vein invasion)', urgency: 'urgent' },
      { label: 'Hepatitis B/C serology', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'BCLC 0/A (single ≤2 cm, no portal HTN): hepatic resection or ablation (RFA/MWA).' },
      { phase: 'surgical', step: 'BCLC B (multinodular): transarterial chemoembolisation (TACE).' },
      { phase: 'conservative', step: 'BCLC C (vascular invasion / metastases): sorafenib or lenvatinib.' },
      { phase: 'conservative', step: 'Liver transplantation for Milan-criteria tumours in compensated cirrhosis.' },
      { phase: 'followup', step: 'USS + AFP 3-monthly post-ablation/resection.' },
    ],
    referral: 'Hepatology / HPB MDT.',
  },
  {
    diseaseId: 'primary_sclerosing_cholangitis',
    icd10Prefixes: ['K83.01'],
    label: 'Primary Sclerosing Cholangitis',
    keyPoints: [
      'Associated with IBD in 70–80% (predominantly UC); conversely 5% of UC patients develop PSC.',
      'Multifocal biliary strictures on MRCP ("beads on a string") are characteristic.',
      'Lifetime risk of cholangiocarcinoma is 10–15%; annual MRCP + CA 19-9 surveillance required.',
    ],
    redFlags: [
      'Dominant biliary stricture with raised CA 19-9 — exclude cholangiocarcinoma urgently.',
      'Ascending cholangitis — IV antibiotics and urgent biliary decompression.',
    ],
    investigations: [
      { label: 'LFTs, GGT, ALP, bilirubin', urgency: 'urgent' },
      { label: 'MRCP (biliary tree characterisation)', urgency: 'urgent' },
      { label: 'CA 19-9, CEA (baseline)', urgency: 'routine' },
      { label: 'Colonoscopy (IBD assessment)', urgency: 'routine' },
      { label: 'Liver biopsy if parenchymal disease assessment needed', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'No disease-modifying therapy proven; ursodeoxycholic acid not routinely recommended at high doses.' },
      { phase: 'surgical', step: 'Dominant stricture: ERCP balloon dilation ± short-term stenting.' },
      { phase: 'conservative', step: 'Liver transplantation for end-stage liver disease or recurrent cholangitis — best curative option.' },
      { phase: 'followup', step: 'Annual MRCP, CA 19-9, colonoscopy (surveillance for CRC in IBD-PSC).' },
    ],
    referral: 'Hepatology / transplant centre.',
  },
  {
    diseaseId: 'liver_abscess',
    icd10Prefixes: ['K75.0'],
    label: 'Liver Abscess',
    keyPoints: [
      'Pyogenic (E. coli, Klebsiella, Streptococcus) commonest in Caribbean; amoebic (E. histolytica) in travellers.',
      'Single right lobe abscess is typical; CT liver with contrast is the diagnostic standard.',
      'USS-guided percutaneous aspiration / drainage is the primary intervention.',
    ],
    redFlags: [
      'Septic shock — emergency resuscitation; percutaneous drainage without delay.',
      'Rupture into pleura or peritoneum — emergency surgical intervention.',
    ],
    investigations: [
      { label: 'FBC, CRP, blood cultures × 2', urgency: 'stat' },
      { label: 'LFTs, bilirubin', urgency: 'urgent' },
      { label: 'CT abdomen with IV contrast (abscess characteristics)', urgency: 'urgent' },
      { label: 'Amoebic serology (IHA / ELISA)', urgency: 'routine' },
      { label: 'Aspiration fluid C&S, AFB', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV broad-spectrum antibiotics: piperacillin-tazobactam + metronidazole.' },
      { phase: 'immediate', step: 'IV fluids, analgesia, antipyretics.' },
      { phase: 'surgical', step: 'USS-guided percutaneous aspiration / drain insertion (abscess >3 cm).' },
      { phase: 'conservative', step: 'Amoebic abscess: metronidazole 800 mg TDS × 10 days (often responds without drainage).' },
      { phase: 'followup', step: 'CT at 4–6 weeks to confirm resolution; prolonged oral antibiotics (4–6 weeks total).' },
    ],
    referral: 'General surgery / interventional radiology + infectious diseases.',
  },
  {
    diseaseId: 'acute_hepatitis',
    icd10Prefixes: ['B17', 'B16', 'B15', 'K72'],
    label: 'Acute Hepatitis',
    keyPoints: [
      'Hepatitis A and E are faeco-oral (epidemic in Caribbean); B and C are blood-borne.',
      'ALT >10× ULN indicates significant hepatocellular injury.',
      'Acute liver failure (INR >1.5 + encephalopathy): immediate transfer to hepatology/transplant centre.',
    ],
    redFlags: [
      'INR >1.5 + encephalopathy — acute liver failure; emergency hepatology referral.',
      'Bilirubin >300 µmol/L + rapidly falling transaminases — poor prognostic sign.',
    ],
    investigations: [
      { label: 'LFTs, ALT, AST, bilirubin, ALP', urgency: 'urgent' },
      { label: 'INR, albumin, glucose (synthetic function)', urgency: 'urgent' },
      { label: 'Viral hepatitis serology (A IgM, HBsAg, HBeAg, HCV PCR, HEV IgM)', urgency: 'urgent' },
      { label: 'Autoimmune screen (ANA, ASMA, AMA) if viral negative', urgency: 'routine' },
      { label: 'USS abdomen', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Supportive: IV fluids, rest, avoid hepatotoxic drugs / alcohol.' },
      { phase: 'conservative', step: 'Hepatitis B: nucleoside analogues (tenofovir / entecavir) if severe or fulminant.' },
      { phase: 'conservative', step: 'Hepatitis C: direct-acting antivirals (sofosbuvir-based) after acute phase.' },
      { phase: 'conservative', step: 'Autoimmune hepatitis: corticosteroids (prednisolone 40–60 mg/day).' },
      { phase: 'followup', step: 'LFTs monthly until normalised; screen household contacts for Hep A / B; vaccination.' },
    ],
    referral: 'Hepatology; urgent transfer if acute liver failure.',
  },
  {
    diseaseId: 'gallbladder_carcinoma',
    icd10Prefixes: ['C23'],
    label: 'Gallbladder Carcinoma',
    keyPoints: [
      'Most incidentally discovered post-cholecystectomy (pT1a — no further surgery required).',
      'Porcelain gallbladder has lower carcinoma risk than historically reported.',
      'pT1b and above require re-resection with a 1 cm margin of liver bed ± lymphadenectomy.',
    ],
    redFlags: [
      'Jaundice with gallbladder mass — locally advanced disease; HPB MDT urgently.',
      'Peritoneal disease — unresectable; goals-of-care discussion.',
    ],
    investigations: [
      { label: 'LFTs, CA 19-9, CEA, AFP', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'MRI liver / MRCP (biliary involvement)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Incidental pT1a: simple cholecystectomy — curative.' },
      { phase: 'surgical', step: 'pT1b: radical cholecystectomy (liver segment IVb/V resection + lymphadenectomy).' },
      { phase: 'surgical', step: 'pT2/T3: extended resection ± bile duct resection — HPB centre.' },
      { phase: 'conservative', step: 'Unresectable: gemcitabine + cisplatin; biliary stenting for obstruction.' },
      { phase: 'followup', step: 'CT at 3-monthly intervals × 2 years; HPB MDT ongoing.' },
    ],
    referral: 'HPB MDT — urgent.',
  },
  {
    diseaseId: 'sphincter_oddi_dysfunction',
    icd10Prefixes: ['K83.4'],
    label: 'Sphincter of Oddi Dysfunction',
    keyPoints: [
      'Biliary SOD: biliary-type pain + abnormal LFTs or CBD dilation (Rome IV criteria).',
      'Pancreatic SOD: recurrent pancreatitis with no other cause — diagnosis of exclusion.',
      'Sphincterotomy benefits most patients with Type I / II SOD; manometry needed for Type III.',
    ],
    redFlags: [
      'Recurrent pancreatitis — exclude anatomical, genetic, and autoimmune causes first.',
    ],
    investigations: [
      { label: 'LFTs, amylase (during episode)', urgency: 'urgent' },
      { label: 'USS abdomen + MRCP (exclude stones, stricture)', urgency: 'urgent' },
      { label: 'ERCP with sphincter of Oddi manometry (specialist centres)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Calcium channel blockers or nitrates may reduce pain in Type III.' },
      { phase: 'surgical', step: 'Endoscopic biliary sphincterotomy (Type I/II).' },
      { phase: 'surgical', step: 'Pancreatic sphincterotomy if pancreatic-type SOD.' },
      { phase: 'followup', step: 'Symptom review at 6 weeks; repeat LFTs and amylase.' },
    ],
    referral: 'Gastroenterology / HPB for ERCP manometry.',
  },
  {
    diseaseId: 'biliary_stricture',
    icd10Prefixes: ['K83.1'],
    label: 'Biliary Stricture',
    keyPoints: [
      'Commonest causes: post-cholecystectomy (benign) or malignant (cholangiocarcinoma, pancreatic cancer).',
      'MRCP is first-line imaging; brush cytology at ERCP has low sensitivity (30–40%).',
      'Bismuth classification for hilar strictures guides surgical approach.',
    ],
    redFlags: [
      'Rising CA 19-9 with stricture — strong suspicion for cholangiocarcinoma; HPB MDT urgently.',
      'Cholangitis superimposed on stricture — emergency biliary decompression.',
    ],
    investigations: [
      { label: 'LFTs, bilirubin, CA 19-9', urgency: 'urgent' },
      { label: 'MRCP (stricture morphology, level)', urgency: 'urgent' },
      { label: 'ERCP + brush cytology / biopsy', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging if malignant)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Benign: ERCP balloon dilation + stenting; repeat dilations q3 months × 1 year.' },
      { phase: 'surgical', step: 'Malignant resectable: oncological resection (Whipple\'s or extended hepatectomy).' },
      { phase: 'conservative', step: 'Malignant unresectable: metal biliary stent (SEMS) for palliation.' },
      { phase: 'followup', step: 'LFTs and imaging at 3-monthly intervals.' },
    ],
    referral: 'HPB surgery / gastroenterology.',
  },
];
