import type { ManagementProtocol } from '../types.js';

export const skinSoftTissueProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'melanoma',
    icd10Prefixes: ['C43'],
    label: 'Melanoma',
    keyPoints: [
      'Breslow thickness is the single most important prognostic factor — thickness determines excision margin and SLNB indication.',
      'ABCDE clinical rule: Asymmetry, Border irregularity, Colour variation, Diameter >6 mm, Evolution — any feature warrants dermoscopy.',
      'SLNB for Breslow >1 mm (or 0.8 mm with ulceration) — positive node → completion lymphadenectomy or adjuvant immunotherapy.',
    ],
    redFlags: [
      'Rapidly enlarging pigmented lesion — urgent dermatology / excision biopsy within 2 weeks.',
      'Satellite nodules, in-transit metastases, or fixed regional nodes — stage III disease; urgent MDT.',
      'Neurological symptoms with known melanoma — brain metastases; urgent CT/MRI head.',
    ],
    investigations: [
      { label: 'Excision biopsy with 2 mm margin (diagnostic, not shave biopsy)', urgency: 'urgent' },
      { label: 'Histopathology: Breslow thickness, ulceration, mitotic rate, Clark level', urgency: 'urgent' },
      { label: 'SLNB (Breslow >1 mm or ≥0.8 mm with ulceration)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis + CT/MRI brain (stage III/IV)', urgency: 'urgent' },
      { label: 'BRAF V600E mutation status (targeted therapy eligibility)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Wide local excision: margins based on Breslow (<1 mm = 1 cm; 1–2 mm = 1–2 cm; >2 mm = 2 cm).' },
      { phase: 'surgical', step: 'SLNB at time of WLE for Breslow >1 mm — determines stage III disease.' },
      { phase: 'surgical', step: 'Stage III (positive nodes): completion lymphadenectomy or active surveillance + adjuvant therapy.' },
      { phase: 'conservative', step: 'Adjuvant therapy (stage IIB–III): nivolumab, pembrolizumab, or dabrafenib + trametinib (BRAF V600+).' },
      { phase: 'conservative', step: 'Stage IV: combination ipilimumab + nivolumab or BRAF-targeted therapy if V600+.' },
      { phase: 'followup', step: 'Dermatology review every 3 months × 3 years; CT staging 6-monthly × 3 years for stage II+.' },
    ],
    referral: 'Urgent 2-week wait skin cancer MDT.',
  },
  {
    diseaseId: 'bcc',
    icd10Prefixes: ['C44.9'],
    label: 'Basal Cell Carcinoma (BCC)',
    keyPoints: [
      'Commonest skin malignancy — locally invasive but rarely metastasises (<0.1%).',
      'Nodular BCC (pearlescent rolled edge with telangiectasia) is the commonest subtype; morphoeic/infiltrating carries highest recurrence.',
      'Mohs micrographic surgery achieves lowest recurrence rates for high-risk or facial BCC.',
    ],
    redFlags: [
      'Perineural invasion or morphoeic BCC on face / near vital structures — Mohs surgery or radiation.',
      'Metastatic BCC (extremely rare): hedgehog pathway inhibitor (vismodegib).',
    ],
    investigations: [
      { label: 'Clinical examination + dermoscopy', urgency: 'routine' },
      { label: 'Punch or excision biopsy for histological subtype', urgency: 'routine' },
      { label: 'MRI (if deep tissue / perineural invasion suspected)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Standard excision with 4 mm margin (low-risk sites) — primary closure or flap.' },
      { phase: 'surgical', step: 'Mohs micrographic surgery (face, ears, nose, eyelids, recurrent or morphoeic BCC).' },
      { phase: 'conservative', step: 'Superficial BCC: photodynamic therapy (PDT), imiquimod 5% cream × 6 weeks, or cryotherapy.' },
      { phase: 'conservative', step: 'Inoperable / advanced: external beam radiotherapy; vismodegib for metastatic / locally advanced.' },
      { phase: 'followup', step: 'Wound review at 2 weeks; 5-year follow-up for high-risk BCC (morphoeic, recurrent, deep); sun protection counselling.' },
    ],
    referral: 'Dermatology / plastic surgery skin cancer MDT.',
  },
  {
    diseaseId: 'scc_skin',
    icd10Prefixes: ['C44.92'],
    label: 'Squamous Cell Carcinoma of Skin (SCC)',
    keyPoints: [
      'Metastatic risk 3–5% for cutaneous SCC — higher with perineural invasion, immunosuppression, >20 mm lesion, or depth >4 mm.',
      'Bowen\'s disease (SCC in situ) can progress to invasive SCC in 3–5% if untreated.',
      'Regional lymph node assessment is essential for high-risk features — USS ± FNA of suspicious nodes.',
    ],
    redFlags: [
      'Fixed or ulcerated draining lymph nodes — metastatic SCC; urgent MDT.',
      'Rapid growth, perineural invasion symptoms (paraesthesia) — high-risk lesion; urgent excision.',
      'Immunosuppressed patient (transplant, HIV) — higher risk; aggressive surveillance.',
    ],
    investigations: [
      { label: 'Excision biopsy with 4–6 mm margin (diagnostic)', urgency: 'urgent' },
      { label: 'Regional lymph node USS + FNA if nodes enlarged', urgency: 'urgent' },
      { label: 'CT neck/chest (high-risk SCC with nodal involvement)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Wide local excision: 4 mm margin (low-risk); 6–10 mm (high-risk, perineural, recurrent).' },
      { phase: 'surgical', step: 'Mohs surgery for high-risk facial or perineural-invading SCC.' },
      { phase: 'surgical', step: 'Involved lymph nodes: therapeutic lymph node dissection ± adjuvant RT.' },
      { phase: 'conservative', step: 'Bowen\'s disease: topical 5-FU, imiquimod, PDT, or cryotherapy.' },
      { phase: 'conservative', step: 'Unresectable / metastatic: cemiplimab (PD-1 inhibitor) — first-line immunotherapy.' },
      { phase: 'followup', step: 'Review at 3, 6, 12 months × 2 years; annual dermoscopy of skin thereafter.' },
    ],
    referral: 'Urgent 2-week wait skin cancer MDT.',
  },
  {
    diseaseId: 'lipoma',
    icd10Prefixes: ['D17.9'],
    label: 'Lipoma',
    keyPoints: [
      'Commonest benign soft tissue tumour — soft, mobile, lobulated, non-tender subcutaneous mass.',
      'Most lipomas do not require treatment — excision for rapidly growing, symptomatic, or cosmetically troublesome lesions.',
      'Any firm, deep, or rapidly enlarging lipoma: MRI to exclude liposarcoma before excision.',
    ],
    redFlags: [
      'Firm, deep (subfascial), rapidly growing, or >5 cm — MRI mandatory to exclude liposarcoma.',
      'Multiple lipomas in a young patient — consider familial multiple lipomatosis or MEN1.',
    ],
    investigations: [
      { label: 'Clinical examination (soft, lobulated, mobile — usually diagnostic)', urgency: 'routine' },
      { label: 'USS (if deep or atypical features)', urgency: 'routine' },
      { label: 'MRI (if >5 cm, deep to fascia, or hard — exclude liposarcoma)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Reassurance and observation if <5 cm, soft, superficial, and not troublesome.' },
      { phase: 'surgical', step: 'Excision under LA (outpatient) — blunt dissection in its capsule.' },
      { phase: 'surgical', step: 'Liposuction-assisted excision for large or recurrent superficial lipomas.' },
      { phase: 'followup', step: 'No routine follow-up required for benign lipoma post-excision; histology to confirm.' },
    ],
    referral: 'General / plastic surgery for excision; MRI-suspicious lesions to sarcoma unit.',
  },
  {
    diseaseId: 'sebaceous_cyst',
    icd10Prefixes: ['L72.0'],
    label: 'Epidermoid / Sebaceous Cyst',
    keyPoints: [
      'True epidermoid cyst: keratin-filled, central punctum, non-mobile; not truly sebaceous in origin.',
      'Infected cyst: incise and drain acutely — do not attempt excision; complete excision once settled (6 weeks).',
      'Recurrence prevented by excising the entire capsule intact — punctum must be included.',
    ],
    redFlags: [
      'Rapidly enlarging or multilocular cyst — biopsy to exclude pilomatrixoma or malignant transformation (rare).',
    ],
    investigations: [
      { label: 'Clinical diagnosis — punctum, cheese-like content', urgency: 'routine' },
      { label: 'USS if deep or atypical', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Asymptomatic: observe — explain risk of infection and recurrence.' },
      { phase: 'surgical', step: 'Infected: I&D under LA; clean wound; oral antibiotics if cellulitis (flucloxacillin 500 mg QDS).' },
      { phase: 'surgical', step: 'Elective excision under LA (6 weeks after infection settles) — complete capsule excision via ellipse including punctum.' },
      { phase: 'followup', step: 'Wound review at 10–14 days; no routine follow-up if histology confirms benign.' },
    ],
    referral: 'GP or general surgery minor ops.',
  },
  {
    diseaseId: 'skin_abscess',
    icd10Prefixes: ['L02.9'],
    label: 'Skin Abscess / Furuncle / Carbuncle',
    keyPoints: [
      'S. aureus (including MRSA in high-risk groups) is the causative organism in >75% of skin abscesses.',
      'Incision and drainage (I&D) is the definitive treatment — antibiotics alone are not sufficient for a formed abscess.',
      'Cultures should be sent routinely given rising MRSA prevalence in the Caribbean region.',
    ],
    redFlags: [
      'Spreading cellulitis, fever >38.5°C, or sepsis — IV antibiotics + urgent surgical review.',
      'Periorbital, nasal, or ear canal abscess — specialist referral; risk of cavernous sinus thrombosis.',
    ],
    investigations: [
      { label: 'Clinical diagnosis (fluctuant, tender, warm)', urgency: 'routine' },
      { label: 'FBC, CRP if systemically unwell', urgency: 'urgent' },
      { label: 'Pus C&S + MRSA swab', urgency: 'routine' },
      { label: 'Random glucose (recurrent abscesses — screen for diabetes)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'I&D under LA (or ring block): cruciate or elliptical incision, evacuate pus, break loculations, pack wound.' },
      { phase: 'conservative', step: 'Oral antibiotics only if surrounding cellulitis: co-amoxiclav 625 mg TDS or doxycycline + metronidazole.' },
      { phase: 'conservative', step: 'MRSA-suspected (IV drug user, contact, recurrent): trimethoprim-sulfamethoxazole + rifampicin.' },
      { phase: 'followup', step: 'Wound review and repack at 48 h; recurrent abscesses — screen household contacts and decolonise (mupirocin nasal ointment + chlorhexidine washes × 5 days).' },
    ],
  },
  {
    diseaseId: 'cellulitis',
    icd10Prefixes: ['L03.9'],
    label: 'Cellulitis',
    keyPoints: [
      'Group A Streptococcus (Strep. pyogenes) causes 80% of cellulitis — most do not require microbiological confirmation.',
      'Bilateral lower limb "cellulitis" is almost always venous insufficiency or lymphoedema — true cellulitis is nearly always unilateral.',
      'Eron classification (I–IV) guides outpatient vs inpatient treatment and IV vs oral antibiotics.',
    ],
    redFlags: [
      'Eron class III–IV (fever >38°C, systemic sepsis, bullae, haemorrhagic skin, crepitus) — hospital admission, IV antibiotics.',
      'Rapid progression despite antibiotics after 48 h — consider necrotising fasciitis; urgent surgical assessment.',
    ],
    investigations: [
      { label: 'Clinical examination (mark border of erythema with pen to monitor progression)', urgency: 'routine' },
      { label: 'FBC, CRP, blood cultures (if systemically unwell)', urgency: 'urgent' },
      { label: 'USS (if abscess formation suspected)', urgency: 'urgent' },
      { label: 'LRINEC score if NF suspected (FBC, CRP, glucose, Na, creatinine, Hb)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Eron I (no systemic features): oral phenoxymethylpenicillin 500 mg QDS × 7 days; add flucloxacillin if staph suspected.' },
      { phase: 'conservative', step: 'Eron II: oral co-amoxiclav 625 mg TDS or IV amoxicillin; elevate limb, bed rest.' },
      { phase: 'conservative', step: 'Eron III–IV: IV benzylpenicillin + flucloxacillin (or vancomycin if MRSA risk).' },
      { phase: 'surgical', step: 'If no response at 48–72 h: urgent USS to exclude abscess; senior surgical review for NF.' },
      { phase: 'followup', step: 'Review at 48 h to confirm improvement; treat underlying venous insufficiency / tinea pedis (portal of entry).' },
    ],
  },
  {
    diseaseId: 'necrotising_fasciitis',
    icd10Prefixes: ['M72.6'],
    label: 'Necrotising Fasciitis',
    keyPoints: [
      'Life-threatening surgical emergency — mortality 25–35%; every hour\'s delay worsens outcome.',
      'Type I (polymicrobial — Meleney\'s, Fournier\'s) and Type II (Group A Streptococcus) are the two main types.',
      'LRINEC score >6 raises suspicion; do NOT wait for CT or laboratory confirmation if the diagnosis is clinically likely.',
    ],
    redFlags: [
      'Disproportionate pain, fever, crepitus, skin necrosis, haemodynamic instability — immediate theatre.',
      'Fournier\'s gangrene (perineal / scrotal) — emergency bilateral debridement with wide margins; repeat take-back at 24 h.',
    ],
    investigations: [
      { label: 'LRINEC score: WBC, CRP, glucose, Na, creatinine, Hb (urgently)', urgency: 'stat' },
      { label: 'FBC, U&E, coagulation, blood cultures × 2, blood glucose', urgency: 'stat' },
      { label: 'CT with IV contrast (gas tracking along fascial planes — "dirty fascia" sign)', urgency: 'stat' },
      { label: 'Intraoperative tissue cultures (aerobic + anaerobic + fungal)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Emergency resuscitation: IV fluids, oxygen; activate major trauma pathway if haemodynamically unstable.' },
      { phase: 'immediate', step: 'Empirical IV antibiotics: meropenem + clindamycin + vancomycin — broad-spectrum pending cultures.' },
      { phase: 'surgical', step: 'Emergency wide radical surgical debridement to bleeding viable tissue — take-back at 24–48 h.' },
      { phase: 'surgical', step: 'Fournier\'s: perineal debridement ± defunctioning colostomy; wound vacuum-assisted closure (VAC).' },
      { phase: 'conservative', step: 'Hyperbaric oxygen therapy (HBOT) as adjunct if available — reduces mortality in some centres.' },
      { phase: 'followup', step: 'HDU / ICU admission; plastic surgery for reconstruction; prolonged antibiotics per cultures.' },
    ],
    referral: 'Emergency general surgery + plastic surgery; ICU; infectious diseases.',
  },
  {
    diseaseId: 'sarcoma_soft_tissue',
    icd10Prefixes: ['C49'],
    label: 'Soft Tissue Sarcoma',
    keyPoints: [
      'Soft tissue lump rule: >5 cm, deep to fascia, growing, or firm — sarcoma until proven otherwise; do NOT incise.',
      'MRI is the investigation of choice — defines tissue planes, neurovascular involvement, and surgical margins.',
      'Core needle biopsy is mandatory before any surgical excision — enables subtype diagnosis and preoperative planning.',
    ],
    redFlags: [
      'Any soft tissue mass >5 cm, or any deep subfascial mass of any size — urgent MDT referral.',
      'Unplanned excision of a sarcoma ("whoops procedure") — refer immediately to sarcoma centre for re-resection.',
    ],
    investigations: [
      { label: 'MRI with contrast (define extent, compartment, neurovascular proximity)', urgency: 'urgent' },
      { label: 'Core needle biopsy (minimum 2 cores, 14G, at sarcoma centre)', urgency: 'urgent' },
      { label: 'CT chest (pulmonary metastases — commonest site)', urgency: 'urgent' },
      { label: 'CT abdomen/pelvis if myxoid liposarcoma (retroperitoneal staging)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'Wide local excision with R0 margins (minimum 1 cm or an intact fascial plane) — at specialist sarcoma centre.' },
      { phase: 'conservative', step: 'Neoadjuvant or adjuvant radiotherapy (50–66 Gy) reduces local recurrence for limb-sparing surgery.' },
      { phase: 'conservative', step: 'High-grade resectable: adjuvant doxorubicin + ifosfamide chemotherapy (selected subtypes).' },
      { phase: 'conservative', step: 'Metastatic / unresectable: doxorubicin-based chemotherapy; pazopanib after first-line failure.' },
      { phase: 'followup', step: 'MRI primary site 3-monthly × 2 years; CT chest 6-monthly × 5 years; MDT review throughout.' },
    ],
    referral: 'Urgent sarcoma MDT at specialist centre.',
  },
  {
    diseaseId: 'desmoid_tumour',
    icd10Prefixes: ['D48.1'],
    label: 'Desmoid Tumour (Aggressive Fibromatosis)',
    keyPoints: [
      'Locally aggressive fibroblastic tumour — does not metastasise but causes significant morbidity through local invasion.',
      'Strongly associated with FAP (Gardner\'s syndrome) — intra-abdominal desmoids in mesentery are common.',
      'Modern management is non-operative first: many desmoids plateau spontaneously; systemic therapy before surgery.',
    ],
    redFlags: [
      'Intra-abdominal desmoid with bowel obstruction or ureteric compression — urgent multidisciplinary management.',
      'Rapid progression on imaging — escalate systemic therapy promptly.',
    ],
    investigations: [
      { label: 'MRI with contrast (local extent, T2 signal predicts activity)', urgency: 'urgent' },
      { label: 'CT chest/abdomen (exclude metastatic disease, define abdominal extent)', urgency: 'routine' },
      { label: 'Core biopsy (confirm diagnosis — beta-catenin nuclear staining)', urgency: 'urgent' },
      { label: 'Genetic testing (APC mutation, CTNNB1) — informs prognosis', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Active surveillance (watch-and-wait) — 50% of desmoids stabilise or regress without treatment.' },
      { phase: 'conservative', step: 'Systemic therapy: low-dose (anti-oestrogen: tamoxifen + sulindac) or tyrosine kinase inhibitor (sorafenib, imatinib).' },
      { phase: 'conservative', step: 'Chemotherapy: methotrexate + vinblastine (low-dose) for progressive or paediatric desmoids.' },
      { phase: 'surgical', step: 'Surgery reserved for R0-resectable tumours not responding to systemic therapy — high recurrence rate if margins involved.' },
      { phase: 'followup', step: 'MRI 3-monthly × 1 year then 6-monthly; colonoscopy if FAP-associated (annual surveillance).' },
    ],
    referral: 'Sarcoma / FAP MDT centre.',
  },
];
