import type { ManagementProtocol } from '../types.js';

export const traumaProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'blunt_abdominal_trauma',
    icd10Prefixes: ['S39.9'],
    label: 'Blunt Abdominal Trauma',
    keyPoints: [
      'FAST (Focused Assessment with Sonography in Trauma) is the first-line imaging in haemodynamically unstable patients — positive FAST + instability = immediate laparotomy.',
      'CT abdomen/pelvis with contrast is the gold standard for haemodynamically stable patients; identifies solid organ injury grade.',
      'Splenic and hepatic lacerations (grades I–III) are managed non-operatively in stable patients with ICU/HDU monitoring.',
    ],
    redFlags: [
      'Haemodynamic instability (SBP <90 mmHg after 2 L crystalloid) — immediate damage-control surgery',
      'Peritonism or evisceration — emergency laparotomy',
      'Positive FAST with haemodynamic instability — operating theatre immediately',
      'Delayed presentation (>6 h) with falling Hb or expanding haematoma',
    ],
    investigations: [
      { label: 'FAST ultrasound (bedside, immediate)', urgency: 'stat' },
      { label: 'FBC, U&E, LFTs, amylase, coagulation, crossmatch 6 units', urgency: 'stat' },
      { label: 'ABG / VBG (lactate, base excess)', urgency: 'stat' },
      { label: 'CT abdomen/pelvis with IV contrast (haemodynamically stable)', urgency: 'urgent' },
      { label: 'Urinalysis / urinary catheter (haematuria)', urgency: 'urgent' },
      { label: 'CXR / pelvic X-ray (primary survey)', urgency: 'stat' },
    ],
    management: [
      { phase: 'immediate', step: 'Primary survey ABCDE: airway with C-spine control, breathing, circulation (two large-bore IV access, 1 L warmed crystalloid), disability (GCS, pupils), exposure.' },
      { phase: 'immediate', step: 'Activate MTP if SBP <90 + HR >120: PRBC:FFP:Platelets = 1:1:1; tranexamic acid 1 g IV within 3 hours of injury.' },
      { phase: 'immediate', step: 'FAST scan: free fluid in Morrison\'s pouch, splenorenal recess, pelvis, pericardium.' },
      { phase: 'surgical', step: 'Damage-control laparotomy: control haemorrhage (packing, vessel ligation), prevent contamination, temporary closure — definitive repair after resuscitation.' },
      { phase: 'conservative', step: 'Non-operative management for grades I–III solid organ injury in stable patients: ICU monitoring, serial FBC/Hb every 6 h, NPO, bed rest.' },
      { phase: 'conservative', step: 'Angioembolisation via interventional radiology for contained vascular injury in stable patient (splenic, hepatic).' },
      { phase: 'followup', step: 'Repeat CT at 48–72 h for high-grade injuries; graduated mobilisation; driving restrictions per organ injury grade.' },
    ],
    medications: [
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'Once (loading dose over 10 min)', route: 'IV (intravenous)', indication: 'Haemorrhage control — administer within 3 h of injury', phase: 'immediate' },
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'Once (over 8 h) — 1 h after loading dose', route: 'IV (intravenous)', indication: 'Second dose if still bleeding', phase: 'immediate', alternativeTo: 'Tranexamic acid loading dose' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '500 mL', frequency: 'Stat bolus', route: 'IV (intravenous)', indication: 'Balanced crystalloid resuscitation', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antibiotics — hollow viscus injury or enteric contamination', phase: 'immediate' },
      { drugName: 'Noradrenaline', dose: '0.1–0.5 mcg/kg/min', frequency: 'Continuous infusion', route: 'IV (intravenous)', indication: 'Vasopressor — haemorrhagic shock refractory to fluid resuscitation', phase: 'immediate' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'IV (intravenous)', indication: 'Stress ulcer prophylaxis in critical care', phase: 'immediate' },
    ],
    referral: 'Trauma Surgery immediately; Interventional Radiology for angioembolisation; ICU/HDU admission for all significant injuries.',
  },

  {
    diseaseId: 'penetrating_abdominal_trauma',
    icd10Prefixes: ['S31.6'],
    label: 'Penetrating Abdominal Trauma',
    keyPoints: [
      'Gunshot wounds: mandatory exploratory laparotomy (trajectory unpredictable). Stab wounds: selective non-operative management for anterior stab wounds with stable vitals and no peritonism.',
      'Evisceration — do not attempt to reduce bowel at bedside; cover with saline-moistened dressings; emergency laparotomy.',
      'Permissive hypotension (target SBP 80–90 mmHg) until surgical haemostasis in penetrating trauma without TBI.',
    ],
    redFlags: [
      'Haemodynamic instability — immediate laparotomy; no time for CT',
      'Peritonism, evisceration, or impalement — emergency surgery',
      'Gunshot wound — mandatory laparotomy regardless of stability',
      'Diaphragmatic injury suspected (left haemothorax after LUQ stab)',
    ],
    investigations: [
      { label: 'FAST ultrasound (bedside)', urgency: 'stat' },
      { label: 'FBC, coagulation, crossmatch', urgency: 'stat' },
      { label: 'CT abdomen/pelvis (stable anterior stab only)', urgency: 'urgent' },
      { label: 'Upright CXR (pneumoperitoneum, haemothorax)', urgency: 'stat' },
      { label: 'Wound exploration under local anaesthesia (anterior stab, stable)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Primary survey ABCDE; two large-bore IV access; permissive hypotension (SBP 80–90 mmHg) until haemostasis.' },
      { phase: 'immediate', step: 'Do NOT remove impaled objects — stabilise in situ and take to theatre.' },
      { phase: 'immediate', step: 'Tranexamic acid 1 g IV within 3 hours of injury.' },
      { phase: 'surgical', step: 'Exploratory laparotomy: systematic inspection of all abdominal contents, bowel run from duodenojejunal flexure to rectum, retroperitoneal assessment.' },
      { phase: 'surgical', step: 'Damage-control if coagulopathic/hypothermic: pack, close, ICU resuscitation, planned relook at 24–48 h.' },
      { phase: 'conservative', step: 'Selective non-operative management for isolated anterior stab: wound exploration confirms fascial integrity, observations every 2 h × 24 h, NPO.' },
      { phase: 'followup', step: 'Secondary survey for missed injuries; wound care; tetanus prophylaxis; psychological support post-trauma.' },
    ],
    medications: [
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'Once (over 10 min)', route: 'IV (intravenous)', indication: 'Haemorrhage control — administer within 3 h of injury', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Empirical antibiotics — enteric contamination', phase: 'immediate' },
      { drugName: 'Metronidazole', dose: '500 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Anaerobic cover — add to pip-tazo for colorectal injury', phase: 'immediate' },
      { drugName: 'Tetanus immunoglobulin', dose: '250 IU', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Wound contamination prophylaxis — if not immunised', phase: 'immediate' },
      { drugName: 'Tetanus toxoid', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Booster if >5 years since last dose or uncertain immunisation', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '500 mL', frequency: 'Stat bolus', route: 'IV (intravenous)', indication: 'Resuscitation', phase: 'immediate' },
    ],
    referral: 'Trauma Surgery immediately; ICU; Forensic documentation if assault.',
  },

  {
    diseaseId: 'traumatic_brain_injury',
    icd10Prefixes: ['S09.9'],
    label: 'Traumatic Brain Injury',
    keyPoints: [
      'GCS classification: mild TBI (GCS 13–15), moderate (GCS 9–12), severe (GCS ≤8 — intubate and ventilate).',
      'CT head is indicated for any GCS <15, loss of consciousness, amnesia, vomiting, focal neurological deficit, or high-risk mechanism.',
      'Avoid secondary brain injury: maintain SBP ≥90 mmHg, SpO2 ≥95%, temperature normothermia; target PaCO2 35–40 mmHg (avoid hyperventilation except for herniation).',
    ],
    redFlags: [
      'GCS ≤8 or rapidly deteriorating GCS — secure airway immediately (RSI)',
      'Unilateral fixed dilated pupil — uncal herniation; immediate neurosurgical review',
      'Cushing\'s triad (hypertension, bradycardia, irregular respiration) — raised ICP emergency',
      'Extradural / subdural haematoma on CT with mass effect — emergency craniotomy',
    ],
    investigations: [
      { label: 'CT head without contrast (within 1 hour of presentation)', urgency: 'stat' },
      { label: 'ABG (PaCO2, PaO2, oxygenation)', urgency: 'stat' },
      { label: 'Blood glucose (avoid hypoglycaemia)', urgency: 'stat' },
      { label: 'FBC, coagulation, U&E (coagulopathy correction)', urgency: 'urgent' },
      { label: 'CT cervical spine (if mechanism warrants)', urgency: 'urgent' },
      { label: 'MRI brain (delayed, for diffuse axonal injury / posterior fossa)', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Airway: intubate (RSI) if GCS ≤8 or airway compromise; target SpO2 ≥97%, ETCO2 35–40 mmHg.' },
      { phase: 'immediate', step: 'Circulation: target SBP ≥90 mmHg (avoid hypotension); use vasopressors if needed; avoid hypotonic fluids.' },
      { phase: 'immediate', step: 'C-spine immobilisation until cleared clinically or radiologically.' },
      { phase: 'immediate', step: 'Neuroprotection: head of bed 30°, avoid neck flexion/rotation, normoglycaemia (4–10 mmol/L), normothermia.' },
      { phase: 'conservative', step: 'ICP monitoring (EVD or Camino) for GCS <8 + CT lesion or GCS <8 + two of: age >40, motor posturing, SBP <90.' },
      { phase: 'conservative', step: 'Raised ICP management: osmotherapy (mannitol 0.25–1 g/kg IV or hypertonic saline 3% 250 mL), hyperventilate briefly for herniation.' },
      { phase: 'surgical', step: 'Neurosurgical evacuation for: extradural haematoma >30 mL, subdural haematoma >10 mm midline shift, depressed skull fracture.' },
      { phase: 'followup', step: 'Neurorehabilitation; cognitive assessment at 6 weeks; driving licence authority notification; return-to-sport/work protocol.' },
    ],
    medications: [
      { drugName: 'Mannitol 20%', dose: '0.25–1 g/kg', frequency: 'Once (over 15–20 min); repeat PRN', route: 'IV (intravenous)', indication: 'Osmotherapy — raised ICP / cerebral oedema', phase: 'immediate' },
      { drugName: 'Hypertonic saline 3%', dose: '250 mL', frequency: 'Once (bolus)', route: 'IV (intravenous)', indication: 'Alternative osmotherapy — renal failure or euvolaemic patient', phase: 'immediate', alternativeTo: 'Mannitol 20%' },
      { drugName: 'Propofol', dose: '1–4 mg/kg/h', frequency: 'Continuous infusion', route: 'IV (intravenous)', indication: 'Sedation for intubated TBI', phase: 'immediate' },
      { drugName: 'Levetiracetam', dose: '1 g', frequency: 'BD (twice daily) × 7 days', route: 'IV (intravenous)', duration: '7 days', indication: 'Post-traumatic seizure prophylaxis', phase: 'immediate' },
      { drugName: 'Phenytoin', dose: '15–20 mg/kg', frequency: 'Once (loading dose)', route: 'IV (intravenous)', indication: 'Seizure prophylaxis — alternative', phase: 'immediate', alternativeTo: 'Levetiracetam' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', indication: 'Antipyretic — fever worsens secondary brain injury', phase: 'immediate' },
      { drugName: 'Dexamethasone', dose: '4 mg', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', indication: 'Oedema in associated spinal cord injury — NOT recommended for isolated head injury', phase: 'immediate' },
      { drugName: 'Noradrenaline', dose: 'Titrated to effect', frequency: 'Continuous infusion', route: 'IV (intravenous)', indication: 'Maintain cerebral perfusion pressure (CPP) ≥60–70 mmHg', phase: 'immediate' },
      { drugName: 'Suxamethonium', dose: '1.5 mg/kg', frequency: 'Once', route: 'IV (intravenous)', indication: 'Rapid sequence intubation (RSI) for airway management', phase: 'immediate' },
    ],
    referral: 'Neurosurgery urgently for GCS <15 with CT abnormality; ICU for severe TBI; Neurorehabilitation for all moderate-severe TBI.',
  },

  {
    diseaseId: 'rib_fractures',
    icd10Prefixes: ['S29.0'],
    label: 'Rib Fractures',
    keyPoints: [
      'Flail chest (≥3 consecutive ribs fractured in ≥2 places) causes paradoxical breathing — may require intubation and mechanical ventilation.',
      'Elderly patients with ≥3 rib fractures have significantly increased mortality — consider HDU admission for pain control and respiratory monitoring.',
      'Adequate analgesia (epidural or intercostal nerve block) is critical to prevent respiratory splinting, atelectasis, and pneumonia.',
    ],
    redFlags: [
      'Flail segment with respiratory failure — intubation and IPPV',
      'Associated tension pneumothorax: absent breath sounds, tracheal deviation, hypotension — immediate needle decompression',
      'Haemothorax >1500 mL or continuing bleeding >200 mL/h — thoracotomy',
      'SpO2 <92% despite O2 — HDU/ICU escalation',
    ],
    investigations: [
      { label: 'CXR (rib fractures, pneumothorax, haemothorax)', urgency: 'stat' },
      { label: 'CT chest with contrast (better rib fracture count, vascular injury)', urgency: 'urgent' },
      { label: 'ABG (respiratory function, CO2 retention)', urgency: 'urgent' },
      { label: 'FBC, coagulation (pre-procedure bloods)', urgency: 'urgent' },
      { label: 'ECG (rib fractures may be associated with myocardial contusion)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'High-flow O2; pulse oximetry; IV access; adequate analgesia immediately (IV morphine titrated).' },
      { phase: 'conservative', step: 'Multi-modal analgesia: IV opioids + NSAIDs (if no renal contraindication) + paracetamol + regional: thoracic epidural or serratus anterior plane block.' },
      { phase: 'conservative', step: 'Respiratory physiotherapy: incentive spirometry, deep breathing exercises, early ambulation where possible.' },
      { phase: 'conservative', step: 'Intercostal chest drain for pneumothorax >2 cm or haemothorax.' },
      { phase: 'surgical', step: 'Rib fixation (ORIF) for flail chest not responding to conservative management, severe pain, or planned thoracotomy for other injuries.' },
      { phase: 'followup', step: 'Repeat CXR at 24–48 h; physiotherapy follow-up; analgesia step-down; return to work assessment at 4–6 weeks.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia — severe multirib fracture pain', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV or PO', indication: 'Multimodal analgesia', phase: 'immediate' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'NSAID analgesia — avoid in renal impairment or GI risk', phase: 'immediate' },
      { drugName: 'Ketorolac', dose: '30 mg', frequency: 'Q6H (every 6 hours) × 5 days', route: 'IV (intravenous)', duration: '5 days', indication: 'IV NSAID — short-term use for severe pain', phase: 'immediate', alternativeTo: 'Ibuprofen' },
      { drugName: 'Pregabalin', dose: '75 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Neuropathic pain component — severe rib fractures', phase: 'immediate' },
      { drugName: 'Oxycodone MR', dose: '10 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Step-down opioid for ≥4 rib fractures', phase: 'discharge' },
      { drugName: 'Bupivacaine 0.5%', dose: '10 mL', frequency: 'As required per block', route: 'Intercostal / regional injection', indication: 'Intercostal nerve block or serratus anterior plane block — regional analgesia', phase: 'immediate' },
      { drugName: 'Enoxaparin', dose: '40 mg', frequency: 'OD (once daily)', route: 'SC (subcutaneous)', indication: 'VTE prophylaxis — once haemostasis achieved', phase: 'immediate' },
    ],
    referral: 'Trauma Surgery; Anaesthesia for regional analgesia; Thoracic Surgery for rib fixation or ongoing haemothorax.',
  },

  {
    diseaseId: 'pneumothorax_traumatic',
    icd10Prefixes: ['S27.0'],
    label: 'Traumatic Pneumothorax',
    keyPoints: [
      'Tension pneumothorax is a clinical diagnosis — do NOT wait for CXR; needle decompression at 2nd ICS midclavicular line, then definitive chest drain.',
      'Simple pneumothorax >2 cm or symptomatic: intercostal chest drain (ICD) 4th/5th ICS anterior axillary line (ATLS 11 — avoid 2nd ICS midclavicular for ICD).',
      'Occult pneumothorax (CT-only finding, haemodynamically stable, no ventilation): observe; drain if clinical deterioration or ventilation required.',
    ],
    redFlags: [
      'Tracheal deviation, absent breath sounds, JVD, hypotension — tension pneumothorax; immediate needle decompression',
      'Bilateral pneumothorax — bilateral chest drains, alert anaesthetics',
      'SpO2 <90% despite O2 supplementation',
    ],
    investigations: [
      { label: 'CXR (erect or supine)', urgency: 'stat' },
      { label: 'ABG', urgency: 'stat' },
      { label: 'CT chest (occult pneumothorax, haemothorax volume)', urgency: 'urgent' },
      { label: 'Bedside USS (pleural sliding — absent in pneumothorax)', urgency: 'stat' },
    ],
    management: [
      { phase: 'immediate', step: 'Tension pneumothorax: needle decompression (14G cannula 2nd ICS MCL) → immediate clinical improvement → proceed to ICD.' },
      { phase: 'immediate', step: 'High-flow O2 (accelerates pneumothorax reabsorption for small, asymptomatic PTX).' },
      { phase: 'surgical', step: 'ICD: 4th/5th ICS anterior axillary line, blunt dissection, 28–32 Fr drain; confirm on CXR. Water-seal drainage.' },
      { phase: 'conservative', step: 'Monitor drain output; remove when <100 mL/24 h and lung fully expanded on CXR.' },
      { phase: 'followup', step: 'CXR post-drain removal; air travel restriction 6 weeks; referral for recurrent pneumothorax (VATS pleurodesis).' },
    ],
    medications: [
      { drugName: 'Oxygen', dose: '15 L/min', frequency: 'Continuous', route: 'Non-rebreather mask', indication: 'Tension PTX support pre-decompression / simple PTX — accelerates gas reabsorption', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Once (procedural)', route: 'IV (intravenous)', indication: 'Procedural analgesia for ICD insertion', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV or PO', indication: 'Post-ICD analgesia', phase: 'immediate' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '625 mg', frequency: 'TDS (three times daily) × 5 days', route: 'PO (oral)', duration: '5 days', indication: 'Post-ICD infection prophylaxis', phase: 'discharge' },
      { drugName: 'Midazolam', dose: '1–2 mg', frequency: 'Once (procedural)', route: 'IV (intravenous)', indication: 'Procedural sedation for ICD insertion', phase: 'immediate' },
    ],
    referral: 'Trauma Surgery / Thoracic Surgery; ICU if bilateral or tension.',
  },

  {
    diseaseId: 'haemothorax',
    icd10Prefixes: ['S27.1'],
    label: 'Haemothorax',
    keyPoints: [
      'Massive haemothorax (>1500 mL on initial drainage or >200 mL/h × 2–4 h): emergency thoracotomy.',
      'ICD is both diagnostic (quantifies volume) and therapeutic; adequately draining prevents clotted haemothorax and empyema.',
      'Video-assisted thoracoscopic surgery (VATS) is effective for retained haemothorax failing ICD drainage.',
    ],
    redFlags: [
      'Immediate drainage >1500 mL — massive haemothorax; immediate thoracotomy activation',
      'Haemodynamic instability not responding to drainage — emergency surgery',
      'Retained haemothorax on CXR despite ICD — risk of empyema; VATS',
    ],
    investigations: [
      { label: 'CXR (opacification, mediastinal shift)', urgency: 'stat' },
      { label: 'FBC, coagulation, crossmatch 6 units pRBC', urgency: 'stat' },
      { label: 'CT chest with contrast (vessels, injury extent)', urgency: 'urgent' },
      { label: 'ABG', urgency: 'stat' },
    ],
    management: [
      { phase: 'immediate', step: 'Two large-bore IV access; group and save / crossmatch; resuscitate with blood products (MTP if massive haemothorax).' },
      { phase: 'surgical', step: 'ICD insertion (32–36 Fr): drain completely; note initial output and hourly drain output.' },
      { phase: 'surgical', step: 'Emergency thoracotomy for: initial drainage >1500 mL, continued >200 mL/h × 3 h, persistent haemodynamic instability.' },
      { phase: 'conservative', step: 'Autotransfusion of collected blood via ICD where available.' },
      { phase: 'conservative', step: 'VATS for retained haemothorax >300 mL at 48–72 h; reduces empyema risk.' },
      { phase: 'followup', step: 'Serial CXR; drain removal when output <100 mL/24 h; physiotherapy.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'Once', route: 'IV (intravenous)', indication: 'Haemorrhage control — massive haemothorax', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '500 mL', frequency: 'Stat bolus', route: 'IV (intravenous)', indication: 'Resuscitation', phase: 'immediate' },
      { drugName: 'Piperacillin-tazobactam (Tazocin)', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', duration: '24 h', indication: 'Antibiotic prophylaxis post-ICD for haemothorax — 24 h course only', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV (intravenous)', indication: 'Multimodal analgesia', phase: 'immediate' },
      { drugName: 'Enoxaparin', dose: '40 mg', frequency: 'OD (once daily)', route: 'SC (subcutaneous)', indication: 'VTE prophylaxis — once haemostasis confirmed', phase: 'immediate' },
    ],
    referral: 'Trauma Surgery / Thoracic Surgery immediately; Interventional Radiology for contained vascular injury.',
  },

  {
    diseaseId: 'splenic_laceration',
    icd10Prefixes: ['S36.0'],
    label: 'Splenic Laceration',
    keyPoints: [
      'AAST grading (I–V): grades I–III managed non-operatively in stable adults; grades IV–V often require surgery or angioembolisation.',
      'Kehr\'s sign: left shoulder tip pain on Trendelenburg (blood tracking under diaphragm) is pathognomonic but present in only ~50%.',
      'Non-operative management failure rate ~5–10%; must have reliable access to OR and blood products at all times during observation.',
    ],
    redFlags: [
      'Haemodynamic instability after 2 L crystalloid — emergency splenectomy',
      'Positive FAST + haemodynamic instability — immediate laparotomy',
      'Grade IV–V injury with pseudoaneurysm — angioembolisation or splenectomy',
      'Deterioration during non-operative management (rising tachycardia, falling Hb)',
    ],
    investigations: [
      { label: 'FAST ultrasound (free fluid LUQ, Morrison\'s pouch)', urgency: 'stat' },
      { label: 'CT abdomen/pelvis with IV contrast (AAST grading)', urgency: 'urgent' },
      { label: 'FBC, crossmatch 4 units pRBC', urgency: 'stat' },
      { label: 'Coagulation screen, ABG (lactate)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Primary survey; IV access; blood products standby; strict bed rest; NPO.' },
      { phase: 'conservative', step: 'Non-operative: HDU monitoring, serial FBC (6-hourly × 24 h then 12-hourly), BP and HR continuous monitoring.' },
      { phase: 'conservative', step: 'Angioembolisation for grade III–IV with active blush or pseudoaneurysm on CT.' },
      { phase: 'surgical', step: 'Emergency splenectomy (or splenorrhaphy if technically feasible) for grade V, haemodynamic instability, or failed NOM.' },
      { phase: 'followup', step: 'Post-splenectomy vaccination (pneumococcal, meningococcal, Hib, influenza); penicillin prophylaxis lifelong; OPSI education.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Analgesia', phase: 'immediate' },
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'Once', route: 'IV (intravenous)', indication: 'Haemorrhage control', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution', dose: '500 mL', frequency: 'Stat bolus', route: 'IV (intravenous)', indication: 'Resuscitation', phase: 'immediate' },
      { drugName: 'Pneumococcal vaccine (Pneumovax 23)', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Post-splenectomy vaccination — at least 2 weeks post-surgery or pre-operatively', phase: 'immediate' },
      { drugName: 'Meningococcal ACWY conjugate vaccine', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Post-splenectomy vaccination', phase: 'immediate' },
      { drugName: 'Haemophilus influenzae type b (Hib) vaccine', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Post-splenectomy vaccination', phase: 'immediate' },
      { drugName: 'Influenza vaccine', dose: 'Standard dose IM', frequency: 'Annually', route: 'IM (intramuscular)', indication: 'Post-splenectomy annual vaccination', phase: 'maintenance' },
      { drugName: 'Phenoxymethylpenicillin', dose: '500 mg', frequency: 'BD (twice daily) — lifelong', route: 'PO (oral)', indication: 'Lifelong antibiotic prophylaxis post-splenectomy — OPSI prevention', phase: 'maintenance' },
      { drugName: 'Amoxicillin', dose: '500 mg', frequency: 'BD (twice daily) — lifelong', route: 'PO (oral)', indication: 'Penicillin prophylaxis — alternative to phenoxymethylpenicillin', phase: 'maintenance', alternativeTo: 'Phenoxymethylpenicillin' },
    ],
    referral: 'Trauma Surgery immediately; Interventional Radiology for embolisation; ICU/HDU admission.',
  },

  {
    diseaseId: 'thermal_burn_major',
    icd10Prefixes: ['T31.3', 'T31.4', 'T31.5', 'T31.6', 'T31.7', 'T31.8', 'T31.9'],
    label: 'Major Thermal Burn (≥20% TBSA)',
    keyPoints: [
      'Parkland formula: 4 × weight (kg) × TBSA (%) = mL Lactated Ringer\'s in first 24 h from time of burn. Half in first 8 h, half in next 16 h.',
      'Target urine output: 0.5–1 mL/kg/hr adults, 1 mL/kg/hr children — titrate fluids accordingly.',
      'Inhalation injury significantly increases mortality; early intubation if any signs (singed nasal hair, hoarse voice, sooty sputum, stridor).',
    ],
    redFlags: [
      'Inhalation injury: stridor, hoarseness, singed nasal hair — immediate intubation before airway oedema progresses',
      'TBSA >40% or full-thickness involvement of face, hands, feet, genitalia — burns unit transfer',
      'Circumferential full-thickness burns of limb (limb-threatening) or chest (respiratory compromise) — escharotomy',
      'Carbon monoxide poisoning: headache, confusion, cherry-red skin — 100% O2 for ≥4 h',
    ],
    investigations: [
      { label: 'ABG with carboxyhaemoglobin (CO poisoning)', urgency: 'stat' },
      { label: 'FBC, U&E, LFTs, coagulation, glucose', urgency: 'stat' },
      { label: 'Urinary catheter and hourly urine output', urgency: 'stat' },
      { label: 'CXR (inhalation injury, pulmonary oedema)', urgency: 'urgent' },
      { label: 'ECG (electrical burns — arrhythmia screening)', urgency: 'urgent' },
      { label: 'Wound photography and surface area assessment (Rule of Nines)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Stop the burning process; remove clothing/jewellery; cool with running water 20 min (if <3 h post burn); wrap in cling film.' },
      { phase: 'immediate', step: 'Airway: 100% O2 via non-rebreather mask; intubate if ANY inhalation injury signs — do not delay.' },
      { phase: 'immediate', step: 'IV access × 2 (large bore, avoid burnt skin); Parkland formula: 4 × kg × TBSA% mL LR; give ½ in first 8 h from time of burn, ½ in next 16 h.' },
      { phase: 'immediate', step: 'Urinary catheter; target UO 0.5–1 mL/kg/hr adults; adjust fluid rate accordingly.' },
      { phase: 'conservative', step: 'Analgesia: IV morphine titrated; NSAIDs cautiously. Tetanus prophylaxis.' },
      { phase: 'conservative', step: 'Wound care: non-adherent dressings (silver sulfadiazine / mepitel / Mepilex Ag); daily wound review.' },
      { phase: 'conservative', step: 'Nutritional support: enteral feeding within 6–8 h via NGT; dietitian review; caloric requirements = Curreri formula.' },
      { phase: 'surgical', step: 'Escharotomy for circumferential full-thickness burns: limb and/or chest; fasciotomy if compartment syndrome.' },
      { phase: 'surgical', step: 'Early excision and split-skin grafting (within 72 h) for deep partial and full-thickness burns.' },
      { phase: 'followup', step: 'Scar management: pressure garments, silicone sheets after wound closure. Physiotherapy and occupational therapy. Psychological support.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '5–10 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Severe burn pain — titrate to response', phase: 'immediate' },
      { drugName: 'Hartmann\'s solution (Lactated Ringer\'s)', dose: 'Parkland: 4 × kg × %TBSA mL', frequency: 'Half in first 8 h, half in next 16 h', route: 'IV (intravenous)', indication: 'Fluid resuscitation post-major burn', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic with opioids', phase: 'immediate' },
      { drugName: 'Silver sulfadiazine 1% cream', dose: 'Apply topically', frequency: 'OD (once daily)', route: 'Topical', indication: 'Antimicrobial wound dressing', phase: 'immediate' },
      { drugName: 'Tetanus toxoid', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Wound prophylaxis if >5 years since last dose or uncertain', phase: 'immediate' },
      { drugName: 'Tetanus immunoglobulin', dose: '250 IU', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Unimmunised patient', phase: 'immediate' },
      { drugName: 'Ketamine', dose: '1–2 mg/kg', frequency: 'As required (procedural)', route: 'IV (intravenous)', indication: 'Procedural sedation for dressing changes — dissociative anaesthesia', phase: 'immediate' },
      { drugName: 'Vitamin C (ascorbic acid)', dose: '66 mg/kg/h', frequency: 'Continuous infusion × 24 h', route: 'IV (intravenous)', duration: '24 h', indication: 'Reduces oedema formation post-major burn — antioxidant effect', phase: 'immediate' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'IV (intravenous)', indication: 'Curling\'s ulcer prophylaxis', phase: 'immediate' },
      { drugName: 'Enoxaparin', dose: '40 mg', frequency: 'OD (once daily)', route: 'SC (subcutaneous)', indication: 'VTE prophylaxis — once haemostasis achieved', phase: 'immediate' },
    ],
    referral: 'Burns unit transfer (TBSA >20%, full-thickness >5%, hands/face/genitalia, inhalation, electrical, chemical, paediatric). Plastic Surgery.',
  },

  {
    diseaseId: 'thermal_burn_minor',
    icd10Prefixes: ['T30.0', 'T14.0'],
    label: 'Minor Thermal Burn (<20% TBSA)',
    keyPoints: [
      'Superficial (1st degree, erythema only) — does not count towards TBSA; treat with cool water and analgesia.',
      'Superficial partial thickness (2nd degree, blistering) — heals within 14 days with non-adherent dressings; do NOT de-roof intact blisters.',
      'Deep partial thickness / full thickness burns require early surgical review regardless of size.',
    ],
    redFlags: [
      'Burns of face, hands, feet, genitalia, or circumferential — refer to Burns specialist',
      'Chemical or electrical burns (TBSA can be deceiving)',
      'Child with scalds suggesting non-accidental injury — safeguarding referral',
      'Failure to heal at 14 days — likely deep partial thickness; surgical review',
    ],
    investigations: [
      { label: 'Rule of Nines TBSA assessment + burn depth documentation', urgency: 'urgent' },
      { label: 'FBC, U&E (if TBSA >10% or systemic features)', urgency: 'routine' },
      { label: 'Wound swab if signs of infection (purulent discharge, cellulitis)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Cool burn with running water 20 minutes (start within 3 h of injury); do NOT use ice.' },
      { phase: 'conservative', step: 'Analgesia: paracetamol + ibuprofen (oral); consider IV morphine for severe pain.' },
      { phase: 'conservative', step: 'Non-adherent dressings (Mepitel, Adaptic, or silver-containing if infection risk); change every 3–5 days.' },
      { phase: 'conservative', step: 'Intact blisters: leave; burst blisters: de-roof and dress. Tetanus prophylaxis.' },
      { phase: 'followup', step: 'Review at 48 h (infection check) and 5–7 days (healing progress). Refer if no healing at 14 days.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'As required (initial)', route: 'PO or IV', indication: 'Initial severe pain — titrate', phase: 'immediate' },
      { drugName: 'Tetanus toxoid', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Wound prophylaxis if >5 years since last dose', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily) × 3–5 days', route: 'PO (oral)', duration: '3–5 days', indication: 'Analgesia', phase: 'discharge' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily) with food × 3–5 days', route: 'PO (oral)', duration: '3–5 days', indication: 'Anti-inflammatory analgesia', phase: 'discharge' },
      { drugName: 'Chlorhexidine 0.05% solution', dose: 'Apply topically', frequency: 'As required', route: 'Topical', indication: 'Wound hygiene', phase: 'discharge' },
      { drugName: 'Silver sulfadiazine 1% cream', dose: 'Apply topically', frequency: 'OD (once daily)', route: 'Topical', indication: 'Antimicrobial dressing for superficial partial thickness burns', phase: 'discharge' },
      { drugName: 'Cefalexin', dose: '500 mg', frequency: 'QDS (four times daily) × 5 days', route: 'PO (oral)', duration: '5 days', indication: 'Infected burn', phase: 'discharge' },
    ],
    referral: 'Plastic Surgery / Burns Clinic if deep partial or full thickness, special areas, or failure to heal.',
  },

  {
    diseaseId: 'electrical_burn',
    icd10Prefixes: ['T75.4'],
    label: 'Electrical Burn / Electrocution Injury',
    keyPoints: [
      'Entry and exit wounds underestimate internal injury — deep tissue necrosis along current path (cardiac, vascular, nerve, muscle).',
      'High-voltage (>1000 V): mandatory cardiac monitoring for 24 h, rhabdomyolysis screening (myoglobinuria — urine appears dark).',
      'Rhabdomyolysis: aggressive IV fluids to maintain UO 1–2 mL/kg/hr; urine alkalinisation with bicarbonate helps prevent myoglobin cast nephropathy.',
    ],
    redFlags: [
      'Cardiac arrest at scene — CPR; defibrillation if ventricular fibrillation (lightning and high-voltage both cause VF)',
      'Arrhythmia on ECG (any) — continuous monitoring minimum 24 h',
      'Myoglobinuria (dark urine) — aggressive hydration urgently; risk of acute renal failure',
      'Compartment syndrome of limb — urgent fasciotomy',
    ],
    investigations: [
      { label: 'ECG (arrhythmia, Q-T prolongation)', urgency: 'stat' },
      { label: 'Urinalysis (myoglobinuria — dipstick positive for blood with no RBCs)', urgency: 'stat' },
      { label: 'CK (creatine kinase — rhabdomyolysis)', urgency: 'stat' },
      { label: 'Renal function, U&E, myoglobin', urgency: 'urgent' },
      { label: 'FBC, troponin (myocardial injury)', urgency: 'urgent' },
      { label: 'Continuous cardiac monitoring × 24 h (high-voltage)', urgency: 'stat' },
    ],
    management: [
      { phase: 'immediate', step: 'Ensure scene safety before patient contact. Primary survey ABCDE; CPR if cardiac arrest.' },
      { phase: 'immediate', step: 'Cardiac monitoring: continuous ECG for minimum 24 h for high-voltage injury.' },
      { phase: 'immediate', step: 'Aggressive IV fluid resuscitation: LR at high rate to maintain UO 1–2 mL/kg/hr until myoglobinuria clears.' },
      { phase: 'conservative', step: 'Urine alkalinisation: sodium bicarbonate (50–100 mmol in 1 L 5% dextrose) if myoglobinuria.' },
      { phase: 'conservative', step: 'Serial CK every 6–8 h; if rising or UO inadequate — consider nephrology input.' },
      { phase: 'surgical', step: 'Wound debridement of electrical entry/exit; repeated at 24–48 h as demarcation becomes clearer.' },
      { phase: 'surgical', step: 'Fasciotomy for compartment syndrome; amputation if limb not salvageable.' },
      { phase: 'followup', step: 'Neurological follow-up (delayed peripheral neuropathy); ophthalmology (cataracts); psychological support.' },
    ],
    medications: [
      { drugName: 'Lactated Ringer\'s solution', dose: 'High rate — titrate to UO 1–2 mL/kg/h', frequency: 'Continuous IV infusion', route: 'IV (intravenous)', indication: 'Aggressive fluid resuscitation for myoglobinuria', phase: 'immediate' },
      { drugName: 'Sodium bicarbonate 8.4%', dose: '50 mmol in 1 L 5% dextrose', frequency: 'Once (over 2 h); repeat if pH <6.5', route: 'IV (intravenous)', indication: 'Urine alkalinisation to prevent myoglobin nephropathy — target urinary pH >6.5', phase: 'immediate' },
      { drugName: 'Mannitol', dose: '0.25–0.5 g/kg', frequency: 'As required', route: 'IV (intravenous)', indication: 'Diuresis for myoglobinuria / compartment syndrome', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '5–10 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Severe pain', phase: 'immediate' },
      { drugName: 'Tetanus toxoid', dose: '0.5 mL', frequency: 'Once', route: 'IM (intramuscular)', indication: 'Wound prophylaxis', phase: 'immediate' },
      { drugName: 'Omeprazole', dose: '40 mg', frequency: 'OD (once daily)', route: 'IV (intravenous)', indication: 'Stress ulcer prophylaxis', phase: 'immediate' },
      { drugName: 'Calcium gluconate 10%', dose: '10 mL', frequency: 'As required', route: 'IV (intravenous)', indication: 'Cardiac arrhythmia or hyperkalaemia from muscle necrosis', phase: 'immediate' },
    ],
    referral: 'Burns unit; Cardiology if arrhythmia; Nephrology if renal impairment; Plastic / Reconstructive Surgery for wound management.',
  },
];
