import type { ManagementProtocol } from '../types.js';

export const upperGIProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'barretts_oesophagus',
    icd10Prefixes: ['K22.7'],
    label: "Barrett's Oesophagus",
    keyPoints: [
      "Barrett's is intestinal metaplasia of the distal oesophagus due to chronic GORD — confirmed by biopsy showing goblet cells.",
      'Surveillance endoscopy interval depends on segment length: <1 cm — no surveillance; 1–3 cm every 5 years; >3 cm every 3 years.',
      'High-grade dysplasia or early cancer: radiofrequency ablation (RFA) or endoscopic mucosal resection (EMR) — curative in 90%.',
    ],
    redFlags: [
      'Dysphagia or odynophagia in known Barrett\'s — urgent OGD to exclude progression.',
      'High-grade dysplasia on surveillance biopsy — immediate endoscopic therapy.',
    ],
    investigations: [
      { label: 'OGD + biopsies (Seattle protocol: 4-quadrant every 2 cm)', urgency: 'routine' },
      { label: 'Oesophageal manometry + pH/impedance monitoring', urgency: 'routine' },
      { label: 'CT chest/abdomen if dysplasia or suspicious lesion', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'High-dose PPI (esomeprazole 40 mg BD) — reduces dysplasia risk; lifestyle modification (weight loss, elevate head of bed).' },
      { phase: 'conservative', step: 'Surveillance endoscopy per British Society of Gastroenterology (BSG) guidelines.' },
      { phase: 'surgical', step: 'Low-grade dysplasia: RFA — mucosal ablation; endoscopic follow-up at 1 year.' },
      { phase: 'surgical', step: 'High-grade dysplasia / T1a cancer: EMR ± RFA — curative; avoids oesophagectomy.' },
      { phase: 'followup', step: 'Post-ablation OGD at 3, 12 months then annually × 5 years.' },
    ],
    referral: 'Gastroenterology / upper GI surgery — complex dysplasia to specialist Barrett\'s unit.',
  },
  {
    diseaseId: 'oesophageal_carcinoma',
    icd10Prefixes: ['C15'],
    label: 'Oesophageal Carcinoma',
    keyPoints: [
      'Squamous cell carcinoma (mid-oesophagus, alcohol/smoking) and adenocarcinoma (GOJ/distal, GORD/Barrett\'s) are the two main types.',
      'CT + PET-CT staging is essential — only ~30% are resectable at presentation.',
      'Ivor-Lewis oesophagectomy (two-phase) or McKeown (three-phase) with curative intent in fit patients.',
    ],
    redFlags: [
      'Complete dysphagia — aspiration risk, dehydration; urgent stenting or NGT.',
      'Haematemesis from tumour — emergency endoscopy / embolisation.',
      'Tracheo-oesophageal fistula (food/fluids causing cough) — emergency covered stent.',
    ],
    investigations: [
      { label: 'OGD + biopsy (confirm histology)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'PET-CT (exclude occult metastases)', urgency: 'urgent' },
      { label: 'Endoscopic USS (EUS) — T- and N-staging', urgency: 'urgent' },
      { label: 'Lung function tests + cardiac assessment (fitness for oesophagectomy)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Neoadjuvant chemotherapy (FLOT × 4 cycles) or chemoradiotherapy (CROSS protocol) before surgery.' },
      { phase: 'surgical', step: 'Ivor-Lewis oesophagectomy (laparotomy + right thoracotomy) — adenocarcinoma of GOJ / distal oesophagus.' },
      { phase: 'surgical', step: 'McKeown three-phase oesophagectomy — upper/mid thoracic SCC.' },
      { phase: 'conservative', step: 'Unresectable / metastatic: platinum-based chemotherapy ± ramucirumab; palliative self-expanding metal stent (SEMS) for dysphagia.' },
      { phase: 'followup', step: 'CT at 3-monthly × 2 years post-resection; dietetic review (weight management post-oesophagectomy).' },
    ],
    referral: 'Urgent upper GI / thoracic MDT — two-week wait referral.',
  },
  {
    diseaseId: 'gastric_carcinoma',
    icd10Prefixes: ['C16'],
    label: 'Gastric Carcinoma',
    keyPoints: [
      'H. pylori eradication is the most important preventable cause — test and treat in all patients.',
      'Virchow\'s node (left supraclavicular lymphadenopathy) and Sister Mary Joseph nodule (umbilical) indicate advanced disease.',
      'Only 25–30% resectable at presentation — total or subtotal gastrectomy depending on site.',
    ],
    redFlags: [
      'Haematemesis / melaena from gastric tumour — emergency endoscopy.',
      'Gastric outlet obstruction — urgent venting gastrostomy or stenting.',
      'Malnutrition / weight loss >10% — urgent dietetic support and nutritional optimisation.',
    ],
    investigations: [
      { label: 'OGD + biopsy (minimum 6 biopsies from lesion)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging)', urgency: 'urgent' },
      { label: 'EUS (T/N staging, resectability)', urgency: 'urgent' },
      { label: 'H. pylori testing (CLO test, serology, or stool antigen)', urgency: 'routine' },
      { label: 'HER2 status (trastuzumab eligibility)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Perioperative chemotherapy: FLOT × 4 pre-op + 4 post-op (preferred in fit patients).' },
      { phase: 'surgical', step: 'Distal tumours: subtotal gastrectomy + D2 lymphadenectomy.' },
      { phase: 'surgical', step: 'Proximal / total stomach: total gastrectomy + Roux-en-Y reconstruction.' },
      { phase: 'conservative', step: 'Metastatic: chemotherapy (FLOT or FOLFOX); HER2+: trastuzumab + chemotherapy.' },
      { phase: 'conservative', step: 'H. pylori eradication in all patients (triple therapy: PPI + amoxicillin + clarithromycin × 7 days).' },
      { phase: 'followup', step: 'CT + OGD at 12 months; dietetic monitoring (B12 injections 3-monthly after gastrectomy).' },
    ],
    referral: 'Urgent upper GI MDT — two-week wait.',
  },
  {
    diseaseId: 'hiatus_hernia',
    icd10Prefixes: ['K44'],
    label: 'Hiatus Hernia',
    keyPoints: [
      'Type I (sliding, 95%) — GOJ slides into chest; type II (rolling) — gastric fundus herniates with GOJ in abdomen.',
      'Type III/IV (giant, complex) — entire stomach and other viscera herniated; risk of volvulus.',
      'Most symptomatic sliding hernias respond to PPI therapy — surgery only for refractory symptoms or mechanical complications.',
    ],
    redFlags: [
      'Gastric volvulus — acute epigastric pain, inability to retch, NGT won\'t pass (Borchardt\'s triad) — emergency surgery.',
      'Incarcerated / strangulated type II/III — emergency laparoscopic repair.',
    ],
    investigations: [
      { label: 'OGD (confirm type, exclude oesophagitis / Barrett\'s)', urgency: 'routine' },
      { label: 'CT chest/abdomen (for type II/III/IV — define anatomy)', urgency: 'routine' },
      { label: 'Oesophageal manometry + 24h pH study (before anti-reflux surgery)', urgency: 'routine' },
      { label: 'Barium swallow (gastric volvulus, paraoeosphageal anatomy)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Type I symptomatic: PPI (omeprazole 20 mg OD), lifestyle measures, head-of-bed elevation.' },
      { phase: 'surgical', step: 'Laparoscopic Nissen fundoplication (360°) — gold standard for GORD-dominant symptoms.' },
      { phase: 'surgical', step: 'Laparoscopic Toupet (270°) fundoplication — preferred if oesophageal dysmotility.' },
      { phase: 'surgical', step: 'Type II/III repair: laparoscopic reduction, crural repair ± mesh, fundoplication.' },
      { phase: 'followup', step: 'Post-op OGD at 3 months; symptom review; PPI wean at 3–6 months.' },
    ],
    referral: 'Upper GI surgery — elective; emergency if volvulus or incarceration.',
  },
  {
    diseaseId: 'achalasia',
    icd10Prefixes: ['K22.0'],
    label: 'Achalasia',
    keyPoints: [
      'Neurogenic degeneration of Auerbach\'s plexus → failed LOS relaxation + absent oesophageal peristalsis.',
      'Oesophageal manometry is gold standard: elevated LOS pressure + aperistalsis (Chicago Classification).',
      'POEM (per-oral endoscopic myotomy) and laparoscopic Heller myotomy + fundoplication have equivalent efficacy.',
    ],
    redFlags: [
      'Aspiration pneumonia — urgent OGD / dilation to reduce aspiration risk.',
      'Sigmoid oesophagus (end-stage) — oesophagectomy may be required.',
    ],
    investigations: [
      { label: 'Barium swallow (bird-beak deformity)', urgency: 'routine' },
      { label: 'High-resolution oesophageal manometry (definitive diagnosis)', urgency: 'routine' },
      { label: 'OGD (exclude pseudoachalasia / malignancy at GOJ)', urgency: 'urgent' },
      { label: 'CT chest/abdomen if pseudoachalasia suspected (age >60)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Pneumatic balloon dilation (PD): 80% success at 5 years; repeated dilations may be needed.' },
      { phase: 'surgical', step: 'Laparoscopic Heller myotomy + partial fundoplication (Dor or Toupet): durable, low reflux.' },
      { phase: 'surgical', step: 'POEM (per-oral endoscopic myotomy): endoscopic full-thickness myotomy — no external incisions.' },
      { phase: 'conservative', step: 'Botulinum toxin injection into LOS (elderly / unfit — temporary 6–12 months).' },
      { phase: 'followup', step: 'Timed barium swallow at 3 months; manometry at 12 months to confirm response.' },
    ],
    referral: 'Upper GI / specialist oesophageal centre.',
  },
  {
    diseaseId: 'oesophageal_perforation',
    icd10Prefixes: ['K22.3'],
    label: 'Oesophageal Perforation (Boerhaave Syndrome)',
    keyPoints: [
      'Boerhaave syndrome: spontaneous full-thickness tear at left posterolateral distal oesophagus after vomiting.',
      'Iatrogenic perforation (endoscopy) is the most common cause overall — early recognition critical.',
      'Mortality rises from 10% if treated within 24 h to >50% if delayed >24 h — this is a surgical emergency.',
    ],
    redFlags: [
      'Mackler triad (vomiting + chest pain + subcutaneous emphysema) — immediate senior surgical review.',
      'Septic shock from mediastinitis — emergency thoracotomy / thoracoscopy.',
    ],
    investigations: [
      { label: 'CT chest/abdomen with oral contrast (pneumomediastinum, pleural effusion)', urgency: 'stat' },
      { label: 'Water-soluble contrast swallow (if CT equivocal)', urgency: 'stat' },
      { label: 'FBC, CRP, U&E, blood cultures', urgency: 'stat' },
      { label: 'CXR (pneumomediastinum, pleural effusion — screening)', urgency: 'stat' },
    ],
    management: [
      { phase: 'immediate', step: 'NBM, IV broad-spectrum antibiotics (piperacillin-tazobactam + metronidazole), IV fluids, analgesia.' },
      { phase: 'immediate', step: 'Nasogastric tube (if stable) — decompression; chest drain for pleural effusion.' },
      { phase: 'surgical', step: 'Small contained iatrogenic perforation (<24 h): endoscopic stenting or clip closure.' },
      { phase: 'surgical', step: 'Boerhaave / large perforation: primary repair with drainage ± intercostal muscle flap reinforcement.' },
      { phase: 'surgical', step: 'Late / contaminated: oesophageal exclusion + T-tube drainage; oesophagectomy in severe cases.' },
      { phase: 'followup', step: 'Water-soluble swallow at 7–10 days to confirm healing; prolonged IV antibiotics (4–6 weeks).' },
    ],
    referral: 'Emergency thoracic / upper GI surgery + ICU.',
  },
  {
    diseaseId: 'mallory_weiss',
    icd10Prefixes: ['K22.6'],
    label: 'Mallory-Weiss Tear',
    keyPoints: [
      'Mucosal tear at the GOJ following forceful vomiting — classically post-alcohol binge or hyperemesis.',
      'Accounts for 5–15% of upper GI bleeding presentations; the majority stop spontaneously.',
      'Endoscopy is diagnostic and therapeutic (injection, haemoclip, or band ligation for active bleeding).',
    ],
    redFlags: [
      'Haemodynamic instability — resuscitate; urgent endoscopy.',
      'Haematemesis with coagulopathy (cirrhosis, anticoagulants) — correct coagulopathy urgently.',
    ],
    investigations: [
      { label: 'FBC, coagulation, group & crossmatch', urgency: 'urgent' },
      { label: 'Blatchford score (risk stratify — inpatient vs outpatient endoscopy)', urgency: 'urgent' },
      { label: 'OGD within 24 h (diagnostic + therapeutic)', urgency: 'urgent' },
      { label: 'U&E, LFTs', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access × 2, fluid resuscitation; transfuse if Hb <70 g/L (target 70–90 g/L).' },
      { phase: 'conservative', step: 'Most tears resolve spontaneously — supportive management + PPI.' },
      { phase: 'surgical', step: 'Active bleeding at endoscopy: adrenaline injection + haemoclip or band ligation.' },
      { phase: 'conservative', step: 'Post-endoscopy: PPI BD × 4 weeks; alcohol cessation counselling.' },
      { phase: 'followup', step: 'Outpatient review in 4–6 weeks; repeat OGD only if re-bleeding.' },
    ],
    referral: 'Gastroenterology / on-call medical or surgical team for urgent endoscopy.',
  },
  {
    diseaseId: 'gastritis',
    icd10Prefixes: ['K29.7', 'K29.0'],
    label: 'Gastritis (Acute / Chronic)',
    keyPoints: [
      'H. pylori is the commonest cause of chronic gastritis — test all patients with dyspepsia.',
      'NSAID-induced gastritis: switch to COX-2 inhibitor or add PPI gastroprotection.',
      'Autoimmune gastritis (type A) causes pernicious anaemia — check B12 and intrinsic factor antibodies.',
    ],
    redFlags: [
      'Haematemesis or melaena — upper GI bleed; urgent OGD.',
      'Severe epigastric pain with rigidity — consider peptic ulcer perforation.',
    ],
    investigations: [
      { label: 'H. pylori: urea breath test (gold standard) or stool antigen test', urgency: 'routine' },
      { label: 'OGD + biopsies if alarm features or age >55 (exclude malignancy)', urgency: 'urgent' },
      { label: 'FBC (exclude iron-deficiency anaemia from chronic blood loss)', urgency: 'routine' },
      { label: 'B12, intrinsic factor antibodies (if pernicious anaemia suspected)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'H. pylori eradication: triple therapy (PPI + amoxicillin + clarithromycin × 7 days); confirm eradication with breath test at 4 weeks.' },
      { phase: 'conservative', step: 'NSAID-induced: stop NSAID; switch to COX-2 inhibitor ± PPI (esomeprazole 20–40 mg OD).' },
      { phase: 'conservative', step: 'Lifestyle: avoid alcohol, caffeine, spicy foods; small frequent meals.' },
      { phase: 'conservative', step: 'Autoimmune: B12 injections (hydroxocobalamin 1 mg IM every 3 months lifelong).' },
      { phase: 'followup', step: 'Symptom review at 4–6 weeks; repeat OGD only if symptoms persist or alarm features.' },
    ],
  },
  {
    diseaseId: 'upper_gi_bleed',
    icd10Prefixes: ['K92.2', 'K92.0', 'K92.1'],
    label: 'Upper GI Haemorrhage',
    keyPoints: [
      'Blatchford score at presentation guides admission; Rockall score post-endoscopy guides re-bleeding risk.',
      'Peptic ulcer disease (35–50%), varices (10–25%), Mallory-Weiss (5–15%), and malignancy (5%) are the main causes.',
      'Variceal bleeding: terlipressin + prophylactic antibiotics before endoscopy — band ligation is definitive.',
    ],
    redFlags: [
      'SBP <90 mmHg or HR >100 — haemodynamic instability; activate major haemorrhage protocol.',
      'Active haematemesis with haemodynamic compromise — immediate resuscitation + emergency OGD.',
      'Variceal haemorrhage not controlled by banding — Sengstaken-Blakemore tube as bridge to TIPS.',
    ],
    investigations: [
      { label: 'FBC, coagulation screen, group & crossmatch × 2 units', urgency: 'stat' },
      { label: 'U&E (elevated urea:creatinine ratio suggests upper GI source)', urgency: 'stat' },
      { label: 'Blatchford score (pre-endoscopy risk stratification)', urgency: 'stat' },
      { label: 'OGD within 24 h (12 h if unstable)', urgency: 'urgent' },
      { label: 'LFTs, INR (cirrhosis screen)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'IV access × 2 large-bore; fluid resuscitation (crystalloid); transfuse to Hb 70–90 g/L (80–100 in varices).' },
      { phase: 'immediate', step: 'IV PPI (omeprazole 80 mg bolus then 8 mg/h) for suspected peptic ulcer.' },
      { phase: 'immediate', step: 'Suspected varices: terlipressin 2 mg QDS + prophylactic IV ceftriaxone.' },
      { phase: 'surgical', step: 'OGD: peptic ulcer — inject adrenaline + haemoclip or thermal coagulation. Varices — endoscopic band ligation.' },
      { phase: 'surgical', step: 'Refractory peptic ulcer bleeding: interventional radiology (embolisation) or emergency surgery (oversewing ± pyloroplasty).' },
      { phase: 'followup', step: 'H. pylori test-and-treat post-discharge; secondary prophylaxis (PPI long-term if NSAID cannot be stopped; propranolol ± endoscopic surveillance for varices).' },
    ],
    referral: 'Emergency gastroenterology / general surgery + endoscopy on-call.',
  },
  {
    diseaseId: 'gastric_outlet_obstruction',
    icd10Prefixes: ['K31.1'],
    label: 'Gastric Outlet Obstruction',
    keyPoints: [
      'Benign causes: peptic stricture (H. pylori), adult hypertrophic pyloric stenosis; malignant: gastric, duodenal, pancreatic carcinoma.',
      'Hypochloraemic hypokalaemic metabolic alkalosis (loss of HCl from vomiting) is characteristic — correct before any procedure.',
      'Endoscopic balloon dilation for benign strictures; surgical bypass or stenting for malignant obstruction.',
    ],
    redFlags: [
      'Aspiration of large-volume vomit — NBM, NGT decompression urgently.',
      'Severe electrolyte derangement (K <3.0 mmol/L) — correct before endoscopy or surgery.',
    ],
    investigations: [
      { label: 'FBC, U&E, venous blood gas (metabolic alkalosis confirmation)', urgency: 'urgent' },
      { label: 'CT abdomen with oral + IV contrast (define cause, exclude perforation)', urgency: 'urgent' },
      { label: 'OGD + biopsy (confirm benign vs malignant, H. pylori testing)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'NBM, wide-bore NGT aspiration, IV saline with KCl replacement; correct alkalosis.' },
      { phase: 'conservative', step: 'Benign (H. pylori peptic stricture): eradication therapy + endoscopic balloon dilation × 3 sessions.' },
      { phase: 'surgical', step: 'Refractory benign: laparoscopic gastrojejunostomy or pyloroplasty.' },
      { phase: 'surgical', step: 'Malignant (unresectable): palliative gastroduodenal SEMS or surgical bypass (gastrojejunostomy).' },
      { phase: 'followup', step: 'Nutritional support (NG feeds initially); OGD at 6–8 weeks to confirm dilation response.' },
    ],
    referral: 'Upper GI surgery + gastroenterology; MDT if malignant.',
  },
  {
    diseaseId: 'oesophageal_stricture',
    icd10Prefixes: ['K22.2'],
    label: 'Benign Oesophageal Stricture',
    keyPoints: [
      'Peptic stricture (GORD, 60%) is the commonest benign cause — high-dose PPI essential alongside dilation.',
      'Eosinophilic oesophagitis: in young patients with food bolus impaction; requires steroid therapy + dilation.',
      'Progressive dilation (Savary-Gilliard or through-the-scope balloon) — start with 3 dilations at 3-week intervals.',
    ],
    redFlags: [
      'Inability to swallow saliva — emergency OGD; food bolus disimpaction.',
      'Rapid progression of dysphagia despite dilation — malignant stricture until proven otherwise; CT + biopsy.',
    ],
    investigations: [
      { label: 'OGD + biopsies (exclude malignancy, eosinophilic oesophagitis)', urgency: 'urgent' },
      { label: 'Barium swallow (stricture length and morphology)', urgency: 'routine' },
      { label: 'CT chest if malignant features on endoscopy', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'High-dose PPI (esomeprazole 40 mg BD) — acid suppression reduces recurrence of peptic strictures.' },
      { phase: 'surgical', step: 'Endoscopic balloon dilation or Savary-Gilliard bougienage — staged to avoid perforation.' },
      { phase: 'conservative', step: 'Eosinophilic oesophagitis: swallowed fluticasone or budesonide + dietary elimination.' },
      { phase: 'surgical', step: 'Refractory: SEMS (temporary / retrievable) or surgical oesophagogastroplasty.' },
      { phase: 'followup', step: 'Symptom review at 4–6 weeks post-dilation; repeat OGD if dysphagia returns.' },
    ],
    referral: 'Gastroenterology / upper GI surgery.',
  },
  {
    diseaseId: 'dumping_syndrome',
    icd10Prefixes: ['K91.1'],
    label: 'Dumping Syndrome',
    keyPoints: [
      'Early dumping (15–30 min post-meal): rapid gastric emptying → osmotic fluid shift + vasoactive mediators.',
      'Late dumping (1–3 h): reactive hypoglycaemia from insulin surge following hyperglycaemia.',
      'Dietary modification (small frequent meals, no fluids with meals, low simple carbohydrates) resolves 85% of cases.',
    ],
    redFlags: [
      'Severe hypoglycaemic episodes — risk of loss of consciousness; urgent dietetic review + acarbose / octreotide.',
    ],
    investigations: [
      { label: 'Glucose profile (capillary monitoring at 30 min, 1 h, 2 h post-meal)', urgency: 'routine' },
      { label: 'Gastric emptying study (confirm rapid transit)', urgency: 'routine' },
      { label: 'Nutritional assessment (dietitian)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Small frequent meals (6/day); separate fluids from solids; reduce simple carbohydrates.' },
      { phase: 'conservative', step: 'Acarbose (glucosidase inhibitor) — delays carbohydrate absorption; useful for late dumping.' },
      { phase: 'conservative', step: 'Subcutaneous octreotide before meals — reduces symptoms in refractory cases.' },
      { phase: 'surgical', step: 'Refractory: surgical reconstruction (Roux-en-Y conversion, reversed jejunal segment).' },
      { phase: 'followup', step: 'Dietitian review at 3 months; weight and nutritional status monitoring.' },
    ],
    referral: 'Upper GI surgery (post-gastrectomy clinic) + dietitian.',
  },
];
