import type { ManagementProtocol } from '../types.js';

export const urologyProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'renal_colic',
    icd10Prefixes: ['N20', 'N21', 'N22'],
    label: 'Renal Colic / Urolithiasis',
    keyPoints: [
      'Loin-to-groin colicky pain with haematuria — 95% of ureteric stones <4 mm pass spontaneously.',
      'CT KUB (non-contrast) is the gold standard for diagnosis — more sensitive than IVU or USS.',
      'Alpha-blocker (tamsulosin 0.4 mg OD) facilitates stone passage for distal ureteric stones ≤10 mm (MET therapy).',
    ],
    redFlags: [
      'Fever + loin pain (infected obstructed kidney) — urological emergency; IV antibiotics + urgent drainage (JJ stent or PCN).',
      'Bilateral obstruction or solitary kidney — acute renal failure risk; emergency urological referral.',
      'Intractable pain, vomiting, or unable to maintain oral hydration — hospital admission.',
    ],
    investigations: [
      { label: 'CT KUB (non-contrast) — stone size, location, hydronephrosis', urgency: 'urgent' },
      { label: 'Urinalysis + MSU C&S', urgency: 'urgent' },
      { label: 'FBC, U&E, eGFR, CRP, blood cultures (if febrile)', urgency: 'urgent' },
      { label: 'USS KUB (pregnancy, children — avoids radiation)', urgency: 'urgent' },
      { label: 'Stone metabolic workup (24h urine calcium, oxalate, urate, citrate — recurrent stones)', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Analgesia: diclofenac 75 mg IM / PR (first-line); opioids if NSAIDs contraindicated; antiemetic.' },
      { phase: 'conservative', step: 'MET (medical expulsive therapy): tamsulosin 0.4 mg OD for distal ureteric stone ≤10 mm × 4 weeks.' },
      { phase: 'conservative', step: 'High fluid intake (>2 L/day) — dilutes urine, prevents crystal aggregation.' },
      { phase: 'surgical', step: 'ESWL (extracorporeal shockwave lithotripsy) for renal or proximal ureteric stones <20 mm.' },
      { phase: 'surgical', step: 'Ureteroscopy + laser lithotripsy (URS): stones >10 mm, distal ureter, or ESWL failure.' },
      { phase: 'surgical', step: 'PCNL (percutaneous nephrolithotomy): staghorn / large renal stones >20 mm.' },
      { phase: 'followup', step: 'KUB X-ray / USS at 4 weeks (stone passage); dietary advice (hydration, reduce salt/oxalate/animal protein).' },
    ],
    medications: [
      { drugName: 'Diclofenac', dose: '75 mg', frequency: 'Single dose (repeat after 30 min if required)', route: 'IM / PR (intramuscular or per rectum)', indication: 'First-line NSAID analgesia', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '5–10 mg', frequency: 'Q4H (every 4 hours) PRN', route: 'IV / IM (intravenous or intramuscular)', indication: 'Breakthrough analgesia if NSAIDs contraindicated', phase: 'immediate', alternativeTo: 'Diclofenac' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV / PO (intravenous or oral)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Tamsulosin', dose: '0.4 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: 'Until stone passes or 4 weeks', indication: 'MET — medical expulsive therapy for distal ureteric stone ≤10 mm', phase: 'conservative' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Supplemental analgesia', phase: 'conservative' },
    ],
    referral: 'Urology — urgent if infected, bilateral, solitary kidney, or stone >10 mm.',
  },
  {
    diseaseId: 'haematuria_investigation',
    icd10Prefixes: ['R31'],
    label: 'Haematuria Investigation',
    keyPoints: [
      'Any visible (macroscopic) haematuria in patients >45 requires urgent investigation to exclude urothelial malignancy.',
      'Two-week wait referral: visible haematuria (any age >45); non-visible with age >60 + dysuria or raised WBC.',
      'Flexible cystoscopy + CT urogram is the standard haematuria investigation pathway.',
    ],
    redFlags: [
      'Visible haematuria + clot retention — emergency bladder irrigation ± cystoscopy.',
      'Haematuria + loin pain (renal colic pattern) — CT KUB urgently (renal calculus vs tumour).',
      'Haematuria + weight loss / bone pain — suspected malignancy with possible metastases.',
    ],
    investigations: [
      { label: 'Urinalysis + MSU C&S (exclude infection before imaging)', urgency: 'urgent' },
      { label: 'FBC, U&E, eGFR, INR (exclude coagulopathy)', urgency: 'urgent' },
      { label: 'CT urogram (renal, ureteric, and bladder phases)', urgency: 'urgent' },
      { label: 'Flexible cystoscopy (exclude bladder tumour / inflammation)', urgency: 'urgent' },
      { label: 'Urine cytology (3 morning specimens — supplementary to cystoscopy)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Haematuria due to UTI: treat with appropriate antibiotics + repeat urinalysis at 6 weeks.' },
      { phase: 'conservative', step: 'Benign haematuria (anti-GBM, IgA nephropathy): nephrology referral; no urological intervention.' },
      { phase: 'surgical', step: 'Bladder lesion at cystoscopy: TURBT (transurethral resection) for histological diagnosis.' },
      { phase: 'surgical', step: 'Renal mass: MDT discussion — partial or radical nephrectomy, ablation, or surveillance.' },
      { phase: 'followup', step: 'All visible haematuria cases: urology review at 6 weeks with investigation results.' },
    ],
    medications: [
      { drugName: 'Trimethoprim', dose: '200 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7 days', indication: 'If UTI confirmed per culture', phase: 'conservative' },
      { drugName: 'Nitrofurantoin MR', dose: '100 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '5 days', indication: 'If UTI confirmed — alternative to trimethoprim', phase: 'conservative', alternativeTo: 'Trimethoprim' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia for dysuria', phase: 'conservative' },
    ],
    referral: 'Urgent 2-week wait urology referral for visible haematuria age >45.',
  },
  {
    diseaseId: 'bladder_carcinoma',
    icd10Prefixes: ['C67'],
    label: 'Bladder Carcinoma',
    keyPoints: [
      'Transitional cell carcinoma (TCC / urothelial carcinoma) accounts for 90% of bladder cancers — smoking is the main risk factor.',
      'Non-muscle invasive (NMIBC, Ta/T1) vs muscle invasive (MIBC, T2+) determines treatment pathway — TURBT is essential for staging.',
      'Intravesical BCG (for high-risk NMIBC) reduces recurrence and progression; radical cystectomy is curative for MIBC.',
    ],
    redFlags: [
      'T2+ disease on TURBT histology — urgent CT staging and MDT discussion for radical intent treatment.',
      'Ureteric obstruction from tumour — bilateral nephrostomies to preserve renal function.',
    ],
    investigations: [
      { label: 'Flexible cystoscopy + biopsy', urgency: 'urgent' },
      { label: 'TURBT (transurethral resection — staging and therapeutic)', urgency: 'urgent' },
      { label: 'CT urogram (staging, upper tract)', urgency: 'urgent' },
      { label: 'CT chest (if MIBC — pulmonary staging)', urgency: 'urgent' },
      { label: 'Urine cytology (sensitivity for CIS and high-grade disease)', urgency: 'routine' },
    ],
    management: [
      { phase: 'surgical', step: 'NMIBC (Ta/T1): TURBT ± single-dose intravesical mitomycin C immediately post-op.' },
      { phase: 'conservative', step: 'High-risk NMIBC: intravesical BCG induction (6 weekly instillations) + maintenance × 3 years.' },
      { phase: 'surgical', step: 'MIBC (T2–T4a, N0, M0): radical cystectomy + ileal conduit or neobladder.' },
      { phase: 'conservative', step: 'Neoadjuvant chemotherapy before radical cystectomy: gemcitabine + cisplatin × 4 cycles (if fit).' },
      { phase: 'conservative', step: 'Metastatic: gemcitabine + cisplatin; pembrolizumab / atezolizumab after platinum failure.' },
      { phase: 'followup', step: 'NMIBC surveillance: cystoscopy at 3, 12 months then annually; MIBC: CT 6-monthly × 2 years.' },
    ],
    medications: [
      { drugName: 'Mitomycin C', dose: '40 mg', frequency: 'Single instillation within 6 h of TURBT', route: 'Intravesical', indication: 'Post-TURBT adjuvant — reduces NMIBC recurrence', phase: 'immediate' },
      { drugName: 'BCG (intravesical)', dose: '81 mg', frequency: 'Weekly × 6 (induction), then × 3 at 3, 6, 12 months (maintenance)', route: 'Intravesical', indication: 'High-risk NMIBC — reduces relapse and progression', phase: 'immediate' },
      { drugName: 'Gemcitabine', dose: '1250 mg/m²', frequency: 'Days 1 and 8 per cycle', route: 'IV (intravenous)', indication: 'Metastatic urothelial carcinoma — refer oncology', phase: 'conservative' },
      { drugName: 'Cisplatin', dose: '70 mg/m²', frequency: 'Day 1 per cycle', route: 'IV (intravenous)', indication: 'Metastatic combination chemotherapy with gemcitabine — refer oncology', phase: 'conservative' },
      { drugName: 'Pembrolizumab', dose: '200 mg', frequency: 'Every 3 weeks', route: 'IV (intravenous)', indication: 'Post-platinum metastatic — immunotherapy checkpoint inhibitor, refer oncology', phase: 'conservative' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Post-TURBT pain', phase: 'immediate' },
    ],
    referral: 'Urgent 2-week wait urology MDT.',
  },
  {
    diseaseId: 'bph',
    icd10Prefixes: ['N40'],
    label: 'Benign Prostatic Hyperplasia (BPH)',
    keyPoints: [
      'IPSS (International Prostate Symptom Score) guides severity: ≤7 mild, 8–19 moderate, ≥20 severe.',
      'PSA should be measured in all patients before treatment — cancer must be excluded or discussed.',
      'Medical therapy effective for IPSS 8–19: alpha-blocker (tamsulosin) for symptom relief; 5-ARI (finasteride) reduces prostate volume.',
    ],
    redFlags: [
      'Acute urinary retention — catheterise immediately (14–16F urethral or suprapubic); TWOC at 48–72 h on tamsulosin.',
      'Haematuria, recurrent UTI, bladder stones, renal impairment — surgical intervention indicated.',
      'PSA >4.0 ng/mL (or rising) — prostate cancer must be excluded; urgent urology referral.',
    ],
    investigations: [
      { label: 'Urinalysis + MSU C&S', urgency: 'routine' },
      { label: 'PSA (discuss implications before testing)', urgency: 'routine' },
      { label: 'U&E, eGFR (renal impairment from obstruction)', urgency: 'routine' },
      { label: 'Bladder USS (post-void residual — PVR)', urgency: 'routine' },
      { label: 'Uroflowmetry (maximum flow rate Qmax <10 mL/s suggests obstruction)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Lifestyle: fluid restriction at night, reduce caffeine / alcohol, bladder retraining.' },
      { phase: 'conservative', step: 'Alpha-blocker: tamsulosin 0.4 mg OD — onset in 2 weeks; first-line for LUTS.' },
      { phase: 'conservative', step: '5-alpha-reductase inhibitor: finasteride 5 mg OD — reduces prostate volume 20–30% over 6 months; best for >40 mL gland.' },
      { phase: 'conservative', step: 'Combination therapy: tamsulosin + dutasteride (CombAT) — superior to monotherapy in large glands.' },
      { phase: 'surgical', step: 'TURP (transurethral resection of prostate) — gold standard surgery; HoLEP for larger glands.' },
      { phase: 'followup', step: 'PSA at 6 months (finasteride halves PSA — adjust threshold); IPSS at 3 months; annual PSA thereafter.' },
    ],
    medications: [
      { drugName: 'Tamsulosin', dose: '0.4 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Alpha-1 blocker — onset 2 weeks; first-line for LUTS', phase: 'conservative' },
      { drugName: 'Finasteride', dose: '5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: '5-alpha reductase inhibitor — reduces prostate volume over 6 months, halves PSA', phase: 'conservative' },
      { drugName: 'Dutasteride + Tamsulosin (CombAT)', dose: '0.5 mg + 0.4 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'CombAT combination — superior to monotherapy for LUTS with enlarged prostate', phase: 'conservative', alternativeTo: 'Finasteride' },
      { drugName: 'Solifenacin', dose: '5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antimuscarinic for storage LUTS if predominant OAB component', phase: 'conservative' },
    ],
    referral: 'Urology — for surgical assessment or elevated PSA.',
  },
  {
    diseaseId: 'urinary_retention',
    icd10Prefixes: ['R33'],
    label: 'Acute Urinary Retention (AUR)',
    keyPoints: [
      'Precipitated AUR (post-op, constipation, drugs) has 40–50% chance of successful TWOC; spontaneous AUR has lower rate.',
      'Suprapubic catheter (SPC) preferred over urethral if difficult catheterisation, urethral trauma, or planned TURP.',
      'TWOC after 48–72 h on tamsulosin 0.4 mg — success rate ~60%; failure → repeat TWOC or proceed to surgery.',
    ],
    redFlags: [
      'Retention with high-pressure chronic retention (bilateral hydronephrosis, eGFR <60) — emergency decompression; watch for post-obstructive diuresis.' ,
      'Urosepsis signs with retention — IV antibiotics + urgent catheterisation.',
    ],
    investigations: [
      { label: 'Urinalysis + MSU C&S', urgency: 'urgent' },
      { label: 'U&E, eGFR, PSA (once catheterised)', urgency: 'urgent' },
      { label: 'Bladder USS (confirm retention; exclude malignancy as cause)', urgency: 'urgent' },
      { label: 'CT abdomen/pelvis (if pelvic mass or trauma suspected)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Catheterise (14–16F Foley, lubricate generously) — drain slowly, record volume; >800 mL confirms AUR.' },
      { phase: 'conservative', step: 'Start tamsulosin 0.4 mg OD immediately; attempt TWOC at 48–72 h.' },
      { phase: 'surgical', step: 'Difficult catheterisation: flexible cystoscopy-guided catheter or SPC under USS guidance.' },
      { phase: 'surgical', step: 'Failed TWOC × 2 or high residual volume: TURP / HoLEP — definitive surgical decompression.' },
      { phase: 'conservative', step: 'Post-obstructive diuresis: IV fluid replacement + hourly urine output monitoring.' },
      { phase: 'followup', step: 'Urology review within 2 weeks; PSA reassay at 6 weeks post-catheter.' },
    ],
    medications: [
      { drugName: 'Tamsulosin', dose: '0.4 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Start immediately for TWOC preparation; reduces urethral resistance', phase: 'immediate' },
      { drugName: 'Sodium chloride 0.9%', dose: '1 L', frequency: 'Titrated to urine output', route: 'IV (intravenous)', indication: 'Post-obstructive diuresis fluid replacement', phase: 'immediate' },
      { drugName: 'Bethanechol', dose: '25 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Cholinergic agent for atonic detrusor — rarely used; specialist decision only', phase: 'conservative' },
    ],
    referral: 'Urology — urgent same-day.',
  },
  {
    diseaseId: 'uti',
    icd10Prefixes: ['N39.0', 'N30'],
    label: 'Urinary Tract Infection (UTI)',
    keyPoints: [
      'Uncomplicated lower UTI (young, non-pregnant women): empirical treatment without urine culture.',
      'Complicated UTI (male, pregnant, catheterised, diabetic, upper tract): MSU C&S mandatory before antibiotics.',
      'Pyelonephritis: 10–14 days of antibiotic therapy; oral ciprofloxacin first-line if not systemically unwell.',
    ],
    redFlags: [
      'Sepsis (HR >90, temp >38°C or <36°C, RR >20, confusion) — IV antibiotics + fluid resuscitation urgently.',
      'UTI in male <50 — exclude structural abnormality and STI; urological assessment.',
      'Recurrent UTIs (>3/year) — investigate for calculi, structural abnormality, or malignancy.',
    ],
    investigations: [
      { label: 'MSU C&S (mid-stream urine — before antibiotics)', urgency: 'urgent' },
      { label: 'Urinalysis (nitrites, leucocytes, blood)', urgency: 'urgent' },
      { label: 'FBC, CRP, blood cultures (if pyelonephritis / sepsis)', urgency: 'urgent' },
      { label: 'USS renal tract (complicated / recurrent UTI)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Uncomplicated lower UTI: trimethoprim 200 mg BD × 7 days (first-line) or nitrofurantoin MR 100 mg BD × 5 days.' },
      { phase: 'conservative', step: 'Pyelonephritis: oral ciprofloxacin 500 mg BD × 14 days; IV co-amoxiclav or ceftriaxone if systemically unwell.' },
      { phase: 'conservative', step: 'Catheter-associated UTI (CAUTI): remove or change catheter; antibiotics only if symptomatic.' },
      { phase: 'conservative', step: 'Recurrent UTI prophylaxis: low-dose nitrofurantoin 50 mg nocte or trimethoprim 100 mg nocte × 6 months.' },
      { phase: 'followup', step: 'MSU at 5–7 days post-treatment for pyelonephritis; investigate recurrent cases (USS, cystoscopy).' },
    ],
    medications: [
      { drugName: 'Trimethoprim', dose: '200 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7 days', indication: 'Uncomplicated lower UTI — first-line', phase: 'conservative' },
      { drugName: 'Nitrofurantoin MR', dose: '100 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '5 days', indication: 'Uncomplicated lower UTI — alternative', phase: 'conservative', alternativeTo: 'Trimethoprim' },
      { drugName: 'Cefalexin', dose: '500 mg', frequency: 'QDS (four times daily)', route: 'PO (oral)', duration: '7 days', indication: 'If trimethoprim / nitrofurantoin not suitable', phase: 'conservative' },
      { drugName: 'Ciprofloxacin', dose: '500 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '14 days', indication: 'Pyelonephritis — first-line oral', phase: 'conservative' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'IV then PO (intravenous, transition to oral)', indication: 'Systemically unwell — step-down from IV', phase: 'immediate' },
      { drugName: 'Ceftriaxone', dose: '1 g', frequency: 'OD (once daily)', route: 'IV (intravenous)', indication: 'Severe pyelonephritis / urosepsis', phase: 'immediate' },
      { drugName: 'Nitrofurantoin', dose: '50 mg', frequency: 'Nocte (once nightly)', route: 'PO (oral)', duration: '6 months', indication: 'Prophylaxis for recurrent UTI', phase: 'prophylaxis' },
      { drugName: 'Trimethoprim', dose: '100 mg', frequency: 'Nocte (once nightly)', route: 'PO (oral)', duration: '6 months', indication: 'Prophylaxis for recurrent UTI — alternative', phase: 'prophylaxis', alternativeTo: 'Nitrofurantoin 50 mg nocte' },
    ],
  },
  {
    diseaseId: 'testicular_torsion',
    icd10Prefixes: ['N44.0'],
    label: 'Testicular Torsion',
    keyPoints: [
      'Surgical emergency — viability is 90–100% within 6 h, drops to <10% at 24 h; do NOT delay for imaging.',
      '"Bell clapper" deformity (horizontal testicular lie, absent gubernaculum) is the anatomical predisposition.',
      'Bilateral orchidopexy is performed at the same sitting — contralateral testis has same anatomical risk.',
    ],
    redFlags: [
      'Acute scrotal pain in a male < 35 — testicular torsion until proven otherwise; emergency exploration.',
      'Do NOT perform colour Doppler USS if clinical suspicion is high — proceed directly to theatre.',
    ],
    investigations: [
      { label: 'Clinical diagnosis (acute pain, high-riding testis, absent cremasteric reflex)', urgency: 'stat' },
      { label: 'Colour Doppler USS only if diagnosis genuinely uncertain and theatre delay is negligible', urgency: 'urgent' },
      { label: 'Urinalysis (exclude epididymo-orchitis — white cells, bacteria)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'Consented emergency scrotal exploration without imaging delay; IV access, NBM, analgesia.' },
      { phase: 'surgical', step: 'Scrotal exploration: de-torsion + assessment of viability (warm saline swab × 5 minutes).' },
      { phase: 'surgical', step: 'Viable testis: bilateral orchidopexy (3-point fixation with non-absorbable suture).' },
      { phase: 'surgical', step: 'Non-viable testis: orchidectomy + contralateral orchidopexy; offer prosthesis at same or later sitting.' },
      { phase: 'followup', step: 'USS at 3 months (assess salvaged testis volume); counsel on fertility implications if orchidectomy performed.' },
    ],
    medications: [
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Pre-operative analgesia', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '4 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Antiemetic', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV / PO (intravenous or oral)', indication: 'Post-operative multimodal analgesia', phase: 'immediate' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Anti-inflammatory post-orchidopexy — take with food', phase: 'conservative' },
      { drugName: 'Co-amoxiclav (Augmentin)', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5 days', indication: 'Post-operative wound prophylaxis', phase: 'conservative' },
    ],
    referral: 'Emergency urology / general surgery — scrotal exploration within 1 hour of decision.',
  },
  {
    diseaseId: 'epididymo_orchitis',
    icd10Prefixes: ['N45'],
    label: 'Epididymo-orchitis',
    keyPoints: [
      'In men <35: sexually transmitted (Chlamydia trachomatis, Neisseria gonorrhoeae) — take sexual history and STI screen.',
      'In men >35: enteric organisms (E. coli) associated with BPH or urological instrumentation — MSU mandatory.',
      'USS Doppler confirms diagnosis and excludes torsion — increased blood flow in epididymo-orchitis vs absent in torsion.',
    ],
    redFlags: [
      'Clinically cannot exclude torsion — emergency exploration takes priority over antibiotics.',
      'Testicular abscess on USS — I&D or orchidectomy; do not treat conservatively.',
    ],
    investigations: [
      { label: 'Urinalysis + MSU C&S', urgency: 'urgent' },
      { label: 'Urethral swab + NAAT (Chlamydia / Gonorrhoea) in sexually active <35', urgency: 'urgent' },
      { label: 'Colour Doppler USS (confirm diagnosis, exclude abscess, exclude torsion)', urgency: 'urgent' },
      { label: 'FBC, CRP, blood cultures (if systemic sepsis)', urgency: 'urgent' },
      { label: 'Tumour markers (AFP, β-hCG, LDH) if testicular swelling and no inflammatory cause identified', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'STI-related (<35): doxycycline 100 mg BD × 14 days + single-dose ceftriaxone 500 mg IM (gonorrhoea cover).' },
      { phase: 'conservative', step: 'Enteric / non-STI (>35): ciprofloxacin 500 mg BD × 14 days.' },
      { phase: 'conservative', step: 'Analgesia (NSAID), scrotal support, rest; avoid intercourse until 1 week post-treatment.' },
      { phase: 'conservative', step: 'Partner notification and treatment (STI-related); sexual health clinic referral.' },
      { phase: 'followup', step: 'Review at 2 weeks (clinical); USS at 6 weeks if slow to settle (exclude malignancy).' },
    ],
    medications: [
      { drugName: 'Doxycycline', dose: '100 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '14 days', indication: 'STI-associated epididymo-orchitis — age <35; covers Chlamydia', phase: 'conservative' },
      { drugName: 'Ceftriaxone', dose: '500 mg', frequency: 'Single dose', route: 'IM (intramuscular)', indication: 'STI-associated — gonorrhoea cover (Neisseria gonorrhoeae)', phase: 'immediate' },
      { drugName: 'Ciprofloxacin', dose: '500 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '14 days', indication: 'Enteric-associated epididymo-orchitis — age >35', phase: 'conservative', alternativeTo: 'Doxycycline' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Anti-inflammatory / analgesia — take with food', phase: 'conservative' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Supplemental analgesia', phase: 'conservative' },
    ],
    referral: 'Urology / sexual health clinic (STI-related).',
  },
  {
    diseaseId: 'hydrocele',
    icd10Prefixes: ['N43.3'],
    label: 'Hydrocele',
    keyPoints: [
      'Primary (idiopathic) hydrocele: insidious onset, transilluminates, testis palpable separately.',
      'Secondary hydrocele: associated with infection, trauma, or malignancy — always USS to examine the testis.',
      'Surgery (Lord\'s or Jaboulay procedure) is definitive; aspiration is temporising only (high recurrence).',
    ],
    redFlags: [
      'Acute hydrocele with pain — haematocele or secondary to torsion / orchitis; urgent USS.',
      'Non-transilluminable or testis not separately palpable — USS to exclude testicular tumour.',
    ],
    investigations: [
      { label: 'Scrotal USS (primary vs secondary, testis assessment)', urgency: 'routine' },
      { label: 'Tumour markers (AFP, β-hCG, LDH) if testis abnormal on USS', urgency: 'urgent' },
      { label: 'FBC, CRP (if tender — secondary causes)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Asymptomatic primary hydrocele: observe — many are stable and non-troublesome.' },
      { phase: 'surgical', step: 'Jaboulay procedure (eversion of tunica vaginalis) or Lord\'s plication — elective under GA / spinal.' },
      { phase: 'conservative', step: 'Aspiration ± sclerotherapy (phenol or tetracycline) for unfit patients — 30–50% recurrence.' },
      { phase: 'surgical', step: 'Secondary hydrocele: treat underlying cause (antibiotics, orchidectomy for tumour).' },
      { phase: 'followup', step: 'Wound review at 2 weeks; USS at 3 months if secondary hydrocele.' },
    ],
    medications: [
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Post-aspiration or post-operative analgesia', phase: 'conservative' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Anti-inflammatory post-procedure — take with food', phase: 'conservative' },
      { drugName: 'Tetracycline', dose: '500 mg', frequency: 'Single instillation', route: 'Intrascrotal (sclerotherapy)', indication: 'Sclerotherapy agent for aspiration ± sclerotherapy in unfit patients — procedural', phase: 'immediate' },
    ],
    referral: 'Urology — elective, or urgent if secondary / malignancy suspected.',
  },
  {
    diseaseId: 'testicular_cancer',
    icd10Prefixes: ['C62'],
    label: 'Testicular Cancer (Germ Cell Tumour)',
    keyPoints: [
      'Commonest solid tumour in males aged 15–40; excellent prognosis (95% overall 5-year survival).',
      'Seminoma (50%) and non-seminoma (NSGCT, 50%) are the two main histological types — treatment differs.',
      'Radical inguinal orchidectomy is both diagnostic and therapeutic — never trans-scrotal biopsy (disrupts lymphatic drainage).',
    ],
    redFlags: [
      'Painless testicular mass in young male — orchidectomy within 2 weeks; do not delay for chemotherapy response.',
      'Back pain + testicular mass — retroperitoneal lymphadenopathy (L1–L2 para-aortic); urgent CT.',
      'Gynaecomastia + testicular mass — hCG-secreting tumour; gynaenomastia may precede the testicular mass.',
    ],
    investigations: [
      { label: 'Tumour markers: AFP, β-hCG, LDH (before orchidectomy)', urgency: 'urgent' },
      { label: 'Scrotal USS (confirm mass, characteristics, contralateral testis)', urgency: 'urgent' },
      { label: 'CT chest/abdomen/pelvis (staging — retroperitoneal, mediastinal, pulmonary)', urgency: 'urgent' },
      { label: 'Sperm banking (before chemotherapy — counsel all patients)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'surgical', step: 'Radical inguinal orchidectomy (ligation of spermatic cord at internal ring) — pathological staging.' },
      { phase: 'conservative', step: 'Stage I seminoma: surveillance (preferred) or 1× carboplatin AUC7 adjuvant; 97% cure rate.' },
      { phase: 'conservative', step: 'Stage I NSGCT low-risk: surveillance; high-risk (LVI present): 1× BEP chemotherapy.' },
      { phase: 'conservative', step: 'Stage II–IV seminoma or NSGCT: BEP × 3–4 cycles (bleomycin + etoposide + cisplatin).' },
      { phase: 'surgical', step: 'Post-chemotherapy residual mass: RPLND (retroperitoneal lymph node dissection) for NSGCT.' },
      { phase: 'followup', step: 'Tumour markers + CT at 3-monthly × 2 years; annual × 5 years thereafter; contralateral USS annually.' },
    ],
    medications: [
      { drugName: 'Carboplatin', dose: 'AUC7', frequency: 'Single IV infusion', route: 'IV (intravenous)', indication: 'Stage I seminoma adjuvant — 97% cure rate; refer oncology', phase: 'immediate' },
      { drugName: 'Bleomycin', dose: '30 units', frequency: 'Days 2 and 9 per BEP cycle', route: 'IV (intravenous)', indication: 'BEP chemotherapy (bleomycin + etoposide + cisplatin) — refer oncology', phase: 'immediate' },
      { drugName: 'Etoposide', dose: '100 mg/m²', frequency: 'Days 1–5 per BEP cycle', route: 'IV (intravenous)', indication: 'BEP chemotherapy — refer oncology', phase: 'immediate' },
      { drugName: 'Cisplatin', dose: '20 mg/m²', frequency: 'Days 1–5 per BEP cycle', route: 'IV (intravenous)', duration: 'BEP × 3–4 cycles for stage II–IV', indication: 'BEP chemotherapy for stage II–IV seminoma and NSGCT — refer oncology', phase: 'immediate' },
      { drugName: 'Ondansetron', dose: '8 mg', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Chemotherapy-induced nausea and vomiting', phase: 'immediate' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'IV / PO (intravenous or oral)', indication: 'Post-orchidectomy analgesia', phase: 'immediate' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Post-operative pain', phase: 'immediate' },
    ],
    referral: 'Urgent urology + oncology MDT — two-week wait.',
  },
];
