import type { ManagementProtocol } from '../types.js';

export const vascularProtocols: ManagementProtocol[] = [
  {
    diseaseId: 'peripheral_arterial_disease',
    icd10Prefixes: ['I73.9'],
    label: 'Peripheral Arterial Disease',
    keyPoints: [
      'ABI <0.9 is diagnostic; <0.5 suggests critical limb ischaemia requiring urgent revascularisation.',
      'Fontaine staging: I (asymptomatic) → II (claudication) → III (rest pain) → IV (tissue loss/gangrene).',
      'Aggressive cardiovascular risk factor modification reduces MACE risk, which is the leading cause of mortality in PAD.',
    ],
    redFlags: [
      'Critical limb ischaemia: rest pain, tissue loss, or ABI <0.4 — urgent vascular review within 24 hours',
      'Acute limb ischaemia ("6 Ps"): pain, pallor, pulselessness, paraesthesia, paralysis, perishingly cold — surgical emergency',
      'Rapidly progressive gangrene or ascending infection',
    ],
    investigations: [
      { label: 'Ankle-brachial index (ABI) bilaterally', urgency: 'urgent' },
      { label: 'Arterial duplex ultrasound', urgency: 'urgent' },
      { label: 'CT angiography (CTA) of aorta and lower limbs for revascularisation planning', urgency: 'routine' },
      { label: 'FBC, renal function, lipid profile, HbA1c, eGFR', urgency: 'routine' },
      { label: 'ECG (cardiovascular comorbidity screening)', urgency: 'routine' },
      { label: 'Wound swab if tissue loss (for antibiotic guidance)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Antiplatelet therapy: aspirin 75 mg or clopidogrel 75 mg daily lifelong.' },
      { phase: 'conservative', step: 'Statin therapy (atorvastatin 40–80 mg) regardless of baseline LDL; smoking cessation absolute priority.' },
      { phase: 'conservative', step: 'Supervised exercise programme (at least 3×/week for ≥3 months) for claudication.' },
      { phase: 'conservative', step: 'Optimal diabetes and hypertension control; meticulous foot care and footwear.' },
      { phase: 'surgical', step: 'Endovascular angioplasty ± stenting for short-segment stenosis (TASC A/B lesions).' },
      { phase: 'surgical', step: 'Surgical bypass (femoro-popliteal/distal bypass) for extensive occlusions or failed endovascular intervention.' },
      { phase: 'followup', step: 'Duplex surveillance of bypass grafts at 1, 3, 6, and 12 months; annual limb assessment thereafter.' },
    ],
    medications: [
      { drugName: 'Aspirin', dose: '75 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antiplatelet — lifelong cardiovascular risk reduction', phase: 'maintenance' },
      { drugName: 'Clopidogrel', dose: '75 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antiplatelet — alternative to aspirin or add-on post-intervention', phase: 'maintenance', alternativeTo: 'Aspirin' },
      { drugName: 'Atorvastatin', dose: '40–80 mg', frequency: 'OD at night (once daily, nocte)', route: 'PO (oral)', indication: 'Statin therapy — regardless of baseline LDL', phase: 'maintenance' },
      { drugName: 'Amlodipine', dose: '5–10 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antihypertensive', phase: 'maintenance' },
      { drugName: 'Ramipril', dose: '5–10 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antihypertensive — ALLHAT benefit demonstrated in PAD', phase: 'maintenance' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Rest pain or ischaemic ulcer — titrate to pain score', phase: 'immediate' },
    ],
    referral: 'Vascular Surgery urgently if ABI <0.5, rest pain, or tissue loss; routine referral for claudication not improving with 3 months conservative management.',
  },

  {
    diseaseId: 'aortic_aneurysm',
    icd10Prefixes: ['I71.9'],
    label: 'Aortic Aneurysm',
    keyPoints: [
      'Abdominal aortic aneurysm (AAA): defined as aortic diameter >3 cm; risk of rupture rises sharply above 5.5 cm (men) and 5.0 cm (women).',
      'Rupture presents as triad of hypotension, back/abdominal pain, and pulsatile abdominal mass — mortality without surgery >90%.',
      'Symptomatic or rapidly expanding AAA (>1 cm/year or >0.5 cm/6 months) warrants urgent repair regardless of size.',
    ],
    redFlags: [
      'Acute severe back, abdominal, or flank pain in known AAA — suspect rupture; immediate resuscitation and emergency surgery',
      'Haemodynamic instability + pulsatile abdominal mass — immediate vascular surgery activation',
      'Rapid expansion >1 cm in 6 months on surveillance',
      'Mycotic aneurysm: fever, raised inflammatory markers, eccentric saccular aneurysm',
    ],
    investigations: [
      { label: 'Abdominal ultrasound (initial screening, surveillance)', urgency: 'routine' },
      { label: 'CT aortography (definitive assessment, operative planning)', urgency: 'urgent' },
      { label: 'FBC, coagulation screen, group and save', urgency: 'urgent' },
      { label: 'Renal function, eGFR (contrast planning)', urgency: 'urgent' },
      { label: 'ECG, troponin (cardiac risk stratification)', urgency: 'routine' },
      { label: 'Echo (if cardiac symptoms or high-risk surgery planned)', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Ruptured AAA: two large-bore IV cannulae, cross-match 6 units RBC, permissive hypotension (systolic 70–80 mmHg) until in theatre.' },
      { phase: 'conservative', step: 'Small AAA (3.0–5.4 cm): surveillance ultrasound 3-yearly (3–4.4 cm) or annually (4.5–5.4 cm).' },
      { phase: 'conservative', step: 'Cardiovascular risk reduction: statin, antiplatelet, smoking cessation, blood pressure control.' },
      { phase: 'surgical', step: 'Elective repair for AAA ≥5.5 cm (men) / ≥5.0 cm (women), or symptomatic/rapidly expanding: EVAR preferred where anatomy permits.' },
      { phase: 'surgical', step: 'Open surgical repair (midline laparotomy, aortic graft) for anatomy unsuitable for EVAR or EVAR failure.' },
      { phase: 'followup', step: 'Post-EVAR: CT at 1 month, 12 months, then annually for endoleak surveillance.' },
    ],
    medications: [
      { drugName: 'Atorvastatin', dose: '40 mg', frequency: 'OD at night (once daily, nocte)', route: 'PO (oral)', indication: 'Cardiovascular risk reduction', phase: 'maintenance' },
      { drugName: 'Aspirin', dose: '75 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antiplatelet', phase: 'maintenance' },
      { drugName: 'Ramipril', dose: '5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antihypertensive — caution: do NOT aggressively lower BP in ruptured AAA pre-operatively', phase: 'maintenance' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Pain', phase: 'immediate' },
      { drugName: '0.9% Sodium Chloride', dose: 'titrate to SBP 70–80 mmHg', frequency: 'continuous infusion', route: 'IV (intravenous)', indication: 'Permissive hypotensive resuscitation — ruptured AAA (avoid aggressive fluid resuscitation pre-repair)', phase: 'immediate' },
      { drugName: 'Tranexamic acid', dose: '1 g', frequency: 'stat (single dose)', route: 'IV (intravenous)', indication: 'Haemorrhage control — ruptured AAA', phase: 'immediate' },
    ],
    referral: 'Vascular Surgery immediately for symptomatic or ruptured AAA; urgent referral for AAA ≥5.5 cm or rapidly expanding.',
  },

  {
    diseaseId: 'deep_vein_thrombosis',
    icd10Prefixes: ['I82.4'],
    label: 'Deep Vein Thrombosis',
    keyPoints: [
      'Wells score guides pre-test probability: ≥2 = high probability, requires USS; negative D-dimer safely excludes DVT if Wells <2.',
      'Proximal DVT (popliteal and above) carries higher PE risk than distal (calf vein) DVT.',
      'Provoked DVT (surgery, immobility) — 3 months anticoagulation; unprovoked or recurrent — consider indefinite therapy.',
    ],
    redFlags: [
      'Massive iliofemoral DVT with limb-threatening phlegmasia cerulea dolens — urgent vascular referral',
      'Associated PE symptoms: dyspnoea, pleuritic chest pain, haemoptysis, haemodynamic instability',
      'DVT in unusual sites (cerebral venous sinus, mesenteric, hepatic) — consider thrombophilia or malignancy',
    ],
    investigations: [
      { label: 'D-dimer (only if pre-test probability low/intermediate)', urgency: 'urgent' },
      { label: 'Venous duplex ultrasound of affected limb', urgency: 'urgent' },
      { label: 'FBC, coagulation screen (APTT, PT, fibrinogen)', urgency: 'urgent' },
      { label: 'Renal function (guides anticoagulant choice)', urgency: 'urgent' },
      { label: 'Thrombophilia screen (protein C, S, antithrombin, Factor V Leiden, APLA) if unprovoked or recurrent', urgency: 'routine' },
      { label: 'CT chest/abdomen/pelvis if occult malignancy suspected', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Anticoagulate immediately on clinical suspicion (do not delay for imaging if high probability).' },
      { phase: 'conservative', step: 'Direct oral anticoagulant (DOAC): rivaroxaban 15 mg BD for 21 days then 20 mg OD; or apixaban 10 mg BD for 7 days then 5 mg BD.' },
      { phase: 'conservative', step: 'Alternative: LMWH bridging to warfarin (target INR 2–3) if DOAC contraindicated (severe renal failure, pregnancy).' },
      { phase: 'conservative', step: 'Graduated compression stockings (knee-high, 20–30 mmHg) to reduce post-thrombotic syndrome.' },
      { phase: 'conservative', step: 'Ambulation encouraged — bed rest does not reduce PE risk and increases post-thrombotic morbidity.' },
      { phase: 'followup', step: 'Review at 3 months; decision on duration of anticoagulation based on provoked vs unprovoked status and bleeding risk.' },
    ],
    medications: [
      { drugName: 'Rivaroxaban', dose: '15 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '21 days', indication: 'Initial anticoagulation — DOAC first line', phase: 'immediate' },
      { drugName: 'Rivaroxaban', dose: '20 mg', frequency: 'OD with evening meal (once daily)', route: 'PO (oral)', duration: '3–6 months', indication: 'Maintenance anticoagulation', phase: 'maintenance', alternativeTo: 'Apixaban' },
      { drugName: 'Apixaban', dose: '10 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7 days', indication: 'Alternative initial anticoagulation', phase: 'immediate', alternativeTo: 'Rivaroxaban 15mg BD' },
      { drugName: 'Apixaban', dose: '5 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '3–6 months', indication: 'Maintenance anticoagulation', phase: 'maintenance' },
      { drugName: 'Enoxaparin', dose: '1.5 mg/kg', frequency: 'OD (once daily)', route: 'SC (subcutaneous)', indication: 'LMWH bridge if DOAC contraindicated (pregnancy, antiphospholipid syndrome)', phase: 'immediate' },
      { drugName: 'Warfarin', dose: '5 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'If DOAC contraindicated — target INR 2–3', phase: 'maintenance' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia', phase: 'discharge' },
    ],
    referral: 'Vascular Surgery for phlegmasia or catheter-directed thrombolysis consideration; Haematology for thrombophilia or recurrent DVT; Respiratory Medicine if concurrent PE.',
  },

  {
    diseaseId: 'varicose_veins',
    icd10Prefixes: ['I83.9'],
    label: 'Varicose Veins',
    keyPoints: [
      'Great saphenous vein (GSV) incompetence is the most common cause; assess with duplex ultrasound for saphenofemoral junction reflux.',
      'CEAP classification grades venous disease: C2 (varicosities) → C3 (oedema) → C4 (skin changes) → C5/C6 (healed/active ulcer).',
      'Thermal ablation (EVLA or RFA) has largely replaced open saphenofemoral ligation and stripping as first-line surgical treatment.',
    ],
    redFlags: [
      'Bleeding varix — direct pressure, elevate limb, urgent referral',
      'Active or recurrent venous ulceration (CEAP C6)',
      'Superficial thrombophlebitis extending to SFJ — DVT risk; duplex and anticoagulation consideration',
    ],
    investigations: [
      { label: 'Venous duplex ultrasound (reflux mapping, SFJ/SPJ incompetence, saphenous diameter)', urgency: 'routine' },
      { label: 'ABI (exclude concurrent arterial disease before compression therapy)', urgency: 'routine' },
      { label: 'FBC, coagulation (pre-operative)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Graduated compression stockings (class 2: 18–24 mmHg) for symptom relief; elevate limb when resting.' },
      { phase: 'conservative', step: 'Weight reduction, regular walking, avoid prolonged standing.' },
      { phase: 'surgical', step: 'Endovenous laser ablation (EVLA) or radiofrequency ablation (RFA) of incompetent truncal vein under tumescent local anaesthesia — preferred first-line.' },
      { phase: 'surgical', step: 'Ultrasound-guided foam sclerotherapy for tributary or residual varicosities after truncal ablation.' },
      { phase: 'surgical', step: 'Phlebectomy (ambulatory avulsion) of large surface varicosities under local anaesthesia.' },
      { phase: 'followup', step: 'Post-operative duplex at 6 weeks to confirm occlusion and assess residual reflux; compression for 2 weeks post-procedure.' },
    ],
    medications: [
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', duration: '5 days', indication: 'Post-procedural analgesia', phase: 'discharge' },
      { drugName: 'Ibuprofen', dose: '400 mg', frequency: 'TDS (three times daily) with food', route: 'PO (oral)', duration: '5 days', indication: 'Anti-inflammatory — post-procedure', phase: 'discharge' },
      { drugName: 'Enoxaparin', dose: '40 mg', frequency: 'OD (once daily)', route: 'SC (subcutaneous)', duration: '7 days', indication: 'VTE prophylaxis post-procedure if high-risk', phase: 'discharge' },
    ],
    referral: 'Vascular Surgery for treatment; Wound Care team for venous ulceration.',
  },

  {
    diseaseId: 'chronic_venous_insufficiency',
    icd10Prefixes: ['I87.2'],
    label: 'Chronic Venous Insufficiency',
    keyPoints: [
      'Results from sustained venous hypertension due to reflux, obstruction, or calf muscle pump failure.',
      'Skin changes progress: haemosiderosis → lipodermatosclerosis → atrophie blanche → venous ulceration.',
      'Compression therapy (20–40 mmHg) is the cornerstone of management; must exclude arterial disease (ABI >0.8) before applying.',
    ],
    redFlags: [
      'ABI <0.6: full compression contraindicated; modified compression under vascular supervision only',
      'Active cellulitis overlying CVI — treat before compression',
      'Rapidly enlarging ulcer or malignant transformation in a chronic wound',
    ],
    investigations: [
      { label: 'Venous duplex ultrasound (reflux, obstruction, calf vein assessment)', urgency: 'routine' },
      { label: 'ABI (mandatory before compression)', urgency: 'routine' },
      { label: 'Wound swab if infected ulcer', urgency: 'urgent' },
      { label: 'Punch biopsy of ulcer edge if >3 months duration or atypical features (exclude malignancy)', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Four-layer compression bandaging for active venous ulceration; change 1–2× weekly.' },
      { phase: 'conservative', step: 'Once ulcer healed: class 3 compression stockings (34–46 mmHg) indefinitely.' },
      { phase: 'conservative', step: 'Leg elevation above heart level when seated or supine; regular calf exercises.' },
      { phase: 'conservative', step: 'Pentoxifylline 400 mg TDS as adjunct to compression for venous ulcers.' },
      { phase: 'surgical', step: 'Correction of superficial venous reflux (EVLA/RFA) improves ulcer healing and reduces recurrence.' },
      { phase: 'followup', step: 'Regular wound review; SSKIN care bundle (surface, skin, keep moving, incontinence, nutrition).' },
    ],
    medications: [
      { drugName: 'Pentoxifylline', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Adjunct to compression — improves microcirculation in venous ulcers', phase: 'maintenance' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia for ulcer pain', phase: 'maintenance' },
      { drugName: 'Co-amoxiclav', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Infected venous ulcer with surrounding cellulitis', phase: 'discharge' },
    ],
    referral: 'Vascular Surgery if reflux amenable to treatment; Wound Care specialist for complex ulceration; Dermatology if contact dermatitis suspected.',
  },

  {
    diseaseId: 'arterial_ulcer',
    icd10Prefixes: ['I70.2'],
    label: 'Arterial (Ischaemic) Ulcer',
    keyPoints: [
      'Punched-out, painful ulcers over pressure points (heel, metatarsal heads, toes) with pale base; ABI <0.5 typical.',
      'Compression is contraindicated in arterial ulcers — verify ABI before any dressing plan.',
      'Revascularisation is the only definitive treatment; wound care alone will not heal without improved perfusion.',
    ],
    redFlags: [
      'ABI <0.3 or absolute ankle pressure <50 mmHg — critical limb ischaemia requiring emergency vascular review',
      'Gangrene extending proximally; wet gangrene with sepsis',
      'Ascending cellulitis in a critically ischaemic limb — IV antibiotics and urgent revascularisation',
    ],
    investigations: [
      { label: 'ABI (both limbs)', urgency: 'urgent' },
      { label: 'Toe-brachial index (TBI) if ABI falsely elevated by calcification', urgency: 'routine' },
      { label: 'Arterial duplex ultrasound', urgency: 'urgent' },
      { label: 'CT angiography for revascularisation planning', urgency: 'urgent' },
      { label: 'Wound swab (antibiotic guidance)', urgency: 'urgent' },
      { label: 'HbA1c, lipids, renal function', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'IV antibiotics for infected/gangrenous wound (piperacillin-tazobactam or meropenem for severe infection).' },
      { phase: 'conservative', step: 'Pain management: regular opioids often required; limb dependency (hanging leg over bedside) may temporarily improve perfusion.' },
      { phase: 'conservative', step: 'Non-adherent dressings to protect wound; no debridement until revascularisation unless wet gangrene.' },
      { phase: 'surgical', step: 'Urgent revascularisation: endovascular angioplasty/stenting or surgical bypass.' },
      { phase: 'surgical', step: 'Minor amputation (digit, forefoot) after successful revascularisation for gangrenous tissue.' },
      { phase: 'followup', step: 'Post-revascularisation wound care; cardiovascular risk optimisation; graft surveillance duplex.' },
    ],
    medications: [
      { drugName: 'Piperacillin-tazobactam', dose: '4.5 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Infected or gangrenous wound', phase: 'immediate' },
      { drugName: 'Meropenem', dose: '1 g', frequency: 'TDS (three times daily)', route: 'IV (intravenous)', indication: 'Severe infection with MDRO risk', phase: 'immediate', alternativeTo: 'Piperacillin-tazobactam' },
      { drugName: 'Morphine sulfate', dose: '2.5–5 mg', frequency: 'Q4H (every 4 hours)', route: 'IV (intravenous)', indication: 'Rest pain — titrate to pain score', phase: 'immediate' },
      { drugName: 'Oxycodone MR', dose: '10 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Chronic rest pain', phase: 'maintenance' },
      { drugName: 'Aspirin', dose: '75 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Antiplatelet', phase: 'maintenance' },
      { drugName: 'Atorvastatin', dose: '40 mg', frequency: 'OD at night (once daily, nocte)', route: 'PO (oral)', indication: 'Cardiovascular risk reduction', phase: 'maintenance' },
    ],
    referral: 'Urgent Vascular Surgery for all arterial ulcers; Endocrinology/Diabetology for diabetic foot; Orthotics for offloading footwear.',
  },

  {
    diseaseId: 'venous_ulcer',
    icd10Prefixes: ['I87.3'],
    label: 'Venous Leg Ulcer',
    keyPoints: [
      'Medial gaiter area is the classic site; surrounding skin shows haemosiderosis, lipodermatosclerosis, and varicose eczema.',
      'Chronic wound >3 months or atypical appearance — biopsy to exclude malignant transformation (Marjolin\'s ulcer).',
      'High compression (40 mmHg) achieves healing in ~70% within 24 weeks; recurrence rate 50–70% at 5 years without ongoing compression.',
    ],
    redFlags: [
      'Rapidly enlarging ulcer, raised indurated edges — exclude Marjolin\'s ulcer (squamous cell carcinoma)',
      'Systemic sepsis from infected ulcer',
      'ABI <0.6 contraindicating full compression',
    ],
    investigations: [
      { label: 'ABI (to exclude arterial disease)', urgency: 'routine' },
      { label: 'Venous duplex ultrasound', urgency: 'routine' },
      { label: 'Wound swab if clinical infection (purulent discharge, cellulitis)', urgency: 'urgent' },
      { label: 'Biopsy of ulcer edge if >3 months or atypical features', urgency: 'routine' },
      { label: 'FBC, albumin, CRP (nutritional and inflammatory status)', urgency: 'routine' },
    ],
    management: [
      { phase: 'immediate', step: 'Antimicrobial dressings (silver-containing) or systemic antibiotics only for clinically infected wounds.' },
      { phase: 'conservative', step: 'Four-layer high compression bandaging as standard; maintain until healed.' },
      { phase: 'conservative', step: 'Wound bed preparation: debridement of slough; moisture-balancing dressings beneath compression.' },
      { phase: 'conservative', step: 'Pentoxifylline 400 mg TDS as adjunct to compression.' },
      { phase: 'surgical', step: 'Correction of superficial venous reflux (EVLA) once ulcer is small or healed — reduces recurrence.' },
      { phase: 'followup', step: 'Lifelong class 3 compression stockings after healing; patient education on skin care and adherence.' },
    ],
    medications: [
      { drugName: 'Pentoxifylline', dose: '400 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', indication: 'Adjunct to compression — improves microcirculation', phase: 'maintenance' },
      { drugName: 'Co-amoxiclav', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '5–7 days', indication: 'Infected ulcer with surrounding cellulitis', phase: 'discharge' },
      { drugName: 'Paracetamol', dose: '1 g', frequency: 'QDS (four times daily)', route: 'PO (oral)', indication: 'Analgesia for ulcer pain', phase: 'maintenance' },
      { drugName: 'Silver sulfadiazine 1% cream', dose: '1% cream', frequency: 'OD (once daily)', route: 'Topical', indication: 'Antimicrobial dressing for clinically infected wound', phase: 'immediate' },
    ],
    referral: 'Vascular Surgery for reflux correction; Wound Care specialist; Dermatology for eczema or suspected malignant transformation.',
  },

  {
    diseaseId: 'lymphoedema',
    icd10Prefixes: ['I89.0'],
    label: 'Lymphoedema',
    keyPoints: [
      'Primary lymphoedema: Milroy\'s (congenital), lymphoedema praecox (puberty), lymphoedema tarda (after 35 years).',
      'Secondary lymphoedema: most common globally due to filariasis; in Caribbean — post-cancer treatment (surgery/radiotherapy) and obesity.',
      'Pitting oedema early; progresses to non-pitting, woody, fibrotic (elephantiasis) with chronic skin changes.',
    ],
    redFlags: [
      'Acute lymphangitis: streaking erythema, fever, rigors — IV antibiotics and admission',
      'Rapidly increasing limb volume suggesting malignant lymphatic obstruction',
      'Skin breakdown with chronic lymphoedema — portal for recurrent cellulitis',
    ],
    investigations: [
      { label: 'Clinical diagnosis in most cases; lymphoscintigraphy to confirm and classify', urgency: 'routine' },
      { label: 'MRI limb (if malignant obstruction suspected or atypical presentation)', urgency: 'routine' },
      { label: 'Duplex ultrasound (exclude DVT in acute presentation)', urgency: 'urgent' },
      { label: 'FBC, CRP (during acute cellulitis episodes)', urgency: 'urgent' },
      { label: 'Filarial serology (ELISA) in endemic areas', urgency: 'routine' },
    ],
    management: [
      { phase: 'conservative', step: 'Complete decongestive therapy (CDT): manual lymphatic drainage + multilayer bandaging daily during intensive phase.' },
      { phase: 'conservative', step: 'Maintenance: compression garments (flat-knit, class 3–4) fitted after decongestion; worn lifelong.' },
      { phase: 'conservative', step: 'Skin care: daily moisturising, avoidance of trauma, prompt treatment of fungal infections.' },
      { phase: 'conservative', step: 'Antibiotics: penicillin V 500 mg BD prophylaxis if ≥2 cellulitis episodes per year.' },
      { phase: 'surgical', step: 'Liposuction for end-stage non-pitting lymphoedema after CDT fails; lymphatic microsurgery (LYMPHA, LVA) in selected centres.' },
      { phase: 'followup', step: 'Lifelong follow-up with lymphoedema nurse specialist; weight management; annual limb volume measurement.' },
    ],
    medications: [
      { drugName: 'Phenoxymethylpenicillin (Penicillin V)', dose: '500 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'Prophylaxis for recurrent cellulitis (≥2 episodes/year)', phase: 'maintenance' },
      { drugName: 'Fluconazole', dose: '50 mg', frequency: 'OD (once daily)', route: 'PO (oral)', duration: '7 days', indication: 'Tinea pedis — eliminates cellulitis entry portal', phase: 'discharge' },
      { drugName: 'Co-amoxiclav', dose: '625 mg', frequency: 'TDS (three times daily)', route: 'PO (oral)', duration: '10–14 days', indication: 'Acute cellulitis episode', phase: 'immediate' },
    ],
    referral: 'Lymphoedema clinic; Vascular Surgery for surgical options; ID/Tropical Medicine if filariasis.',
  },

  {
    diseaseId: 'pulmonary_embolism',
    icd10Prefixes: ['I26.9'],
    label: 'Pulmonary Embolism',
    keyPoints: [
      'Wells PE score and PERC rule guide pre-test probability; CT pulmonary angiography (CTPA) is the gold-standard investigation.',
      'Massive PE (haemodynamic instability): systemic thrombolysis (alteplase 100 mg IV over 2 hours) is life-saving.',
      'Troponin and BNP predict right heart strain; PESI score guides outpatient vs inpatient management.',
    ],
    redFlags: [
      'Haemodynamic instability (SBP <90 mmHg or drop >40 mmHg) — massive PE; immediate thrombolysis or surgical embolectomy',
      'Right ventricular failure on echo or CT (RV:LV ratio >0.9)',
      'Cardiac arrest with PEA — consider thrombolysis empirically',
      'Falling O2 saturations despite high-flow oxygen',
    ],
    investigations: [
      { label: 'D-dimer (if low pre-test probability — Wells <2)', urgency: 'stat' },
      { label: 'CTPA (CT pulmonary angiography) — gold standard', urgency: 'stat' },
      { label: 'ECG (sinus tachycardia, S1Q3T3, new RBBB)', urgency: 'stat' },
      { label: 'ABG / pulse oximetry', urgency: 'stat' },
      { label: 'Troponin, BNP/NT-proBNP (risk stratification)', urgency: 'urgent' },
      { label: 'Echocardiography (RV function; if CTPA unavailable)', urgency: 'urgent' },
      { label: 'Venous duplex USS lower limbs (concurrent DVT)', urgency: 'urgent' },
    ],
    management: [
      { phase: 'immediate', step: 'High-flow O2; IV access; haemodynamic monitoring; alert anaesthetics/ICU if unstable.' },
      { phase: 'immediate', step: 'Massive PE: alteplase 10 mg IV bolus then 90 mg over 2 h (if no contraindication); surgical embolectomy if thrombolysis fails or contraindicated.' },
      { phase: 'conservative', step: 'Anticoagulation: rivaroxaban 15 mg BD × 21 days then 20 mg OD; or LMWH/warfarin.' },
      { phase: 'conservative', step: 'Low-risk PE (PESI I–II, normal troponin/BNP, adequate home support): early discharge protocol.' },
      { phase: 'followup', step: 'Duration of anticoagulation: 3 months for provoked, ≥6 months for unprovoked; reassess bleeding vs clot risk at 3 months.' },
      { phase: 'followup', step: 'Thrombophilia screen and malignancy workup if unprovoked; CTPA at 3–6 months to exclude chronic thromboembolic disease.' },
    ],
    medications: [
      { drugName: 'Alteplase', dose: '10 mg IV bolus, then 90 mg over 2 hours', frequency: 'stat (once)', route: 'IV (intravenous)', indication: 'Massive PE with haemodynamic compromise — systemic thrombolysis', phase: 'immediate' },
      { drugName: 'Unfractionated heparin', dose: '80 units/kg bolus, then 18 units/kg/h', frequency: 'continuous infusion', route: 'IV (intravenous)', indication: 'Concurrent with thrombolysis or high-risk PE', phase: 'immediate' },
      { drugName: 'Rivaroxaban', dose: '15 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '21 days', indication: 'Non-massive PE — initial anticoagulation', phase: 'immediate' },
      { drugName: 'Rivaroxaban', dose: '20 mg', frequency: 'OD with evening meal (once daily)', route: 'PO (oral)', duration: '3–6 months', indication: 'Maintenance anticoagulation', phase: 'maintenance' },
      { drugName: 'Apixaban', dose: '10 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '7 days', indication: 'Alternative initial anticoagulation', phase: 'immediate', alternativeTo: 'Rivaroxaban 15mg BD' },
      { drugName: 'Apixaban', dose: '5 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', duration: '3–6 months', indication: 'Maintenance anticoagulation', phase: 'maintenance', alternativeTo: 'Rivaroxaban 20mg OD' },
      { drugName: 'Oxygen', dose: '15 L/min', frequency: 'continuous', route: 'inhalation via non-rebreather mask', indication: 'Hypoxia — maintain SpO₂ ≥94%', phase: 'immediate' },
    ],
    referral: 'Respiratory/Acute Medicine for submassive/massive PE; Vascular Surgery for surgical embolectomy; Haematology for thrombophilia workup.',
  },

  {
    diseaseId: 'raynauds_phenomenon',
    icd10Prefixes: ['I73.0'],
    label: 'Raynaud\'s Phenomenon',
    keyPoints: [
      'Triphasic colour change: pallor (white) → cyanosis (blue) → erythema (red) on cold exposure or emotional stress.',
      'Primary Raynaud\'s: young women, bilateral, no tissue loss, normal nailfold capillaroscopy, negative ANA.',
      'Secondary Raynaud\'s: associated with systemic sclerosis, SLE, CREST — nailfold capillary dropout on capillaroscopy.',
    ],
    redFlags: [
      'Digital ulceration or gangrene — critical digital ischaemia; urgent vascular review',
      'Abnormal nailfold capillaroscopy or positive ANA — underlying connective tissue disease',
      'Asymmetric symptoms or onset after age 35 — exclude secondary causes',
    ],
    investigations: [
      { label: 'FBC, ESR, CRP, ANA, anti-dsDNA, anti-Scl-70, anti-centromere antibodies', urgency: 'routine' },
      { label: 'Nailfold capillaroscopy (giant loops, capillary dropout in secondary)', urgency: 'routine' },
      { label: 'Thyroid function tests', urgency: 'routine' },
      { label: 'Cold challenge test (clinical in most cases)', urgency: 'routine' },
      { label: 'Arterial duplex if digital ischaemia or asymmetric disease', urgency: 'urgent' },
    ],
    management: [
      { phase: 'conservative', step: 'Avoid cold; warm gloves, layered clothing, heated hand warmers; smoking cessation mandatory.' },
      { phase: 'conservative', step: 'First-line: nifedipine modified-release 10–20 mg BD (calcium channel blocker).' },
      { phase: 'conservative', step: 'Second-line: losartan 50 mg OD, or amlodipine, or fluoxetine 20 mg OD for refractory primary Raynaud\'s.' },
      { phase: 'conservative', step: 'Digital ulcers: IV iloprost (prostacyclin analogue) infusion for severe secondary Raynaud\'s.' },
      { phase: 'surgical', step: 'Digital sympathectomy for refractory digital ischaemia not responding to medical therapy.' },
      { phase: 'followup', step: 'Monitor for development of connective tissue disease annually; Rheumatology co-management for secondary Raynaud\'s.' },
    ],
    medications: [
      { drugName: 'Nifedipine MR', dose: '10–20 mg', frequency: 'BD (twice daily)', route: 'PO (oral)', indication: 'First-line vasodilator — reduces frequency and severity of attacks', phase: 'maintenance' },
      { drugName: 'Losartan', dose: '50 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Second-line — angiotensin II receptor blocker with vasodilatory effect', phase: 'maintenance', alternativeTo: 'Nifedipine MR' },
      { drugName: 'Amlodipine', dose: '5–10 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Second-line CCB alternative', phase: 'maintenance', alternativeTo: 'Nifedipine MR' },
      { drugName: 'Fluoxetine', dose: '20 mg', frequency: 'OD (once daily)', route: 'PO (oral)', indication: 'Third-line — SSRIs have vasodilatory effect in refractory Raynaud\'s', phase: 'maintenance' },
      { drugName: 'Iloprost', dose: '0.5–2 ng/kg/min', frequency: 'continuous infusion over 6 hours (repeat for 5 days)', route: 'IV (intravenous)', duration: '5 days', indication: 'Severe digital ulcers — IV prostacyclin analogue', phase: 'immediate' },
    ],
    referral: 'Rheumatology if secondary Raynaud\'s suspected; Vascular Surgery if digital ischaemia or ulceration; Dermatology for skin changes.',
  },
];
