// ─── Fact taxonomy ───────────────────────────────────────────────────────────

export type FactType =
  | 'allergy'
  | 'medication'
  | 'diagnosis'
  | 'symptom'
  | 'vital'
  | 'anthropometric'
  | 'lab_result'
  | 'imaging_result'
  | 'pathology_result'
  | 'procedure'
  | 'prescription'
  | 'investigation_order'
  | 'clinical_note'
  | 'follow_up'
  | 'task'
  | 'consent'
  | 'family_history'
  | 'social_history';

export type FactStatus =
  | 'active'      // currently applies
  | 'resolved'    // was true, no longer applies
  | 'suspected'   // unconfirmed, needs clinician verification
  | 'confirmed'   // verified by a clinician
  | 'refuted'     // investigated and excluded
  | 'pending'     // awaiting action or result
  | 'cancelled'   // deliberately stopped
  | 'completed'   // task / order / procedure done
  | 'overdue';    // past due date, not completed

export type FactSource =
  | 'manual'                // clinician typed it
  | 'ai_extracted'          // AI extracted from narrative text
  | 'ai_suggested'          // AI suggestion, not yet accepted
  | 'intake_questionnaire'  // patient-reported at intake
  | 'lab_import'            // imported from lab / external system
  | 'derived_rule'          // generated by clinical rules engine
  | 'historic_record'       // carried forward from prior encounter
  | 'referral_letter';      // from referring clinician's letter

// ─── Typed fact values ───────────────────────────────────────────────────────

export interface AllergyValue {
  substance: string;
  category: 'drug' | 'food' | 'environmental' | 'latex' | 'contrast' | 'other';
  reaction: string;
  severity: 'mild' | 'moderate' | 'severe' | 'anaphylaxis' | 'unknown';
  crossReactivities: string[];
  onsetDate: string | null;
}

export interface MedicationValue {
  name: string;
  genericName: string | null;
  dose: string;
  unit: string;
  route: string;
  frequency: string;
  indication: string | null;
  startDate: string | null;
  endDate: string | null;
  isLongTerm: boolean;
}

export interface DiagnosisValue {
  name: string;
  icd10: string | null;
  certainty: 'working' | 'probable' | 'confirmed' | 'excluded';
  laterality: 'left' | 'right' | 'bilateral' | null;
  onsetDate: string | null;
  resolvedDate: string | null;
  supportingFactIds: string[];
}

export type VitalParameter =
  | 'systolicBp' | 'diastolicBp' | 'heartRate'
  | 'temperatureC' | 'respiratoryRate' | 'spo2' | 'glucoseMmol';

export interface VitalValue {
  parameter: VitalParameter;
  numericValue: number;
  unit: string;
  isAbnormal: boolean;
  isCritical: boolean;
  referenceRange: [number, number];
  takenAt: string;
  method: string | null;
}

export type AnthropometricParameter = 'weightKg' | 'heightCm' | 'waistCm' | 'hipCm' | 'muacCm' | 'bmi';

export interface AnthropometricValue {
  parameter: AnthropometricParameter;
  numericValue: number;
  unit: string;
  takenAt: string;
}

export interface LabResultValue {
  testName: string;
  panel: string | null;
  result: number | string;
  unit: string;
  referenceRange: string;
  isAbnormal: boolean;
  isCritical: boolean;
  trend: 'improving' | 'worsening' | 'stable' | 'new' | null;
  previousValue: number | string | null;
  previousDate: string | null;
  reportedAt: string;
  laboratory: string | null;
  orderFactId: string | null;
}

export interface ImagingResultValue {
  modality: string;
  region: string;
  laterality: string | null;
  findings: string;
  impression: string;
  isAbnormal: boolean;
  urgentFindings: string[];
  performedAt: string;
  reportedBy: string | null;
  orderFactId: string | null;
}

export interface InvestigationOrderValue {
  testName: string;
  panel: string | null;
  category: 'laboratory' | 'radiology' | 'histopathology' | 'endoscopy' | 'cardiology' | 'other';
  urgency: 'stat' | 'urgent' | 'routine';
  indication: string;
  clinicalQuestion: string | null;
  orderedAt: string;
  dueBy: string | null;
  resultFactId: string | null;
  resultReceivedAt: string | null;
}

export interface PrescriptionValue extends MedicationValue {
  prescriptionRef: string | null;
  dispensed: boolean;
  dispensedAt: string | null;
  allergyChecked: boolean;
  interactionChecked: boolean;
  overrideReason: string | null;
}

export interface TaskValue {
  title: string;
  description: string;
  category: 'clinical' | 'administrative' | 'investigation' | 'follow_up' | 'documentation' | 'safety';
  priority: 'critical' | 'high' | 'medium' | 'low';
  assignedTo: string | null;
  dueAt: string | null;
  completedAt: string | null;
  completedBy: string | null;
  completionEvidence: string | null;
  triggeringFactId: string | null;
  ruleId: string | null;
  acknowledgedBy: string | null;
  acknowledgedAt: string | null;
}

export interface FollowUpValue {
  reason: string;
  timeframe: string;
  dueDateIso: string;
  instructions: string;
  appointmentType: string | null;
  triggeringFactId: string | null;
  scheduledAt: string | null;
  completedAt: string | null;
  completionNote: string | null;
}

export interface ConsentValue {
  procedure: string;
  type: 'informed' | 'verbal' | 'written' | 'implied' | 'refused';
  capacityAssessed: boolean;
  witnessedBy: string | null;
  documentRef: string | null;
  refusalReason: string | null;
}

export interface ClinicalNoteValue {
  noteType: 'hpi' | 'progress' | 'procedure' | 'discharge' | 'referral' | 'assessment';
  content: string;
  draftedBy: string | null;
  isDraft: boolean;
  signedAt: string | null;
}

export interface SymptomValue {
  name: string;
  system: string | null;
  onset: string | null;
  duration: string | null;
  severity: number | null;
  character: string | null;
  isPositive: boolean;
}

export interface FamilyHistoryValue {
  condition: string;
  relation: string;
  ageOfOnset: number | null;
  isDeceased: boolean;
}

export interface SocialHistoryValue {
  category: 'smoking' | 'alcohol' | 'drugs' | 'occupation' | 'travel' | 'diet' | 'exercise' | 'other';
  detail: string;
  quantified: string | null;
  startDate: string | null;
  endDate: string | null;
}

export interface FactValueMap {
  allergy: AllergyValue;
  medication: MedicationValue;
  diagnosis: DiagnosisValue;
  symptom: SymptomValue;
  vital: VitalValue;
  anthropometric: AnthropometricValue;
  lab_result: LabResultValue;
  imaging_result: ImagingResultValue;
  pathology_result: LabResultValue;
  procedure: { name: string; icd9: string | null; performedAt: string; notes: string; surgeon: string | null };
  prescription: PrescriptionValue;
  investigation_order: InvestigationOrderValue;
  clinical_note: ClinicalNoteValue;
  follow_up: FollowUpValue;
  task: TaskValue;
  consent: ConsentValue;
  family_history: FamilyHistoryValue;
  social_history: SocialHistoryValue;
}

// ─── Core fact entity ─────────────────────────────────────────────────────────

export interface ClinicalFact<T extends FactType = FactType> {
  id: string;
  patientId: string;
  encounterId: string | null;
  factType: T;
  value: T extends keyof FactValueMap ? FactValueMap[T] : Record<string, unknown>;
  status: FactStatus;
  version: number;           // monotonically increasing per fact
  source: FactSource;
  sourceFactIds: string[];   // facts this was derived/extracted from
  ruleId: string | null;     // rules-engine rule that created this, if any
  createdBy: string;         // user ID, 'system', or 'ai'
  createdAt: string;
  updatedAt: string;
  verifiedBy: string | null; // clinician who explicitly verified safety-critical facts
  verifiedAt: string | null;
  expiresAt: string | null;  // auto-expire time-limited facts
  displayReason: string | null; // WHY this fact appears — shown in provenance UI
  metadata: Record<string, unknown>;
}

// ─── Encounter state machine ──────────────────────────────────────────────────

export type EncounterState =
  | 'registration'
  | 'intake'
  | 'triage'
  | 'consultation'
  | 'investigation'
  | 'treatment'
  | 'procedure'
  | 'discharge'
  | 'follow_up'
  | 'closed';

export interface EncounterStateEntry {
  state: EncounterState;
  enteredAt: string;
  exitedAt: string | null;
  enteredBy: string;
  notes: string | null;
}

export interface EncounterRecord {
  id: string;
  patientId: string;
  state: EncounterState;
  type: string;
  site: string;
  startedAt: string;
  closedAt: string | null;
  stateHistory: EncounterStateEntry[];
  assignedTo: string | null;
  checklist: Record<string, boolean>;
}

// ─── Rules engine ─────────────────────────────────────────────────────────────

export interface RuleAlert {
  severity: 'critical' | 'warning' | 'info';
  message: string;
  detail: string;
  requiresAcknowledgement: boolean;
  requiresOverrideReason: boolean;
  actionLabel: string | null;
}

export interface RuleOutput {
  alert?: RuleAlert;
  tasks?: Array<Partial<TaskValue> & { title: string }>;
  suggestedFacts?: Array<{
    factType: FactType;
    value: Record<string, unknown>;
    displayReason: string;
  }>;
  block?: { reason: string };
  followUps?: Array<Partial<FollowUpValue> & { reason: string; timeframe: string; dueDateIso: string }>;
}

export interface ActiveAlert {
  id: string;
  ruleId: string;
  severity: RuleAlert['severity'];
  message: string;
  detail: string;
  triggeringFactId: string;
  relatedFactIds: string[];
  requiresAcknowledgement: boolean;
  acknowledgedBy: string | null;
  acknowledgedAt: string | null;
  overrideReason: string | null;
  createdAt: string;
}

export interface ClinicalRule {
  id: string;
  name: string;
  description: string;
  category: 'safety' | 'guideline' | 'quality' | 'workflow';
  priority: 'critical' | 'high' | 'medium' | 'low';
  triggerTypes: FactType[];
  evaluate: (allFacts: ClinicalFact[], trigger: ClinicalFact) => RuleOutput | null;
}

// ─── Audit log ────────────────────────────────────────────────────────────────

export interface AuditEntry {
  id: string;
  timestamp: string;
  userId: string;
  sessionId: string;
  action:
    | 'fact_created'
    | 'fact_updated'
    | 'fact_status_changed'
    | 'fact_verified'
    | 'fact_acknowledged'
    | 'encounter_transitioned'
    | 'rule_fired'
    | 'sync_push'
    | 'sync_pull'
    | 'conflict_resolved'
    | 'override_recorded';
  entityType: 'fact' | 'encounter' | 'alert';
  entityId: string;
  previousValue: unknown;
  newValue: unknown;
  source: 'ui' | 'api' | 'rules_engine' | 'ai' | 'sync' | 'import';
  clinicalSignificance: 'safety_critical' | 'clinical' | 'administrative';
  overrideJustification: string | null;
}

// ─── Sync ─────────────────────────────────────────────────────────────────────

export interface SyncConflict {
  factId: string;
  localFact: ClinicalFact;
  remoteFact: ClinicalFact;
  detectedAt: string;
  resolution: 'local_wins' | 'remote_wins' | 'merge' | 'pending';
  resolvedBy: string | null;
  resolvedAt: string | null;
}

export interface SyncState {
  lastSyncAt: string | null;
  pendingPushCount: number;
  pendingPullCount: number;
  conflicts: SyncConflict[];
  isOnline: boolean;
  isSyncing: boolean;
}

// ─── Store events ─────────────────────────────────────────────────────────────

export type StoreEventType =
  | 'fact:created'
  | 'fact:updated'
  | 'fact:status_changed'
  | 'fact:verified'
  | 'alert:raised'
  | 'alert:acknowledged'
  | 'task:created'
  | 'task:completed'
  | 'encounter:transitioned'
  | 'store:loaded'
  | 'store:cleared';

export interface StoreEvent {
  type: StoreEventType;
  factId?: string;
  alertId?: string;
  encounterId?: string;
  userId: string;
  timestamp: string;
  payload?: unknown;
}
