-- ============================================================
-- Amise Medical Services — Clinical Records Migration
-- Adds: clinical_notes, documents, billing_charges,
--       imaging_orders, investigation_results
--
-- Run in: Supabase Dashboard → SQL Editor
-- Prerequisites: supabase-schema.sql must have been applied first
--   (depends on patients, encounters, auth_role(), set_updated_at())
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- CLINICAL NOTES
-- Physician SOAP, progress, operative and discharge notes.
-- AI-drafted notes must be reviewed and signed by a physician
-- before status can move to 'signed'. Unsigned drafts are only
-- visible to the authoring doctor and admins.
-- ─────────────────────────────────────────────────────────────
create table if not exists clinical_notes (
  id               uuid        primary key default uuid_generate_v4(),
  patient_id       uuid        not null references patients(id)   on delete cascade,
  encounter_id     uuid        references encounters(id) on delete set null,

  note_type        text        not null default 'progress'
                               check (note_type in (
                                 'soap', 'progress', 'operative', 'procedure',
                                 'discharge', 'consultation', 'referral_letter', 'other'
                               )),
  status           text        not null default 'draft'
                               check (status in ('draft', 'signed', 'amended', 'addendum')),

  content          text        not null,
  content_html     text,

  -- AI provenance — required for the sign-before-use workflow
  ai_assisted      boolean     not null default false,
  ai_model_used    text,

  -- Physician signature
  signed_by        uuid        references auth.users(id) on delete set null,
  signed_at        timestamptz,
  amended_reason   text,

  created_by       uuid        references auth.users(id) on delete set null,
  updated_by       uuid        references auth.users(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table clinical_notes is
  'Physician notes: SOAP, progress, operative, discharge. AI-drafted notes require physician signature before status becomes ''signed''.';
comment on column clinical_notes.ai_assisted is
  'True when content was initially generated by AI — physician must review and sign before any clinical use.';
comment on column clinical_notes.signed_by is
  'UUID of the physician who signed the note. Null until explicitly signed.';

-- ─────────────────────────────────────────────────────────────
-- DOCUMENTS
-- Uploaded PDFs, scanned forms, generated summaries, received
-- referral letters and lab reports.
-- Actual files are stored in Supabase Storage; this table holds
-- metadata and the storage object path.
-- ─────────────────────────────────────────────────────────────
create table if not exists documents (
  id               uuid        primary key default uuid_generate_v4(),
  patient_id       uuid        not null references patients(id) on delete cascade,
  encounter_id     uuid        references encounters(id) on delete set null,

  document_type    text        not null default 'other'
                               check (document_type in (
                                 'lab_report', 'imaging_report', 'referral_letter',
                                 'consent_form', 'surgical_report', 'discharge_summary',
                                 'prescription', 'insurance_form', 'other'
                               )),
  title            text        not null,
  file_name        text,
  -- Path within the Supabase Storage bucket (e.g. patients/{patient_id}/{uuid}.pdf)
  storage_path     text,
  mime_type        text,
  file_size_bytes  bigint,

  source           text        not null default 'uploaded'
                               check (source in (
                                 'uploaded', 'generated', 'received_fax',
                                 'received_email', 'scanned'
                               )),
  is_confidential  boolean     not null default false,
  notes            text,

  created_by       uuid        references auth.users(id) on delete set null,
  updated_by       uuid        references auth.users(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

comment on table documents is
  'Patient documents: uploaded PDFs, generated summaries, scanned forms, received reports. Files are stored in Supabase Storage.';
comment on column documents.storage_path is
  'Object path within the Supabase Storage ''patient-documents'' bucket.';

-- ─────────────────────────────────────────────────────────────
-- BILLING CHARGES
-- Line-item charges per encounter, in XCD.
-- Waived charges are retained for audit. Totals are computed
-- at query time (quantity × unit_price − discount).
-- ─────────────────────────────────────────────────────────────
create table if not exists billing_charges (
  id                  uuid          primary key default uuid_generate_v4(),
  patient_id          uuid          not null references patients(id)   on delete cascade,
  encounter_id        uuid          not null references encounters(id)  on delete cascade,

  charge_code         text,
  charge_description  text          not null,
  quantity            integer       not null default 1  check (quantity > 0),
  unit_price_xcd      numeric(10,2) not null             check (unit_price_xcd >= 0),
  discount_xcd        numeric(10,2) not null default 0   check (discount_xcd >= 0),

  category            text          not null default 'consultation'
                                    check (category in (
                                      'consultation', 'procedure', 'investigation',
                                      'medication', 'facility', 'anaesthesia', 'other'
                                    )),
  status              text          not null default 'pending'
                                    check (status in (
                                      'pending', 'invoiced', 'paid', 'waived', 'disputed'
                                    )),
  invoice_number      text,
  invoiced_at         timestamptz,
  paid_at             timestamptz,
  payment_method      text          check (payment_method in (
                                      'cash', 'card', 'insurance', 'transfer', 'waived'
                                    )),
  notes               text,

  created_by          uuid          references auth.users(id) on delete set null,
  updated_by          uuid          references auth.users(id) on delete set null,
  created_at          timestamptz   not null default now(),
  updated_at          timestamptz   not null default now()
);

comment on table billing_charges is
  'Line-item billing charges per encounter, in XCD. Query total as: quantity * unit_price_xcd - discount_xcd.';
comment on column billing_charges.charge_code is
  'CPT code or internal Amise charge code.';

-- ─────────────────────────────────────────────────────────────
-- IMAGING ORDERS
-- X-ray, CT, MRI, ultrasound, endoscopy (colonoscopy, ERCP,
-- OGD) and other imaging / interventional radiology orders.
-- ─────────────────────────────────────────────────────────────
create table if not exists imaging_orders (
  id                    uuid        primary key default uuid_generate_v4(),
  patient_id            uuid        not null references patients(id) on delete cascade,
  encounter_id          uuid        references encounters(id) on delete set null,

  order_type            text        not null
                                    check (order_type in (
                                      'xray', 'ultrasound', 'ct', 'mri', 'pet',
                                      'ercp', 'colonoscopy', 'egd', 'flexible_sig',
                                      'mammogram', 'dexa', 'angiogram', 'other'
                                    )),
  body_area             text,
  laterality            text        check (laterality in (
                                      'left', 'right', 'bilateral', 'not_applicable'
                                    )),
  clinical_indication   text        not null,
  urgency               text        not null default 'routine'
                                    check (urgency in ('routine', 'soon', 'urgent', 'emergency')),
  contrast_required     boolean     not null default false,
  patient_preparation   text,

  status                text        not null default 'ordered'
                                    check (status in (
                                      'ordered', 'scheduled', 'performed',
                                      'reported', 'reviewed', 'cancelled'
                                    )),
  ordered_at            timestamptz not null default now(),
  scheduled_at          timestamptz,
  performed_at          timestamptz,

  performing_facility   text,
  performing_technician text,
  radiologist           text,
  report_received_at    timestamptz,
  report_text           text,

  -- Link to the PDF report in documents table once received
  linked_document_id    uuid        references documents(id) on delete set null,
  reviewed_by           uuid        references auth.users(id) on delete set null,
  reviewed_at           timestamptz,
  notes                 text,

  created_by            uuid        references auth.users(id) on delete set null,
  updated_by            uuid        references auth.users(id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

comment on table imaging_orders is
  'Imaging and endoscopy orders — X-ray, CT, MRI, ultrasound, colonoscopy, ERCP, OGD.';
comment on column imaging_orders.linked_document_id is
  'FK to documents.id — set when the report PDF is received and uploaded.';
comment on column imaging_orders.urgency is
  '''emergency'' orders require same-session action; ''urgent'' within 24 h; ''soon'' within 1 week.';

-- ─────────────────────────────────────────────────────────────
-- INVESTIGATION RESULTS
-- Laboratory, pathology, microbiology and serology results.
-- Single-result tests use result_value / result_unit / reference_range.
-- Multi-analyte panels (FBC, LFTs, U&E) store individual
-- analytes in the JSONB column.
-- ─────────────────────────────────────────────────────────────
create table if not exists investigation_results (
  id                  uuid        primary key default uuid_generate_v4(),
  patient_id          uuid        not null references patients(id) on delete cascade,
  encounter_id        uuid        references encounters(id) on delete set null,

  test_name           text        not null,
  test_category       text        not null default 'other'
                                  check (test_category in (
                                    'haematology', 'biochemistry', 'microbiology',
                                    'pathology', 'serology', 'hormonal', 'cardiac',
                                    'urine', 'stool', 'other'
                                  )),
  specimen_type       text,
  collected_at        timestamptz,
  received_at         timestamptz,
  reported_at         timestamptz,
  performing_lab      text,

  -- Single-result convenience columns
  result_value        text,
  result_unit         text,
  reference_range     text,

  -- Multi-analyte panel:
  -- [{"name":"Hb","value":"12.5","unit":"g/dL","ref":"13–17","abnormal":true}, ...]
  analytes            jsonb,

  is_abnormal         boolean     not null default false,
  -- Critical = requires immediate physician notification
  is_critical         boolean     not null default false,

  status              text        not null default 'ordered'
                                  check (status in (
                                    'ordered', 'collected', 'pending',
                                    'resulted', 'reviewed', 'amended'
                                  )),
  reviewed_by         uuid        references auth.users(id) on delete set null,
  reviewed_at         timestamptz,
  linked_document_id  uuid        references documents(id) on delete set null,
  notes               text,

  created_by          uuid        references auth.users(id) on delete set null,
  updated_by          uuid        references auth.users(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table investigation_results is
  'Lab, pathology, microbiology and serology results. Multi-analyte panels stored in the analytes JSONB column.';
comment on column investigation_results.analytes is
  'JSONB array of per-analyte results for multi-test panels. Single-test results use result_value/result_unit/reference_range.';
comment on column investigation_results.is_critical is
  'True when the result requires immediate physician notification (e.g. K+ < 2.5, Hb < 7.0, positive blood culture).';

-- ─────────────────────────────────────────────────────────────
-- updated_at TRIGGERS
-- ─────────────────────────────────────────────────────────────
do $$ declare t text; begin
  foreach t in array array[
    'clinical_notes', 'documents', 'billing_charges',
    'imaging_orders', 'investigation_results'
  ] loop
    execute format(
      'drop trigger if exists trg_updated_at on %I;
       create trigger trg_updated_at before update on %I
         for each row execute function set_updated_at();', t, t);
  end loop;
end $$;

-- ─────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────
do $$ declare t text; begin
  foreach t in array array[
    'clinical_notes', 'documents', 'billing_charges',
    'imaging_orders', 'investigation_results'
  ] loop
    execute format('alter table %I enable row level security;', t);
  end loop;
end $$;

-- ── clinical_notes ──
-- Drafts visible only to author + admins; signed notes visible to nurses too.
-- Only doctors/admins can write notes.
create policy "staff_select_clinical_notes" on clinical_notes
  for select using (
    auth_role() in ('doctor', 'admin')
    or (auth_role() = 'nurse' and status = 'signed')
  );
create policy "doctors_insert_clinical_notes" on clinical_notes
  for insert with check (auth_role() in ('doctor', 'admin'));
create policy "doctors_update_clinical_notes" on clinical_notes
  for update using (
    created_by = auth.uid()
    or auth_role() = 'admin'
  );
create policy "admins_delete_clinical_notes" on clinical_notes
  for delete using (auth_role() = 'admin');

-- ── documents ──
create policy "staff_select_documents" on documents
  for select using (auth.uid() is not null);
create policy "staff_insert_documents" on documents
  for insert with check (auth.uid() is not null);
create policy "staff_update_documents" on documents
  for update using (
    created_by = auth.uid()
    or auth_role() in ('doctor', 'admin')
  );
create policy "admins_delete_documents" on documents
  for delete using (auth_role() = 'admin');

-- ── billing_charges ──
create policy "staff_select_billing" on billing_charges
  for select using (auth.uid() is not null);
create policy "staff_insert_billing" on billing_charges
  for insert with check (auth.uid() is not null);
create policy "staff_update_billing" on billing_charges
  for update using (auth.uid() is not null);
create policy "admins_delete_billing" on billing_charges
  for delete using (auth_role() = 'admin');

-- ── imaging_orders ──
create policy "staff_select_imaging" on imaging_orders
  for select using (auth.uid() is not null);
create policy "clinical_insert_imaging" on imaging_orders
  for insert with check (auth_role() in ('doctor', 'admin', 'nurse'));
create policy "clinical_update_imaging" on imaging_orders
  for update using (auth_role() in ('doctor', 'admin', 'nurse'));
create policy "admins_delete_imaging" on imaging_orders
  for delete using (auth_role() = 'admin');

-- ── investigation_results ──
create policy "staff_select_investigations" on investigation_results
  for select using (auth.uid() is not null);
create policy "staff_insert_investigations" on investigation_results
  for insert with check (auth.uid() is not null);
create policy "clinical_update_investigations" on investigation_results
  for update using (auth_role() in ('doctor', 'admin', 'nurse'));
create policy "admins_delete_investigations" on investigation_results
  for delete using (auth_role() = 'admin');

-- ─────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────

-- clinical_notes
create index if not exists idx_clinical_notes_patient   on clinical_notes(patient_id);
create index if not exists idx_clinical_notes_encounter on clinical_notes(encounter_id);
create index if not exists idx_clinical_notes_status    on clinical_notes(status);
create index if not exists idx_clinical_notes_type      on clinical_notes(note_type);
create index if not exists idx_clinical_notes_signed    on clinical_notes(signed_at desc nulls last);

-- documents
create index if not exists idx_documents_patient    on documents(patient_id);
create index if not exists idx_documents_encounter  on documents(encounter_id);
create index if not exists idx_documents_type       on documents(document_type);
create index if not exists idx_documents_created    on documents(created_at desc);

-- billing_charges
create index if not exists idx_billing_patient   on billing_charges(patient_id);
create index if not exists idx_billing_encounter on billing_charges(encounter_id);
create index if not exists idx_billing_status    on billing_charges(status);
create index if not exists idx_billing_created   on billing_charges(created_at desc);

-- imaging_orders
create index if not exists idx_imaging_patient   on imaging_orders(patient_id);
create index if not exists idx_imaging_encounter on imaging_orders(encounter_id);
create index if not exists idx_imaging_status    on imaging_orders(status);
create index if not exists idx_imaging_urgency   on imaging_orders(urgency);
create index if not exists idx_imaging_ordered   on imaging_orders(ordered_at desc);

-- investigation_results
create index if not exists idx_invest_patient   on investigation_results(patient_id);
create index if not exists idx_invest_encounter on investigation_results(encounter_id);
create index if not exists idx_invest_status    on investigation_results(status);
create index if not exists idx_invest_critical  on investigation_results(is_critical)
  where is_critical = true;
create index if not exists idx_invest_reported  on investigation_results(reported_at desc nulls last);
create index if not exists idx_invest_category  on investigation_results(test_category);

-- ─────────────────────────────────────────────────────────────
-- GRANTS
-- ─────────────────────────────────────────────────────────────
grant select, insert, update on public.clinical_notes        to authenticated;
grant select, insert, update on public.documents             to authenticated;
grant select, insert, update on public.billing_charges       to authenticated;
grant select, insert, update on public.imaging_orders        to authenticated;
grant select, insert, update on public.investigation_results to authenticated;

-- service_role (artifacts/api-server's sb() client) needs full table
-- privileges — see supabase-service-role-grants-fix-migration.sql.
grant select, insert, update, delete on public.clinical_notes        to service_role;
grant select, insert, update, delete on public.documents             to service_role;
grant select, insert, update, delete on public.billing_charges       to service_role;
grant select, insert, update, delete on public.imaging_orders        to service_role;
grant select, insert, update, delete on public.investigation_results to service_role;

-- ─────────────────────────────────────────────────────────────
-- SUPABASE STORAGE BUCKET (run separately or via Supabase CLI)
-- ─────────────────────────────────────────────────────────────
-- The documents table uses a 'patient-documents' storage bucket.
-- Create it via: Supabase Dashboard → Storage → New Bucket
--   Name: patient-documents
--   Public: false  (authenticated access only)
--   File size limit: 50 MB
--   Allowed MIME types: application/pdf, image/*
--
-- Then add these storage policies in the Supabase Dashboard:
--   Allow authenticated users to upload:
--     (bucket_id = 'patient-documents' and auth.uid() is not null)
--   Allow authenticated users to read:
--     (bucket_id = 'patient-documents' and auth.uid() is not null)
--   Allow owner or admin to delete:
--     (bucket_id = 'patient-documents' and auth.uid() is not null)
