/**
 * Generators for the history frames (CLI: gen-history-frames.ts):
 *   - ios/AmiseMedFlow/Services/HistoryFrameData.swift from the TypeScript frames
 *     (lib/triage-engine/src/history-frames), so both platforms show the same chips with the same
 *     stored values;
 *   - lib/triage-engine/src/history-frames/record-only.ts from the engine-mapping audit.
 * lint:history-frames fails when either is stale.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  CLASSIFIER_RULES, HISTORY_FRAMES, HISTORY_FRAMES_VERSION, PAIN_SYSTEM_DEFAULTS, VARIANT_RULES,
  dimensionKey, optionKey, optionValue,
} from '../../lib/triage-engine/src/history-frames/index';
import { ROOT } from './history-frames-corpus';

export const SWIFT_DATA_PATH = join(ROOT, 'ios/AmiseMedFlow/Services/HistoryFrameData.swift');

function q(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
function list(items: string[]): string {
  return `[${items.map(q).join(', ')}]`;
}
function ident(id: string): string {
  return 'frame_' + id.replace(/[^A-Za-z0-9]/g, '_');
}

export function generateSwift(): string {
  const out: string[] = [];
  out.push('// HistoryFrameData.swift');
  out.push('// GENERATED by scripts/src/gen-history-frames.ts from lib/triage-engine/src/history-frames.');
  out.push('// Do not edit: change the TypeScript and run pnpm --filter @workspace/scripts run gen:history-frames.');
  out.push('// lint:history-frames fails when this file is out of date.');
  out.push('');
  out.push('import Foundation');
  out.push('');
  out.push('// swiftlint:disable line_length file_length type_body_length');
  out.push('extension HistoryFrameData {');
  out.push(`    static let version = ${q(HISTORY_FRAMES_VERSION)}`);
  out.push('');
  for (const f of HISTORY_FRAMES) {
    out.push(`    static let ${ident(f.id)} = HistoryFrameSpec(`);
    out.push(`        id: ${q(f.id)}, type: ${q(f.type)}, variant: ${f.variant ? q(f.variant) : 'nil'},`);
    out.push(`        label: ${q(f.label)}, title: ${q(f.title)},`);
    out.push('        dimensions: [');
    for (const d of f.dimensions) {
      out.push(`            HistoryDimensionSpec(id: ${q(d.id)}, title: ${q(d.title)}, question: ${q(d.question)}, icon: ${q(d.icon)}, multiSelect: ${d.multiSelect}, key: ${q(dimensionKey(d))}, options: [`);
      for (const o of d.options) {
        out.push(`                HistoryOptionSpec(label: ${q(o.label)}, value: ${q(optionValue(o))}, key: ${q(optionKey(d, o))}, recordOnlyIOS: ${!!o.recordOnly?.includes('ios')}, excludes: ${list(o.excludes ?? [])}),`);
      }
      out.push('            ]),');
    }
    out.push('        ],');
    out.push(`        secondaryDims: ${list(f.secondaryDims)},`);
    out.push('        aliases: [');
    for (const a of f.aliases ?? []) {
      out.push(`            HistoryAliasSpec(key: ${q(a.key)}, legacy: ${q(a.legacy)}, current: ${q(a.current)}),`);
    }
    out.push('        ]');
    out.push('    )');
    out.push('');
  }
  out.push('    static let frames: [HistoryFrameSpec] = [');
  for (const f of HISTORY_FRAMES) out.push(`        ${ident(f.id)},`);
  out.push('    ]');
  out.push('');
  out.push('    static let classifierRules: [HistoryClassifierRuleSpec] = [');
  for (const r of CLASSIFIER_RULES) {
    out.push(`        HistoryClassifierRuleSpec(type: ${q(r.type)}, tier: ${r.tier}, keywords: ${list(r.keywords)}, unless: ${list(r.unless ?? [])}),`);
  }
  out.push('    ]');
  out.push('');
  out.push('    static let variantSets: [HistoryVariantSetSpec] = [');
  for (const [type, spec] of Object.entries(VARIANT_RULES)) {
    if (!spec) continue;
    out.push(`        HistoryVariantSetSpec(type: ${q(type)}, fallback: ${q(spec.fallback)}, rules: [`);
    for (const r of spec.rules) out.push(`            HistoryVariantRuleSpec(variant: ${q(r.variant)}, keywords: ${list(r.keywords)}),`);
    out.push('        ]),');
  }
  out.push('    ]');
  out.push('');
  out.push('    static let painSystemDefaults: [String: String] = [');
  for (const [k, v] of Object.entries(PAIN_SYSTEM_DEFAULTS)) out.push(`        ${q(k)}: ${q(v)},`);
  out.push('    ]');
  out.push('}');
  out.push('// swiftlint:enable line_length file_length type_body_length');
  out.push('');
  return out.join('\n');
}

export const RECORD_ONLY_PATH = join(ROOT, 'lib/triage-engine/src/history-frames/record-only.ts');

/** record-only.ts from the engine-mapping audit (a chip no engine feature reads, per platform). */
export async function generateRecordOnly(): Promise<string> {
  const { auditChips } = await import('./history-frames-audit');
  const table = new Map<string, { ios: string[]; web: string[] }>();
  for (const c of auditChips()) {
    const k = `${c.frame}/${c.dim}`;
    if (!table.has(k)) table.set(k, { ios: [], web: [] });
    if (!c.ios.length) table.get(k)!.ios.push(c.label);
    if (!c.web.length) table.get(k)!.web.push(c.label);
  }
  const lines = [
    '/**',
    ' * Record-only chips: recorded in the history (and the HPI text) but feeding no diagnosis-engine',
    ' * feature on that platform. Keyed "frameId/dimensionId".',
    ' *',
    ' * GENERATED by pnpm --filter @workspace/scripts run gen:history-frames -- --record-only from the',
    ' * engine-mapping audit (history-frames-audit.ts). lint:history-frames fails when this table and',
    ' * the engines disagree. Review the diff: a chip leaving this table now feeds the engine.',
    ' */',
    '',
    "import type { Platform } from './types';",
    '',
    'export const RECORD_ONLY: Record<string, Partial<Record<Platform, string[]>>> = {',
  ];
  const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  for (const [k, v] of table) {
    if (!v.ios.length && !v.web.length) continue;
    const parts: string[] = [];
    if (v.ios.length) parts.push(`ios: [${v.ios.map(q).join(', ')}]`);
    if (v.web.length) parts.push(`web: [${v.web.map(q).join(', ')}]`);
    lines.push(`  ${q(k)}: { ${parts.join(', ')} },`);
  }
  lines.push('};', '');
  return lines.join('\n');
}
