import XCTest
import SwiftData
@testable import AmiseMedFlow

// Treatment decision layer (BayesianDecisionEngine+Treatment.swift).
// DRIFT NOTE: the vectors are shared with the web (lib/pane-engine/src/__tests__/decision.test.ts)
// and generated by scripts/src/gen-decision-vectors.ts from the web engine; both platforms must give
// the same bands, thresholds, rankings and wording for the same inputs.

private final class DecisionVectorsBundleToken {}

@MainActor
final class TreatmentDecisionTests: XCTestCase {

    private struct VectorFile: Decodable {
        let contentVersion: String
        let vectors: [Vector]
    }

    private struct Vector: Decodable {
        let id: String
        let input: TreatmentDecisions.Input
        let expected: ClinValJSON
    }

    private var container: ModelContainer!
    private var context: ModelContext!

    override func setUp() async throws {
        let schema = Schema([Patient.self, ClinicalNote.self, VitalsEntry.self, Prescription.self,
                             PatientDocument.self, OperativePlan.self, BillingLineItem.self,
                             Encounter.self, ScoreHistoryEntry.self])
        container = try ModelContainer(for: schema, configurations: ModelConfiguration(isStoredInMemoryOnly: true))
        context = container.mainContext
    }

    // MARK: - Loading

    private func vectorsURL() -> URL? {
        let bundle = Bundle(for: DecisionVectorsBundleToken.self)
        if let url = bundle.url(forResource: "decision-vectors", withExtension: "json") { return url }
        let source = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appendingPathComponent("DecisionSupport").appendingPathComponent("decision-vectors.json")
        return FileManager.default.fileExists(atPath: source.path) ? source : nil
    }

    private func loadVectors() throws -> VectorFile {
        let url = try XCTUnwrap(vectorsURL(), "decision-vectors.json not found in the test bundle or next to this file")
        return try JSONDecoder().decode(VectorFile.self, from: Data(contentsOf: url))
    }

    func testContentDecodesFromTheAppBundle() throws {
        let content = try XCTUnwrap(TreatmentDecisions.content, "Resources/TreatmentDecisions.json missing or not decoding")
        XCTAssertEqual(content.status, "needs-sign-off")
        XCTAssertFalse(content.decisions.isEmpty)
        XCTAssertEqual(try loadVectors().contentVersion, content.version)
    }

    // MARK: - Shared vectors

    private func obj(_ j: ClinValJSON?) -> [String: ClinValJSON] {
        if case .object(let o)? = j { return o }
        return [:]
    }

    private func arr(_ j: ClinValJSON?) -> [ClinValJSON] {
        if case .array(let a)? = j { return a }
        return []
    }

    private func str(_ j: ClinValJSON?) -> String? {
        if case .string(let s)? = j { return s }
        return nil
    }

    private func num(_ j: ClinValJSON?) -> Double? {
        if case .number(let n)? = j { return n }
        return nil
    }

    private func strings(_ j: ClinValJSON?) -> [String] {
        arr(j).compactMap { str($0) }
    }

    private func assertTriple(_ actual: TreatmentDecisions.Triple?, _ expected: ClinValJSON?, _ what: String) {
        let e = arr(expected).compactMap { num($0) }
        guard let a = actual else {
            XCTAssertTrue(e.isEmpty, "\(what): expected \(e), got nil")
            return
        }
        XCTAssertEqual(e.count, 3, "\(what): expected a range")
        if e.count == 3 {
            XCTAssertEqual(a.low, e[0], accuracy: 0.0011, "\(what) low")
            XCTAssertEqual(a.point, e[1], accuracy: 0.0011, "\(what) point")
            XCTAssertEqual(a.high, e[2], accuracy: 0.0011, "\(what) high")
        }
    }

    func testSharedVectorsMatchTheWebEngine() throws {
        let file = try loadVectors()
        let content = try XCTUnwrap(TreatmentDecisions.content)
        XCTAssertGreaterThanOrEqual(file.vectors.count, 20)
        for v in file.vectors {
            let r = TreatmentDecisions.decisionSupport(v.input, content, TreatmentDecisions.identityFilter)
            let e = obj(v.expected)
            let id = v.id
            XCTAssertEqual(r.activeFactors, strings(e["activeFactors"]), "\(id): active factors")

            let es = arr(e["scoreActions"])
            XCTAssertEqual(r.scoreActions.count, es.count, "\(id): score actions")
            for (c, x) in zip(r.scoreActions, es) {
                let o = obj(x)
                XCTAssertEqual(c.id, str(o["id"]), "\(id): score action id")
                XCTAssertEqual(c.chip, str(o["chip"]), "\(id): score chip")
                XCTAssertEqual(c.band, str(o["band"]), "\(id): score band")
                XCTAssertEqual(c.level, str(o["level"]), "\(id): score level")
                XCTAssertEqual(c.addAs, str(o["addAs"]), "\(id): score addAs")
            }

            let er = arr(e["resultActions"])
            XCTAssertEqual(r.resultActions.count, er.count, "\(id): result actions")
            for (c, x) in zip(r.resultActions, er) {
                let o = obj(x)
                XCTAssertEqual(c.id, str(o["id"]), "\(id): result id")
                XCTAssertEqual(c.chip, str(o["chip"]), "\(id): result chip")
                XCTAssertEqual(c.thresholdText, str(o["thresholdText"]), "\(id): result threshold text")
            }

            let ed = arr(e["decisions"])
            XCTAssertEqual(r.decisions.count, ed.count, "\(id): decisions")
            for (d, x) in zip(r.decisions, ed) {
                let o = obj(x)
                XCTAssertEqual(d.id, str(o["id"]), "\(id): decision id")
                if let p = num(o["probability"]) {
                    XCTAssertEqual(d.probability ?? -1, p, accuracy: 0.0011, "\(id): \(d.id) probability")
                } else {
                    XCTAssertNil(d.probability, "\(id): \(d.id) probability")
                }
                XCTAssertEqual(d.probabilitySource, str(o["probabilitySource"]), "\(id): \(d.id) probability source")
                XCTAssertEqual(d.chip, str(o["chip"]), "\(id): \(d.id) chip")
                XCTAssertEqual(d.missing, strings(o["missing"]), "\(id): \(d.id) missing inputs")
                let eo = arr(o["options"])
                XCTAssertEqual(d.options.count, eo.count, "\(id): \(d.id) options")
                for (op, y) in zip(d.options, eo) {
                    let q = obj(y)
                    let what = "\(id): \(d.id)/\(op.id)"
                    XCTAssertEqual(op.id, str(q["id"]), "\(what) id")
                    XCTAssertEqual(op.band.rawValue, str(q["band"]), "\(what) band")
                    XCTAssertEqual(op.bandRange.map { $0.rawValue }, strings(q["bandRange"]), "\(what) band range")
                    if let rank = num(q["rank"]) {
                        XCTAssertEqual(op.rank, Int(rank), "\(what) rank")
                    } else {
                        XCTAssertNil(op.rank, "\(what) rank")
                    }
                    assertTriple(op.treatThreshold, q["treatThreshold"], "\(what) treat threshold")
                    if case .null? = q["testThreshold"] {
                        XCTAssertNil(op.testThreshold, "\(what) test threshold")
                    } else {
                        assertTriple(op.testThreshold, q["testThreshold"], "\(what) test threshold")
                    }
                    assertTriple(op.benefit, q["benefit"], "\(what) benefit")
                    assertTriple(op.harm, q["harm"], "\(what) harm")
                    assertTriple(op.net, q["net"], "\(what) net")
                    XCTAssertEqual(op.topFactors.map { $0.modifierId }, strings(q["topFactors"]), "\(what) top factors")
                    XCTAssertEqual(op.factorSummary, str(q["factorSummary"]), "\(what) factor summary")
                    if case .bool(let excluded)? = q["excluded"] {
                        XCTAssertEqual(op.excludedReason != nil, excluded, "\(what) excluded")
                    }
                }
            }
        }
    }

    // MARK: - Threshold arithmetic

    func testThresholds() {
        XCTAssertEqual(TreatmentDecisions.thresholds(0.3, 0.1, nil).treat, 0.25, accuracy: 1e-12)
        XCTAssertNil(TreatmentDecisions.thresholds(0.3, 0.1, nil).test)
        XCTAssertEqual(TreatmentDecisions.thresholds(0, 0.1, nil).treat, 1)
        XCTAssertEqual(TreatmentDecisions.thresholds(0.3, 0, nil).treat, 0)
        let perfect = TreatmentDecisions.Test(label: "t", sensitivity: 1, specificity: 1, harm: 0, sources: [])
        let t = TreatmentDecisions.thresholds(0.3, 0.1, perfect)
        XCTAssertEqual(t.test, 0)
        XCTAssertEqual(t.treat, 1)
        let good = TreatmentDecisions.Test(label: "t", sensitivity: 0.9, specificity: 0.9, harm: 0.001, sources: [])
        let g = TreatmentDecisions.thresholds(0.3, 0.05, good)
        XCTAssertEqual(TreatmentDecisions.bandFor(0.01, g), .observe)
        XCTAssertEqual(TreatmentDecisions.bandFor(0.2, g), .test)
        XCTAssertEqual(TreatmentDecisions.bandFor(0.9, g), .treat)
        XCTAssertEqual(TreatmentDecisions.bandFor(nil, g), .unknown)
    }

    func testFormattingMatchesTheWeb() {
        XCTAssertEqual(TreatmentDecisions.formatPercent(0.953), "95%")
        XCTAssertEqual(TreatmentDecisions.formatPercent(0.0374), "3.7%")
        XCTAssertEqual(TreatmentDecisions.formatPercent(0.04), "4%")
        XCTAssertEqual(TreatmentDecisions.formatPercent(0.004), "0.4%")
        XCTAssertEqual(TreatmentDecisions.formatValue(3), "3")
        XCTAssertEqual(TreatmentDecisions.formatValue(4.5), "4.5")
        XCTAssertTrue(TreatmentDecisions.keywordAt("Perforated duodenal ulcer", "perforat"))
        XCTAssertFalse(TreatmentDecisions.keywordAt("imperforate anus", "perforat"))
        XCTAssertFalse(TreatmentDecisions.keywordAt("uncomplicated diverticulitis", "complicated"))
        XCTAssertEqual(TreatmentDecisions.lowerFirst("Early laparoscopic cholecystectomy"), "early laparoscopic cholecystectomy")
        XCTAssertEqual(TreatmentDecisions.lowerFirst("IV antibiotics within 1 hour"), "IV antibiotics within 1 hour")
    }

    // MARK: - Record → input, and the PlanSafetyFilter as the final hard filter

    private func patient(age: Int, sex: Sex = .female) -> Patient {
        let p = Patient(fullName: "Decision Test", setting: .outpatient)
        p.sex = sex
        let cal = Calendar.current
        if let years = cal.date(byAdding: .year, value: -age, to: .now) {
            p.dateOfBirth = cal.date(byAdding: .day, value: -30, to: years)
        }
        context.insert(p)
        return p
    }

    func testPenicillinAllergyWithholdsTheCurb65AntibioticLine() throws {
        let p = patient(age: 60)
        p.allergies = [AllergyEntry(name: "Penicillin", severity: "Severe", reaction: "anaphylaxis")]
        p.curb65Score = 3
        let r = try XCTUnwrap(DecisionSupportPatient.support(for: p, bayes: []))
        let card = try XCTUnwrap(r.scoreActions.first(where: { $0.score == "curb65" }))
        XCTAssertTrue(card.withheld)
        XCTAssertTrue(card.action.contains("ALLERGY"), card.action)
    }

    func testFrailPatientWithCholecystitisGetsDrainageFirst() throws {
        let p = patient(age: 88)
        p.workingDiagnosis = "Acute cholecystitis"
        p.workingDiagnosisICD = "K81.0"
        p.cfsScore = 7
        p.asaClass = 4
        let r = try XCTUnwrap(DecisionSupportPatient.support(for: p, bayes: []))
        let d = try XCTUnwrap(r.decisions.first(where: { $0.id == "cholecystitis" }))
        XCTAssertEqual(d.options.first?.id, "percutaneous-cholecystostomy")
        let lc = try XCTUnwrap(d.options.first(where: { $0.id == "early-lap-chole" }))
        XCTAssertEqual(lc.band, .observe)
        XCTAssertTrue((lc.factorSummary ?? "").contains("Frailty CFS 7"), lc.factorSummary ?? "")
    }

    func testRecentSurgeryExcludesThrombolysis() throws {
        let p = patient(age: 64, sex: .male)
        p.workingDiagnosis = "Pulmonary embolism"
        p.workingDiagnosisICD = "I26.0"
        p.operationDate = Calendar.current.date(byAdding: .day, value: -5, to: .now)
        let r = try XCTUnwrap(DecisionSupportPatient.support(for: p, bayes: []))
        let d = try XCTUnwrap(r.decisions.first(where: { $0.id == "pulmonary-embolism" }))
        let lysis = try XCTUnwrap(d.options.first(where: { $0.id == "thrombolysis" }))
        XCTAssertEqual(lysis.band, .notForPatient)
        XCTAssertNil(lysis.rank)
    }

    func testNegatedImmunosuppressionIsNotAFactor() {
        let p = patient(age: 52, sex: .male)
        p.hpi = "Otherwise fit, no immunosuppression. Non-smoker."
        XCTAssertFalse(DecisionSupportPatient.decisionPatient(p).immunosuppressed)
    }

    func testSummaryLinesSplitSuggestedFromNotForPatient() throws {
        let file = try loadVectors()
        let content = try XCTUnwrap(TreatmentDecisions.content)
        let v = try XCTUnwrap(file.vectors.first(where: { $0.id == "pe-shock-recent-surgery" }))
        let lines = TreatmentDecisions.summaryLines(TreatmentDecisions.decisionSupport(v.input, content, TreatmentDecisions.identityFilter))
        XCTAssertTrue(lines.contains { $0.kind == "safety" && $0.text.contains("not for this patient: Systemic thrombolysis") })
        XCTAssertFalse(lines.contains { $0.kind == "management" && $0.text.contains("Systemic thrombolysis — TREAT") })
    }
}
