import XCTest
@testable import AmiseMedFlow

// "What's missing" core (WhatsMissingCore*.swift).
// DRIFT NOTE: the vectors are shared with the web (lib/pane-engine/src/__tests__/whats-missing.test.ts)
// and generated by scripts/src/gen-whats-missing-vectors.ts from the web core; both platforms must
// give the same auto-fill, the same probed decision gaps and the same ranked list, word for word.

private final class WhatsMissingVectorsBundleToken {}

final class WhatsMissingTests: XCTestCase {

    private struct ActionJSON: Decodable, Equatable {
        let kind: String
        let field: String?
        let test: String?
    }

    private struct ItemJSON: Decodable {
        let id: String
        let tier: String
        let what: String
        let why: String
        let also: [String]
        let action: ActionJSON
        let alt: ActionJSON?
        let sources: [String]
    }

    private struct ResultJSON: Decodable {
        let version: String
        let topN: Int
        let items: [ItemJSON]
    }

    private struct FillVector: Decodable {
        let id: String
        let score: String
        let record: WhatsMissing.Record
        let expected: WhatsMissing.ScoreFill
    }

    private struct ProbeVector: Decodable {
        let id: String
        let input: TreatmentDecisions.Input
        let expected: [WhatsMissing.DecisionGap]
    }

    private struct RankVector: Decodable {
        let id: String
        let input: WhatsMissing.Input
        let expected: ResultJSON
    }

    private struct TermVector: Decodable {
        let text: String
        let term: String
        let expected: Bool
    }

    private struct PartsVector: Decodable {
        let parts: [String]
        let expected: String
    }

    private struct VectorFile: Decodable {
        let version: String
        let fill: [FillVector]
        let probe: [ProbeVector]
        let rank: [RankVector]
        let terms: [TermVector]
        let parts: [PartsVector]
    }

    private func vectorsURL() -> URL? {
        let bundle = Bundle(for: WhatsMissingVectorsBundleToken.self)
        if let url = bundle.url(forResource: "whats-missing-vectors", withExtension: "json") { return url }
        let source = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appendingPathComponent("WhatsMissing").appendingPathComponent("whats-missing-vectors.json")
        return FileManager.default.fileExists(atPath: source.path) ? source : nil
    }

    private func loadVectors() throws -> VectorFile {
        let url = try XCTUnwrap(vectorsURL(), "whats-missing-vectors.json not found in the test bundle or next to this file")
        return try JSONDecoder().decode(VectorFile.self, from: Data(contentsOf: url))
    }

    private func rules() throws -> WhatsMissing.Rules {
        try XCTUnwrap(WhatsMissing.rules, "rules/whats-missing-rules.json missing or not decoding")
    }

    func testRulesDecodeAndMatchTheVectorsVersion() throws {
        let r = try rules()
        XCTAssertEqual(r.status, "needs-sign-off")
        XCTAssertEqual(try loadVectors().version, r.version)
        XCTAssertEqual(r.topN, 5)
    }

    func testFillVectors() throws {
        let r = try rules()
        for v in try loadVectors().fill {
            XCTAssertEqual(WhatsMissing.scoreRecordFill(v.score, v.record, r), v.expected, v.id)
        }
    }

    @MainActor
    func testProbeVectors() throws {
        let r = try rules()
        let content = try XCTUnwrap(TreatmentDecisions.content)
        for v in try loadVectors().probe {
            XCTAssertEqual(WhatsMissing.decisionGaps(v.input, rules: r, content: content), v.expected, v.id)
        }
    }

    func testRankVectors() throws {
        let r = try rules()
        for v in try loadVectors().rank {
            let got = WhatsMissing.whatsMissing(v.input, rules: r)
            XCTAssertEqual(got.version, v.expected.version, v.id)
            XCTAssertEqual(got.topN, v.expected.topN, v.id)
            XCTAssertEqual(got.items.count, v.expected.items.count, "\(v.id): item count")
            for (g, e) in zip(got.items, v.expected.items) {
                XCTAssertEqual(g.id, e.id, v.id)
                XCTAssertEqual(g.tier, e.tier, "\(v.id)/\(e.id)")
                XCTAssertEqual(g.what, e.what, "\(v.id)/\(e.id)")
                XCTAssertEqual(g.why, e.why, "\(v.id)/\(e.id)")
                XCTAssertEqual(g.also, e.also, "\(v.id)/\(e.id)")
                XCTAssertEqual(ActionJSON(kind: g.action.kind, field: g.action.field, test: g.action.test), e.action, "\(v.id)/\(e.id)")
                XCTAssertEqual(g.alt.map { ActionJSON(kind: $0.kind, field: $0.field, test: $0.test) }, e.alt, "\(v.id)/\(e.id)")
                XCTAssertEqual(g.sources, e.sources, "\(v.id)/\(e.id)")
            }
        }
    }

    func testTermMatcherAndPartJoiner() throws {
        let file = try loadVectors()
        for t in file.terms { XCTAssertEqual(WhatsMissing.termIn(t.text, t.term), t.expected, "\(t.term) in \(t.text)") }
        for p in file.parts { XCTAssertEqual(WhatsMissing.joinParts(p.parts), p.expected) }
    }

    /// The owner's examples, read from the shared vectors.
    func testOwnersExamplesTopItem() throws {
        let r = try rules()
        let rank = try loadVectors().rank
        func top(_ id: String) -> String? {
            guard let v = rank.first(where: { $0.id == id }) else { return nil }
            return WhatsMissing.whatsMissing(v.input, rules: r).items.first?.id
        }
        XCTAssertEqual(top("child-no-weight"), "weight")
        XCTAssertEqual(top("woman-30-ct-planned"), "pregnancy")
        XCTAssertEqual(top("cholecystitis-no-wbc"), "fbc")
        XCTAssertEqual(top("nsaid-no-egfr"), "renal")
    }
}
