import { Router, type IRouter } from "express";
import healthRouter from "./health";
import intakeRouter from "./intake";
import triagePreviewRouter from "./triage-preview";
import cronRouter from "./cron";
import summaryRouter from "./summary";
import schedulingRouter from "./scheduling";
import bookingRouter from "./booking";
import questionnaireRouter from "./questionnaire";
import whatsappRouter from "./whatsapp";
import portalRouter from "./portal";
import investigationsRouter from "./investigations";
import emailIntakeRouter from "./email-intake";
import visitLifecycleRouter from "./visit-lifecycle";
import billingRouter from "./billing";
import preProcedureRouter from "./pre-procedure";
import aiConsultRouter from "./ai-consult";
import narrativeRouter from "./narrative";
import voiceRouter from "./voice";
import callsRouter from "./calls";
import callRecordingRouter from "./call-recording";
import patientMessagesRouter from "./patient-messages";
import generateLetterRouter from "./generate-letter";
import procedureReportRouter from "./procedure-report";
import dischargeSummaryRouter from "./discharge-summary";
import patientAuthRouter from "./patient-auth";
import patientRouter from "./patient";
import documentScanRouter from "./document-scan";
import generateEndoscopyReportRouter from "./generate-endoscopy-report";
import generateOperativeNoteRouter from "./generate-operative-note";
import suggestCodesRouter from "./suggest-codes";
import referralsRouter from "./referrals";
import fhirRouter from "./fhir";
import adminRouter from "./admin";
import analyticsRouter from "./analytics";
import theatreRouter from "./theatre";

const router: IRouter = Router();

router.use(healthRouter);
router.use(intakeRouter);
router.use(triagePreviewRouter);
router.use(cronRouter);
router.use(summaryRouter);
router.use(schedulingRouter);
router.use(bookingRouter);
router.use(questionnaireRouter);
router.use(whatsappRouter);
router.use(portalRouter);
router.use(investigationsRouter);
router.use(emailIntakeRouter);
router.use(visitLifecycleRouter);
router.use(billingRouter);
router.use(preProcedureRouter);
router.use(aiConsultRouter);
router.use(narrativeRouter);
router.use(voiceRouter);
router.use(callsRouter);
router.use(callRecordingRouter);
router.use(patientMessagesRouter);
router.use('/api/generate-letter', generateLetterRouter);
router.use(procedureReportRouter);
router.use(dischargeSummaryRouter);
router.use(patientAuthRouter);
router.use(patientRouter);
router.use('/api/document-scan', documentScanRouter);
router.use('/api/generate-endoscopy-report', generateEndoscopyReportRouter);
router.use('/api/generate-operative-note', generateOperativeNoteRouter);
router.use('/api/suggest-codes', suggestCodesRouter);
router.use(referralsRouter);
router.use(fhirRouter);
router.use(adminRouter);
router.use(analyticsRouter);
router.use(theatreRouter);

export default router;
