#!/bin/bash
# One-time signing setup — run once per Mac, then xcodegen is permanent.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
XCCONFIG="$SCRIPT_DIR/Configuration.xcconfig"
PBXPROJ="$SCRIPT_DIR/AmiseMedFlow.xcodeproj/project.pbxproj"

echo "==> Detecting Apple Development Team ID..."

TEAM_ID=""

# Method 1: from project.pbxproj after user has selected team in Xcode
if [ -f "$PBXPROJ" ]; then
    TEAM_ID=$(grep 'DEVELOPMENT_TEAM = ' "$PBXPROJ" | grep -v '= "";' | grep -oE '[A-Z0-9]{10}' | head -1 || true)
    [ -n "$TEAM_ID" ] && echo "Found from project.pbxproj: $TEAM_ID"
fi

# Method 2: from provisioning profiles on this Mac
if [ -z "$TEAM_ID" ]; then
    PROFILE_DIR=~/Library/MobileDevice/Provisioning\ Profiles
    for profile in "$PROFILE_DIR"/*.mobileprovision 2>/dev/null; do
        [ -f "$profile" ] || continue
        T=$(security cms -D -i "$profile" 2>/dev/null | python3 -c "
import sys, plistlib
try:
    data = plistlib.loads(sys.stdin.buffer.read())
    teams = data.get('TeamIdentifier', [])
    print(teams[0] if teams else '')
except: pass
" 2>/dev/null)
        if [ -n "$T" ]; then
            TEAM_ID="$T"
            echo "Found from provisioning profile: $TEAM_ID"
            break
        fi
    done
fi

# Method 3: from Apple Development certificate OU
if [ -z "$TEAM_ID" ]; then
    TEAM_ID=$(security find-identity -v -p codesigning 2>/dev/null \
        | grep "Apple Development" | head -1 \
        | grep -oE '\([A-Z0-9]+\)' | tr -d '()' || true)
    [ -n "$TEAM_ID" ] && echo "Found from certificate: $TEAM_ID"
fi

if [ -z "$TEAM_ID" ]; then
    echo ""
    echo "ERROR: Could not detect team ID automatically."
    echo "Steps:"
    echo "  1. Open Xcode -> AmiseMedFlow target -> Signing & Capabilities"
    echo "  2. Set Team to 'Dawit Kabiye (Personal Team)'"
    echo "  3. Re-run this script: ./setup.sh"
    exit 1
fi

# Write xcconfig
cat > "$XCCONFIG" << EOF
// Local signing config — NOT committed to git
// Auto-generated by setup.sh — re-run after any new Mac setup
DEVELOPMENT_TEAM = $TEAM_ID
EOF
echo "==> Saved to Configuration.xcconfig (DEVELOPMENT_TEAM = $TEAM_ID)"

# Regenerate xcodeproj
if command -v xcodegen &>/dev/null; then
    echo "==> Running xcodegen..."
    cd "$SCRIPT_DIR" && xcodegen generate

    # Patch DEVELOPMENT_TEAM into the generated pbxproj so Xcode's
    # Signing & Capabilities dropdown shows the team without manual selection.
    # Xcode reads the dropdown from the project-level `attributes` dict AND
    # the per-config buildSettings — both must carry the team ID.
    PBXPROJ="$SCRIPT_DIR/AmiseMedFlow.xcodeproj/project.pbxproj"
    if [ -f "$PBXPROJ" ]; then
        # 1. Patch build settings (quoted empty string form and bare form)
        sed -i '' "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = $TEAM_ID;/g" "$PBXPROJ"
        sed -i '' "s/DEVELOPMENT_TEAM = [A-Z0-9][A-Z0-9]*;/DEVELOPMENT_TEAM = $TEAM_ID;/g" "$PBXPROJ"
        # 2. Patch project-level attributes dict — this is what the Xcode UI dropdown reads
        #    Pattern: DEVELOPMENT_TEAM = ""; inside the attributes = { ... }; block
        sed -i '' '/attributes = {/,/};/{s/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = '"$TEAM_ID"';/g}' "$PBXPROJ"
        echo "==> Patched DEVELOPMENT_TEAM = $TEAM_ID into project.pbxproj (build settings + attributes)"
    fi
    echo "==> Project regenerated with team $TEAM_ID"
else
    echo "WARN: xcodegen not found. Install with: brew install xcodegen"
fi

echo ""
echo "Done. In Xcode: select your iPhone and hit Cmd+R."
