// Patient+Handover.swift
// Clinical handover summary and contextual snapshot generation.

import SwiftUI
import SwiftData


// MARK: - Clinical handover summary

extension Patient {
    var handoverText: String {
        let today = Date.now.formatted(date: .abbreviated, time: .shortened)
        var lines: [String] = []

        lines.append("CLINICAL HANDOVER — \(today)")
        lines.append("Generated by Amise MedFlow EMR · \(PracticeProfile.current.clinicianSignature)")
        lines.append(String(repeating: "─", count: 48))
        lines.append("")

        // Patient identity
        var idLine = "\(fullName) · \(sex.rawValue) · \(ageYears > 0 ? "\(ageYears)y" : "age unknown")"
        if let m = mrn { idLine += " · MRN: \(m)" }
        lines.append(idLine)

        var locationLine = "\(setting.rawValue) — \(location.rawValue)"
        if let w = ward { locationLine += " · Ward: \(w)" }
        if let b = bedNumber { locationLine += " · Bed: \(b)" }
        lines.append(locationLine)
        lines.append("Acuity: \(acuity.label.uppercased())")
        lines.append("")

        // Diagnosis / complaint
        if let dx = workingDiagnosis {
            let icd = workingDiagnosisICD.map { " [\($0)]" } ?? ""
            lines.append("DIAGNOSIS: \(dx)\(icd)")
        }
        if let cc = chiefComplaint {
            lines.append("Chief complaint: \(cc)")
        }
        if let hpi = hpi, !hpi.isEmpty {
            lines.append("HPI: \(hpi.prefix(200))\(hpi.count > 200 ? "…" : "")")
        }
        lines.append("")

        // Anthropometrics
        if let h = heightCm {
            var anthropLine = String(format: "Height: %.0f cm", h)
            if let bmi = latestBMI(), let cat = bmiCategory {
                anthropLine += String(format: "  BMI: %.1f (%@)", bmi, cat)
            }
            lines.append(anthropLine)
        }

        // Vitals
        if let v = vitalsEntries.sorted(by: { $0.recordedAt > $1.recordedAt }).first, v.hasAnyValue {
            lines.append("LATEST VITALS (\(v.recordedAt.formatted(date: .omitted, time: .shortened)))")
            var vParts = [v.news2Summary]
            if let bp = v.bpString { vParts.append("BP \(bp) mmHg") }
            if let hr = v.heartRate { vParts.append("HR \(hr) bpm") }
            if let rr = v.respiratoryRate { vParts.append("RR \(rr)/min") }
            if let temp = v.temperatureCelsius { vParts.append(String(format: "Temp %.1f°C", temp)) }
            if let spo = v.spo2 { vParts.append("SpO₂ \(spo)%") }
            lines.append(vParts.joined(separator: " · "))
            lines.append("")
        }

        // PMH
        let pmhList = pmhEntries
        if !pmhList.isEmpty {
            lines.append("PMH: " + pmhList.map { e in
                e.yearText.isEmpty ? e.condition : "\(e.condition) (\(e.yearText))"
            }.joined(separator: "; "))
        } else if let pmh = pmhNotes, !pmh.isEmpty {
            lines.append("PMH: \(pmh)")
        }

        // PSHx
        let pshxList = pshxEntries
        if !pshxList.isEmpty {
            lines.append("PSHx: " + pshxList.map { e in
                var s = e.procedure
                if !e.yearText.isEmpty { s += " (\(e.yearText))" }
                return s
            }.joined(separator: "; "))
        } else if let pshx = surgicalHistory, !pshx.isEmpty {
            lines.append("PSHx: \(pshx)")
        }

        // Allergies
        let allergyList = recordedAllergies
        if allergyList.isEmpty {
            lines.append(hasExplicitNKDA ? "ALLERGIES: NKDA" : "ALLERGIES: NOT RECORDED")
        } else {
            lines.append("ALLERGIES: " + allergyList.map { "\($0.name) (\($0.reaction), \($0.severity))" }.joined(separator: "; "))
        }

        // Medications
        if !prescriptions.isEmpty {
            lines.append("")
            lines.append("MEDICATIONS:")
            prescriptions.forEach { lines.append("  • \($0.displayLine)") }
        }

        // Investigations
        let pending = investigations.filter { $0.status == .ordered || $0.status == .pending }
        let resulted = investigations.filter { $0.status == .resulted }
        if !pending.isEmpty || !resulted.isEmpty {
            lines.append("")
            lines.append("INVESTIGATIONS:")
            pending.forEach { lines.append("  ⏳ \($0.name) (awaiting)") }
            resulted.forEach { lines.append("  ✓ \($0.name)\($0.result.isEmpty ? "" : ": \($0.result)")") }
        }

        // Assessment
        if let assess = assessmentText, !assess.isEmpty {
            lines.append("")
            lines.append("ASSESSMENT:")
            lines.append(assess)
        }

        // Management plan
        if let plan = managementPlan, !plan.isEmpty {
            lines.append("")
            lines.append("MANAGEMENT PLAN:")
            lines.append(plan)
        }

        // Admission dates
        if let admitted = admittedAt {
            lines.append("")
            lines.append("Admitted: \(admitted.formatted(date: .abbreviated, time: .omitted))")
            if let exp = expectedDischarge {
                lines.append("Expected discharge: \(exp.formatted(date: .abbreviated, time: .omitted))")
            }
        }

        lines.append("")
        lines.append(String(repeating: "─", count: 48))
        lines.append("This handover is a summary. Verify all details in the full record.")
        return lines.joined(separator: "\n")
    }
}
