/**
 * Medication formulary for Dr Kabiye's outpatient general & endoscopic
 * surgery practice in Saint Lucia.
 *
 * Covers analgesics, antibiotics, GI medications, anticoagulants,
 * cardiovascular, diabetes, anaesthesia/procedural agents, steroids,
 * wound care, bowel prep, supplements, and anxiolytics/muscle relaxants.
 *
 * Dosing follows British-Caribbean conventions (OD, BD, TDS, QDS, PRN).
 * Drug interactions reference internal MED-XXX codes.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface Medication {
  code: string;
  genericName: string;
  brandNames: string[];
  class: string;
  subclass: string;
  forms: string[];
  commonDoses: string[];
  indications: string[];
  contraindications: string[];
  interactions: string[];
  category: 'formulary' | 'controlled' | 'restricted';
  surgicalRelevance: string[];
}

// ---------------------------------------------------------------------------
// Surgical-relevance tag vocabulary (for documentation / autocomplete)
// ---------------------------------------------------------------------------

export type SurgicalRelevanceTag =
  | 'pre-op_hold'
  | 'post-op_pain'
  | 'post-op_nausea'
  | 'antibiotic_prophylaxis'
  | 'dvt_prophylaxis'
  | 'bowel_prep'
  | 'endoscopy_sedation'
  | 'anaesthesia'
  | 'wound_care'
  | 'perioperative'
  | 'blood_glucose_management';

// ---------------------------------------------------------------------------
// Formulary data
// ---------------------------------------------------------------------------

export const FORMULARY: Medication[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ANALGESICS  MED-001 → MED-008
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-001',
    genericName: 'Paracetamol',
    brandNames: ['Panadol', 'Tylenol', 'Calpol'],
    class: 'Analgesic',
    subclass: 'Non-opioid',
    forms: ['tablet', 'suspension', 'suppository', 'IV infusion'],
    commonDoses: ['500mg–1g QDS PRN (max 4g/day)', '15mg/kg IV over 15min QDS'],
    indications: ['Mild-moderate pain', 'Pyrexia', 'Post-operative analgesia'],
    contraindications: ['Severe hepatic impairment', 'Active liver disease'],
    interactions: ['MED-036 (warfarin — may potentiate INR at high doses)'],
    category: 'formulary',
    surgicalRelevance: ['post-op_pain', 'perioperative'],
  },
  {
    code: 'MED-002',
    genericName: 'Ibuprofen',
    brandNames: ['Brufen', 'Advil', 'Nurofen'],
    class: 'Analgesic',
    subclass: 'NSAID',
    forms: ['tablet', 'capsule', 'suspension'],
    commonDoses: ['200–400mg TDS with food', '600mg TDS (max 2.4g/day)'],
    indications: ['Mild-moderate pain', 'Inflammation', 'Dysmenorrhoea', 'Pyrexia'],
    contraindications: [
      'Active GI bleeding or peptic ulcer',
      'Severe renal impairment (eGFR <30)',
      'Third trimester pregnancy',
      'Aspirin-sensitive asthma',
      'Post-CABG surgery',
    ],
    interactions: [
      'MED-036 (warfarin — increased bleeding risk)',
      'MED-037 (aspirin — reduced cardioprotection)',
      'MED-038 (clopidogrel — additive bleeding)',
      'MED-046 (lisinopril — reduced antihypertensive effect, nephrotoxicity)',
      'MED-047 (enalapril — reduced antihypertensive effect)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_pain', 'pre-op_hold'],
  },
  {
    code: 'MED-003',
    genericName: 'Diclofenac',
    brandNames: ['Voltaren', 'Cataflam', 'Voltarol'],
    class: 'Analgesic',
    subclass: 'NSAID',
    forms: ['tablet', 'suppository', 'IM injection', 'topical gel'],
    commonDoses: ['50mg BD-TDS', '75mg IM stat then 50mg PO TDS', '100mg SR OD'],
    indications: ['Moderate pain', 'Post-operative pain', 'Renal colic', 'Musculoskeletal inflammation'],
    contraindications: [
      'Active GI bleeding or peptic ulcer',
      'Severe hepatic/renal impairment',
      'Ischaemic heart disease',
      'Cerebrovascular disease',
      'Heart failure (NYHA II-IV)',
    ],
    interactions: [
      'MED-036 (warfarin — increased bleeding risk)',
      'MED-037 (aspirin — additive GI risk)',
      'MED-038 (clopidogrel — additive bleeding)',
      'MED-052 (furosemide — reduced diuretic effect)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_pain', 'pre-op_hold'],
  },
  {
    code: 'MED-004',
    genericName: 'Ketorolac',
    brandNames: ['Toradol'],
    class: 'Analgesic',
    subclass: 'NSAID',
    forms: ['tablet', 'IM injection', 'IV injection'],
    commonDoses: ['10mg PO QDS (max 5 days)', '30mg IV/IM stat then 15–30mg Q6H (max 2 days IV)'],
    indications: ['Moderate-severe acute pain', 'Post-operative analgesia'],
    contraindications: [
      'Active GI bleeding or peptic ulcer',
      'Severe renal impairment',
      'Perioperative CABG pain',
      'Coagulopathy',
      'Hypovolaemia',
      'Use >5 days',
    ],
    interactions: [
      'MED-036 (warfarin — increased bleeding risk)',
      'MED-040 (enoxaparin — additive bleeding)',
      'MED-006 (tramadol — may reduce seizure threshold)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_pain', 'perioperative'],
  },
  {
    code: 'MED-005',
    genericName: 'Naproxen',
    brandNames: ['Naprosyn', 'Aleve', 'Naprogesic'],
    class: 'Analgesic',
    subclass: 'NSAID',
    forms: ['tablet'],
    commonDoses: ['250–500mg BD', '500mg stat then 250mg Q6-8H'],
    indications: ['Pain', 'Inflammation', 'Dysmenorrhoea', 'Gout flare'],
    contraindications: [
      'Active GI bleeding or peptic ulcer',
      'Severe renal impairment',
      'Third trimester pregnancy',
    ],
    interactions: [
      'MED-036 (warfarin — increased bleeding risk)',
      'MED-037 (aspirin — additive GI risk)',
      'MED-046 (lisinopril — reduced effect, nephrotoxicity)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_pain', 'pre-op_hold'],
  },
  {
    code: 'MED-006',
    genericName: 'Tramadol',
    brandNames: ['Tramal', 'Ultram', 'Zydol'],
    class: 'Analgesic',
    subclass: 'Opioid',
    forms: ['capsule', 'tablet', 'injection', 'SR tablet'],
    commonDoses: ['50–100mg QDS PRN', '100mg SR BD', '50–100mg IV/IM Q4-6H'],
    indications: ['Moderate-severe pain', 'Post-operative pain'],
    contraindications: [
      'Uncontrolled epilepsy',
      'Concurrent MAOIs',
      'Acute alcohol intoxication',
      'Severe respiratory depression',
    ],
    interactions: [
      'MED-092 (diazepam — additive CNS depression)',
      'MED-067 (midazolam — additive CNS/respiratory depression)',
      'MED-030 (ondansetron — reduced tramadol efficacy)',
      'MED-004 (ketorolac — seizure threshold)',
    ],
    category: 'controlled',
    surgicalRelevance: ['post-op_pain', 'perioperative'],
  },
  {
    code: 'MED-007',
    genericName: 'Morphine',
    brandNames: ['MS Contin', 'Oramorph', 'Sevredol'],
    class: 'Analgesic',
    subclass: 'Opioid',
    forms: ['injection', 'oral solution', 'SR tablet', 'tablet'],
    commonDoses: ['2.5–10mg IV/SC Q4H PRN', '10–30mg PO Q4H PRN', '10–30mg SR BD'],
    indications: ['Severe pain', 'Post-operative pain', 'Renal/biliary colic'],
    contraindications: [
      'Respiratory depression',
      'Paralytic ileus',
      'Acute asthma',
      'Head injury with raised ICP',
      'Concurrent MAOIs',
    ],
    interactions: [
      'MED-092 (diazepam — additive CNS/respiratory depression)',
      'MED-067 (midazolam — additive CNS/respiratory depression)',
      'MED-068 (fentanyl — additive opioid effects)',
    ],
    category: 'controlled',
    surgicalRelevance: ['post-op_pain', 'perioperative'],
  },
  {
    code: 'MED-008',
    genericName: 'Pethidine',
    brandNames: ['Demerol', 'Meperidine'],
    class: 'Analgesic',
    subclass: 'Opioid',
    forms: ['injection', 'tablet'],
    commonDoses: ['25–100mg IM/IV Q3-4H PRN', '50–150mg PO Q4H PRN'],
    indications: ['Severe acute pain', 'Post-operative pain', 'Rigors'],
    contraindications: [
      'Concurrent MAOIs (risk of serotonin syndrome)',
      'Severe renal impairment (norpethidine accumulation)',
      'Raised intracranial pressure',
      'Respiratory depression',
    ],
    interactions: [
      'MED-092 (diazepam — additive CNS depression)',
      'MED-007 (morphine — additive opioid effects)',
    ],
    category: 'controlled',
    surgicalRelevance: ['post-op_pain'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ANTIBIOTICS  MED-009 → MED-020
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-009',
    genericName: 'Amoxicillin',
    brandNames: ['Amoxil', 'Ospamox'],
    class: 'Antibiotic',
    subclass: 'Penicillin',
    forms: ['capsule', 'suspension'],
    commonDoses: ['500mg TDS for 5–7 days', '1g TDS (high-dose)', '250mg TDS (mild)'],
    indications: ['Upper/lower respiratory tract infections', 'Urinary tract infections', 'H. pylori eradication (triple therapy)', 'Dental abscess'],
    contraindications: ['Penicillin hypersensitivity', 'History of penicillin-associated jaundice/hepatic dysfunction'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
      'MED-020 (doxycycline — antagonistic, avoid combination)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis'],
  },
  {
    code: 'MED-010',
    genericName: 'Co-amoxiclav (Amoxicillin/Clavulanate)',
    brandNames: ['Augmentin', 'Clavulin'],
    class: 'Antibiotic',
    subclass: 'Penicillin + beta-lactamase inhibitor',
    forms: ['tablet', 'suspension', 'IV injection'],
    commonDoses: ['625mg TDS for 5–7 days', '1.2g IV TDS'],
    indications: ['Skin/soft tissue infections', 'Intra-abdominal infections', 'Bite wounds', 'Surgical prophylaxis', 'Diabetic foot infections'],
    contraindications: ['Penicillin hypersensitivity', 'History of co-amoxiclav-associated jaundice'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-011',
    genericName: 'Metronidazole',
    brandNames: ['Flagyl', 'Metrogyl'],
    class: 'Antibiotic',
    subclass: 'Nitroimidazole',
    forms: ['tablet', 'IV infusion', 'suppository'],
    commonDoses: ['400mg TDS for 7 days', '500mg IV TDS', '500mg TDS (anaerobic cover)'],
    indications: ['Anaerobic infections', 'C. difficile colitis', 'Surgical prophylaxis (colorectal)', 'Intra-abdominal sepsis', 'H. pylori eradication', 'Amoebiasis'],
    contraindications: ['Disulfiram-like reaction with alcohol', 'First trimester pregnancy (high dose)'],
    interactions: [
      'MED-036 (warfarin — potentiates INR significantly)',
      'Alcohol (disulfiram-like reaction)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-012',
    genericName: 'Ciprofloxacin',
    brandNames: ['Cipro', 'Ciproxin'],
    class: 'Antibiotic',
    subclass: 'Fluoroquinolone',
    forms: ['tablet', 'IV infusion'],
    commonDoses: ['500mg BD for 7–14 days', '400mg IV BD'],
    indications: ['Urinary tract infections', 'Intra-abdominal infections (with metronidazole)', 'GI infections', 'Osteomyelitis', 'Diabetic foot (Gram-negative cover)'],
    contraindications: [
      'History of tendon disorders with quinolones',
      'Concurrent tizanidine',
      'Myasthenia gravis',
      'Children/adolescents (relative — risk to growing cartilage)',
    ],
    interactions: [
      'MED-036 (warfarin — potentiates INR)',
      'MED-056 (metformin — may alter glucose)',
      'Antacids/calcium/iron (chelation — reduce absorption, separate by 2h)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis'],
  },
  {
    code: 'MED-013',
    genericName: 'Levofloxacin',
    brandNames: ['Levaquin', 'Tavanic'],
    class: 'Antibiotic',
    subclass: 'Fluoroquinolone',
    forms: ['tablet', 'IV infusion'],
    commonDoses: ['500mg OD for 7–14 days', '750mg OD (severe infections)'],
    indications: ['Community-acquired pneumonia', 'Complicated UTI', 'Skin/soft tissue infections', 'Surgical prophylaxis (penicillin-allergic)'],
    contraindications: [
      'History of tendon disorders with quinolones',
      'Epilepsy (lowers seizure threshold)',
      'QT prolongation',
      'Myasthenia gravis',
    ],
    interactions: [
      'MED-036 (warfarin — potentiates INR)',
      'MED-030 (ondansetron — additive QT prolongation)',
      'MED-056 (metformin — glucose dysregulation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis'],
  },
  {
    code: 'MED-014',
    genericName: 'Ceftriaxone',
    brandNames: ['Rocephin'],
    class: 'Antibiotic',
    subclass: 'Third-generation cephalosporin',
    forms: ['IM injection', 'IV injection'],
    commonDoses: ['1g IV/IM OD', '2g IV OD (severe infections)', '2g IV stat (surgical prophylaxis)'],
    indications: ['Surgical prophylaxis', 'Intra-abdominal sepsis', 'Meningitis', 'Pyelonephritis', 'Community-acquired pneumonia'],
    contraindications: [
      'Severe penicillin/cephalosporin hypersensitivity (anaphylaxis)',
      'Neonates with hyperbilirubinaemia (calcium-ceftriaxone precipitates)',
    ],
    interactions: [
      'Calcium-containing IV solutions (do not co-administer)',
      'MED-036 (warfarin — may potentiate INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-015',
    genericName: 'Cefuroxime',
    brandNames: ['Zinnat', 'Ceftin'],
    class: 'Antibiotic',
    subclass: 'Second-generation cephalosporin',
    forms: ['tablet', 'IV injection'],
    commonDoses: ['250–500mg BD for 5–7 days', '750mg–1.5g IV TDS', '1.5g IV stat (surgical prophylaxis)'],
    indications: ['Surgical prophylaxis', 'Skin/soft tissue infections', 'UTI', 'Lower respiratory infections'],
    contraindications: ['Severe cephalosporin/penicillin hypersensitivity'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-016',
    genericName: 'Cephalexin',
    brandNames: ['Keflex', 'Ceporex'],
    class: 'Antibiotic',
    subclass: 'First-generation cephalosporin',
    forms: ['capsule', 'suspension'],
    commonDoses: ['500mg QDS for 7 days', '250mg QDS (mild)'],
    indications: ['Skin/soft tissue infections', 'UTI', 'Surgical wound infections', 'Cellulitis'],
    contraindications: ['Severe cephalosporin/penicillin hypersensitivity'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['wound_care', 'antibiotic_prophylaxis'],
  },
  {
    code: 'MED-017',
    genericName: 'Clindamycin',
    brandNames: ['Dalacin', 'Cleocin'],
    class: 'Antibiotic',
    subclass: 'Lincosamide',
    forms: ['capsule', 'IV injection'],
    commonDoses: ['300mg QDS for 7 days', '600mg IV QDS', '900mg IV TDS (severe)'],
    indications: ['Skin/soft tissue infections', 'Surgical prophylaxis (penicillin-allergic)', 'Osteomyelitis', 'Anaerobic cover', 'Diabetic foot'],
    contraindications: ['History of C. difficile colitis', 'Diarrhoeal states'],
    interactions: [
      'MED-072 (succinylcholine — enhanced neuromuscular blockade)',
      'MED-036 (warfarin — may potentiate INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-018',
    genericName: 'Gentamicin',
    brandNames: ['Garamycin', 'Genticin'],
    class: 'Antibiotic',
    subclass: 'Aminoglycoside',
    forms: ['IV injection', 'IM injection'],
    commonDoses: ['5–7mg/kg IV OD (extended interval)', '80mg IV TDS (traditional)', 'Monitor trough levels'],
    indications: ['Gram-negative sepsis', 'Surgical prophylaxis (with metronidazole)', 'Endocarditis (synergy)', 'Pyelonephritis'],
    contraindications: ['Myasthenia gravis', 'Severe renal impairment (dose adjustment required)'],
    interactions: [
      'MED-052 (furosemide — additive ototoxicity)',
      'MED-072 (succinylcholine — enhanced neuromuscular blockade)',
      'Other nephrotoxic agents',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-019',
    genericName: 'Azithromycin',
    brandNames: ['Zithromax', 'Azithral'],
    class: 'Antibiotic',
    subclass: 'Macrolide',
    forms: ['tablet', 'suspension', 'IV infusion'],
    commonDoses: ['500mg OD for 3 days', '500mg day 1 then 250mg OD days 2–5'],
    indications: ['Community-acquired pneumonia', 'Skin/soft tissue (penicillin-allergic)', 'Chlamydial infections', 'H. pylori (salvage regimen)'],
    contraindications: ['Severe hepatic impairment', 'QT prolongation', 'Macrolide hypersensitivity'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
      'MED-030 (ondansetron — additive QT prolongation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['antibiotic_prophylaxis'],
  },
  {
    code: 'MED-020',
    genericName: 'Doxycycline',
    brandNames: ['Vibramycin', 'Doxylin'],
    class: 'Antibiotic',
    subclass: 'Tetracycline',
    forms: ['capsule', 'tablet'],
    commonDoses: ['100mg BD for 7 days', '200mg stat then 100mg OD'],
    indications: ['Skin/soft tissue infections', 'Pelvic inflammatory disease', 'Acne', 'Malaria prophylaxis'],
    contraindications: ['Pregnancy', 'Children <12 years', 'Severe hepatic dysfunction'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
      'Antacids/calcium/iron (chelation — separate by 2h)',
      'MED-009 (amoxicillin — antagonistic, avoid combination)',
    ],
    category: 'formulary',
    surgicalRelevance: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GI MEDICATIONS  MED-021 → MED-035
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-021',
    genericName: 'Omeprazole',
    brandNames: ['Losec', 'Prilosec'],
    class: 'Gastrointestinal',
    subclass: 'PPI',
    forms: ['capsule', 'IV injection'],
    commonDoses: ['20mg OD', '40mg OD (erosive oesophagitis)', '40mg IV BD (GI bleed)'],
    indications: ['GORD', 'Peptic ulcer disease', 'H. pylori eradication', 'NSAID gastroprotection', 'Zollinger-Ellison syndrome', 'Upper GI bleed'],
    contraindications: ['PPI hypersensitivity'],
    interactions: [
      'MED-038 (clopidogrel — reduced antiplatelet effect via CYP2C19)',
      'MED-056 (metformin — may increase absorption)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-022',
    genericName: 'Pantoprazole',
    brandNames: ['Protonix', 'Controloc', 'Pantoloc'],
    class: 'Gastrointestinal',
    subclass: 'PPI',
    forms: ['tablet', 'IV injection'],
    commonDoses: ['40mg OD', '80mg IV stat then 8mg/h infusion (GI bleed)', '40mg IV BD'],
    indications: ['GORD', 'Peptic ulcer disease', 'Upper GI bleed', 'NSAID gastroprotection', 'Stress ulcer prophylaxis in ICU'],
    contraindications: ['PPI hypersensitivity'],
    interactions: [
      'MED-056 (metformin — may increase absorption)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-023',
    genericName: 'Esomeprazole',
    brandNames: ['Nexium'],
    class: 'Gastrointestinal',
    subclass: 'PPI',
    forms: ['tablet', 'IV injection', 'granules'],
    commonDoses: ['20mg OD', '40mg OD', '80mg IV stat then 8mg/h (GI bleed)'],
    indications: ['GORD', 'Peptic ulcer disease', 'H. pylori eradication', 'NSAID gastroprotection'],
    contraindications: ['PPI hypersensitivity'],
    interactions: [
      'MED-038 (clopidogrel — may reduce antiplatelet effect)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-024',
    genericName: 'Lansoprazole',
    brandNames: ['Prevacid', 'Zoton'],
    class: 'Gastrointestinal',
    subclass: 'PPI',
    forms: ['capsule', 'orodispersible tablet'],
    commonDoses: ['15mg OD', '30mg OD'],
    indications: ['GORD', 'Peptic ulcer disease', 'H. pylori eradication', 'NSAID gastroprotection'],
    contraindications: ['PPI hypersensitivity'],
    interactions: [
      'MED-038 (clopidogrel — may reduce antiplatelet effect)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-025',
    genericName: 'Famotidine',
    brandNames: ['Pepcid'],
    class: 'Gastrointestinal',
    subclass: 'H2 receptor antagonist',
    forms: ['tablet', 'IV injection'],
    commonDoses: ['20mg BD', '40mg nocte', '20mg IV BD'],
    indications: ['GORD', 'Peptic ulcer disease', 'Stress ulcer prophylaxis'],
    contraindications: ['H2-blocker hypersensitivity'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-026',
    genericName: 'Ranitidine',
    brandNames: ['Zantac'],
    class: 'Gastrointestinal',
    subclass: 'H2 receptor antagonist',
    forms: ['tablet', 'IV injection'],
    commonDoses: ['150mg BD', '300mg nocte', '50mg IV TDS'],
    indications: ['GORD', 'Peptic ulcer disease', 'Pre-anaesthetic aspiration prophylaxis'],
    contraindications: [
      'H2-blocker hypersensitivity',
      'NOTE: Withdrawn in many markets (2020) due to NDMA impurity concerns — verify local availability before prescribing',
    ],
    interactions: [
      'MED-036 (warfarin — may alter metabolism)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-027',
    genericName: 'Sucralfate',
    brandNames: ['Carafate', 'Antepsin'],
    class: 'Gastrointestinal',
    subclass: 'Mucosal protectant',
    forms: ['tablet', 'suspension'],
    commonDoses: ['1g QDS (1h before meals and at bedtime)'],
    indications: ['Peptic ulcer disease', 'Gastric mucosal protection', 'Stress ulcer prophylaxis'],
    contraindications: ['Severe renal impairment (aluminium accumulation)'],
    interactions: [
      'Reduces absorption of many drugs — separate by 2h',
      'MED-012 (ciprofloxacin — reduced absorption)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-028',
    genericName: 'Ondansetron',
    brandNames: ['Zofran'],
    class: 'Gastrointestinal',
    subclass: 'Antiemetic (5-HT3 antagonist)',
    forms: ['tablet', 'orodispersible tablet', 'IV injection'],
    commonDoses: ['4–8mg TDS PRN', '4mg IV stat pre-op', '8mg PO 1h pre-anaesthesia'],
    indications: ['Post-operative nausea/vomiting', 'Chemotherapy-induced nausea', 'Gastroenteritis'],
    contraindications: ['Congenital long QT syndrome', 'Concurrent apomorphine'],
    interactions: [
      'MED-006 (tramadol — reduced tramadol analgesic effect)',
      'MED-013 (levofloxacin — additive QT prolongation)',
      'MED-019 (azithromycin — additive QT prolongation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_nausea', 'perioperative', 'endoscopy_sedation'],
  },
  {
    code: 'MED-029',
    genericName: 'Metoclopramide',
    brandNames: ['Maxolon', 'Reglan'],
    class: 'Gastrointestinal',
    subclass: 'Antiemetic (dopamine antagonist)',
    forms: ['tablet', 'IV injection'],
    commonDoses: ['10mg TDS (max 5 days)', '10mg IV stat'],
    indications: ['Nausea/vomiting', 'Gastroparesis', 'Post-operative nausea'],
    contraindications: [
      'GI obstruction/perforation/haemorrhage',
      'Phaeochromocytoma',
      'Epilepsy',
      'Parkinsonism',
      'Use >5 days (risk of tardive dyskinesia)',
    ],
    interactions: [
      'MED-092 (diazepam — enhanced sedation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_nausea', 'perioperative'],
  },
  {
    code: 'MED-030',
    genericName: 'Domperidone',
    brandNames: ['Motilium'],
    class: 'Gastrointestinal',
    subclass: 'Antiemetic (peripheral dopamine antagonist)',
    forms: ['tablet'],
    commonDoses: ['10mg TDS (max 7 days)'],
    indications: ['Nausea/vomiting', 'Gastroparesis'],
    contraindications: [
      'QT prolongation',
      'Hepatic impairment',
      'Cardiac conditions where QT may be affected',
      'Concurrent QT-prolonging drugs',
    ],
    interactions: [
      'MED-019 (azithromycin — additive QT prolongation)',
      'MED-013 (levofloxacin — additive QT prolongation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_nausea'],
  },
  {
    code: 'MED-031',
    genericName: 'Promethazine',
    brandNames: ['Phenergan'],
    class: 'Gastrointestinal',
    subclass: 'Antiemetic (antihistamine/phenothiazine)',
    forms: ['tablet', 'injection', 'syrup'],
    commonDoses: ['12.5–25mg PO/IM TDS PRN', '25mg nocte (sedative antiemetic)'],
    indications: ['Nausea/vomiting', 'Motion sickness', 'Sedation', 'Allergic reactions'],
    contraindications: [
      'Children <2 years (respiratory depression)',
      'Comatose states',
      'Intra-arterial injection (tissue necrosis)',
    ],
    interactions: [
      'MED-007 (morphine — additive CNS depression)',
      'MED-006 (tramadol — additive sedation)',
      'MED-092 (diazepam — additive CNS depression)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_nausea', 'perioperative'],
  },
  {
    code: 'MED-032',
    genericName: 'Lactulose',
    brandNames: ['Duphalac', 'Lactugal'],
    class: 'Gastrointestinal',
    subclass: 'Osmotic laxative',
    forms: ['oral solution'],
    commonDoses: ['15–30mL BD', '30–50mL TDS (hepatic encephalopathy)'],
    indications: ['Constipation', 'Hepatic encephalopathy', 'Pre-/post-operative bowel regulation'],
    contraindications: ['Galactosaemia', 'Intestinal obstruction'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-033',
    genericName: 'Bisacodyl',
    brandNames: ['Dulcolax'],
    class: 'Gastrointestinal',
    subclass: 'Stimulant laxative',
    forms: ['tablet', 'suppository'],
    commonDoses: ['5–10mg nocte PO', '10mg PR'],
    indications: ['Constipation', 'Bowel preparation (adjunct)', 'Post-operative ileus prevention'],
    contraindications: ['Intestinal obstruction', 'Acute abdominal conditions', 'Severe dehydration'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['bowel_prep', 'perioperative'],
  },
  {
    code: 'MED-034',
    genericName: 'Macrogol (Polyethylene glycol)',
    brandNames: ['MiraLAX', 'Movicol', 'ClenPrep'],
    class: 'Gastrointestinal',
    subclass: 'Osmotic laxative',
    forms: ['powder for oral solution'],
    commonDoses: ['1 sachet OD-TDS in water', '8 sachets in 1L over 6h (bowel prep)'],
    indications: ['Chronic constipation', 'Faecal impaction', 'Bowel preparation (adjunct)'],
    contraindications: ['Intestinal obstruction', 'Intestinal perforation', 'Toxic megacolon'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['bowel_prep'],
  },
  {
    code: 'MED-035',
    genericName: 'Senna',
    brandNames: ['Senokot'],
    class: 'Gastrointestinal',
    subclass: 'Stimulant laxative',
    forms: ['tablet', 'syrup'],
    commonDoses: ['7.5–15mg nocte', '15mg BD (severe constipation)'],
    indications: ['Constipation', 'Opioid-induced constipation', 'Bowel preparation (adjunct)'],
    contraindications: ['Intestinal obstruction', 'Acute inflammatory bowel disease'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['bowel_prep', 'perioperative'],
  },
  {
    code: 'MED-036A',
    genericName: 'Hyoscine butylbromide',
    brandNames: ['Buscopan'],
    class: 'Gastrointestinal',
    subclass: 'Antispasmodic',
    forms: ['tablet', 'IV/IM injection'],
    commonDoses: ['10–20mg TDS PRN', '20mg IV stat for colic'],
    indications: ['Abdominal/renal colic', 'IBS-related spasm', 'Biliary colic', 'Endoscopy (reduce peristalsis)'],
    contraindications: ['Myasthenia gravis', 'Megacolon', 'Paralytic ileus', 'Tachycardia'],
    interactions: [
      'MED-029 (metoclopramide — antagonistic effects on GI motility)',
    ],
    category: 'formulary',
    surgicalRelevance: ['endoscopy_sedation', 'perioperative'],
  },
  {
    code: 'MED-036B',
    genericName: 'Dicyclomine',
    brandNames: ['Bentyl', 'Merbentyl'],
    class: 'Gastrointestinal',
    subclass: 'Antispasmodic',
    forms: ['tablet', 'capsule', 'injection'],
    commonDoses: ['10–20mg TDS-QDS', '20mg IM (acute colic)'],
    indications: ['IBS-related spasm', 'Functional abdominal pain'],
    contraindications: ['Myasthenia gravis', 'GI obstruction', 'Paralytic ileus', 'Glaucoma'],
    interactions: [
      'MED-029 (metoclopramide — antagonistic effects)',
    ],
    category: 'formulary',
    surgicalRelevance: [],
  },
  {
    code: 'MED-036C',
    genericName: 'Loperamide',
    brandNames: ['Imodium'],
    class: 'Gastrointestinal',
    subclass: 'Antidiarrhoeal',
    forms: ['capsule', 'tablet'],
    commonDoses: ['4mg stat then 2mg after each loose stool (max 16mg/day)'],
    indications: ['Acute diarrhoea', 'Chronic diarrhoea', 'Ileostomy output reduction'],
    contraindications: [
      'Acute dysentery (bloody stool with fever)',
      'Active ulcerative colitis',
      'C. difficile colitis',
      'Children <4 years',
    ],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ANTICOAGULANTS / ANTIPLATELETS  MED-036 → MED-043
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-036',
    genericName: 'Warfarin',
    brandNames: ['Coumadin', 'Marevan'],
    class: 'Anticoagulant',
    subclass: 'Vitamin K antagonist',
    forms: ['tablet'],
    commonDoses: ['Individualised dose, target INR 2.0–3.0 (DVT/PE/AF)', 'INR 2.5–3.5 (mechanical heart valve)'],
    indications: ['DVT/PE treatment and prevention', 'Atrial fibrillation', 'Mechanical heart valves', 'Post-surgical DVT prophylaxis'],
    contraindications: [
      'Active bleeding',
      'Haemorrhagic stroke',
      'Severe uncontrolled hypertension',
      'Pregnancy (teratogenic)',
      'Severe hepatic impairment',
    ],
    interactions: [
      'MED-002 (ibuprofen — increased bleeding)',
      'MED-003 (diclofenac — increased bleeding)',
      'MED-005 (naproxen — increased bleeding)',
      'MED-011 (metronidazole — potentiates INR)',
      'MED-012 (ciprofloxacin — potentiates INR)',
      'MED-037 (aspirin — additive bleeding risk)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'dvt_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-037',
    genericName: 'Aspirin',
    brandNames: ['Disprin', 'Ecotrin', 'Aspro'],
    class: 'Antiplatelet',
    subclass: 'COX inhibitor',
    forms: ['tablet', 'dispersible tablet', 'enteric-coated tablet'],
    commonDoses: ['75–100mg OD (antiplatelet)', '300mg stat (ACS)', '300–600mg QDS (analgesic)'],
    indications: ['Secondary prevention of MI/stroke', 'Acute coronary syndrome', 'Post-stent antiplatelet therapy'],
    contraindications: [
      'Active GI bleeding',
      'Haemophilia/bleeding disorders',
      'Children <16 years (Reye syndrome)',
      'Aspirin-sensitive asthma',
    ],
    interactions: [
      'MED-036 (warfarin — additive bleeding risk)',
      'MED-002 (ibuprofen — reduced cardioprotective effect)',
      'MED-040 (enoxaparin — additive bleeding)',
      'MED-038 (clopidogrel — additive bleeding, but intended dual antiplatelet therapy)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'perioperative'],
  },
  {
    code: 'MED-038',
    genericName: 'Clopidogrel',
    brandNames: ['Plavix'],
    class: 'Antiplatelet',
    subclass: 'P2Y12 inhibitor',
    forms: ['tablet'],
    commonDoses: ['75mg OD', '300mg stat loading dose (ACS)'],
    indications: ['ACS', 'Post-PCI/stent', 'Secondary stroke/TIA prevention', 'Peripheral vascular disease'],
    contraindications: ['Active bleeding', 'Severe hepatic impairment'],
    interactions: [
      'MED-021 (omeprazole — reduced antiplatelet effect)',
      'MED-023 (esomeprazole — reduced antiplatelet effect)',
      'MED-036 (warfarin — additive bleeding risk)',
      'MED-002 (ibuprofen — additive bleeding)',
      'MED-003 (diclofenac — additive bleeding)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'perioperative'],
  },
  {
    code: 'MED-039',
    genericName: 'Rivaroxaban',
    brandNames: ['Xarelto'],
    class: 'Anticoagulant',
    subclass: 'Direct oral anticoagulant (Factor Xa inhibitor)',
    forms: ['tablet'],
    commonDoses: ['10mg OD (DVT prophylaxis post-surgery)', '15mg BD x21d then 20mg OD (DVT/PE treatment)', '20mg OD with food (AF)'],
    indications: ['DVT/PE treatment and prevention', 'Atrial fibrillation', 'Post-surgical DVT prophylaxis (orthopaedic)'],
    contraindications: [
      'Active clinically significant bleeding',
      'Severe hepatic impairment (coagulopathy)',
      'Pregnancy/breastfeeding',
      'Lesion at high bleeding risk',
    ],
    interactions: [
      'MED-002 (ibuprofen — increased bleeding)',
      'MED-037 (aspirin — additive bleeding)',
      'Strong CYP3A4/P-gp inhibitors (ketoconazole, ritonavir)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'dvt_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-040',
    genericName: 'Enoxaparin',
    brandNames: ['Clexane', 'Lovenox'],
    class: 'Anticoagulant',
    subclass: 'Low molecular weight heparin',
    forms: ['SC injection'],
    commonDoses: ['40mg SC OD (DVT prophylaxis)', '1mg/kg SC BD (treatment)', '1.5mg/kg SC OD (treatment alternative)'],
    indications: ['DVT/PE prophylaxis (post-surgical)', 'DVT/PE treatment', 'ACS', 'Bridging anticoagulation'],
    contraindications: [
      'Active major bleeding',
      'Heparin-induced thrombocytopaenia (HIT)',
      'Severe thrombocytopaenia',
    ],
    interactions: [
      'MED-037 (aspirin — additive bleeding)',
      'MED-002 (ibuprofen — additive bleeding)',
      'MED-004 (ketorolac — additive bleeding)',
    ],
    category: 'formulary',
    surgicalRelevance: ['dvt_prophylaxis', 'perioperative', 'pre-op_hold'],
  },
  {
    code: 'MED-041',
    genericName: 'Heparin (unfractionated)',
    brandNames: ['Heparin Sodium'],
    class: 'Anticoagulant',
    subclass: 'Unfractionated heparin',
    forms: ['IV injection', 'SC injection'],
    commonDoses: ['5000 units SC BD-TDS (DVT prophylaxis)', '80 units/kg IV bolus then 18 units/kg/h (treatment, target aPTT)'],
    indications: ['DVT/PE treatment', 'DVT prophylaxis', 'ACS', 'DIC', 'Extracorporeal circuits'],
    contraindications: [
      'Active uncontrolled bleeding',
      'Heparin-induced thrombocytopaenia (HIT)',
      'Severe thrombocytopaenia',
    ],
    interactions: [
      'MED-037 (aspirin — additive bleeding)',
      'MED-036 (warfarin — overlap during bridging)',
    ],
    category: 'formulary',
    surgicalRelevance: ['dvt_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-042',
    genericName: 'Apixaban',
    brandNames: ['Eliquis'],
    class: 'Anticoagulant',
    subclass: 'Direct oral anticoagulant (Factor Xa inhibitor)',
    forms: ['tablet'],
    commonDoses: ['2.5mg BD (DVT prophylaxis post-surgery)', '5mg BD (AF)', '10mg BD x7d then 5mg BD (DVT/PE treatment)'],
    indications: ['Atrial fibrillation', 'DVT/PE treatment and prevention', 'Post-surgical DVT prophylaxis'],
    contraindications: [
      'Active clinically significant bleeding',
      'Severe hepatic impairment (coagulopathy)',
      'Lesion at high bleeding risk',
    ],
    interactions: [
      'MED-037 (aspirin — additive bleeding)',
      'MED-002 (ibuprofen — additive bleeding)',
      'Strong CYP3A4/P-gp inhibitors',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'dvt_prophylaxis', 'perioperative'],
  },
  {
    code: 'MED-043',
    genericName: 'Dabigatran',
    brandNames: ['Pradaxa'],
    class: 'Anticoagulant',
    subclass: 'Direct oral anticoagulant (Direct thrombin inhibitor)',
    forms: ['capsule'],
    commonDoses: ['110mg BD (AF, age >80 or high bleeding risk)', '150mg BD (AF)', '220mg OD (DVT prophylaxis post-surgery)'],
    indications: ['Atrial fibrillation', 'DVT/PE treatment and prevention', 'Post-surgical DVT prophylaxis'],
    contraindications: [
      'Active clinically significant bleeding',
      'Severe renal impairment (CrCl <30)',
      'Concurrent dronedarone/ketoconazole',
      'Mechanical heart valve',
    ],
    interactions: [
      'MED-037 (aspirin — additive bleeding)',
      'MED-002 (ibuprofen — additive bleeding)',
      'P-gp inhibitors (amiodarone, verapamil — dose adjust)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'dvt_prophylaxis', 'perioperative'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARDIOVASCULAR  MED-044 → MED-055
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-044',
    genericName: 'Amlodipine',
    brandNames: ['Norvasc', 'Istin'],
    class: 'Cardiovascular',
    subclass: 'Calcium channel blocker (dihydropyridine)',
    forms: ['tablet'],
    commonDoses: ['5mg OD', '10mg OD'],
    indications: ['Hypertension', 'Stable angina'],
    contraindications: ['Severe aortic stenosis', 'Cardiogenic shock', 'Unstable angina'],
    interactions: [
      'MED-055 (simvastatin — limit simvastatin to 20mg)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-045',
    genericName: 'Nifedipine',
    brandNames: ['Adalat', 'Procardia'],
    class: 'Cardiovascular',
    subclass: 'Calcium channel blocker (dihydropyridine)',
    forms: ['SR tablet', 'capsule'],
    commonDoses: ['20–30mg SR BD', '30–60mg MR OD'],
    indications: ['Hypertension', 'Angina', 'Raynaud phenomenon'],
    contraindications: ['Cardiogenic shock', 'Advanced aortic stenosis', 'Unstable angina', 'Within 1 month of MI'],
    interactions: [
      'MED-055 (simvastatin — increased statin levels)',
      'MED-050 (atenolol — additive bradycardia/hypotension)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-046',
    genericName: 'Lisinopril',
    brandNames: ['Zestril', 'Prinivil'],
    class: 'Cardiovascular',
    subclass: 'ACE inhibitor',
    forms: ['tablet'],
    commonDoses: ['5–10mg OD (start)', '20–40mg OD'],
    indications: ['Hypertension', 'Heart failure', 'Post-MI', 'Diabetic nephropathy'],
    contraindications: [
      'History of ACE inhibitor-related angioedema',
      'Bilateral renal artery stenosis',
      'Pregnancy',
      'Concurrent aliskiren in diabetes/renal impairment',
    ],
    interactions: [
      'MED-002 (ibuprofen — reduced effect, nephrotoxicity)',
      'MED-003 (diclofenac — reduced effect, nephrotoxicity)',
      'MED-053 (spironolactone — hyperkalaemia)',
      'MED-048 (losartan — dual RAAS blockade, hyperkalaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'pre-op_hold'],
  },
  {
    code: 'MED-047',
    genericName: 'Enalapril',
    brandNames: ['Vasotec', 'Renitec'],
    class: 'Cardiovascular',
    subclass: 'ACE inhibitor',
    forms: ['tablet'],
    commonDoses: ['5mg OD (start)', '10–20mg BD'],
    indications: ['Hypertension', 'Heart failure', 'Asymptomatic LV dysfunction'],
    contraindications: [
      'History of ACE inhibitor-related angioedema',
      'Bilateral renal artery stenosis',
      'Pregnancy',
    ],
    interactions: [
      'MED-002 (ibuprofen — reduced effect, nephrotoxicity)',
      'MED-053 (spironolactone — hyperkalaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'pre-op_hold'],
  },
  {
    code: 'MED-048',
    genericName: 'Losartan',
    brandNames: ['Cozaar'],
    class: 'Cardiovascular',
    subclass: 'Angiotensin II receptor blocker',
    forms: ['tablet'],
    commonDoses: ['50mg OD', '100mg OD'],
    indications: ['Hypertension', 'Diabetic nephropathy (type 2)', 'Heart failure (if ACEi intolerant)'],
    contraindications: [
      'Pregnancy',
      'Bilateral renal artery stenosis',
      'Severe hepatic impairment',
    ],
    interactions: [
      'MED-002 (ibuprofen — reduced effect, nephrotoxicity)',
      'MED-053 (spironolactone — hyperkalaemia)',
      'MED-046 (lisinopril — dual RAAS blockade, avoid)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'pre-op_hold'],
  },
  {
    code: 'MED-049',
    genericName: 'Valsartan',
    brandNames: ['Diovan'],
    class: 'Cardiovascular',
    subclass: 'Angiotensin II receptor blocker',
    forms: ['capsule', 'tablet'],
    commonDoses: ['80mg OD', '160mg OD', '320mg OD (max)'],
    indications: ['Hypertension', 'Heart failure', 'Post-MI (if ACEi intolerant)'],
    contraindications: [
      'Pregnancy',
      'Bilateral renal artery stenosis',
      'Severe hepatic impairment/biliary cirrhosis',
    ],
    interactions: [
      'MED-002 (ibuprofen — reduced effect)',
      'MED-053 (spironolactone — hyperkalaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'pre-op_hold'],
  },
  {
    code: 'MED-050',
    genericName: 'Atenolol',
    brandNames: ['Tenormin'],
    class: 'Cardiovascular',
    subclass: 'Beta-blocker (cardioselective)',
    forms: ['tablet'],
    commonDoses: ['25–50mg OD', '100mg OD'],
    indications: ['Hypertension', 'Angina', 'Arrhythmias', 'Perioperative heart rate control'],
    contraindications: [
      'Severe bradycardia (HR <50)',
      'Second/third-degree heart block',
      'Uncompensated heart failure',
      'Cardiogenic shock',
      'Untreated phaeochromocytoma',
    ],
    interactions: [
      'MED-045 (nifedipine — additive bradycardia/hypotension)',
      'MED-044 (amlodipine — additive hypotension)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-051',
    genericName: 'Metoprolol',
    brandNames: ['Lopressor', 'Betaloc'],
    class: 'Cardiovascular',
    subclass: 'Beta-blocker (cardioselective)',
    forms: ['tablet', 'SR tablet', 'IV injection'],
    commonDoses: ['25–50mg BD', '50–100mg SR OD', '5mg IV over 2min (acute)'],
    indications: ['Hypertension', 'Angina', 'Heart failure (SR)', 'Arrhythmias', 'Perioperative heart rate control'],
    contraindications: [
      'Severe bradycardia',
      'Second/third-degree heart block',
      'Cardiogenic shock',
      'Decompensated heart failure',
    ],
    interactions: [
      'MED-045 (nifedipine — additive bradycardia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-052',
    genericName: 'Furosemide',
    brandNames: ['Lasix', 'Frusemide'],
    class: 'Cardiovascular',
    subclass: 'Loop diuretic',
    forms: ['tablet', 'IV injection'],
    commonDoses: ['20–40mg OD-BD', '40–80mg IV stat', '250mg IV infusion (severe oedema)'],
    indications: ['Heart failure', 'Pulmonary oedema', 'Oedema (hepatic/renal)', 'Hypertension (adjunct)'],
    contraindications: [
      'Anuria (unresponsive renal failure)',
      'Severe hyponatraemia/hypokalaemia',
      'Hepatic encephalopathy (pre-coma)',
    ],
    interactions: [
      'MED-018 (gentamicin — additive ototoxicity)',
      'MED-003 (diclofenac — reduced diuretic effect)',
      'MED-046 (lisinopril — first-dose hypotension)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-052A',
    genericName: 'Hydrochlorothiazide',
    brandNames: ['HCTZ', 'Esidrex', 'Microzide'],
    class: 'Cardiovascular',
    subclass: 'Thiazide diuretic',
    forms: ['tablet'],
    commonDoses: ['12.5–25mg OD', '50mg OD (max)'],
    indications: ['Hypertension', 'Oedema', 'Nephrogenic diabetes insipidus'],
    contraindications: [
      'Severe renal impairment (eGFR <30, usually ineffective)',
      'Severe hypokalaemia/hyponatraemia',
      'Addison disease',
      'Hypercalcaemia',
    ],
    interactions: [
      'MED-046 (lisinopril — additive hypotension/first-dose)',
      'MED-056 (metformin — glucose dysregulation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-053',
    genericName: 'Spironolactone',
    brandNames: ['Aldactone'],
    class: 'Cardiovascular',
    subclass: 'Potassium-sparing diuretic (aldosterone antagonist)',
    forms: ['tablet'],
    commonDoses: ['25mg OD (heart failure)', '50–100mg OD (ascites)', '100–200mg OD (hyperaldosteronism)'],
    indications: ['Heart failure (NYHA III-IV)', 'Ascites', 'Primary hyperaldosteronism', 'Resistant hypertension'],
    contraindications: [
      'Hyperkalaemia (K+ >5.5)',
      'Severe renal impairment',
      'Addison disease',
      'Concurrent eplerenone',
    ],
    interactions: [
      'MED-046 (lisinopril — hyperkalaemia)',
      'MED-047 (enalapril — hyperkalaemia)',
      'MED-048 (losartan — hyperkalaemia)',
      'MED-002 (ibuprofen — reduced diuretic effect, nephrotoxicity, hyperkalaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-054',
    genericName: 'Atorvastatin',
    brandNames: ['Lipitor'],
    class: 'Cardiovascular',
    subclass: 'Statin (HMG-CoA reductase inhibitor)',
    forms: ['tablet'],
    commonDoses: ['10–20mg OD (primary prevention)', '40–80mg OD (secondary prevention/ACS)'],
    indications: ['Hypercholesterolaemia', 'Primary/secondary cardiovascular prevention', 'ACS'],
    contraindications: [
      'Active liver disease (raised transaminases >3x ULN)',
      'Pregnancy/breastfeeding',
      'Concurrent ciclosporin',
    ],
    interactions: [
      'MED-012 (ciprofloxacin — increased statin levels)',
      'MED-019 (azithromycin — increased statin levels, minor)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-055',
    genericName: 'Simvastatin',
    brandNames: ['Zocor'],
    class: 'Cardiovascular',
    subclass: 'Statin (HMG-CoA reductase inhibitor)',
    forms: ['tablet'],
    commonDoses: ['10–20mg nocte', '40mg nocte (max without interacting drugs)'],
    indications: ['Hypercholesterolaemia', 'Cardiovascular prevention'],
    contraindications: [
      'Active liver disease',
      'Pregnancy/breastfeeding',
      'Concurrent strong CYP3A4 inhibitors',
    ],
    interactions: [
      'MED-044 (amlodipine — limit simvastatin to 20mg)',
      'MED-045 (nifedipine — increased simvastatin levels)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DIABETES  MED-056 → MED-062
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-056',
    genericName: 'Metformin',
    brandNames: ['Glucophage', 'Glycomet'],
    class: 'Antidiabetic',
    subclass: 'Biguanide',
    forms: ['tablet', 'SR tablet'],
    commonDoses: ['500mg BD with meals (start)', '850mg TDS', '1g BD (max 2g/day)'],
    indications: ['Type 2 diabetes mellitus', 'Insulin resistance', 'PCOS'],
    contraindications: [
      'eGFR <30 (contraindicated), eGFR 30–45 (reduce dose)',
      'Acute metabolic acidosis / DKA',
      'Hold 48h pre-contrast / pre-GA',
      'Hepatic failure',
      'Acute alcohol intoxication',
    ],
    interactions: [
      'MED-012 (ciprofloxacin — glucose dysregulation)',
      'MED-052A (HCTZ — glucose dysregulation)',
      'IV contrast media (withhold 48h)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'blood_glucose_management', 'perioperative'],
  },
  {
    code: 'MED-057',
    genericName: 'Glimepiride',
    brandNames: ['Amaryl'],
    class: 'Antidiabetic',
    subclass: 'Sulphonylurea',
    forms: ['tablet'],
    commonDoses: ['1mg OD (start)', '2–4mg OD', '6mg OD (max)'],
    indications: ['Type 2 diabetes mellitus'],
    contraindications: [
      'Type 1 diabetes',
      'DKA',
      'Severe renal/hepatic impairment',
      'Sulphonamide hypersensitivity',
    ],
    interactions: [
      'MED-012 (ciprofloxacin — enhanced hypoglycaemia)',
      'MED-002 (ibuprofen — enhanced hypoglycaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'blood_glucose_management'],
  },
  {
    code: 'MED-058',
    genericName: 'Gliclazide',
    brandNames: ['Diamicron'],
    class: 'Antidiabetic',
    subclass: 'Sulphonylurea',
    forms: ['tablet', 'MR tablet'],
    commonDoses: ['40–80mg BD', '30–60mg MR OD (max 120mg MR OD)'],
    indications: ['Type 2 diabetes mellitus'],
    contraindications: [
      'Type 1 diabetes',
      'DKA',
      'Severe renal/hepatic impairment',
    ],
    interactions: [
      'MED-011 (metronidazole — enhanced hypoglycaemia)',
      'MED-012 (ciprofloxacin — enhanced hypoglycaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['pre-op_hold', 'blood_glucose_management'],
  },
  {
    code: 'MED-059',
    genericName: 'Insulin Regular (Soluble)',
    brandNames: ['Actrapid', 'Humulin R'],
    class: 'Antidiabetic',
    subclass: 'Insulin (short-acting)',
    forms: ['injection (SC/IV)'],
    commonDoses: ['Sliding scale IV (perioperative)', '4–10 units SC pre-meals', 'Variable rate IV insulin infusion (VRII)'],
    indications: ['Type 1 diabetes', 'Type 2 diabetes (perioperative)', 'DKA', 'Hyperkalaemia (with dextrose)'],
    contraindications: ['Hypoglycaemia'],
    interactions: [
      'MED-050 (atenolol — masks hypoglycaemia symptoms)',
      'MED-051 (metoprolol — masks hypoglycaemia symptoms)',
    ],
    category: 'formulary',
    surgicalRelevance: ['blood_glucose_management', 'perioperative'],
  },
  {
    code: 'MED-060',
    genericName: 'Insulin NPH (Isophane)',
    brandNames: ['Insulatard', 'Humulin N'],
    class: 'Antidiabetic',
    subclass: 'Insulin (intermediate-acting)',
    forms: ['injection (SC)'],
    commonDoses: ['10–20 units SC nocte (start)', 'Adjust by 2–4 units every 3 days to fasting target'],
    indications: ['Type 1 diabetes', 'Type 2 diabetes (basal insulin)'],
    contraindications: ['Hypoglycaemia'],
    interactions: [
      'MED-050 (atenolol — masks hypoglycaemia symptoms)',
    ],
    category: 'formulary',
    surgicalRelevance: ['blood_glucose_management', 'perioperative'],
  },
  {
    code: 'MED-061',
    genericName: 'Insulin Glargine',
    brandNames: ['Lantus', 'Basaglar', 'Toujeo'],
    class: 'Antidiabetic',
    subclass: 'Insulin (long-acting basal analogue)',
    forms: ['injection (SC)'],
    commonDoses: ['10 units SC OD (start)', 'Adjust by 2–4 units every 3 days to fasting target', 'Give at same time daily'],
    indications: ['Type 1 diabetes', 'Type 2 diabetes (basal insulin)'],
    contraindications: ['Hypoglycaemia'],
    interactions: [
      'MED-050 (atenolol — masks hypoglycaemia symptoms)',
    ],
    category: 'formulary',
    surgicalRelevance: ['blood_glucose_management', 'perioperative'],
  },
  {
    code: 'MED-062',
    genericName: 'Sitagliptin',
    brandNames: ['Januvia'],
    class: 'Antidiabetic',
    subclass: 'DPP-4 inhibitor',
    forms: ['tablet'],
    commonDoses: ['100mg OD', '50mg OD (eGFR 30–45)', '25mg OD (eGFR <30)'],
    indications: ['Type 2 diabetes mellitus (add-on to metformin or sulphonylurea)'],
    contraindications: ['History of pancreatitis (caution)', 'DPP-4 inhibitor hypersensitivity'],
    interactions: [
      'MED-057 (glimepiride — additive hypoglycaemia, reduce SU dose)',
      'MED-058 (gliclazide — additive hypoglycaemia, reduce SU dose)',
    ],
    category: 'formulary',
    surgicalRelevance: ['blood_glucose_management'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ANAESTHESIA / PROCEDURAL  MED-063 → MED-072
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-063',
    genericName: 'Lidocaine',
    brandNames: ['Xylocaine', 'Lignocaine'],
    class: 'Anaesthetic',
    subclass: 'Local anaesthetic (amide)',
    forms: ['injection', 'topical gel', 'topical spray', 'patch'],
    commonDoses: ['1–2% infiltration (max 4.5mg/kg without adrenaline, 7mg/kg with)', '2% gel topical', '10% spray (oropharyngeal)'],
    indications: ['Local/regional anaesthesia', 'Wound repair', 'Endoscopy (throat spray)', 'Ventricular arrhythmias'],
    contraindications: [
      'Amide local anaesthetic allergy',
      'Complete heart block',
      'Severe myocardial depression',
    ],
    interactions: [
      'MED-050 (atenolol — increased lidocaine levels)',
      'MED-051 (metoprolol — increased lidocaine levels)',
    ],
    category: 'formulary',
    surgicalRelevance: ['anaesthesia', 'endoscopy_sedation', 'wound_care'],
  },
  {
    code: 'MED-064',
    genericName: 'Bupivacaine',
    brandNames: ['Marcaine', 'Sensorcaine'],
    class: 'Anaesthetic',
    subclass: 'Local anaesthetic (amide, long-acting)',
    forms: ['injection'],
    commonDoses: ['0.25–0.5% infiltration (max 2mg/kg)', '0.5% for nerve blocks', '0.5% heavy (spinal)'],
    indications: ['Regional anaesthesia', 'Spinal anaesthesia', 'Nerve blocks', 'Wound infiltration (long-acting)'],
    contraindications: [
      'IV regional anaesthesia (Bier block) — risk of cardiac arrest',
      'Amide local anaesthetic allergy',
    ],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['anaesthesia'],
  },
  {
    code: 'MED-065',
    genericName: 'Propofol',
    brandNames: ['Diprivan'],
    class: 'Anaesthetic',
    subclass: 'IV induction agent',
    forms: ['IV injection/infusion'],
    commonDoses: ['1.5–2.5mg/kg IV induction', '4–12mg/kg/h IV infusion (maintenance)', '0.5–1mg/kg for procedural sedation'],
    indications: ['General anaesthesia induction/maintenance', 'Procedural sedation (endoscopy)', 'ICU sedation'],
    contraindications: [
      'Soya/egg lecithin allergy',
      'Mitochondrial disease',
      'Not for use without airway management capability',
    ],
    interactions: [
      'MED-068 (fentanyl — additive respiratory depression)',
      'MED-067 (midazolam — additive respiratory/CNS depression)',
    ],
    category: 'restricted',
    surgicalRelevance: ['anaesthesia', 'endoscopy_sedation'],
  },
  {
    code: 'MED-066',
    genericName: 'Ketamine',
    brandNames: ['Ketalar'],
    class: 'Anaesthetic',
    subclass: 'Dissociative anaesthetic (NMDA antagonist)',
    forms: ['injection'],
    commonDoses: ['1–2mg/kg IV (induction)', '0.5mg/kg IV (analgesic sub-dissociative)', '4–6mg/kg IM'],
    indications: ['Procedural sedation', 'Anaesthesia (haemodynamically unstable)', 'Analgesic adjunct', 'Burn dressings'],
    contraindications: [
      'Uncontrolled hypertension',
      'Pre-eclampsia/eclampsia',
      'Raised ICP',
      'Psychotic disorders',
      'Thyrotoxicosis',
    ],
    interactions: [
      'MED-067 (midazolam — often co-administered to reduce emergence phenomena)',
    ],
    category: 'controlled',
    surgicalRelevance: ['anaesthesia', 'endoscopy_sedation'],
  },
  {
    code: 'MED-067',
    genericName: 'Midazolam',
    brandNames: ['Versed', 'Dormicum', 'Hypnovel'],
    class: 'Anaesthetic',
    subclass: 'Benzodiazepine (short-acting)',
    forms: ['injection', 'oral solution', 'buccal solution'],
    commonDoses: ['1–2mg IV titrated (sedation)', '0.07–0.1mg/kg IM pre-med', '0.5mg/kg buccal (seizures)'],
    indications: ['Procedural sedation (endoscopy)', 'Anxiolysis pre-operative', 'Status epilepticus', 'ICU sedation'],
    contraindications: [
      'Myasthenia gravis',
      'Severe respiratory depression',
      'Acute pulmonary insufficiency',
      'Sleep apnoea syndrome',
    ],
    interactions: [
      'MED-007 (morphine — additive respiratory depression)',
      'MED-068 (fentanyl — additive respiratory depression)',
      'MED-065 (propofol — additive CNS depression)',
      'MED-006 (tramadol — additive CNS depression)',
    ],
    category: 'controlled',
    surgicalRelevance: ['endoscopy_sedation', 'anaesthesia', 'perioperative'],
  },
  {
    code: 'MED-068',
    genericName: 'Fentanyl',
    brandNames: ['Sublimaze', 'Durogesic'],
    class: 'Analgesic',
    subclass: 'Opioid (potent synthetic)',
    forms: ['injection', 'transdermal patch'],
    commonDoses: ['25–100mcg IV stat (analgesia)', '1–2mcg/kg IV (induction adjunct)', '25mcg/h patch (chronic pain)'],
    indications: ['Intraoperative analgesia', 'Procedural sedation', 'Severe chronic pain (patch)', 'ICU analgesia'],
    contraindications: [
      'Respiratory depression',
      'Paralytic ileus',
      'Opioid-naive patients (patch form)',
      'Concurrent MAOIs',
    ],
    interactions: [
      'MED-067 (midazolam — additive respiratory depression)',
      'MED-065 (propofol — additive respiratory depression)',
      'MED-007 (morphine — additive opioid effects)',
    ],
    category: 'controlled',
    surgicalRelevance: ['anaesthesia', 'endoscopy_sedation', 'post-op_pain'],
  },
  {
    code: 'MED-069',
    genericName: 'Atropine',
    brandNames: ['Atropine Sulfate'],
    class: 'Anaesthetic',
    subclass: 'Antimuscarinic',
    forms: ['injection'],
    commonDoses: ['0.6mg IV stat (bradycardia)', '20mcg/kg IV (pre-med)', '0.5–1mg IV (organophosphate poisoning)'],
    indications: ['Bradycardia', 'Pre-anaesthetic antisialagogue', 'Organophosphate poisoning', 'Reversal agent co-administration (with neostigmine)'],
    contraindications: [
      'Narrow-angle glaucoma',
      'Tachyarrhythmias',
      'Myasthenia gravis (relative)',
    ],
    interactions: [
      'MED-071 (neostigmine — co-administered to block muscarinic side effects)',
    ],
    category: 'formulary',
    surgicalRelevance: ['anaesthesia', 'perioperative'],
  },
  {
    code: 'MED-070',
    genericName: 'Glycopyrrolate',
    brandNames: ['Robinul', 'Glycopyrronium'],
    class: 'Anaesthetic',
    subclass: 'Antimuscarinic',
    forms: ['injection'],
    commonDoses: ['200–400mcg IV (pre-med)', '10–15mcg/kg IV (with neostigmine reversal)'],
    indications: ['Pre-anaesthetic antisialagogue', 'Bradycardia (perioperative)', 'Reversal agent co-administration (with neostigmine)'],
    contraindications: ['Narrow-angle glaucoma', 'Myasthenia gravis', 'Paralytic ileus'],
    interactions: [
      'MED-071 (neostigmine — co-administered to block muscarinic side effects)',
    ],
    category: 'formulary',
    surgicalRelevance: ['anaesthesia', 'perioperative'],
  },
  {
    code: 'MED-071',
    genericName: 'Neostigmine',
    brandNames: ['Prostigmin'],
    class: 'Anaesthetic',
    subclass: 'Anticholinesterase (reversal agent)',
    forms: ['injection'],
    commonDoses: ['2.5mg IV (with glycopyrrolate 500mcg or atropine 1.2mg)', '50–70mcg/kg IV (max 5mg)'],
    indications: ['Reversal of non-depolarising neuromuscular blockade', 'Myasthenia gravis'],
    contraindications: [
      'Mechanical GI/urinary obstruction',
      'Peritonitis',
      'Use without concurrent antimuscarinic',
    ],
    interactions: [
      'MED-069 (atropine — co-administered to prevent muscarinic effects)',
      'MED-070 (glycopyrrolate — co-administered)',
      'MED-072 (succinylcholine — may prolong phase II block)',
    ],
    category: 'formulary',
    surgicalRelevance: ['anaesthesia'],
  },
  {
    code: 'MED-072',
    genericName: 'Succinylcholine (Suxamethonium)',
    brandNames: ['Anectine', 'Scoline'],
    class: 'Anaesthetic',
    subclass: 'Neuromuscular blocker (depolarising)',
    forms: ['injection'],
    commonDoses: ['1–1.5mg/kg IV (rapid sequence induction)'],
    indications: ['Rapid sequence induction', 'Short procedures requiring muscle relaxation'],
    contraindications: [
      'Personal/family history of malignant hyperthermia',
      'Hyperkalaemia',
      'Denervation injuries (burns >24h, spinal cord injury, stroke)',
      'Myopathies (Duchenne)',
      'Pseudocholinesterase deficiency',
    ],
    interactions: [
      'MED-017 (clindamycin — enhanced blockade)',
      'MED-018 (gentamicin — enhanced blockade)',
      'MED-071 (neostigmine — may prolong block)',
    ],
    category: 'restricted',
    surgicalRelevance: ['anaesthesia'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEROIDS  MED-073 → MED-076
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-073',
    genericName: 'Prednisolone',
    brandNames: ['Deltacortril', 'Deltastab'],
    class: 'Corticosteroid',
    subclass: 'Glucocorticoid (oral)',
    forms: ['tablet', 'soluble tablet'],
    commonDoses: ['5–10mg OD (maintenance)', '30–40mg OD (acute flare, taper over 7–14 days)', '1mg/kg/day (max)'],
    indications: ['Inflammatory bowel disease', 'Asthma exacerbation', 'Autoimmune conditions', 'Post-operative swelling'],
    contraindications: [
      'Systemic fungal infections',
      'Live vaccines during high-dose therapy',
    ],
    interactions: [
      'MED-002 (ibuprofen — additive GI ulcer risk)',
      'MED-056 (metformin — steroid-induced hyperglycaemia)',
      'MED-036 (warfarin — may alter INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-074',
    genericName: 'Dexamethasone',
    brandNames: ['Decadron', 'Ozurdex'],
    class: 'Corticosteroid',
    subclass: 'Glucocorticoid (potent)',
    forms: ['tablet', 'injection'],
    commonDoses: ['4–8mg IV stat (antiemetic/anti-oedema)', '0.1–0.2mg/kg IV (PONV prophylaxis)', '4mg PO/IV OD (cerebral oedema)'],
    indications: ['Post-operative nausea/vomiting prophylaxis', 'Cerebral oedema', 'Croup', 'Anaphylaxis (adjunct)', 'Anti-inflammatory'],
    contraindications: [
      'Systemic fungal infections',
      'Cerebral malaria',
    ],
    interactions: [
      'MED-056 (metformin — steroid-induced hyperglycaemia)',
      'MED-057 (glimepiride — steroid-induced hyperglycaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['post-op_nausea', 'perioperative', 'anaesthesia'],
  },
  {
    code: 'MED-075',
    genericName: 'Hydrocortisone',
    brandNames: ['Solu-Cortef', 'Efcortesol'],
    class: 'Corticosteroid',
    subclass: 'Glucocorticoid',
    forms: ['injection', 'tablet', 'cream'],
    commonDoses: ['100mg IV stat (adrenal crisis/stress dose)', '50mg IV QDS (perioperative steroid cover)', '20mg AM + 10mg PM (replacement)'],
    indications: ['Adrenal insufficiency', 'Perioperative steroid cover', 'Anaphylaxis (adjunct)', 'Allergic reactions', 'Inflammatory conditions'],
    contraindications: ['Systemic fungal infections'],
    interactions: [
      'MED-056 (metformin — hyperglycaemia)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'anaesthesia'],
  },
  {
    code: 'MED-076',
    genericName: 'Methylprednisolone',
    brandNames: ['Solu-Medrol', 'Depo-Medrol'],
    class: 'Corticosteroid',
    subclass: 'Glucocorticoid',
    forms: ['injection', 'tablet'],
    commonDoses: ['125mg IV stat (severe inflammation)', '500mg–1g IV daily pulse (autoimmune flares)', '4–16mg PO daily'],
    indications: ['Severe inflammatory conditions', 'Acute spinal cord injury (controversial)', 'Organ transplant rejection', 'Autoimmune flares'],
    contraindications: ['Systemic fungal infections', 'Live vaccines during high-dose therapy'],
    interactions: [
      'MED-056 (metformin — hyperglycaemia)',
      'MED-036 (warfarin — may alter INR)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // WOUND CARE / TOPICAL  MED-077 → MED-080
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-077',
    genericName: 'Silver sulfadiazine',
    brandNames: ['Silvadene', 'Flamazine'],
    class: 'Topical antimicrobial',
    subclass: 'Silver compound',
    forms: ['cream'],
    commonDoses: ['Apply 3–5mm layer to affected area OD-BD'],
    indications: ['Burns (second/third degree)', 'Wound infections', 'Leg ulcers'],
    contraindications: [
      'Sulphonamide hypersensitivity',
      'Pregnancy (near term)',
      'Premature/newborn infants',
      'G6PD deficiency',
    ],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['wound_care'],
  },
  {
    code: 'MED-078',
    genericName: 'Povidone-iodine',
    brandNames: ['Betadine'],
    class: 'Topical antimicrobial',
    subclass: 'Iodophor antiseptic',
    forms: ['solution', 'scrub', 'ointment'],
    commonDoses: ['10% solution for surgical scrub', 'Apply to wound as needed'],
    indications: ['Surgical site antisepsis', 'Wound cleansing', 'Pre-operative skin preparation'],
    contraindications: [
      'Iodine hypersensitivity',
      'Thyroid disorders (large/prolonged application)',
      'Neonates (risk of thyroid suppression)',
    ],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['wound_care', 'perioperative'],
  },
  {
    code: 'MED-079',
    genericName: 'Mupirocin',
    brandNames: ['Bactroban'],
    class: 'Topical antimicrobial',
    subclass: 'Topical antibiotic',
    forms: ['ointment', 'cream', 'nasal ointment'],
    commonDoses: ['Apply TDS for 5–10 days', 'Nasal: apply BD-TDS for 5 days (MRSA decolonisation)'],
    indications: ['Impetigo', 'Superficial wound infections', 'MRSA decolonisation (nasal)', 'Minor skin infections'],
    contraindications: ['Mupirocin hypersensitivity'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['wound_care'],
  },
  {
    code: 'MED-080',
    genericName: 'Chlorhexidine',
    brandNames: ['Hibiscrub', 'Hibitane', 'ChloraPrep'],
    class: 'Topical antimicrobial',
    subclass: 'Biguanide antiseptic',
    forms: ['solution', 'scrub', 'impregnated wipes'],
    commonDoses: ['0.5–4% solution for skin prep', '2% in 70% isopropyl alcohol (surgical skin prep)'],
    indications: ['Surgical site antisepsis', 'Hand hygiene', 'Wound cleansing', 'Pre-operative skin preparation', 'Central line site care'],
    contraindications: [
      'Chlorhexidine hypersensitivity (rare anaphylaxis)',
      'Avoid contact with middle ear (ototoxic)',
      'Avoid contact with meninges/CNS',
    ],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['wound_care', 'perioperative'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BOWEL PREP  MED-081 → MED-082
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-081',
    genericName: 'PEG electrolyte solution',
    brandNames: ['GoLYTELY', 'Klean-Prep', 'CoLyte'],
    class: 'Bowel preparation',
    subclass: 'Osmotic lavage',
    forms: ['powder for reconstitution (4L)'],
    commonDoses: ['4L PO over 4–6h (day before procedure)', 'Split prep: 2L evening + 2L morning'],
    indications: ['Colonoscopy preparation', 'Bowel surgery preparation'],
    contraindications: [
      'GI obstruction',
      'Ileus',
      'Gastric retention',
      'Bowel perforation',
      'Toxic colitis/megacolon',
    ],
    interactions: [
      'Reduces absorption of all oral medications — take essential meds 2h before prep',
    ],
    category: 'formulary',
    surgicalRelevance: ['bowel_prep', 'endoscopy_sedation'],
  },
  {
    code: 'MED-082',
    genericName: 'Sodium picosulfate/Magnesium citrate',
    brandNames: ['Picolax', 'Picoprep', 'CitraFleet'],
    class: 'Bowel preparation',
    subclass: 'Stimulant + osmotic lavage',
    forms: ['powder sachets'],
    commonDoses: ['Sachet 1 at 8AM + sachet 2 at 2–4PM (day before procedure)', 'Each sachet in 150mL water + 250mL clear fluids/h'],
    indications: ['Colonoscopy preparation', 'Bowel surgery preparation'],
    contraindications: [
      'GI obstruction',
      'Congestive heart failure',
      'Ascites',
      'Acute inflammatory bowel disease',
      'Severe renal impairment (Mg accumulation)',
    ],
    interactions: [
      'Reduces absorption of all oral medications — take essential meds 2h before prep',
    ],
    category: 'formulary',
    surgicalRelevance: ['bowel_prep', 'endoscopy_sedation'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUPPLEMENTS / OTHER  MED-083 → MED-090
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-083',
    genericName: 'Ferrous sulfate',
    brandNames: ['Feospan', 'Fer-In-Sol', 'Slow-Fe'],
    class: 'Supplement',
    subclass: 'Iron supplement',
    forms: ['tablet', 'liquid'],
    commonDoses: ['200mg (65mg elemental iron) OD-TDS', '325mg BD-TDS'],
    indications: ['Iron deficiency anaemia', 'Pre-operative anaemia optimisation', 'Post-operative anaemia'],
    contraindications: [
      'Haemochromatosis',
      'Iron overload states',
      'Active peptic ulcer (relative)',
    ],
    interactions: [
      'MED-012 (ciprofloxacin — reduced antibiotic absorption, separate by 2h)',
      'MED-020 (doxycycline — reduced absorption, separate by 2h)',
      'MED-087 (levothyroxine — reduced absorption, separate by 4h)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-084',
    genericName: 'Folic acid',
    brandNames: ['Folacin'],
    class: 'Supplement',
    subclass: 'Vitamin (B9)',
    forms: ['tablet'],
    commonDoses: ['5mg OD', '400mcg OD (prophylaxis)'],
    indications: ['Folate deficiency anaemia', 'Megaloblastic anaemia', 'Pre-conception supplementation', 'Methotrexate adjunct'],
    contraindications: ['Folate-dependent tumours (untreated)'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-085',
    genericName: 'Cyanocobalamin (Vitamin B12)',
    brandNames: ['Cytacon', 'Nascobal'],
    class: 'Supplement',
    subclass: 'Vitamin (B12)',
    forms: ['tablet', 'IM injection'],
    commonDoses: ['50–150mcg OD PO', '1mg IM on alternate days x5 then 1mg IM every 3 months (pernicious anaemia)'],
    indications: ['Vitamin B12 deficiency', 'Pernicious anaemia', 'Post-gastrectomy', 'Neuropathy from B12 deficiency'],
    contraindications: ['Cobalt hypersensitivity'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-086',
    genericName: 'Calcium carbonate + Vitamin D3',
    brandNames: ['Calcichew D3', 'Caltrate', 'Os-Cal'],
    class: 'Supplement',
    subclass: 'Calcium + Vitamin D',
    forms: ['chewable tablet', 'tablet'],
    commonDoses: ['500mg Ca + 400IU D3 OD-BD', '600mg Ca + 800IU D3 OD'],
    indications: ['Calcium/Vitamin D deficiency', 'Osteoporosis prevention', 'Hypoparathyroidism', 'Post-thyroidectomy hypocalcaemia'],
    contraindications: [
      'Hypercalcaemia',
      'Hypercalciuria',
      'Renal calculi (calcium stones)',
      'Severe renal impairment',
    ],
    interactions: [
      'MED-012 (ciprofloxacin — reduced absorption, separate by 2h)',
      'MED-020 (doxycycline — reduced absorption, separate by 2h)',
      'MED-087 (levothyroxine — reduced absorption, separate by 4h)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-087',
    genericName: 'Levothyroxine',
    brandNames: ['Synthroid', 'Eltroxin', 'Euthyrox'],
    class: 'Endocrine',
    subclass: 'Thyroid hormone',
    forms: ['tablet'],
    commonDoses: ['25–50mcg OD (start, elderly/cardiac)', '100–200mcg OD (full replacement)', 'Take on empty stomach 30min before breakfast'],
    indications: ['Hypothyroidism', 'Post-thyroidectomy replacement', 'Myxoedema', 'TSH suppression (thyroid cancer)'],
    contraindications: ['Thyrotoxicosis', 'Uncorrected adrenal insufficiency'],
    interactions: [
      'MED-083 (ferrous sulfate — reduced absorption, separate by 4h)',
      'MED-086 (calcium — reduced absorption, separate by 4h)',
      'MED-036 (warfarin — potentiates anticoagulant effect)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative'],
  },
  {
    code: 'MED-088',
    genericName: 'Allopurinol',
    brandNames: ['Zyloprim', 'Zyloric'],
    class: 'Antigout',
    subclass: 'Xanthine oxidase inhibitor',
    forms: ['tablet'],
    commonDoses: ['100mg OD (start, uptitrate monthly)', '300mg OD (target)', '100–200mg OD (renal impairment)'],
    indications: ['Gout (chronic urate-lowering)', 'Recurrent renal calculi (urate)', 'Tumour lysis syndrome prophylaxis'],
    contraindications: ['Acute gout flare (do not initiate during)', 'Allopurinol hypersensitivity (HLA-B*5801 testing in at-risk populations)'],
    interactions: [
      'MED-036 (warfarin — may potentiate INR)',
    ],
    category: 'formulary',
    surgicalRelevance: [],
  },
  {
    code: 'MED-089',
    genericName: 'Salbutamol',
    brandNames: ['Ventolin', 'Proventil'],
    class: 'Respiratory',
    subclass: 'Short-acting beta-2 agonist (SABA)',
    forms: ['metered-dose inhaler', 'nebuliser solution', 'IV injection'],
    commonDoses: ['100–200mcg (1–2 puffs) PRN via MDI', '2.5–5mg nebulised Q4-6H', '5mg nebulised stat (acute)'],
    indications: ['Acute bronchospasm', 'Asthma', 'COPD exacerbation', 'Perioperative bronchospasm', 'Hyperkalaemia (adjunct)'],
    contraindications: ['Hypersensitivity (rare)'],
    interactions: [
      'MED-050 (atenolol — mutual antagonism in bronchospasm)',
      'MED-051 (metoprolol — may antagonise bronchodilation)',
    ],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'anaesthesia'],
  },
  {
    code: 'MED-090',
    genericName: 'Ipratropium bromide',
    brandNames: ['Atrovent'],
    class: 'Respiratory',
    subclass: 'Short-acting muscarinic antagonist (SAMA)',
    forms: ['metered-dose inhaler', 'nebuliser solution'],
    commonDoses: ['20–40mcg (1–2 puffs) QDS via MDI', '250–500mcg nebulised Q6-8H'],
    indications: ['COPD', 'Acute bronchospasm (with salbutamol)', 'Perioperative bronchospasm'],
    contraindications: ['Soya lecithin/peanut allergy (MDI formulation)'],
    interactions: [],
    category: 'formulary',
    surgicalRelevance: ['perioperative', 'anaesthesia'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ANTI-ANXIETY / MUSCLE RELAXANTS  MED-091 → MED-092
  // ═══════════════════════════════════════════════════════════════════════════
  {
    code: 'MED-091',
    genericName: 'Baclofen',
    brandNames: ['Lioresal'],
    class: 'Muscle relaxant',
    subclass: 'GABA-B agonist',
    forms: ['tablet'],
    commonDoses: ['5mg TDS (start)', '10mg TDS', '20mg TDS (max 80mg/day)'],
    indications: ['Muscle spasticity', 'Spinal cord injury', 'Multiple sclerosis', 'Post-operative muscle spasm'],
    contraindications: ['Active peptic ulcer', 'Epilepsy (may lower seizure threshold)'],
    interactions: [
      'MED-046 (lisinopril — additive hypotension)',
      'MED-092 (diazepam — additive CNS depression)',
    ],
    category: 'formulary',
    surgicalRelevance: [],
  },
  {
    code: 'MED-092',
    genericName: 'Diazepam',
    brandNames: ['Valium', 'Stesolid'],
    class: 'Anxiolytic',
    subclass: 'Benzodiazepine (long-acting)',
    forms: ['tablet', 'injection', 'rectal solution'],
    commonDoses: ['2–5mg BD-TDS (anxiety)', '5–10mg IV (acute seizures)', '5–10mg PO nocte pre-op'],
    indications: ['Anxiety', 'Muscle spasm', 'Status epilepticus', 'Pre-operative anxiolysis', 'Alcohol withdrawal'],
    contraindications: [
      'Myasthenia gravis',
      'Severe respiratory depression',
      'Sleep apnoea',
      'Severe hepatic impairment',
      'Acute pulmonary insufficiency',
    ],
    interactions: [
      'MED-007 (morphine — additive CNS/respiratory depression)',
      'MED-006 (tramadol — additive CNS depression)',
      'MED-008 (pethidine — additive CNS depression)',
      'MED-031 (promethazine — additive sedation)',
      'MED-091 (baclofen — additive CNS depression)',
    ],
    category: 'controlled',
    surgicalRelevance: ['perioperative'],
  },
];

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/**
 * Case-insensitive free-text search across generic name, brand names,
 * therapeutic class, subclass, and indications.
 */
export function searchMedications(query: string): Medication[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return FORMULARY.filter((med) => {
    if (med.genericName.toLowerCase().includes(q)) return true;
    if (med.brandNames.some((b) => b.toLowerCase().includes(q))) return true;
    if (med.class.toLowerCase().includes(q)) return true;
    if (med.subclass.toLowerCase().includes(q)) return true;
    if (med.code.toLowerCase() === q) return true;
    if (med.indications.some((ind) => ind.toLowerCase().includes(q))) return true;
    return false;
  });
}

/**
 * Retrieve a single medication by its internal MED-XXX code.
 */
export function getMedicationByCode(code: string): Medication | undefined {
  return FORMULARY.find((med) => med.code === code);
}

/**
 * Return all medications belonging to a given therapeutic class
 * (case-insensitive partial match).
 */
export function getMedicationsByClass(className: string): Medication[] {
  const q = className.toLowerCase().trim();
  if (!q) return [];

  return FORMULARY.filter(
    (med) =>
      med.class.toLowerCase().includes(q) ||
      med.subclass.toLowerCase().includes(q),
  );
}

/**
 * Return all medications tagged with a given surgical-relevance tag
 * (exact match).
 */
export function getSurgicallyRelevant(tag: string): Medication[] {
  return FORMULARY.filter((med) => med.surgicalRelevance.includes(tag));
}
