// BayesianDiagnosisEngine+HeadNeckEndocrineCandidates.swift
// Head / Neck / Endocrine / Parotid differential candidate tables

extension BayesianDiagnosisEngine {


    // ── Neck / thyroid lump ───────────────────────────────────────────

    static let neckLump: [Candidate] = [
        .init(name: "Benign Thyroid Nodule", icd: "E04.1",
              logPrior: 35, features: [
            .init(key: "exam", value: "midline", logLR: 10, evidenceLabel: "Midline lump"),
            .init(key: "exam", value: "moves on swallow", logLR: 16, evidenceLabel: "Moves on swallowing"),
            .init(key: "sex_female", value: "", logLR: 6, evidenceLabel: "Female sex (higher prevalence)"),
            .init(key: "timing", value: "Progressive", logLR: 4, evidenceLabel: "Slowly enlarging"),
        ]),
        .init(name: "Reactive Lymphadenopathy", icd: "R59.9",
              logPrior: 30, features: [
            .init(key: "associations", value: "Fever", logLR: 12, evidenceLabel: "Fever"),
            .init(key: "exam", value: "tender", logLR: 8, evidenceLabel: "Tender nodes"),
            .init(key: "exam", value: "multiple", logLR: 8, evidenceLabel: "Multiple nodes"),
            .init(key: "age_under", value: "40", logLR: 6, evidenceLabel: "Younger patient"),
        ]),
        .init(name: "Thyroid Carcinoma", icd: "C73",
              logPrior: 10, features: [
            .init(key: "exam", value: "hard", logLR: 10, evidenceLabel: "Hard nodule"),
            .init(key: "exam", value: "fixed", logLR: 12, evidenceLabel: "Fixed nodule"),
            .init(key: "timing", value: "Progressive", logLR: 10, evidenceLabel: "Rapidly enlarging"),
            .init(key: "age_over", value: "45", logLR: 6, evidenceLabel: "Age >45"),
            .init(key: "pmh", value: "radiation", logLR: 12, evidenceLabel: "History of radiation"),
            .init(key: "inv", value: "fnac", logLR: 14, evidenceLabel: "FNAC suspicious"),
        ]),
        .init(name: "Lymphoma", icd: "C85.90",
              logPrior: 8, features: [
            .init(key: "associations", value: "Weight loss", logLR: 12, evidenceLabel: "Weight loss"),
            .init(key: "associations", value: "Fever", logLR: 10, evidenceLabel: "B symptoms"),
            .init(key: "exam", value: "rubbery", logLR: 10, evidenceLabel: "Rubbery nodes"),
            .init(key: "exam", value: "multiple", logLR: 8, evidenceLabel: "Multiple node groups"),
            .init(key: "exam", value: "generalised", logLR: 8, evidenceLabel: "Generalised lymphadenopathy"),
        ]),
        .init(name: "Branchial Cyst", icd: "Q18.0",
              logPrior: 12, features: [
            .init(key: "site", value: "Anterior triangle", logLR: 14, evidenceLabel: "Anterior triangle of neck"),
            .init(key: "age_under", value: "30", logLR: 10, evidenceLabel: "Young adult"),
            .init(key: "character", value: "Cystic", logLR: 14, evidenceLabel: "Cystic / fluctuant"),
            .init(key: "exam", value: "smooth", logLR: 8, evidenceLabel: "Smooth, fluctuant"),
            .init(key: "exam", value: "transilluminates", logLR: 10, evidenceLabel: "Transilluminates"),
            .init(key: "timing", value: "Progressive", logLR: 6, evidenceLabel: "Slowly enlarging"),
        ]),
        .init(name: "Thyroglossal Duct Cyst", icd: "Q89.2",
              logPrior: 12, features: [
            .init(key: "site", value: "Midline", logLR: 16, evidenceLabel: "Midline neck"),
            .init(key: "exam", value: "moves on swallow", logLR: 16, evidenceLabel: "Moves on swallowing"),
            .init(key: "exam", value: "moves on tongue protrusion", logLR: 18, evidenceLabel: "Moves on tongue protrusion"),
            .init(key: "age_under", value: "25", logLR: 8, evidenceLabel: "Young patient"),
            .init(key: "character", value: "Cystic", logLR: 10, evidenceLabel: "Cystic texture"),
        ]),
        .init(name: "Carotid Body Tumour", icd: "D44.6",
              logPrior: 5, features: [
            .init(key: "site", value: "Anterior triangle", logLR: 12, evidenceLabel: "Anterior triangle, carotid bifurcation level"),
            .init(key: "exam", value: "pulsatile", logLR: 16, evidenceLabel: "Pulsatile lump"),
            .init(key: "exam", value: "bruit", logLR: 14, evidenceLabel: "Bruit audible"),
            .init(key: "exam", value: "transmits pulse", logLR: 14, evidenceLabel: "Transmits arterial pulsation"),
            .init(key: "character", value: "Firm", logLR: 6, evidenceLabel: "Firm, compressible"),
            .init(key: "age_over", value: "40", logLR: 6, evidenceLabel: "Middle-age/older"),
        ]),
    ]

    // ── Parotid / salivary gland ──────────────────────────────────────

    static let parotidSalivary: [Candidate] = [
        .init(name: "Pleomorphic Adenoma", icd: "D11.0",
              logPrior: 35, features: [
            .init(key: "timing", value: "Progressive", logLR: 10, evidenceLabel: "Slowly enlarging"),
            .init(key: "exam", value: "smooth", logLR: 8, evidenceLabel: "Smooth, lobulated"),
            .init(key: "exam", value: "mobile", logLR: 10, evidenceLabel: "Mobile"),
            .init(key: "exam", value: "non-tender", logLR: 6, evidenceLabel: "Non-tender"),
            .init(key: "exam", value: "facial nerve intact", logLR: 8, evidenceLabel: "Facial nerve function preserved"),
            .init(key: "age_over", value: "30", logLR: 4, evidenceLabel: "Middle-age peak"),
        ]),
        .init(name: "Sialadenitis (Parotid)", icd: "K11.20",
              logPrior: 20, features: [
            .init(key: "exacerbating", value: "Eating", logLR: 14, evidenceLabel: "Worse on eating / salivary stimulation"),
            .init(key: "character", value: "Painful", logLR: 10, evidenceLabel: "Painful swelling"),
            .init(key: "associations", value: "Fever", logLR: 10, evidenceLabel: "Fever"),
            .init(key: "exam", value: "tender", logLR: 10, evidenceLabel: "Tender gland"),
            .init(key: "exam", value: "erythema", logLR: 8, evidenceLabel: "Overlying skin erythema"),
            .init(key: "inv", value: "wbc", logLR: 8, evidenceLabel: "Leukocytosis"),
        ]),
        .init(name: "Sialolithiasis (Duct Stone)", icd: "K11.5",
              logPrior: 15, features: [
            .init(key: "exacerbating", value: "Eating", logLR: 14, evidenceLabel: "Colicky swelling with meals"),
            .init(key: "character", value: "Colicky", logLR: 12, evidenceLabel: "Episodic / colicky"),
            .init(key: "exam", value: "stone palpable", logLR: 16, evidenceLabel: "Stone bimanually palpable in duct"),
            .init(key: "exam", value: "firm", logLR: 6, evidenceLabel: "Firm, tender gland"),
            .init(key: "inv", value: "ultrasound", logLR: 12, evidenceLabel: "USS — ductal calculus"),
        ]),
        .init(name: "Parotid Carcinoma", icd: "C07",
              logPrior: 5, features: [
            .init(key: "exam", value: "firm, fixed", logLR: 14, evidenceLabel: "Fixed, hard mass"),
            .init(key: "timing", value: "Progressive", logLR: 10, evidenceLabel: "Rapidly enlarging"),
            .init(key: "exam", value: "facial nerve", logLR: 16, evidenceLabel: "Facial nerve palsy"),
            .init(key: "associations", value: "Pain", logLR: 8, evidenceLabel: "Pain"),
            .init(key: "age_over", value: "50", logLR: 8, evidenceLabel: "Older patient"),
            .init(key: "inv", value: "fnac", logLR: 14, evidenceLabel: "FNAC suspicious"),
        ]),
        .init(name: "Warthin's Tumour", icd: "D11.0",
              logPrior: 10, features: [
            .init(key: "exam", value: "smooth", logLR: 6, evidenceLabel: "Smooth, soft"),
            .init(key: "exam", value: "mobile", logLR: 6, evidenceLabel: "Mobile"),
            .init(key: "exam", value: "non-tender", logLR: 6, evidenceLabel: "Non-tender"),
            .init(key: "age_over", value: "50", logLR: 10, evidenceLabel: "Older male"),
            .init(key: "sex_male", value: "", logLR: 6, evidenceLabel: "Male sex"),
            .init(key: "pmh", value: "smoking", logLR: 10, evidenceLabel: "Smoking history"),
        ]),
    ]

    // MARK: – Thyroid Pathology
    static let thyroidPathology: [Candidate] = [
        .init(name: "Papillary Thyroid Carcinoma", icd: "C73",
              logPrior: 30, features: [
            .init(key: "exam",       value: "thyroid nodule",   logLR: 18, evidenceLabel: "Solitary thyroid nodule — RED FLAG"),
            .init(key: "exam",       value: "firm nodule",      logLR: 16, evidenceLabel: "Hard/firm nodule"),
            .init(key: "exam",       value: "lymph node",       logLR: 16, evidenceLabel: "Cervical lymphadenopathy"),
            .init(key: "timing",     value: "Progressive",      logLR: 12, evidenceLabel: "Progressive growth"),
            .init(key: "associations", value: "Hoarseness",     logLR: 14, evidenceLabel: "Hoarseness — recurrent laryngeal nerve"),
            .init(key: "associations", value: "Dysphagia",      logLR: 10, evidenceLabel: "Dysphagia"),
            .init(key: "sex_female", value: "",                 logLR:  8, evidenceLabel: "Female sex (3:1 ratio)"),
            .init(key: "pmh",        value: "radiation",        logLR: 16, evidenceLabel: "Prior neck radiation"),
            .init(key: "inv",        value: "ultrasound",       logLR: 14, evidenceLabel: "USS thyroid — microcalcification, irregular margin"),
            .init(key: "inv",        value: "fnac",             logLR: 20, evidenceLabel: "FNAC — malignant cells"),
            .init(key: "inv",        value: "tsh",              logLR:  6, evidenceLabel: "TSH suppressed or normal"),
        ]),
        .init(name: "Benign Thyroid Nodule / Colloid Goitre", icd: "E04.1",
              logPrior: 55, features: [
            .init(key: "exam",       value: "thyroid nodule",   logLR: 14, evidenceLabel: "Smooth, soft thyroid nodule"),
            .init(key: "exam",       value: "soft nodule",      logLR: 10, evidenceLabel: "Soft/cystic nodule"),
            .init(key: "timing",     value: "Stable",           logLR: 10, evidenceLabel: "Slow / stable growth over years"),
            .init(key: "sex_female", value: "",                 logLR:  6, evidenceLabel: "Female sex"),
            .init(key: "inv",        value: "ultrasound",       logLR: 12, evidenceLabel: "USS — anechoic/cystic, no suspicious features"),
            .init(key: "inv",        value: "tsh",              logLR:  8, evidenceLabel: "TSH — normal"),
            .init(key: "inv",        value: "fnac",             logLR: 14, evidenceLabel: "FNAC — benign (Bethesda II)"),
        ]),
        .init(name: "Graves' Disease / Hyperthyroidism", icd: "E05.0",
              logPrior: 35, features: [
            .init(key: "associations", value: "Palpitations",   logLR: 14, evidenceLabel: "Palpitations — pathognomonic triad sign"),
            .init(key: "associations", value: "Weight loss",    logLR: 14, evidenceLabel: "Weight loss despite good appetite"),
            .init(key: "associations", value: "Tremor",         logLR: 12, evidenceLabel: "Fine tremor of hands"),
            .init(key: "associations", value: "Sweating",       logLR: 12, evidenceLabel: "Heat intolerance, sweating"),
            .init(key: "exam",         value: "exophthalmos",   logLR: 20, evidenceLabel: "Exophthalmos — pathognomonic for Graves'"),
            .init(key: "exam",         value: "goitre",         logLR: 14, evidenceLabel: "Diffuse smooth goitre with bruit"),
            .init(key: "exam",         value: "bruit",          logLR: 16, evidenceLabel: "Thyroid bruit — highly specific for Graves'"),
            .init(key: "sex_female",   value: "",               logLR:  8, evidenceLabel: "Female sex (7:1)"),
            .init(key: "inv",          value: "tsh",            logLR: 18, evidenceLabel: "TSH suppressed (<0.01)"),
            .init(key: "inv",          value: "t4",             logLR: 16, evidenceLabel: "Free T4/T3 elevated"),
            .init(key: "inv",          value: "trab",           logLR: 20, evidenceLabel: "TSH receptor antibodies positive"),
        ]),
        .init(name: "Hashimoto's Thyroiditis / Hypothyroidism", icd: "E06.3",
              logPrior: 35, features: [
            .init(key: "associations", value: "Fatigue",        logLR: 12, evidenceLabel: "Fatigue, lethargy"),
            .init(key: "associations", value: "Weight gain",    logLR: 12, evidenceLabel: "Weight gain"),
            .init(key: "associations", value: "Cold intolerance", logLR: 12, evidenceLabel: "Cold intolerance"),
            .init(key: "associations", value: "Constipation",   logLR: 10, evidenceLabel: "Constipation"),
            .init(key: "associations", value: "Bradycardia",    logLR: 10, evidenceLabel: "Bradycardia"),
            .init(key: "exam",         value: "goitre",         logLR: 14, evidenceLabel: "Rubbery/firm goitre"),
            .init(key: "sex_female",   value: "",               logLR: 10, evidenceLabel: "Female sex (10:1)"),
            .init(key: "inv",          value: "tsh",            logLR: 18, evidenceLabel: "TSH elevated (>4.5)"),
            .init(key: "inv",          value: "tpo",            logLR: 18, evidenceLabel: "Anti-TPO antibodies positive"),
            .init(key: "inv",          value: "t4",             logLR: 14, evidenceLabel: "Free T4 low"),
        ]),
        .init(name: "Toxic Multinodular Goitre / Adenoma", icd: "E05.2",
              logPrior: 25, features: [
            .init(key: "exam",         value: "multinodular",   logLR: 16, evidenceLabel: "Multinodular goitre"),
            .init(key: "age_over",     value: "50",             logLR: 10, evidenceLabel: "Typically age >50"),
            .init(key: "associations", value: "Palpitations",   logLR: 12, evidenceLabel: "Palpitations / AF"),
            .init(key: "associations", value: "Weight loss",    logLR: 10, evidenceLabel: "Weight loss"),
            .init(key: "inv",          value: "tsh",            logLR: 14, evidenceLabel: "TSH suppressed"),
            .init(key: "inv",          value: "scan",           logLR: 14, evidenceLabel: "Isotope scan — hot nodule(s)"),
        ]),
        .init(name: "De Quervain's Thyroiditis", icd: "E06.1",
              logPrior: 15, features: [
            .init(key: "character",    value: "Painful",        logLR: 18, evidenceLabel: "Painful thyroid — pathognomonic"),
            .init(key: "onset",        value: "Acute",          logLR: 14, evidenceLabel: "Acute onset, weeks after URTI"),
            .init(key: "pmh",          value: "viral",          logLR: 12, evidenceLabel: "Recent viral illness"),
            .init(key: "associations", value: "Fever",          logLR: 10, evidenceLabel: "Fever, malaise"),
            .init(key: "associations", value: "Palpitations",   logLR:  8, evidenceLabel: "Transient hyperthyroid phase"),
            .init(key: "inv",          value: "esr",            logLR: 14, evidenceLabel: "ESR markedly elevated"),
            .init(key: "inv",          value: "tsh",            logLR: 10, evidenceLabel: "TSH may be suppressed initially"),
        ]),
        .init(name: "Medullary Thyroid Carcinoma", icd: "C73",
              logPrior: 8, features: [
            .init(key: "associations", value: "Diarrhoea",      logLR: 16, evidenceLabel: "Secretory diarrhoea — pathognomonic"),
            .init(key: "associations", value: "Flushing",       logLR: 14, evidenceLabel: "Flushing — calcitonin secretion"),
            .init(key: "exam",         value: "firm nodule",    logLR: 14, evidenceLabel: "Hard thyroid nodule"),
            .init(key: "exam",         value: "lymph node",     logLR: 14, evidenceLabel: "Cervical nodes"),
            .init(key: "pmh",          value: "men2",           logLR: 20, evidenceLabel: "MEN2 syndrome / family history"),
            .init(key: "inv",          value: "calcitonin",     logLR: 20, evidenceLabel: "Serum calcitonin elevated — specific"),
            .init(key: "inv",          value: "fnac",           logLR: 18, evidenceLabel: "FNAC — amyloid stroma, C-cells"),
        ]),
        .init(name: "Anaplastic Thyroid Carcinoma", icd: "C73",
              logPrior: 3, features: [
            .init(key: "timing",       value: "Rapid",          logLR: 20, evidenceLabel: "Rapidly enlarging neck mass — hallmark"),
            .init(key: "associations", value: "Stridor",        logLR: 18, evidenceLabel: "Stridor — tracheal compression — RED FLAG"),
            .init(key: "associations", value: "Dysphagia",      logLR: 14, evidenceLabel: "Dysphagia"),
            .init(key: "associations", value: "Hoarseness",     logLR: 14, evidenceLabel: "Hoarseness — RLN invasion"),
            .init(key: "age_over",     value: "65",             logLR: 12, evidenceLabel: "Age >65"),
            .init(key: "pmh",          value: "goitre",         logLR: 10, evidenceLabel: "Long-standing goitre"),
            .init(key: "inv",          value: "ct",             logLR: 14, evidenceLabel: "CT — invasive mass, calcification"),
            .init(key: "inv",          value: "biopsy",         logLR: 20, evidenceLabel: "Biopsy — undifferentiated carcinoma"),
        ]),
    ]

    // MARK: – Adrenal & Endocrine
    static let adrenalEndocrine: [Candidate] = [
        .init(name: "Adrenal Incidentaloma (Benign)", icd: "D35.00",
              logPrior: 50, features: [
            .init(key: "exam",         value: "asymptomatic",   logLR: 14, evidenceLabel: "Incidentally found on imaging — most common presentation"),
            .init(key: "inv",          value: "ct",             logLR: 18, evidenceLabel: "CT — well-defined, low HU (<10), <4 cm"),
            .init(key: "inv",          value: "mri",            logLR: 16, evidenceLabel: "MRI — chemical shift loss of signal"),
            .init(key: "inv",          value: "hormones",       logLR: 14, evidenceLabel: "Normal adrenal hormone screen"),
            .init(key: "age_over",     value: "40",             logLR: 10, evidenceLabel: "More common age >40"),
        ]),
        .init(name: "Conn's Syndrome (Primary Hyperaldosteronism)", icd: "E26.01",
              logPrior: 15, features: [
            .init(key: "associations", value: "Hypertension",   logLR: 16, evidenceLabel: "Resistant hypertension — key presentation"),
            .init(key: "associations", value: "Hypokalaemia",   logLR: 20, evidenceLabel: "Spontaneous hypokalaemia — pathognomonic"),
            .init(key: "associations", value: "Weakness",       logLR: 12, evidenceLabel: "Muscle weakness / cramps (hypokalaemia)"),
            .init(key: "associations", value: "Polyuria",       logLR: 10, evidenceLabel: "Polyuria / polydipsia (hypokalaemia)"),
            .init(key: "inv",          value: "aldo:renin",     logLR: 20, evidenceLabel: "Aldosterone:renin ratio >30 — diagnostic"),
            .init(key: "inv",          value: "ct",             logLR: 14, evidenceLabel: "CT adrenal — adenoma"),
            .init(key: "inv",          value: "avs",            logLR: 18, evidenceLabel: "Adrenal vein sampling — lateralisation"),
        ]),
        .init(name: "Cushing's Syndrome", icd: "E24.9",
              logPrior: 10, features: [
            .init(key: "associations", value: "Weight gain",    logLR: 14, evidenceLabel: "Central obesity / weight gain"),
            .init(key: "exam",         value: "moon face",      logLR: 18, evidenceLabel: "Moon face — Cushingoid features"),
            .init(key: "exam",         value: "buffalo hump",   logLR: 18, evidenceLabel: "Buffalo hump"),
            .init(key: "exam",         value: "striae",         logLR: 16, evidenceLabel: "Purple striae — pathognomonic"),
            .init(key: "exam",         value: "hypertension",   logLR: 12, evidenceLabel: "Hypertension"),
            .init(key: "associations", value: "Diabetes",       logLR: 12, evidenceLabel: "Hyperglycaemia / steroid diabetes"),
            .init(key: "associations", value: "Hirsutism",      logLR: 12, evidenceLabel: "Hirsutism (women)"),
            .init(key: "pmh",          value: "steroid",        logLR: 16, evidenceLabel: "Exogenous steroid use — most common cause"),
            .init(key: "inv",          value: "cortisol",       logLR: 18, evidenceLabel: "24h UFC elevated / midnight salivary cortisol"),
            .init(key: "inv",          value: "dexamethasone",  logLR: 18, evidenceLabel: "ODST — non-suppression"),
            .init(key: "inv",          value: "acth",           logLR: 14, evidenceLabel: "ACTH to distinguish adrenal vs. pituitary"),
        ]),
        .init(name: "Phaeochromocytoma", icd: "D35.00",
              logPrior: 5, features: [
            .init(key: "associations", value: "Paroxysmal hypertension", logLR: 20, evidenceLabel: "Paroxysmal hypertension — classic triad"),
            .init(key: "associations", value: "Headache",      logLR: 18, evidenceLabel: "Severe headache — triad component"),
            .init(key: "associations", value: "Sweating",      logLR: 18, evidenceLabel: "Diaphoresis — triad component"),
            .init(key: "associations", value: "Palpitations",  logLR: 18, evidenceLabel: "Palpitations — triad component"),
            .init(key: "associations", value: "Pallor",        logLR: 14, evidenceLabel: "Pallor (not flushing in most)"),
            .init(key: "pmh",          value: "men2",          logLR: 16, evidenceLabel: "MEN2 / VHL / NF1 syndrome"),
            .init(key: "inv",          value: "metanephrines", logLR: 20, evidenceLabel: "Plasma/urine metanephrines — highly sensitive"),
            .init(key: "inv",          value: "ct",            logLR: 14, evidenceLabel: "CT/MRI adrenal — hypervascular mass"),
            .init(key: "inv",          value: "mibg",          logLR: 18, evidenceLabel: "MIBG scan — functional imaging"),
        ]),
        .init(name: "Adrenocortical Carcinoma", icd: "C74.00",
              logPrior: 3, features: [
            .init(key: "exam",         value: "large mass",    logLR: 18, evidenceLabel: "Large adrenal mass >4 cm — HIGH concern"),
            .init(key: "timing",       value: "Progressive",   logLR: 14, evidenceLabel: "Progressive growth on follow-up imaging"),
            .init(key: "associations", value: "Virilisation",  logLR: 18, evidenceLabel: "Virilisation / feminisation — autonomous steroid"),
            .init(key: "associations", value: "Cushing features", logLR: 14, evidenceLabel: "Rapid-onset Cushing features"),
            .init(key: "associations", value: "Weight loss",   logLR: 14, evidenceLabel: "Weight loss — RED FLAG"),
            .init(key: "inv",          value: "ct",            logLR: 18, evidenceLabel: "CT — irregular, >10 HU, heterogeneous, >4 cm"),
            .init(key: "inv",          value: "biopsy",        logLR: 20, evidenceLabel: "Biopsy (only if uncertain origin — not adrenal primary)"),
            .init(key: "inv",          value: "steroids",      logLR: 14, evidenceLabel: "Mixed steroid hypersecretion profile"),
        ]),
    ]

}
