import Foundation

// MARK: - Dosing entry for a single drug within a diagnosis context

struct DosingEntry: Identifiable {
    let id = UUID()
    let drug: String
    let indication: String
    let dose: String
    let route: String
    let weightBased: Bool
    let renalCaution: Bool
    let hepaticCaution: Bool
    /// Patient allergy name must contain one of these strings (case-insensitive) to flag a contraindication
    let allergyKeywords: [String]
    let notes: String?
}

// MARK: - Diagnosis → dosing guide lookup

enum DiagnosisDosingGuide {
    static func lookup(diagnosis: String) -> [DosingEntry] {
        let dx = diagnosis.lowercased()
        for (key, entries) in table where dx.contains(key) { return entries }
        return []
    }

    // swiftlint:disable function_body_length
    private static let table: [String: [DosingEntry]] = [

        // MARK: Appendicitis
        "appendicitis": [
            DosingEntry(drug: "Co-amoxiclav", indication: "Mixed aerobic / anaerobic surgical cover",
                        dose: "1.2 g TDS", route: "IV → PO 625 mg TDS",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin","amoxicillin","co-amoxiclav","augmentin"],
                        notes: "Switch to oral when tolerating. Adjust dose if CrCl <30 mL/min"),
            DosingEntry(drug: "Metronidazole", indication: "Anaerobic cover",
                        dose: "500 mg TDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["metronidazole"],
                        notes: "Avoid alcohol; ↑ warfarin INR"),
            DosingEntry(drug: "Gentamicin", indication: "Gram-negative cover (penicillin allergy alternative)",
                        dose: "5 mg/kg OD", route: "IV",
                        weightBased: true, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Monitor pre-dose levels (trough <1 mg/L); nephrotoxic + ototoxic"),
            DosingEntry(drug: "Paracetamol", indication: "Step 1 analgesia",
                        dose: "1 g QDS", route: "IV/PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["paracetamol"],
                        notes: "Max 4 g/day; reduce to 500 mg QDS in hepatic impairment or <50 kg"),
            DosingEntry(drug: "Morphine", indication: "Step 3 analgesia (opioid)",
                        dose: "2.5–10 mg q4h PRN", route: "IV/SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["morphine"],
                        notes: "Reduce dose in renal failure — morphine-6-glucuronide accumulates"),
            DosingEntry(drug: "Ondansetron", indication: "Post-op nausea and vomiting",
                        dose: "4 mg TDS", route: "IV/PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [],
                        notes: "QT prolongation risk; reduce dose in severe hepatic impairment"),
            DosingEntry(drug: "Enoxaparin", indication: "Post-op VTE prophylaxis",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "20 mg OD if CrCl <30 mL/min; monitor anti-Xa if weight >100 kg or <50 kg"),
        ],

        // MARK: Cholecystitis / Biliary colic
        "cholecystitis": [
            DosingEntry(drug: "Co-amoxiclav", indication: "Biliary sepsis / acute cholecystitis",
                        dose: "1.2 g TDS", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin","amoxicillin","augmentin"],
                        notes: "Step down to PO 625 mg TDS when clinically improving"),
            DosingEntry(drug: "Metronidazole", indication: "Anaerobic cover",
                        dose: "500 mg TDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["metronidazole"], notes: nil),
            DosingEntry(drug: "Diclofenac", indication: "Biliary colic analgesia (NSAID)",
                        dose: "75 mg IM once", route: "IM",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["nsaid","diclofenac","ibuprofen","aspirin"],
                        notes: "Highly effective for colic; avoid in AKI, dehydration, or peptic ulcer"),
            DosingEntry(drug: "Hyoscine butylbromide", indication: "Antispasmodic — biliary colic",
                        dose: "20 mg QDS", route: "IV/IM/PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Ondansetron", indication: "Anti-emetic",
                        dose: "4 mg TDS", route: "IV/PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Enoxaparin", indication: "VTE prophylaxis",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],

        // MARK: Biliary colic
        "biliary colic": [
            DosingEntry(drug: "Diclofenac", indication: "First-line colic analgesia",
                        dose: "75 mg IM once", route: "IM",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["nsaid","diclofenac","ibuprofen","aspirin"],
                        notes: "Avoid in AKI, dehydration, or anticoagulated patients"),
            DosingEntry(drug: "Hyoscine butylbromide", indication: "Antispasmodic",
                        dose: "20 mg QDS", route: "IV/IM/PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Paracetamol", indication: "Background analgesia",
                        dose: "1 g QDS", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["paracetamol"], notes: nil),
            DosingEntry(drug: "Omeprazole", indication: "GI protection with NSAIDs",
                        dose: "20–40 mg OD", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: "Always co-prescribe with NSAIDs"),
        ],

        // MARK: Cholangitis
        "cholangitis": [
            DosingEntry(drug: "Piperacillin/tazobactam", indication: "Empirical broad-spectrum — biliary sepsis",
                        dose: "4.5 g QDS", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin","piperacillin"],
                        notes: "First-line for Grade II–III cholangitis (Tokyo Guidelines)"),
            DosingEntry(drug: "Gentamicin", indication: "Gram-negative bacteraemia cover",
                        dose: "5 mg/kg OD", route: "IV",
                        weightBased: true, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Weight-based dosing; check baseline creatinine; trough <1 mg/L"),
            DosingEntry(drug: "Metronidazole", indication: "Anaerobic cover",
                        dose: "500 mg TDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["metronidazole"], notes: nil),
            DosingEntry(drug: "Paracetamol", indication: "Analgesia",
                        dose: "1 g QDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["paracetamol"], notes: nil),
        ],

        // MARK: Pancreatitis
        "pancreatitis": [
            DosingEntry(drug: "Hartmann's (Ringer's Lactate)", indication: "Fluid resuscitation — first-line crystalloid",
                        dose: "250–500 mL/hr initially, then reassess", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Target urine output 0.5–1 mL/kg/hr; reassess every 6h; avoid Normal Saline"),
            DosingEntry(drug: "Morphine", indication: "Analgesia",
                        dose: "2.5–10 mg q4h PRN", route: "IV/SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["morphine"],
                        notes: "Evidence supports opioid analgesia in acute pancreatitis"),
            DosingEntry(drug: "Paracetamol", indication: "Background analgesia",
                        dose: "1 g QDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["paracetamol"], notes: nil),
            DosingEntry(drug: "Ondansetron", indication: "Anti-emetic",
                        dose: "4 mg TDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Omeprazole", indication: "Stress ulcer prophylaxis",
                        dose: "40 mg OD", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Enoxaparin", indication: "VTE prophylaxis",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "⚠️ Start only when haemorrhage risk acceptable (typically 24–48h after admission)"),
            DosingEntry(drug: "Piperacillin/tazobactam", indication: "Infected pancreatic necrosis ONLY",
                        dose: "4.5 g QDS", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin"],
                        notes: "⚠️ Antibiotics NOT indicated for sterile pancreatitis — only if confirmed/suspected infected necrosis"),
        ],

        // MARK: Diverticulitis
        "diverticulitis": [
            DosingEntry(drug: "Co-amoxiclav", indication: "Uncomplicated diverticulitis (mild–moderate)",
                        dose: "625 mg TDS", route: "PO",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin","amoxicillin","augmentin"],
                        notes: "7-day course; escalate to IV if not improving at 48h"),
            DosingEntry(drug: "Metronidazole", indication: "Anaerobic cover (use with ciprofloxacin if penicillin-allergic)",
                        dose: "400 mg TDS", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["metronidazole"], notes: nil),
            DosingEntry(drug: "Ciprofloxacin", indication: "Alternative gram-negative cover",
                        dose: "400 mg BD", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["ciprofloxacin","quinolone"],
                        notes: "Tendon rupture risk in elderly / steroid-treated patients"),
            DosingEntry(drug: "Piperacillin/tazobactam", indication: "Complicated diverticulitis / peritonitis",
                        dose: "4.5 g QDS", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin"],
                        notes: "For abscess, perforation, or peritonitis"),
            DosingEntry(drug: "Morphine", indication: "Analgesia",
                        dose: "2.5–10 mg q4h PRN", route: "IV/SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["morphine"], notes: nil),
        ],

        // MARK: Peritonitis / Perforated viscus
        "peritonitis": [
            DosingEntry(drug: "Piperacillin/tazobactam", indication: "Empirical broad-spectrum",
                        dose: "4.5 g QDS", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin"],
                        notes: "Add metronidazole if anaerobic cover inadequate"),
            DosingEntry(drug: "Metronidazole", indication: "Anaerobic cover",
                        dose: "500 mg TDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["metronidazole"], notes: nil),
            DosingEntry(drug: "Meropenem", indication: "Severe sepsis / resistant organisms",
                        dose: "500 mg–1 g TDS", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Reserve — discuss with microbiology; reduce dose in renal failure"),
            DosingEntry(drug: "Morphine", indication: "Analgesia (PCA or PRN)",
                        dose: "2.5–10 mg q4h", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["morphine"], notes: nil),
            DosingEntry(drug: "Pantoprazole", indication: "Stress ulcer prophylaxis",
                        dose: "40 mg OD", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Enoxaparin", indication: "VTE prophylaxis (post-op)",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],

        // MARK: Bowel obstruction
        "obstruction": [
            DosingEntry(drug: "Hartmann's (Ringer's Lactate)", indication: "Fluid resuscitation / maintenance",
                        dose: "1 L over 6–8h", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Monitor electrolytes daily — correct hypokalaemia (K+ target 4.0–4.5 mmol/L)"),
            DosingEntry(drug: "Morphine", indication: "Analgesia",
                        dose: "2.5–10 mg q4h PRN", route: "IV/SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["morphine"], notes: nil),
            DosingEntry(drug: "Ondansetron", indication: "Anti-emetic",
                        dose: "4 mg TDS", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Co-amoxiclav", indication: "Pre-op prophylaxis",
                        dose: "1.2 g single dose within 60 min of incision", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin","amoxicillin","augmentin"], notes: nil),
            DosingEntry(drug: "Enoxaparin", indication: "VTE prophylaxis (post-op)",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],

        // MARK: GI haemorrhage
        "haemorrhage": [
            DosingEntry(drug: "Tranexamic acid", indication: "Major haemorrhage — antifibrinolytic",
                        dose: "1 g over 10 min, then 1 g over 8h", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Best effect if given within 3h of haemorrhage onset"),
            DosingEntry(drug: "Pantoprazole", indication: "Upper GI haemorrhage (peptic ulcer)",
                        dose: "80 mg bolus then 8 mg/hr infusion", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [],
                        notes: "Start before endoscopy; switch to 40 mg OD PO after endoscopic haemostasis"),
            DosingEntry(drug: "Octreotide", indication: "Variceal haemorrhage",
                        dose: "50 mcg bolus then 50 mcg/hr infusion", route: "IV",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "If portal hypertension / varices suspected; continue for 3–5 days"),
            DosingEntry(drug: "Vitamin K", indication: "Reversal of warfarin",
                        dose: "5–10 mg", route: "IV slow",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [],
                        notes: "IV onset 4–6h; for immediate reversal also give PCC or FFP"),
            DosingEntry(drug: "Normal Saline (0.9% NaCl)", indication: "Initial resuscitation",
                        dose: "500 mL bolus × 2, then reassess", route: "IV",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "2× large-bore IV access; target SBP ≥90 mmHg; then switch to blood products"),
        ],

        // MARK: GORD / Reflux
        "gord": [
            DosingEntry(drug: "Omeprazole", indication: "PPI — first-line for GORD",
                        dose: "20 mg OD (mild) or 40 mg OD (erosive/severe)", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [],
                        notes: "Take 30 min before breakfast; 4–8 week course; reduce to maintenance 20 mg OD"),
            DosingEntry(drug: "Lansoprazole", indication: "PPI — alternative",
                        dose: "30 mg OD", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Pantoprazole", indication: "PPI — preferred where drug interactions a concern",
                        dose: "40 mg OD", route: "PO/IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [],
                        notes: "Fewer CYP450 interactions than omeprazole or lansoprazole"),
            DosingEntry(drug: "Metoclopramide", indication: "Prokinetic — gastroparesis / delayed gastric emptying",
                        dose: "10 mg TDS (before meals)", route: "PO",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Max 5 days; extrapyramidal effects especially in elderly — avoid in Parkinson's"),
            DosingEntry(drug: "Alginate (Gaviscon)", indication: "Symptomatic relief — antacid + barrier",
                        dose: "10–20 mL after meals and at bedtime", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],

        // MARK: Reflux (alias for GORD)
        "reflux": [
            DosingEntry(drug: "Omeprazole", indication: "PPI — first-line for reflux",
                        dose: "20 mg OD (mild) or 40 mg OD (erosive)", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [],
                        notes: "Take 30 min before breakfast; step-down to on-demand use after 8 weeks if controlled"),
            DosingEntry(drug: "Alginate (Gaviscon)", indication: "Symptomatic relief",
                        dose: "10–20 mL after meals and at bedtime", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],

        // MARK: Hernia
        "hernia": [
            DosingEntry(drug: "Cefazolin", indication: "Pre-op prophylaxis",
                        dose: "1 g IV (<80 kg) or 2 g IV (≥80 kg)", route: "IV",
                        weightBased: true, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["penicillin","cephalosporin","cefazolin"],
                        notes: "Give within 60 min of incision; repeat 3 g if surgery >3h"),
            DosingEntry(drug: "Paracetamol", indication: "Multimodal analgesia — regular background",
                        dose: "1 g QDS", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["paracetamol"], notes: nil),
            DosingEntry(drug: "Ibuprofen", indication: "NSAID — post-op analgesia",
                        dose: "400 mg TDS (with food)", route: "PO",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["nsaid","ibuprofen","aspirin"],
                        notes: "Avoid in renal impairment, peptic ulcer disease, anticoagulated patients"),
            DosingEntry(drug: "Oxycodone", indication: "Breakthrough opioid",
                        dose: "5 mg q4h PRN", route: "PO",
                        weightBased: false, renalCaution: true, hepaticCaution: true,
                        allergyKeywords: ["codeine","oxycodone"],
                        notes: "Short-acting; limit to 2–3 days post-op"),
            DosingEntry(drug: "Enoxaparin", indication: "VTE prophylaxis (moderate/high risk)",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [],
                        notes: "Start 6–12h post-op; continue 7–10 days for laparoscopic, 28 days for major"),
            DosingEntry(drug: "Lactulose", indication: "Prevent straining post-op (opioid constipation)",
                        dose: "15–30 mL BD", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],

        // MARK: Haemorrhoids
        "haemorrhoids": [
            DosingEntry(drug: "Lactulose", indication: "Stool softening — avoid straining",
                        dose: "15 mL BD", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Senna", indication: "Stimulant laxative",
                        dose: "2–4 tablets nocte", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Lidocaine 2% gel", indication: "Local anaesthesia — topical anorectal",
                        dose: "Small amount applied topically up to 4×/day", route: "Topical",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: ["lidocaine","local anaesthetic"],
                        notes: "Avoid large quantities to prevent systemic absorption"),
            DosingEntry(drug: "Metronidazole", indication: "Post-haemorrhoidectomy wound infection",
                        dose: "400 mg TDS", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["metronidazole"],
                        notes: "7-day course for perianal sepsis or haemorrhoidectomy wound infection"),
        ],

        // MARK: Post-op (general)
        "post-op": [
            DosingEntry(drug: "Paracetamol", indication: "Regular background analgesia",
                        dose: "1 g QDS", route: "PO/IV",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: ["paracetamol"], notes: "First-line; regular, not PRN"),
            DosingEntry(drug: "Ibuprofen", indication: "NSAID — adjunct analgesia",
                        dose: "400 mg TDS (with food)", route: "PO",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: ["nsaid","ibuprofen","aspirin"],
                        notes: "Avoid in bowel anastomosis (leak risk), renal failure, anticoagulated patients"),
            DosingEntry(drug: "Oxycodone", indication: "Breakthrough opioid",
                        dose: "5–10 mg q4h PRN", route: "PO",
                        weightBased: false, renalCaution: true, hepaticCaution: true,
                        allergyKeywords: ["codeine","oxycodone"], notes: "Limit to 2–3 days"),
            DosingEntry(drug: "Docusate sodium", indication: "Stool softener — opioid-induced constipation",
                        dose: "100–200 mg BD", route: "PO",
                        weightBased: false, renalCaution: false, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Ondansetron", indication: "Post-op nausea and vomiting",
                        dose: "4 mg TDS", route: "IV/PO",
                        weightBased: false, renalCaution: false, hepaticCaution: true,
                        allergyKeywords: [], notes: nil),
            DosingEntry(drug: "Enoxaparin", indication: "VTE prophylaxis",
                        dose: "40 mg OD", route: "SC",
                        weightBased: false, renalCaution: true, hepaticCaution: false,
                        allergyKeywords: [], notes: nil),
        ],
    ]
    // swiftlint:enable function_body_length
}
