// SurgicalDrug+Formulary2b.swift
// Surgical formulary sub-array _drugs7 (muscle relaxants, reversal agents,
// vasopressors, inotropes, and haemostatic agents).

import Foundation


extension SurgicalDrug {

    static let _drugs7: [SurgicalDrug] = [

        // ─── ANTIBIOTICS — Key Additions ──────────────────────────────────────
        .init(name: "Clindamycin", category: "Antibiotic — Lincosamide",
              commonDoses: "150–450 mg QDS PO; 300–900 mg TDS–QDS IV",
              route: "PO/IV/topical",
              notes: "Anaerobic and Gram-positive cover; skin/soft tissue (MRSA community strains); dental infections; bone/joint; C. difficile risk; NOT for CNS infections (poor penetration)",
              sideEffects: "C. difficile colitis (high risk — use minimum necessary duration), GI upset, oesophageal ulceration (take with water upright), rash, hepatotoxicity (rare)",
              contraindications: "Previous clindamycin-associated diarrhoea/colitis; avoid unnecessary prolonged courses (C. diff risk)",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Reduce dose and frequency in severe hepatic impairment (active liver disease — accumulation); monitor LFTs",
              monitoring: "Stool for C. difficile if diarrhoea develops; LFTs with prolonged IV use; local sensitivities"),

        .init(name: "Benzathine penicillin G (Bicillin L-A)", category: "Antibiotic — Long-acting Penicillin",
              commonDoses: "1.2 MU IM single dose (syphilis primary/secondary/latent <1yr); 2.4 MU IM × 3 doses weekly (late latent/tertiary); 1.2 MU IM monthly (rheumatic fever prophylaxis)",
              route: "Deep IM only",
              notes: "Long-acting depot penicillin; syphilis treatment; rheumatic fever secondary prophylaxis (critical in Caribbean); NEVER IV (cardiac arrest); deep gluteal IM only",
              sideEffects: "Injection-site pain (very common), Jarisch-Herxheimer reaction (syphilis — fever/chills 2–8h post first dose), anaphylaxis",
              contraindications: "Penicillin allergy (anaphylaxis); NEVER administer IV — fatal; not for neurosyphilis (use IV penicillin G)",
              renalDosing: "No dose adjustment for standard dosing; caution in severe renal failure with very high doses",
              hepaticDosing: "No dose adjustment",
              monitoring: "VDRL/RPR titres at 3, 6, 12 months (syphilis); Jarisch-Herxheimer reaction — pre-warn patient; observe 30 min post injection (anaphylaxis)"),

        .init(name: "Cefepime", category: "Antibiotic — Cephalosporin (4th generation)",
              commonDoses: "1–2 g BD–TDS IV; 2 g TDS (febrile neutropenia/meningitis/Pseudomonas)",
              route: "IV/IM",
              notes: "Broad-spectrum including Pseudomonas and ESBL (partial); febrile neutropenia; HAP/VAP; meningitis; overcomes many AmpC-mediated resistances",
              sideEffects: "Neurotoxicity (encephalopathy, seizures — especially in renal impairment; risk higher than other cephalosporins), rash, C. difficile, elevated LFTs",
              contraindications: "Cephalosporin hypersensitivity; use with extreme caution in seizure history/renal impairment (neurotoxicity)",
              renalDosing: "eGFR 30–60: 1–2 g BD. eGFR 11–29: 1–2 g OD. eGFR <11: 500 mg–1 g OD. Neurotoxicity risk increases with renal impairment — reduce dose",
              hepaticDosing: "No dose adjustment",
              monitoring: "Renal function (neurotoxicity risk proportional to exposure); neuro status in ICU; cultures and sensitivities"),

        .init(name: "Aztreonam", category: "Antibiotic — Monobactam",
              commonDoses: "1–2 g TDS–QDS IV/IM; 500 mg TDS–QDS (urinary tract)",
              route: "IV/IM",
              notes: "Gram-negative aerobic coverage only (like gentamicin without renal toxicity); safe in penicillin/cephalosporin allergy; no anaerobic or Gram-positive activity — combine accordingly",
              sideEffects: "GI upset, elevated LFTs, rash (cross-reactivity with ceftazidime — caution), phlebitis (IV), C. difficile (rare)",
              contraindications: "Aztreonam hypersensitivity; caution if ceftazidime allergy (some cross-reactivity due to identical R1 side chain)",
              renalDosing: "eGFR 10–30: 50% dose. eGFR <10: 25% dose or 500 mg after loading dose",
              hepaticDosing: "No dose adjustment in mild–moderate; use with caution in severe hepatic impairment",
              monitoring: "Renal function; LFTs with prolonged use; culture and sensitivity"),

        .init(name: "Ceftolozane/tazobactam (Zerbaxa)", category: "Antibiotic — Reserve Cephalosporin",
              commonDoses: "1.5 g TDS IV (over 1h); 3 g TDS (HAP/VAP)",
              route: "IV",
              notes: "Reserve antibiotic for MDR Pseudomonas aeruginosa (including those resistant to carbapenems); complicated intra-abdominal infections (with metronidazole); HAP/VAP",
              sideEffects: "GI upset, elevated LFTs, headache, hypokalaemia, fever, C. difficile",
              contraindications: "Cephalosporin hypersensitivity; only use for confirmed/suspected MDR Gram-negative infections — antimicrobial stewardship",
              renalDosing: "eGFR 30–50: 750 mg TDS. eGFR 15–29: 375 mg TDS. CRRT: specialist guidance required",
              hepaticDosing: "No hepatic dose adjustment",
              monitoring: "Culture and sensitivity (resistance confirmation before use); renal function; LFTs; antimicrobial stewardship review"),

        // ─── ANALGESICS — Additional ──────────────────────────────────────────
        .init(name: "Hydromorphone (Dilaudid)", category: "Opioid Analgesic",
              commonDoses: "1–4 mg PO q4–6h; 0.2–1 mg IV/SC q4–6h",
              route: "PO/IV/SC",
              notes: "5–7× more potent than morphine; useful when morphine poorly tolerated (less histamine release, less nausea in some patients); renally eliminated — accumulates in renal failure",
              sideEffects: "Respiratory depression, sedation, constipation, nausea, pruritus (less than morphine), confusion/myoclonus in renal failure (metabolite accumulation)",
              contraindications: "Opioid-naive patients without appropriate monitoring; severe respiratory depression; avoid in renal failure (active metabolite accumulation)",
              renalDosing: "Avoid or use extreme caution in eGFR <30 — hydromorphone-3-glucuronide accumulates and causes neuroexcitatory effects (myoclonus, seizures). Fentanyl preferred in renal failure",
              hepaticDosing: "Reduce initial dose in hepatic impairment (reduced first-pass/clearance); titrate carefully",
              monitoring: "Pain scores; sedation scale; respiratory rate; renal function if prolonged use"),

        .init(name: "Tapentadol (Palexia)", category: "Opioid Analgesic / NRI",
              commonDoses: "50–250 mg BD (SR); 50–100 mg q4–6h (IR); max 500 mg/day",
              route: "PO",
              notes: "Dual mechanism: mu-opioid agonist + noradrenaline reuptake inhibitor; less constipation and nausea than equianalgesic oxycodone; neuropathic and nociceptive pain",
              sideEffects: "Nausea, dizziness, constipation (less than oxycodone), somnolence, headache, serotonin syndrome risk (with SSRIs/SNRIs/MAOIs — less than tramadol)",
              contraindications: "MAO inhibitors (within 14 days), seizure disorder (relative), severe respiratory depression, severe hepatic/renal impairment (IR: eGFR <30)",
              renalDosing: "IR formulation: avoid if eGFR <30. SR: use with caution; dose reduce",
              hepaticDosing: "Severe hepatic impairment (Child-Pugh C): avoid IR; SR max 50 mg TDS",
              monitoring: "Pain scores; respiratory function; avoid concomitant serotonergic drugs"),

        // ─── INSULIN — Long-acting / Basal ────────────────────────────────────
        .init(name: "Insulin glargine (Lantus/Toujeo)", category: "Insulin — Long-acting Basal",
              commonDoses: "Individualised SC; typically 0.2–0.4 units/kg OD at same time each day; titrate by 2 units every 3 days to fasting target",
              route: "SC only",
              notes: "Peakless 24h basal insulin; once-daily injection; do NOT mix with other insulins in syringe; Toujeo (300 units/mL) ≠ Lantus (100 units/mL) — not interchangeable",
              sideEffects: "Hypoglycaemia (nocturnal less common than NPH), lipodystrophy at injection sites, weight gain, injection-site reactions, local allergy",
              contraindications: "Hypoglycaemia episode; never given IV (concentration/acidity — fatal); do not mix with other insulins",
              renalDosing: "Reduce dose in renal impairment (reduced insulin clearance increases hypoglycaemia risk); frequent glucose monitoring required",
              hepaticDosing: "Reduce dose in hepatic impairment (reduced gluconeogenesis + insulin degradation altered); titrate carefully",
              monitoring: "Fasting glucose (target 4–7 mmol/L); HbA1c; hypoglycaemic episodes; injection-site rotation; annual eye/foot/renal review"),

        .init(name: "Insulin detemir (Levemir)", category: "Insulin — Long-acting Basal",
              commonDoses: "Individualised SC; typically OD or BD; start 0.1–0.2 units/kg OD; adjust every 3 days",
              route: "SC only",
              notes: "Long-acting basal insulin (18–24h); weight-neutral advantage over glargine/NPH; predictable absorption (albumin binding reduces variability); BD dosing possible",
              sideEffects: "Hypoglycaemia, lipodystrophy, weight gain (less than glargine/NPH), injection-site reactions",
              contraindications: "Never IV; do not mix with other insulins",
              renalDosing: "Dose reduce in renal impairment; monitor closely (hypoglycaemia risk)",
              hepaticDosing: "Reduce dose; careful titration in hepatic impairment",
              monitoring: "Fasting/pre-dose glucose; HbA1c every 3 months; hypoglycaemia frequency"),

        .init(name: "Insulin degludec (Tresiba)", category: "Insulin — Ultra-long-acting Basal",
              commonDoses: "Individualised SC; typically OD at any time (consistent); titrate to fasting glucose target",
              route: "SC only",
              notes: "Ultra-long-acting (>42h half-life); very flat profile; lowest hypoglycaemia risk of all basal insulins; dose can be changed by ≥8h if needed; available 100 and 200 units/mL",
              sideEffects: "Hypoglycaemia (lowest rate of all basal insulins), weight gain, injection-site reactions, lipodystrophy",
              contraindications: "Never IV; do not mix with other insulins; 200 units/mL pen max 160 units/dose",
              renalDosing: "Reduce dose in renal impairment; less affected by renal clearance than older insulins but still monitor",
              hepaticDosing: "Reduce dose; monitor glucose closely",
              monitoring: "Fasting glucose; HbA1c; hypoglycaemia diary — often used to convert patients from NPH with hypoglycaemia problems"),

        .init(name: "Insulin regular (Actrapid/Humulin R)", category: "Insulin — Short-acting",
              commonDoses: "SC: 4–20 units 30 min before meals (patient-specific); IV infusion: 0.05–0.1 units/kg/h (DKA/perioperative); variable rate IV (VRIII/sliding scale)",
              route: "SC/IV",
              notes: "Only insulin that can be used IV (DKA, hyperkalaemia, peri-op); inject SC 30 min before meals (slower onset than rapid-acting); available for VRIII sliding scales",
              sideEffects: "Hypoglycaemia, weight gain, hypokalaemia (IV use — especially DKA protocol), lipodystrophy",
              contraindications: "Active hypoglycaemia; always use with dextrose for IV hyperkalaemia management",
              renalDosing: "Reduce dose; renal impairment prolongs insulin action (reduced renal clearance + insulin sensitivity changes)",
              hepaticDosing: "Reduce dose; hepatic impairment increases hypoglycaemia risk (reduced gluconeogenesis)",
              monitoring: "Glucose hourly during IV infusion; potassium in DKA protocol (replacement essential); fluid balance"),

        // ─── ANTI-MALARIALS ────────────────────────────────────────────────────
        .init(name: "Artemether/lumefantrine (Riamet/Coartem)", category: "Antimalarial — ACT",
              commonDoses: "4 tablets (80/480 mg) at 0, 8, 24, 36, 48, 60 h (adult >35 kg); always take with fat-containing food/milk",
              route: "PO",
              notes: "First-line treatment for uncomplicated Plasmodium falciparum malaria; artemisinin combination therapy (ACT); MUST take with food (poor absorption when fasted); complete 6-dose course",
              sideEffects: "Headache, dizziness, sleep disturbance, arthralgia/myalgia, palpitations, QTc prolongation, anorexia, nausea; generally well tolerated",
              contraindications: "Severe malaria (use IV artesunate), first trimester of pregnancy (teratogenicity — use quinine+doxycycline), QTc >500 ms, concomitant QT-prolonging drugs, mefloquine within 12h",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Use with caution in severe hepatic impairment; no formal dose recommendation",
              monitoring: "Repeat blood film at day 3, 7, 28 to confirm clearance; ECG if cardiac risk (QTc); glucose in children (hypoglycaemia risk)"),

        .init(name: "Artesunate IV (Malacef)", category: "Antimalarial — Artesunate IV",
              commonDoses: "2.4 mg/kg IV at 0, 12, 24h then OD until PO possible (minimum 3 days); then switch to ACT oral",
              route: "IV",
              notes: "Treatment of severe/complicated malaria (P. falciparum); superior to IV quinine (AQUAMAT/SEAQUAMAT trials); always follow with 3-day oral ACT on recovery",
              sideEffects: "Post-artesunate delayed haemolysis (PADH — occurs 2–4 weeks post treatment, especially in hyperparasitaemia; monitor Hb); hepatotoxicity, neurotoxicity (rare at therapeutic doses)",
              contraindications: "Not for uncomplicated malaria; hypersensitivity to artemisinins",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "No dose adjustment; monitor LFTs",
              monitoring: "Blood film for parasitaemia daily until negative; Hb at day 7, 14, 28 (PADH); renal function; blood glucose; LFTs"),

        .init(name: "Chloroquine phosphate", category: "Antimalarial / DMARD",
              commonDoses: "Treatment: 600 mg base loading, then 300 mg at 6h, then 300 mg OD × 2 days; Prophylaxis: 300 mg weekly (start 1 week before travel, 4 weeks after); SLE/RA: 150–300 mg OD",
              route: "PO",
              notes: "Prophylaxis where sensitive (now limited areas); SLE; RA; amoebic liver abscess; NOT for P. falciparum in most regions (widespread resistance). Caribbean: P. vivax/P. malariae still sensitive",
              sideEffects: "GI upset, headache, pruritus (common in Black African patients), retinal toxicity (cumulative dose — annual ophthalmology screen), cardiomyopathy (rare, high dose), QTc prolongation",
              contraindications: "Retinal disease/macular degeneration, G6PD deficiency (haemolysis), porphyria, pre-existing cardiac conduction defects",
              renalDosing: "eGFR <10: reduce dose (accumulation); avoid if severe renal failure",
              hepaticDosing: "Caution in hepatic impairment (hepatotoxicity risk, reduced clearance)",
              monitoring: "Baseline ophthalmology + annual review (retinal toxicity); G6PD screen in at-risk populations; ECG if cardiac risk; LFTs"),

        .init(name: "Atovaquone/proguanil (Malarone)", category: "Antimalarial — Prophylaxis/Treatment",
              commonDoses: "Prophylaxis: 1 adult tablet (250/100 mg) OD starting 1–2 days before travel, continue 7 days after. Treatment: 4 tablets OD × 3 days",
              route: "PO",
              notes: "Preferred prophylaxis for short trips to endemic areas (short pre/post travel dosing); treatment of uncomplicated falciparum malaria; take with food/milk",
              sideEffects: "GI upset (nausea, vomiting, abdominal pain), headache, dizziness, mouth ulcers, elevated LFTs; generally well tolerated",
              contraindications: "eGFR <30 mL/min (treatment); eGFR <30 (prophylaxis — use doxycycline or chloroquine if sensitive); pregnancy (limited data — avoid unless benefit outweighs risk); severe hepatic impairment",
              renalDosing: "Treatment: avoid if eGFR <30 (proguanil accumulates). Prophylaxis: avoid if eGFR <30",
              hepaticDosing: "Caution in severe hepatic impairment (proguanil conversion to active metabolite reduced)",
              monitoring: "LFTs; renal function before prescribing; adherence counselling (must take with food for absorption)"),

        .init(name: "Quinine sulfate", category: "Antimalarial",
              commonDoses: "Treatment: 600 mg TDS × 5–7 days (+ doxycycline 7 days); IV quinine: 20 mg/kg loading over 4h then 10 mg/kg q8h (HDU/ICU); Cramps: 200–300 mg nocte",
              route: "PO/IV",
              notes: "Oral: second-line uncomplicated malaria; IV: second-line severe malaria (if artesunate unavailable); leg cramps (unlicensed, last resort); narrow therapeutic index; cardiac monitoring required IV",
              sideEffects: "Cinchonism (tinnitus, dizziness, nausea, visual disturbances, headache), QTc prolongation, hypoglycaemia (stimulates insulin), thrombocytopenia, haemolysis (G6PD), tinnitus",
              contraindications: "Haemoglobinuria (blackwater fever), optic neuritis, tinnitus, G6PD deficiency (relative), haemolytic anaemia",
              renalDosing: "Reduce IV maintenance dose (by 1/3) in renal failure; accumulation of metabolites",
              hepaticDosing: "Reduce dose in hepatic impairment (prolonged half-life)",
              monitoring: "Continuous cardiac monitoring (QTc) during IV infusion; blood glucose every 4–6h (hypoglycaemia risk); blood film; blood quinine levels if available"),

        .init(name: "Primaquine", category: "Antimalarial — Anti-hypnozoite",
              commonDoses: "P. vivax/ovale radical cure: 15 mg base OD × 14 days; Pneumocystis: 30 mg OD with clindamycin",
              route: "PO",
              notes: "Eradicates dormant liver stages (hypnozoites) of P. vivax and P. ovale — prevents relapse; G6PD TESTING MANDATORY before prescribing (life-threatening haemolysis)",
              sideEffects: "Haemolytic anaemia (severe/life-threatening in G6PD deficiency), methaemoglobinaemia, GI upset, abdominal pain",
              contraindications: "G6PD deficiency (ABSOLUTE — test first), pregnancy, breastfeeding (unless infant G6PD normal), rheumatoid arthritis/SLE",
              renalDosing: "No formal dose adjustment, but avoid in severe renal impairment",
              hepaticDosing: "Avoid in active hepatic disease",
              monitoring: "G6PD level BEFORE starting — mandatory; FBC (Hb, haematocrit) weekly during treatment; methaemoglobin if cyanosis"),

        // ─── GI — Additional ──────────────────────────────────────────────────
        .init(name: "Famotidine (Pepcid)", category: "H2-receptor Antagonist",
              commonDoses: "20–40 mg BD (active ulcer); 20 mg OD (maintenance/prophylaxis); 20 mg IV BD (inpatient acid suppression when PO not possible)",
              route: "PO/IV",
              notes: "Peptic ulcer; GORD; alternative to PPI (fewer drug interactions); useful when PPI causes side effects; less cimetidine-type drug interactions than ranitidine",
              sideEffects: "Headache, dizziness, constipation/diarrhoea, elevated LFTs (rare), QTc prolongation (IV high-dose), thrombocytopenia (rare)",
              contraindications: "Hypersensitivity to H2 blockers; caution in QTc prolongation (IV); phenylketonuria (some formulations contain phenylalanine)",
              renalDosing: "eGFR <50: 50% dose reduction or double interval (accumulation); eGFR <30: 50% dose, 36–48h intervals",
              hepaticDosing: "No dose adjustment in hepatic impairment",
              monitoring: "Renal function before dosing in renal impairment; symptom response; ECG if IV in at-risk patients"),

        .init(name: "Pancreatin (Creon)", category: "Pancreatic Enzyme Supplement",
              commonDoses: "Creon 10,000–25,000 units lipase with each main meal; 5,000–10,000 with snacks; titrate to symptoms",
              route: "PO",
              notes: "Exocrine pancreatic insufficiency (chronic pancreatitis, pancreatic cancer, post-pancreatectomy, cystic fibrosis); swallow whole or open capsule and mix with food; do NOT crush (inactivated by acid)",
              sideEffects: "GI discomfort, nausea, constipation/diarrhoea (dose-dependent), fibrosing colonopathy (very high doses in CF), hyperuricaemia (high doses), perioral soreness (if powder contacts mucosa)",
              contraindications: "Acute pancreatitis; known porcine allergy; early stages of acute pancreatitis",
              renalDosing: "No renal dose adjustment needed",
              hepaticDosing: "No hepatic dose adjustment",
              monitoring: "Stool frequency and consistency; weight; nutritional status; fat-soluble vitamins (A, D, E, K) in chronic use; consider fibrosing colonopathy if doses >10,000 units/kg/day in CF"),

        .init(name: "Loperamide (Imodium)", category: "Antidiarrhoeal",
              commonDoses: "4 mg initially (loading), then 2 mg after each loose stool; max 16 mg/day (adults); ileostomy output management: titrate to output",
              route: "PO",
              notes: "Acute diarrhoea; ileostomy/colostomy high output management; post-op diarrhoea; peripheral mu-opioid agonist (does NOT cross BBB at therapeutic doses); avoid in infectious diarrhoea until culture",
              sideEffects: "Constipation, abdominal cramping, nausea, bloating; toxic megacolon risk (infectious colitis with bloody/fever diarrhoea — avoid), QTc prolongation (very high/illegal doses)",
              contraindications: "Bloody diarrhoea, high fever (possible infectious colitis — exclude first), pseudomembranous colitis, ileus, bowel obstruction, acute inflammatory bowel disease",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Use with caution in severe hepatic impairment (reduced first-pass; risk of CNS effects at therapeutic doses)",
              monitoring: "Stool frequency and consistency; avoid if diarrhoea is bloody/febrile; ileostomy output volume"),

        .init(name: "Sucralfate (Antepsin)", category: "Mucosal Protective Agent",
              commonDoses: "1 g QDS (1h before meals and at bedtime, on empty stomach) for 4–8 weeks",
              route: "PO",
              notes: "Peptic ulcer treatment (alternative to PPIs); stress ulcer prophylaxis (lower C. diff risk than PPIs in ICU); take on empty stomach (1h before food); binds many drugs — space administration",
              sideEffects: "Constipation (most common), nausea, aluminium accumulation (renal failure — avoid), drug binding (decreases absorption of many drugs if taken simultaneously)",
              contraindications: "Severe renal failure (aluminium toxicity — accumulation); avoid concomitant antacids",
              renalDosing: "Avoid in eGFR <30 (aluminium accumulation — encephalopathy, osteomalacia, anaemia)",
              hepaticDosing: "No dose adjustment needed",
              monitoring: "Aluminium levels in renal impairment; space other drug doses by ≥2h; symptom response"),
    ]

}
