// SurgicalDrug+Formulary2.swift
// Surgical formulary sub-arrays _drugs6–_drugs7 (bone health, cardiovascular, respiratory,
// endocrine, immunosuppressants, antifungals/antiparasitics, and GI agents).

import Foundation

extension SurgicalDrug {

    static let _drugs6: [SurgicalDrug] = [

        // ─── BONE HEALTH / OSTEOPOROSIS ───────────────────────────────────────
        .init(name: "Alendronate (Fosamax)", category: "Bisphosphonate",
              commonDoses: "70 mg once weekly PO (osteoporosis); 10 mg OD (Paget's)",
              route: "PO",
              notes: "Take fasting with full glass of water; remain upright ≥30 min post-dose; dental review before starting",
              sideEffects: "Oesophageal ulceration/oesophagitis, musculoskeletal pain, osteonecrosis of jaw (ONJ), atypical femoral fracture (long-term)",
              contraindications: "Oesophageal stricture/achalasia, inability to sit/stand upright for 30 min, hypocalcaemia, eGFR <35 mL/min",
              renalDosing: "Avoid if eGFR <35 mL/min — risk of renal toxicity and bisphosphonate accumulation",
              hepaticDosing: "No dose adjustment required (not hepatically metabolised)",
              monitoring: "Dental review before starting; correct hypocalcaemia/vitamin D deficiency first; BMD (DEXA) every 1–2 years; renal function before starting"),

        .init(name: "Risedronate (Actonel)", category: "Bisphosphonate",
              commonDoses: "35 mg once weekly PO; 5 mg OD",
              route: "PO",
              notes: "As per alendronate (upright 30 min post-dose, fasting); alternative if GI intolerance to alendronate",
              sideEffects: "Oesophageal/GI irritation (less than alendronate), musculoskeletal pain, ONJ, atypical femoral fracture",
              contraindications: "Oesophageal disorders, inability to remain upright 30 min, hypocalcaemia, eGFR <30 mL/min",
              renalDosing: "Avoid if eGFR <30 mL/min",
              hepaticDosing: "No adjustment needed",
              monitoring: "Dental review; correct vitamin D/calcium deficiency; BMD monitoring; renal function"),

        .init(name: "Zoledronic acid (Aclasta/Zometa)", category: "Bisphosphonate — IV",
              commonDoses: "5 mg IV over ≥15 min once yearly (osteoporosis); 4 mg IV q3–4 weeks (bone mets/hypercalcaemia)",
              route: "IV infusion",
              notes: "Annual IV dosing for osteoporosis (superior adherence); potent; pre-hydrate; fracture prevention in Paget's disease",
              sideEffects: "Acute-phase reaction (flu-like: fever, myalgia — first dose, 24–72h, treat with paracetamol); ONJ; atypical femoral fracture; hypocalcaemia; renal toxicity",
              contraindications: "eGFR <35 mL/min (osteoporosis indication); hypocalcaemia; pregnancy",
              renalDosing: "Avoid if eGFR <35 mL/min for osteoporosis; oncology use requires dose reduction (consult SPC)",
              hepaticDosing: "No hepatic dose adjustment",
              monitoring: "Renal function, calcium/phosphate, FBC before each dose; dental review before starting; calcium + vitamin D supplementation required"),

        .init(name: "Denosumab (Prolia/Xgeva)", category: "RANK-L Inhibitor — Bone",
              commonDoses: "60 mg SC every 6 months (osteoporosis — Prolia); 120 mg SC every 4 weeks (bone mets — Xgeva)",
              route: "SC",
              notes: "No renal dose adjustment needed (unlike bisphosphonates); reversal of bone loss on discontinuation — switch to bisphosphonate before stopping",
              sideEffects: "Hypocalcaemia (risk with renal impairment — supplement calcium/D3), ONJ, atypical femoral fracture, serious infections (cellulitis), back pain, rebound vertebral fractures on discontinuation",
              contraindications: "Hypocalcaemia (correct before starting); pregnancy; known hypersensitivity",
              renalDosing: "No dose adjustment required; however, severe CKD (eGFR <30) has HIGH risk of hypocalcaemia — monitor calcium closely and supplement",
              hepaticDosing: "No hepatic metabolism; no dose adjustment",
              monitoring: "Calcium and vitamin D levels before each injection and after (especially in renal impairment); dental review before starting; BMD at 2 years"),

        .init(name: "Calcium carbonate + D3 (Adcal-D3)", category: "Calcium / Vitamin D Supplement",
              commonDoses: "2 tablets BD (1500 mg calcium carbonate = 600 mg elemental Ca, 400 IU D3)",
              route: "PO (chewable)",
              notes: "Bone health supplementation; co-prescribe with bisphosphonates/denosumab; take with meals (PO absorption); separate from levothyroxine by ≥4h",
              sideEffects: "Constipation, nausea, flatulence, hypercalcaemia in excess; milk-alkali syndrome (high-dose prolonged use)",
              contraindications: "Hypercalcaemia, hypercalciuria (calcium oxalate nephrolithiasis risk), sarcoidosis, vitamin D toxicity",
              renalDosing: "Use with caution in CKD — calcium load may worsen vascular calcification; monitor calcium; activated vitamin D (alfacalcidol) preferred in eGFR <30",
              hepaticDosing: "No hepatic adjustment needed",
              monitoring: "Serum calcium (avoid hypercalcaemia); urine calcium if long-term high-dose"),

        // ─── UTI / LOWER URINARY TRACT ANTIBIOTICS ────────────────────────────
        .init(name: "Nitrofurantoin (Macrobid)", category: "Antibiotic — Urinary",
              commonDoses: "50–100 mg QDS × 7 days (treatment); 50–100 mg nocte (prophylaxis)",
              route: "PO",
              notes: "Lower UTI only (achieves urinary but NOT tissue concentrations — not for pyelonephritis); take with food; urine turns brown",
              sideEffects: "Nausea (take with food), pulmonary reactions (acute pneumonitis or chronic fibrosis — prolonged use), peripheral neuropathy, hepatotoxicity, brown urine discolouration",
              contraindications: "eGFR <45 mL/min (inadequate urinary concentrations, accumulates systemically); G6PD deficiency; neonates <3 months",
              renalDosing: "AVOID if eGFR <45 mL/min — no urinary efficacy and systemic accumulation increases toxicity risk",
              hepaticDosing: "Use with caution in hepatic disease (hepatotoxicity risk); avoid in severe hepatic impairment",
              monitoring: "LFTs and CXR if pulmonary symptoms during long-term use; renal function before prescribing"),

        .init(name: "Trimethoprim", category: "Antibiotic — Urinary",
              commonDoses: "200 mg BD × 7 days (treatment); 100 mg nocte (prophylaxis)",
              route: "PO",
              notes: "Lower UTI; avoid in first trimester (folate antagonist); resistance now ~20–30% in many regions — check local sensitivities",
              sideEffects: "GI upset, rash, hyperkalaemia (blocks tubular potassium secretion — risk with ACE inhibitors/ARBs/potassium-sparing diuretics), raised creatinine (inhibits tubular secretion, not true renal impairment), megaloblastic anaemia (prolonged use)",
              contraindications: "First trimester pregnancy (folate antagonist); concurrent methotrexate; severe renal impairment",
              renalDosing: "eGFR 15–30: use half dose. eGFR <15: avoid. Monitor potassium if combined with ACE inhibitor/ARB",
              hepaticDosing: "No dose adjustment required",
              monitoring: "U&E if on ACE inhibitor/ARB (hyperkalaemia); FBC for prolonged courses"),

        .init(name: "Fosfomycin (Monurol)", category: "Antibiotic — Urinary",
              commonDoses: "3 g oral granules single dose (uncomplicated UTI); 8 g IV TDS (complicated/systemic)",
              route: "PO/IV",
              notes: "Single-dose convenience for uncomplicated UTI in women; active against ESBL-producing E. coli and MRSA (IV use); IV for complicated/resistant UTI",
              sideEffects: "Diarrhoea (oral), nausea, headache; IV: hyponatraemia, hypokalaemia (contains sodium), elevated LFTs",
              contraindications: "Severe renal impairment (oral single-dose: eGFR <10); known hypersensitivity",
              renalDosing: "Oral single dose: avoid if eGFR <10. IV: dose reduction required in CKD — adjust to renal function per SPC",
              hepaticDosing: "No dose adjustment for oral; caution with IV in hepatic impairment (monitor LFTs)",
              monitoring: "No routine monitoring for single oral dose; IV: U&E (sodium, potassium), LFTs, cultures"),

        // ─── ANTISPASMODICS ───────────────────────────────────────────────────
        .init(name: "Hyoscine butylbromide (Buscopan)", category: "Antispasmodic",
              commonDoses: "10–20 mg QDS PO; 20 mg IV/IM (acute spasm)",
              route: "PO/IV/IM",
              notes: "Smooth muscle spasm (IBS, biliary colic, ureteric colic, post-op); does NOT cross BBB (quaternary amine — no CNS sedation); IV onset immediate",
              sideEffects: "Dry mouth, tachycardia, urinary retention, constipation, blurred vision (antimuscarinic); minimal CNS effects (unlike hyoscine hydrobromide)",
              contraindications: "Myasthenia gravis, paralytic ileus, megacolon, narrow-angle glaucoma, tachyarrhythmia, urinary retention (BPH)",
              renalDosing: "No dose adjustment needed",
              hepaticDosing: "No dose adjustment needed",
              monitoring: "HR (IV use can cause tachycardia); symptom response"),

        .init(name: "Mebeverine (Colofac)", category: "Antispasmodic — Direct",
              commonDoses: "135 mg TDS (20 min before meals); 200 mg BD (prolonged-release)",
              route: "PO",
              notes: "IBS abdominal cramping; selective smooth muscle relaxant (no antimuscarinic side effects — useful in elderly, BPH, glaucoma)",
              sideEffects: "Generally very well tolerated; rare: allergic reactions (rash, urticaria, angioedema); no antimuscarinic effects",
              contraindications: "Paralytic ileus; known hypersensitivity",
              renalDosing: "No adjustment required",
              hepaticDosing: "No adjustment required",
              monitoring: "Clinical response — no laboratory monitoring needed"),

        // ─── TOPICAL STEROIDS ─────────────────────────────────────────────────
        .init(name: "Hydrocortisone 1% cream", category: "Topical Corticosteroid — Mild",
              commonDoses: "Apply sparingly BD–QDS; thin layer",
              route: "Topical",
              notes: "Mild potency — safe for face, flexures, infants; eczema, contact/seborrhoeic dermatitis, insect bites; limit to 1–2 weeks on face",
              sideEffects: "Skin atrophy, striae, telangiectasias, perioral dermatitis (prolonged facial use), acneiform eruption, systemic absorption (extensive/occluded sites), adrenal suppression (rare)",
              contraindications: "Infected skin (apply only after treating infection); rosacea; peri-orbital (glaucoma risk); varicella/herpes simplex",
              renalDosing: "Not applicable (topical)",
              hepaticDosing: "Not applicable (topical)",
              monitoring: "Assess for skin atrophy with prolonged use; no lab monitoring for mild potency topicals"),

        .init(name: "Betamethasone valerate 0.1% (Betnovate)", category: "Topical Corticosteroid — Potent",
              commonDoses: "Apply sparingly OD–BD; thin layer; limit duration",
              route: "Topical",
              notes: "Potent topical steroid; eczema (not face), psoriasis, lichen planus; avoid face and flexures; fingertip unit (FTU) for dosing",
              sideEffects: "Skin atrophy, striae, telangiectasias, perioral dermatitis (if used on face), tachyphylaxis, HPA suppression (large surface areas/occlusion), secondary infection",
              contraindications: "Infected skin, rosacea, acne vulgaris, perioral dermatitis, face/flexures (long-term), nappy area in infants",
              renalDosing: "Not applicable (topical)",
              hepaticDosing: "Not applicable (topical)",
              monitoring: "Weigh risks of prolonged use against benefits; no lab monitoring for appropriate topical use"),

        .init(name: "Clobetasol propionate 0.05% (Dermovate)", category: "Topical Corticosteroid — Very Potent",
              commonDoses: "Apply sparingly OD–BD; maximum 2 weeks; maximum 50 g/week",
              route: "Topical",
              notes: "Very potent — reserve for severe/resistant eczema, psoriasis, lichen sclerosus; AVOID on face; max 50 g/week; step down to lower potency as soon as possible",
              sideEffects: "Significant adrenal suppression, skin atrophy, striae (irreversible), Cushing's syndrome (systemic absorption), secondary infection (especially tinea), hypertrichosis",
              contraindications: "Face/flexures/groin, infections, rosacea, widespread plaque psoriasis (rebound risk), neonates",
              renalDosing: "Not applicable",
              hepaticDosing: "Potential increased systemic absorption in severe hepatic impairment — use minimum effective amount",
              monitoring: "Limit to 2-week courses; reassess regularly; children: suppress HPA — minimize use"),

        // ─── ANTICOAGULATION — Additional ─────────────────────────────────────
        .init(name: "Fondaparinux (Arixtra)", category: "Anticoagulant — Factor Xa Inhibitor",
              commonDoses: "2.5 mg SC OD (VTE prophylaxis); 5–10 mg SC OD (treatment, weight-adjusted: <50 kg: 5 mg; 50–100 kg: 7.5 mg; >100 kg: 10 mg)",
              route: "SC",
              notes: "Synthetic pentasaccharide; HIT-safe alternative to heparin (no platelet factor 4 binding); no reversal agent licensed (andexanet alfa off-label); renal excretion",
              sideEffects: "Bleeding (no reversal agent — use PCC or rFVIIa in emergencies), thrombocytopenia (less than heparin — HIT extremely rare), injection-site reactions, elevated LFTs",
              contraindications: "eGFR <20 mL/min (prophylaxis); eGFR <30 mL/min (treatment); body weight <50 kg (prophylaxis); bacterial endocarditis; active bleeding",
              renalDosing: "Prophylaxis: avoid if eGFR <20 mL/min. Treatment: avoid if eGFR <30 mL/min. Half-life markedly prolonged in renal impairment",
              hepaticDosing: "Hepatic impairment: no dose adjustment; however, liver disease may worsen bleeding risk",
              monitoring: "Anti-Xa activity (for treatment doses or extremes of weight/renal function); renal function before starting; platelets (lower HIT risk than UFH/LMWH)"),

        .init(name: "Edoxaban (Lixiana/Savaysa)", category: "Anticoagulant — DOAC (Factor Xa inhibitor)",
              commonDoses: "60 mg OD (AF/VTE treatment); 30 mg OD if weight ≤60 kg, eGFR 15–50, or P-gp inhibitor co-prescribed",
              route: "PO",
              notes: "VTE treatment (after ≥5–10 days parenteral anticoagulation) and secondary prevention; non-valvular AF; dose reduce in low weight/renal impairment/P-gp inhibitors",
              sideEffects: "Bleeding (major/minor), anaemia, rash, elevated LFTs, GI upset; reversal: andexanet alfa (licensed), 4-factor PCC (unlicensed)",
              contraindications: "Mechanical heart valves, haemodynamically significant mitral stenosis, eGFR <15 mL/min, active bleeding, pregnancy/breastfeeding, antiphospholipid syndrome",
              renalDosing: "eGFR 15–50 mL/min: reduce to 30 mg OD. eGFR <15 mL/min: avoid. Renal function at least annually (3–6 monthly if eGFR <60)",
              hepaticDosing: "Moderate–severe hepatic impairment: avoid (altered haemostasis). Mild: use with caution",
              monitoring: "Renal function (annually, or more frequently if borderline); LFTs; signs of bleeding; weight; check for P-gp inhibitors/inducers"),

        // ─── PROKINETICS ──────────────────────────────────────────────────────
        .init(name: "Domperidone (Motilium)", category: "Prokinetic / Antiemetic",
              commonDoses: "10 mg TDS (before meals and at bedtime); maximum 30 mg/day; maximum 1 week",
              route: "PO/PR (suppository)",
              notes: "Gastroparesis; post-op nausea; GORD in infants/elderly; does NOT cross BBB (unlike metoclopramide — no EPS/tardive dyskinesia); cardiac risk at higher doses",
              sideEffects: "QTc prolongation (especially if CYP3A4 inhibitors co-prescribed), gynaecomastia/galactorrhoea (dopamine antagonism on pituitary), dry mouth",
              contraindications: "GI perforation/obstruction, prolactinoma, QTc >470 ms (male) or >450 ms (female), concomitant CYP3A4 inhibitors (ketoconazole, clarithromycin, amiodarone), serious hepatic impairment",
              renalDosing: "Dose reduce in severe renal impairment (eGFR <30); use BD instead of TDS",
              hepaticDosing: "Avoid in moderate–severe hepatic impairment (reduced first-pass — higher plasma levels)",
              monitoring: "ECG if at cardiac risk (QTc); minimum effective dose, maximum 1 week; avoid CYP3A4 inhibitors concurrently"),

        // ─── ONCOLOGY SUPPORTIVE CARE ─────────────────────────────────────────
        .init(name: "Filgrastim (G-CSF, Neupogen/Zarzio)", category: "Colony-Stimulating Factor",
              commonDoses: "5 mcg/kg SC OD (starting 24h after chemotherapy, for up to 14 days); prophylaxis: 5 mcg/kg OD × 5–7 days",
              route: "SC/IV",
              notes: "Prevention/treatment of febrile neutropenia after myelosuppressive chemotherapy; bone marrow failure; stem cell mobilisation; NOT for concurrent chemo",
              sideEffects: "Bone pain (very common — treat with paracetamol, NOT NSAIDs in oncology), splenomegaly/rupture (rare), leucocytosis, thrombocytopenia, allergic reactions, ARDS (rare)",
              contraindications: "Concurrent myelosuppressive chemotherapy or radiotherapy; AML (caution — may stimulate leukaemia growth); hypersensitivity to E. coli-derived proteins",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "No dose adjustment required",
              monitoring: "FBC (WBC, neutrophil count) during therapy — stop when neutrophil count adequate (>2×10⁹/L); spleen size if prolonged use"),

        .init(name: "Granisetron (Kytril)", category: "Antiemetic — 5-HT3 Antagonist",
              commonDoses: "1–2 mg IV before chemotherapy; 1 mg BD PO × 5 days (chemo); 3 mg patch (transdermal, 7-day)",
              route: "PO/IV/transdermal",
              notes: "CINV prevention and treatment; post-op nausea; transdermal patch for prolonged coverage; similar efficacy to ondansetron",
              sideEffects: "Headache, constipation, QTc prolongation, elevated LFTs, dizziness",
              contraindications: "Congenital long QT syndrome; concomitant QT-prolonging drugs with caution; hypersensitivity",
              renalDosing: "No dose adjustment",
              hepaticDosing: "No dose adjustment in mild–moderate; use with caution in severe hepatic impairment",
              monitoring: "ECG if QTc risk; LFTs with prolonged use; electrolytes (hypokalaemia/hypomagnesaemia worsen QTc risk)"),

        // ─── PALLIATIVE CARE ──────────────────────────────────────────────────
        .init(name: "Hyoscine hydrobromide (Kwells/Scopoderm patch)", category: "Anticholinergic — Sedating",
              commonDoses: "200–400 mcg SC/IV (death rattle/secretion control); 1.5 mg patch 72h (motion sickness)",
              route: "SC/IV/transdermal/oral",
              notes: "Palliative care (\"death rattle\" — terminal secretions); motion sickness; centrally-acting (crosses BBB) — sedating. Distinct from hyoscine BUTYLBROMIDE (Buscopan) which does NOT cross BBB",
              sideEffects: "Sedation/drowsiness (useful in palliative context), dry mouth, urinary retention, confusion (elderly), tachycardia, blurred vision, paradoxical agitation (children)",
              contraindications: "Narrow-angle glaucoma, urinary retention (BPH), myasthenia gravis, pyloric stenosis",
              renalDosing: "No formal adjustment; use minimum effective dose in renal impairment",
              hepaticDosing: "Reduce dose in hepatic impairment (prolonged half-life)",
              monitoring: "Symptom control; secretion reduction (palliative use); avoid confusion in elderly"),

        .init(name: "Cyclizine", category: "Antiemetic — H1 Antihistamine / Anticholinergic",
              commonDoses: "50 mg TDS PO/IV/IM; 150 mg/24h CSCI (syringe driver)",
              route: "PO/IV/IM/SC (CSCI)",
              notes: "Nausea/vomiting; palliative care (CSCI); vestibular causes of nausea; motion sickness; post-op N&V; compatible with most syringe-driver drugs",
              sideEffects: "Sedation, dry mouth, urinary retention, tachycardia, blurred vision, constipation; tachycardia may be undesirable in IHD",
              contraindications: "Narrow-angle glaucoma, urinary retention (BPH), severe hepatic failure, porphyria",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Avoid in severe hepatic impairment (porphyria precipitation risk, prolonged sedation)",
              monitoring: "Symptom control; HR if cardiac concerns; check syringe-driver compatibility if CSCI"),

        // ─── DIABETES — Kidney-Safe Options ───────────────────────────────────
        .init(name: "Linagliptin (Trajenta)", category: "Antidiabetic — DPP-4 inhibitor",
              commonDoses: "5 mg OD",
              route: "PO",
              notes: "Unique DPP-4 inhibitor with NO renal dose adjustment required (primarily biliary/GI excretion); T2DM; useful in advanced CKD",
              sideEffects: "Nasopharyngitis, arthralgia (rare), pancreatitis (rare signal), bullous pemphigoid (rare), hypoglycaemia only if combined with insulin/sulphonylurea",
              contraindications: "Type 1 DM, history of pancreatitis (caution — signal not proven), diabetic ketoacidosis",
              renalDosing: "NO dose adjustment required at any level of renal impairment — key advantage over other DPP-4 inhibitors",
              hepaticDosing: "No dose adjustment required",
              monitoring: "HbA1c; signs of pancreatitis; skin changes (bullous pemphigoid — rare)"),

        // ─── ADDITIONAL ANTIBIOTICS ───────────────────────────────────────────
        .init(name: "Ceftazidime", category: "Antibiotic — Cephalosporin (Anti-pseudomonal)",
              commonDoses: "1–2 g TDS IV/IM; 3 g TDS (serious infection/cystic fibrosis)",
              route: "IV/IM",
              notes: "Anti-pseudomonal cephalosporin; HAP, VAP, febrile neutropenia, meningitis; weaker Gram-positive activity than ceftriaxone",
              sideEffects: "Rash, diarrhoea, C. difficile, hypersensitivity, phlebitis, elevated LFTs, transient leucopenia",
              contraindications: "Cephalosporin hypersensitivity; caution in penicillin allergy (cross-reactivity ~1–2%)",
              renalDosing: "eGFR 30–50: 1 g BD. eGFR 15–30: 500 mg BD. eGFR <15: 500 mg OD. Renal impairment increases seizure risk at high doses",
              hepaticDosing: "No dose adjustment required",
              monitoring: "Renal function; levels if prolonged use/renal impairment; culture and sensitivity"),

        .init(name: "Amikacin", category: "Antibiotic — Aminoglycoside",
              commonDoses: "15–20 mg/kg OD IV (actual body weight; extended interval dosing); adjust in renal impairment",
              route: "IV",
              notes: "Gram-negative infections including Pseudomonas, ESBL organisms resistant to gentamicin; broader spectrum than gentamicin; TDM essential",
              sideEffects: "Nephrotoxicity (irreversible — ACR monitoring), irreversible ototoxicity/vestibular toxicity, neuromuscular blockade",
              contraindications: "Pre-existing significant hearing impairment (relative); myasthenia gravis (relative — neuromuscular blockade); concurrent nephrotoxic drugs without careful monitoring",
              renalDosing: "Dose adjustment based on TDM (target trough <5 mg/L and peak 20–30 mg/L); interval extended in renal impairment; TDM is MANDATORY",
              hepaticDosing: "No hepatic dose adjustment (eliminated renally); however, liver disease often coexists with renal impairment — adjust per renal function",
              monitoring: "TDM (peak and trough levels); renal function (daily in ICU); audiology if prolonged use; urinalysis for nephrotoxicity"),

        .init(name: "Piperacillin/tazobactam (Tazocin) Extended Infusion", category: "Antibiotic — Extended Infusion",
              commonDoses: "4.5 g over 4h TDS (extended infusion preferred); 4.5 g QDS standard",
              route: "IV",
              notes: "Extended infusion (EI) optimises pharmacodynamics for time-dependent killing — superior to standard bolus for severe infections and higher MIC organisms; same total daily dose",
              sideEffects: "Same as standard piperacillin/tazobactam; stability limit 12h at room temperature — prepare fresh",
              contraindications: "Penicillin hypersensitivity; SAMBA protocol — check local guidelines for EI use",
              renalDosing: "eGFR 20–40: 4.5 g TDS standard dosing. eGFR <20: 4.5 g BD. Adjust further by TDM if available",
              hepaticDosing: "No hepatic dose adjustment",
              monitoring: "Renal function; electrolytes (contains sodium); clinical response; drug compatibility (give separately from other infusions)"),

        // ─── HAEMOSTASIS / OBSTETRICS ─────────────────────────────────────────
        .init(name: "Oxytocin (Syntocinon)", category: "Uterotonic / Haemostatic",
              commonDoses: "5 units slow IV (active management 3rd stage / PPH); 10 units IM; 10–40 units/L infusion at 10–40 mU/min (augmentation)",
              route: "IV/IM",
              notes: "Uterotonic for PPH prevention/treatment; augmentation of labour; caesarean section; SLOW IV injection — bolus causes hypotension/tachycardia; NOT for induction in women with previous uterine surgery (prefer titrated regimes)",
              sideEffects: "Hypotension/cardiovascular collapse (rapid IV bolus), tachycardia, fluid retention/hyponatraemia (prolonged high-dose — antidiuretic effect), uterine hyperstimulation, fetal distress",
              contraindications: "Hypertonic uterine contractions, foetal distress, cephalopelvic disproportion, placenta praevia; rapid IV bolus contraindicated (give slowly)",
              renalDosing: "No dose adjustment; monitor fluid balance (antidiuretic effect with high doses)",
              hepaticDosing: "No dose adjustment; hepatic metabolism (short half-life ~5 min)",
              monitoring: "Continuous fetal monitoring (CTG) during augmentation; fluid balance (hyponatraemia risk with prolonged use); BP and HR after IV administration"),

        // ─── IRON / ANAEMIA ───────────────────────────────────────────────────
        .init(name: "Ferrous fumarate (Fersamal)", category: "Iron Supplement",
              commonDoses: "210 mg BD–TDS (treatment); 210 mg OD (prophylaxis)",
              route: "PO",
              notes: "Iron deficiency anaemia; better tolerated than ferrous sulfate (less GI irritation); take with vitamin C to enhance absorption; pre-op Hb optimisation",
              sideEffects: "Constipation, nausea, epigastric pain, black stools, diarrhoea; better GI profile than ferrous sulfate in some patients",
              contraindications: "Haemochromatosis, haemosiderosis, repeated blood transfusions, anaemia not due to iron deficiency, concomitant parenteral iron",
              renalDosing: "No dose adjustment; accumulation of iron stores possible in advanced CKD — check iron studies before prescribing",
              hepaticDosing: "Caution in hepatic disease (iron metabolism altered); check iron stores",
              monitoring: "Ferritin and transferrin saturation after 4–6 weeks; Hb response (rise ≥20 g/L in 4 weeks expected); reticulocyte count"),

        // ─── CALCIUM CHANNEL BLOCKER — Additional ─────────────────────────────
        .init(name: "Nifedipine (Adalat)", category: "Calcium Channel Blocker (DHP)",
              commonDoses: "5–10 mg TDS (standard-release); 30–90 mg OD (SR); 10 mg SL/buccal (hypertensive urgency — bite and swallow)",
              route: "PO",
              notes: "Hypertension; angina; Raynaud's; tocolysis (off-label); SR formulation preferred; reflex tachycardia less with SR form",
              sideEffects: "Peripheral oedema (dose-related, common), headache, flushing, reflex tachycardia, gingival hyperplasia (long-term)",
              contraindications: "Cardiogenic shock, haemodynamically significant aortic stenosis, within 1 month of acute MI, unstable angina; avoid short-acting in MI (harmful)",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Reduce dose in hepatic impairment (increased plasma levels — longer dosing interval or lower dose); SR form more predictable",
              monitoring: "BP and HR; ankle oedema; avoid grapefruit juice (CYP3A4 inhibition)"),
    ]

    static let _drugs7: [SurgicalDrug] = [

        // ─── ANTIBIOTICS — Key Additions ──────────────────────────────────────
        .init(name: "Clindamycin", category: "Antibiotic — Lincosamide",
              commonDoses: "150–450 mg QDS PO; 300–900 mg TDS–QDS IV",
              route: "PO/IV/topical",
              notes: "Anaerobic and Gram-positive cover; skin/soft tissue (MRSA community strains); dental infections; bone/joint; C. difficile risk; NOT for CNS infections (poor penetration)",
              sideEffects: "C. difficile colitis (high risk — use minimum necessary duration), GI upset, oesophageal ulceration (take with water upright), rash, hepatotoxicity (rare)",
              contraindications: "Previous clindamycin-associated diarrhoea/colitis; avoid unnecessary prolonged courses (C. diff risk)",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Reduce dose and frequency in severe hepatic impairment (active liver disease — accumulation); monitor LFTs",
              monitoring: "Stool for C. difficile if diarrhoea develops; LFTs with prolonged IV use; local sensitivities"),

        .init(name: "Benzathine penicillin G (Bicillin L-A)", category: "Antibiotic — Long-acting Penicillin",
              commonDoses: "1.2 MU IM single dose (syphilis primary/secondary/latent <1yr); 2.4 MU IM × 3 doses weekly (late latent/tertiary); 1.2 MU IM monthly (rheumatic fever prophylaxis)",
              route: "Deep IM only",
              notes: "Long-acting depot penicillin; syphilis treatment; rheumatic fever secondary prophylaxis (critical in Caribbean); NEVER IV (cardiac arrest); deep gluteal IM only",
              sideEffects: "Injection-site pain (very common), Jarisch-Herxheimer reaction (syphilis — fever/chills 2–8h post first dose), anaphylaxis",
              contraindications: "Penicillin allergy (anaphylaxis); NEVER administer IV — fatal; not for neurosyphilis (use IV penicillin G)",
              renalDosing: "No dose adjustment for standard dosing; caution in severe renal failure with very high doses",
              hepaticDosing: "No dose adjustment",
              monitoring: "VDRL/RPR titres at 3, 6, 12 months (syphilis); Jarisch-Herxheimer reaction — pre-warn patient; observe 30 min post injection (anaphylaxis)"),

        .init(name: "Cefepime", category: "Antibiotic — Cephalosporin (4th generation)",
              commonDoses: "1–2 g BD–TDS IV; 2 g TDS (febrile neutropenia/meningitis/Pseudomonas)",
              route: "IV/IM",
              notes: "Broad-spectrum including Pseudomonas and ESBL (partial); febrile neutropenia; HAP/VAP; meningitis; overcomes many AmpC-mediated resistances",
              sideEffects: "Neurotoxicity (encephalopathy, seizures — especially in renal impairment; risk higher than other cephalosporins), rash, C. difficile, elevated LFTs",
              contraindications: "Cephalosporin hypersensitivity; use with extreme caution in seizure history/renal impairment (neurotoxicity)",
              renalDosing: "eGFR 30–60: 1–2 g BD. eGFR 11–29: 1–2 g OD. eGFR <11: 500 mg–1 g OD. Neurotoxicity risk increases with renal impairment — reduce dose",
              hepaticDosing: "No dose adjustment",
              monitoring: "Renal function (neurotoxicity risk proportional to exposure); neuro status in ICU; cultures and sensitivities"),

        .init(name: "Aztreonam", category: "Antibiotic — Monobactam",
              commonDoses: "1–2 g TDS–QDS IV/IM; 500 mg TDS–QDS (urinary tract)",
              route: "IV/IM",
              notes: "Gram-negative aerobic coverage only (like gentamicin without renal toxicity); safe in penicillin/cephalosporin allergy; no anaerobic or Gram-positive activity — combine accordingly",
              sideEffects: "GI upset, elevated LFTs, rash (cross-reactivity with ceftazidime — caution), phlebitis (IV), C. difficile (rare)",
              contraindications: "Aztreonam hypersensitivity; caution if ceftazidime allergy (some cross-reactivity due to identical R1 side chain)",
              renalDosing: "eGFR 10–30: 50% dose. eGFR <10: 25% dose or 500 mg after loading dose",
              hepaticDosing: "No dose adjustment in mild–moderate; use with caution in severe hepatic impairment",
              monitoring: "Renal function; LFTs with prolonged use; culture and sensitivity"),

        .init(name: "Ceftolozane/tazobactam (Zerbaxa)", category: "Antibiotic — Reserve Cephalosporin",
              commonDoses: "1.5 g TDS IV (over 1h); 3 g TDS (HAP/VAP)",
              route: "IV",
              notes: "Reserve antibiotic for MDR Pseudomonas aeruginosa (including those resistant to carbapenems); complicated intra-abdominal infections (with metronidazole); HAP/VAP",
              sideEffects: "GI upset, elevated LFTs, headache, hypokalaemia, fever, C. difficile",
              contraindications: "Cephalosporin hypersensitivity; only use for confirmed/suspected MDR Gram-negative infections — antimicrobial stewardship",
              renalDosing: "eGFR 30–50: 750 mg TDS. eGFR 15–29: 375 mg TDS. CRRT: specialist guidance required",
              hepaticDosing: "No hepatic dose adjustment",
              monitoring: "Culture and sensitivity (resistance confirmation before use); renal function; LFTs; antimicrobial stewardship review"),

        // ─── ANALGESICS — Additional ──────────────────────────────────────────
        .init(name: "Hydromorphone (Dilaudid)", category: "Opioid Analgesic",
              commonDoses: "1–4 mg PO q4–6h; 0.2–1 mg IV/SC q4–6h",
              route: "PO/IV/SC",
              notes: "5–7× more potent than morphine; useful when morphine poorly tolerated (less histamine release, less nausea in some patients); renally eliminated — accumulates in renal failure",
              sideEffects: "Respiratory depression, sedation, constipation, nausea, pruritus (less than morphine), confusion/myoclonus in renal failure (metabolite accumulation)",
              contraindications: "Opioid-naive patients without appropriate monitoring; severe respiratory depression; avoid in renal failure (active metabolite accumulation)",
              renalDosing: "Avoid or use extreme caution in eGFR <30 — hydromorphone-3-glucuronide accumulates and causes neuroexcitatory effects (myoclonus, seizures). Fentanyl preferred in renal failure",
              hepaticDosing: "Reduce initial dose in hepatic impairment (reduced first-pass/clearance); titrate carefully",
              monitoring: "Pain scores; sedation scale; respiratory rate; renal function if prolonged use"),

        .init(name: "Tapentadol (Palexia)", category: "Opioid Analgesic / NRI",
              commonDoses: "50–250 mg BD (SR); 50–100 mg q4–6h (IR); max 500 mg/day",
              route: "PO",
              notes: "Dual mechanism: mu-opioid agonist + noradrenaline reuptake inhibitor; less constipation and nausea than equianalgesic oxycodone; neuropathic and nociceptive pain",
              sideEffects: "Nausea, dizziness, constipation (less than oxycodone), somnolence, headache, serotonin syndrome risk (with SSRIs/SNRIs/MAOIs — less than tramadol)",
              contraindications: "MAO inhibitors (within 14 days), seizure disorder (relative), severe respiratory depression, severe hepatic/renal impairment (IR: eGFR <30)",
              renalDosing: "IR formulation: avoid if eGFR <30. SR: use with caution; dose reduce",
              hepaticDosing: "Severe hepatic impairment (Child-Pugh C): avoid IR; SR max 50 mg TDS",
              monitoring: "Pain scores; respiratory function; avoid concomitant serotonergic drugs"),

        // ─── INSULIN — Long-acting / Basal ────────────────────────────────────
        .init(name: "Insulin glargine (Lantus/Toujeo)", category: "Insulin — Long-acting Basal",
              commonDoses: "Individualised SC; typically 0.2–0.4 units/kg OD at same time each day; titrate by 2 units every 3 days to fasting target",
              route: "SC only",
              notes: "Peakless 24h basal insulin; once-daily injection; do NOT mix with other insulins in syringe; Toujeo (300 units/mL) ≠ Lantus (100 units/mL) — not interchangeable",
              sideEffects: "Hypoglycaemia (nocturnal less common than NPH), lipodystrophy at injection sites, weight gain, injection-site reactions, local allergy",
              contraindications: "Hypoglycaemia episode; never given IV (concentration/acidity — fatal); do not mix with other insulins",
              renalDosing: "Reduce dose in renal impairment (reduced insulin clearance increases hypoglycaemia risk); frequent glucose monitoring required",
              hepaticDosing: "Reduce dose in hepatic impairment (reduced gluconeogenesis + insulin degradation altered); titrate carefully",
              monitoring: "Fasting glucose (target 4–7 mmol/L); HbA1c; hypoglycaemic episodes; injection-site rotation; annual eye/foot/renal review"),

        .init(name: "Insulin detemir (Levemir)", category: "Insulin — Long-acting Basal",
              commonDoses: "Individualised SC; typically OD or BD; start 0.1–0.2 units/kg OD; adjust every 3 days",
              route: "SC only",
              notes: "Long-acting basal insulin (18–24h); weight-neutral advantage over glargine/NPH; predictable absorption (albumin binding reduces variability); BD dosing possible",
              sideEffects: "Hypoglycaemia, lipodystrophy, weight gain (less than glargine/NPH), injection-site reactions",
              contraindications: "Never IV; do not mix with other insulins",
              renalDosing: "Dose reduce in renal impairment; monitor closely (hypoglycaemia risk)",
              hepaticDosing: "Reduce dose; careful titration in hepatic impairment",
              monitoring: "Fasting/pre-dose glucose; HbA1c every 3 months; hypoglycaemia frequency"),

        .init(name: "Insulin degludec (Tresiba)", category: "Insulin — Ultra-long-acting Basal",
              commonDoses: "Individualised SC; typically OD at any time (consistent); titrate to fasting glucose target",
              route: "SC only",
              notes: "Ultra-long-acting (>42h half-life); very flat profile; lowest hypoglycaemia risk of all basal insulins; dose can be changed by ≥8h if needed; available 100 and 200 units/mL",
              sideEffects: "Hypoglycaemia (lowest rate of all basal insulins), weight gain, injection-site reactions, lipodystrophy",
              contraindications: "Never IV; do not mix with other insulins; 200 units/mL pen max 160 units/dose",
              renalDosing: "Reduce dose in renal impairment; less affected by renal clearance than older insulins but still monitor",
              hepaticDosing: "Reduce dose; monitor glucose closely",
              monitoring: "Fasting glucose; HbA1c; hypoglycaemia diary — often used to convert patients from NPH with hypoglycaemia problems"),

        .init(name: "Insulin regular (Actrapid/Humulin R)", category: "Insulin — Short-acting",
              commonDoses: "SC: 4–20 units 30 min before meals (patient-specific); IV infusion: 0.05–0.1 units/kg/h (DKA/perioperative); variable rate IV (VRIII/sliding scale)",
              route: "SC/IV",
              notes: "Only insulin that can be used IV (DKA, hyperkalaemia, peri-op); inject SC 30 min before meals (slower onset than rapid-acting); available for VRIII sliding scales",
              sideEffects: "Hypoglycaemia, weight gain, hypokalaemia (IV use — especially DKA protocol), lipodystrophy",
              contraindications: "Active hypoglycaemia; always use with dextrose for IV hyperkalaemia management",
              renalDosing: "Reduce dose; renal impairment prolongs insulin action (reduced renal clearance + insulin sensitivity changes)",
              hepaticDosing: "Reduce dose; hepatic impairment increases hypoglycaemia risk (reduced gluconeogenesis)",
              monitoring: "Glucose hourly during IV infusion; potassium in DKA protocol (replacement essential); fluid balance"),

        // ─── ANTI-MALARIALS ────────────────────────────────────────────────────
        .init(name: "Artemether/lumefantrine (Riamet/Coartem)", category: "Antimalarial — ACT",
              commonDoses: "4 tablets (80/480 mg) at 0, 8, 24, 36, 48, 60 h (adult >35 kg); always take with fat-containing food/milk",
              route: "PO",
              notes: "First-line treatment for uncomplicated Plasmodium falciparum malaria; artemisinin combination therapy (ACT); MUST take with food (poor absorption when fasted); complete 6-dose course",
              sideEffects: "Headache, dizziness, sleep disturbance, arthralgia/myalgia, palpitations, QTc prolongation, anorexia, nausea; generally well tolerated",
              contraindications: "Severe malaria (use IV artesunate), first trimester of pregnancy (teratogenicity — use quinine+doxycycline), QTc >500 ms, concomitant QT-prolonging drugs, mefloquine within 12h",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Use with caution in severe hepatic impairment; no formal dose recommendation",
              monitoring: "Repeat blood film at day 3, 7, 28 to confirm clearance; ECG if cardiac risk (QTc); glucose in children (hypoglycaemia risk)"),

        .init(name: "Artesunate IV (Malacef)", category: "Antimalarial — Artesunate IV",
              commonDoses: "2.4 mg/kg IV at 0, 12, 24h then OD until PO possible (minimum 3 days); then switch to ACT oral",
              route: "IV",
              notes: "Treatment of severe/complicated malaria (P. falciparum); superior to IV quinine (AQUAMAT/SEAQUAMAT trials); always follow with 3-day oral ACT on recovery",
              sideEffects: "Post-artesunate delayed haemolysis (PADH — occurs 2–4 weeks post treatment, especially in hyperparasitaemia; monitor Hb); hepatotoxicity, neurotoxicity (rare at therapeutic doses)",
              contraindications: "Not for uncomplicated malaria; hypersensitivity to artemisinins",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "No dose adjustment; monitor LFTs",
              monitoring: "Blood film for parasitaemia daily until negative; Hb at day 7, 14, 28 (PADH); renal function; blood glucose; LFTs"),

        .init(name: "Chloroquine phosphate", category: "Antimalarial / DMARD",
              commonDoses: "Treatment: 600 mg base loading, then 300 mg at 6h, then 300 mg OD × 2 days; Prophylaxis: 300 mg weekly (start 1 week before travel, 4 weeks after); SLE/RA: 150–300 mg OD",
              route: "PO",
              notes: "Prophylaxis where sensitive (now limited areas); SLE; RA; amoebic liver abscess; NOT for P. falciparum in most regions (widespread resistance). Caribbean: P. vivax/P. malariae still sensitive",
              sideEffects: "GI upset, headache, pruritus (common in Black African patients), retinal toxicity (cumulative dose — annual ophthalmology screen), cardiomyopathy (rare, high dose), QTc prolongation",
              contraindications: "Retinal disease/macular degeneration, G6PD deficiency (haemolysis), porphyria, pre-existing cardiac conduction defects",
              renalDosing: "eGFR <10: reduce dose (accumulation); avoid if severe renal failure",
              hepaticDosing: "Caution in hepatic impairment (hepatotoxicity risk, reduced clearance)",
              monitoring: "Baseline ophthalmology + annual review (retinal toxicity); G6PD screen in at-risk populations; ECG if cardiac risk; LFTs"),

        .init(name: "Atovaquone/proguanil (Malarone)", category: "Antimalarial — Prophylaxis/Treatment",
              commonDoses: "Prophylaxis: 1 adult tablet (250/100 mg) OD starting 1–2 days before travel, continue 7 days after. Treatment: 4 tablets OD × 3 days",
              route: "PO",
              notes: "Preferred prophylaxis for short trips to endemic areas (short pre/post travel dosing); treatment of uncomplicated falciparum malaria; take with food/milk",
              sideEffects: "GI upset (nausea, vomiting, abdominal pain), headache, dizziness, mouth ulcers, elevated LFTs; generally well tolerated",
              contraindications: "eGFR <30 mL/min (treatment); eGFR <30 (prophylaxis — use doxycycline or chloroquine if sensitive); pregnancy (limited data — avoid unless benefit outweighs risk); severe hepatic impairment",
              renalDosing: "Treatment: avoid if eGFR <30 (proguanil accumulates). Prophylaxis: avoid if eGFR <30",
              hepaticDosing: "Caution in severe hepatic impairment (proguanil conversion to active metabolite reduced)",
              monitoring: "LFTs; renal function before prescribing; adherence counselling (must take with food for absorption)"),

        .init(name: "Quinine sulfate", category: "Antimalarial",
              commonDoses: "Treatment: 600 mg TDS × 5–7 days (+ doxycycline 7 days); IV quinine: 20 mg/kg loading over 4h then 10 mg/kg q8h (HDU/ICU); Cramps: 200–300 mg nocte",
              route: "PO/IV",
              notes: "Oral: second-line uncomplicated malaria; IV: second-line severe malaria (if artesunate unavailable); leg cramps (unlicensed, last resort); narrow therapeutic index; cardiac monitoring required IV",
              sideEffects: "Cinchonism (tinnitus, dizziness, nausea, visual disturbances, headache), QTc prolongation, hypoglycaemia (stimulates insulin), thrombocytopenia, haemolysis (G6PD), tinnitus",
              contraindications: "Haemoglobinuria (blackwater fever), optic neuritis, tinnitus, G6PD deficiency (relative), haemolytic anaemia",
              renalDosing: "Reduce IV maintenance dose (by 1/3) in renal failure; accumulation of metabolites",
              hepaticDosing: "Reduce dose in hepatic impairment (prolonged half-life)",
              monitoring: "Continuous cardiac monitoring (QTc) during IV infusion; blood glucose every 4–6h (hypoglycaemia risk); blood film; blood quinine levels if available"),

        .init(name: "Primaquine", category: "Antimalarial — Anti-hypnozoite",
              commonDoses: "P. vivax/ovale radical cure: 15 mg base OD × 14 days; Pneumocystis: 30 mg OD with clindamycin",
              route: "PO",
              notes: "Eradicates dormant liver stages (hypnozoites) of P. vivax and P. ovale — prevents relapse; G6PD TESTING MANDATORY before prescribing (life-threatening haemolysis)",
              sideEffects: "Haemolytic anaemia (severe/life-threatening in G6PD deficiency), methaemoglobinaemia, GI upset, abdominal pain",
              contraindications: "G6PD deficiency (ABSOLUTE — test first), pregnancy, breastfeeding (unless infant G6PD normal), rheumatoid arthritis/SLE",
              renalDosing: "No formal dose adjustment, but avoid in severe renal impairment",
              hepaticDosing: "Avoid in active hepatic disease",
              monitoring: "G6PD level BEFORE starting — mandatory; FBC (Hb, haematocrit) weekly during treatment; methaemoglobin if cyanosis"),

        // ─── GI — Additional ──────────────────────────────────────────────────
        .init(name: "Famotidine (Pepcid)", category: "H2-receptor Antagonist",
              commonDoses: "20–40 mg BD (active ulcer); 20 mg OD (maintenance/prophylaxis); 20 mg IV BD (inpatient acid suppression when PO not possible)",
              route: "PO/IV",
              notes: "Peptic ulcer; GORD; alternative to PPI (fewer drug interactions); useful when PPI causes side effects; less cimetidine-type drug interactions than ranitidine",
              sideEffects: "Headache, dizziness, constipation/diarrhoea, elevated LFTs (rare), QTc prolongation (IV high-dose), thrombocytopenia (rare)",
              contraindications: "Hypersensitivity to H2 blockers; caution in QTc prolongation (IV); phenylketonuria (some formulations contain phenylalanine)",
              renalDosing: "eGFR <50: 50% dose reduction or double interval (accumulation); eGFR <30: 50% dose, 36–48h intervals",
              hepaticDosing: "No dose adjustment in hepatic impairment",
              monitoring: "Renal function before dosing in renal impairment; symptom response; ECG if IV in at-risk patients"),

        .init(name: "Pancreatin (Creon)", category: "Pancreatic Enzyme Supplement",
              commonDoses: "Creon 10,000–25,000 units lipase with each main meal; 5,000–10,000 with snacks; titrate to symptoms",
              route: "PO",
              notes: "Exocrine pancreatic insufficiency (chronic pancreatitis, pancreatic cancer, post-pancreatectomy, cystic fibrosis); swallow whole or open capsule and mix with food; do NOT crush (inactivated by acid)",
              sideEffects: "GI discomfort, nausea, constipation/diarrhoea (dose-dependent), fibrosing colonopathy (very high doses in CF), hyperuricaemia (high doses), perioral soreness (if powder contacts mucosa)",
              contraindications: "Acute pancreatitis; known porcine allergy; early stages of acute pancreatitis",
              renalDosing: "No renal dose adjustment needed",
              hepaticDosing: "No hepatic dose adjustment",
              monitoring: "Stool frequency and consistency; weight; nutritional status; fat-soluble vitamins (A, D, E, K) in chronic use; consider fibrosing colonopathy if doses >10,000 units/kg/day in CF"),

        .init(name: "Loperamide (Imodium)", category: "Antidiarrhoeal",
              commonDoses: "4 mg initially (loading), then 2 mg after each loose stool; max 16 mg/day (adults); ileostomy output management: titrate to output",
              route: "PO",
              notes: "Acute diarrhoea; ileostomy/colostomy high output management; post-op diarrhoea; peripheral mu-opioid agonist (does NOT cross BBB at therapeutic doses); avoid in infectious diarrhoea until culture",
              sideEffects: "Constipation, abdominal cramping, nausea, bloating; toxic megacolon risk (infectious colitis with bloody/fever diarrhoea — avoid), QTc prolongation (very high/illegal doses)",
              contraindications: "Bloody diarrhoea, high fever (possible infectious colitis — exclude first), pseudomembranous colitis, ileus, bowel obstruction, acute inflammatory bowel disease",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Use with caution in severe hepatic impairment (reduced first-pass; risk of CNS effects at therapeutic doses)",
              monitoring: "Stool frequency and consistency; avoid if diarrhoea is bloody/febrile; ileostomy output volume"),

        .init(name: "Sucralfate (Antepsin)", category: "Mucosal Protective Agent",
              commonDoses: "1 g QDS (1h before meals and at bedtime, on empty stomach) for 4–8 weeks",
              route: "PO",
              notes: "Peptic ulcer treatment (alternative to PPIs); stress ulcer prophylaxis (lower C. diff risk than PPIs in ICU); take on empty stomach (1h before food); binds many drugs — space administration",
              sideEffects: "Constipation (most common), nausea, aluminium accumulation (renal failure — avoid), drug binding (decreases absorption of many drugs if taken simultaneously)",
              contraindications: "Severe renal failure (aluminium toxicity — accumulation); avoid concomitant antacids",
              renalDosing: "Avoid in eGFR <30 (aluminium accumulation — encephalopathy, osteomalacia, anaemia)",
              hepaticDosing: "No dose adjustment needed",
              monitoring: "Aluminium levels in renal impairment; space other drug doses by ≥2h; symptom response"),
    ]

}
