// SurgicalDrug+Formulary3.swift
// Surgical formulary sub-arrays _drugs8–_drugs9 (immunosuppressants — biologics,
// targeted therapies, oncology supportive, antiemetics, and miscellaneous).

import Foundation

extension SurgicalDrug {

    static let _drugs8: [SurgicalDrug] = [

        // ─── LUPUS / SYSTEMIC AUTOIMMUNE ──────────────────────────────────────
        .init(name: "Belimumab (Benlysta)", category: "Immunosuppressant — Anti-BLyS (Biologic)",
              commonDoses: "10 mg/kg IV over 1h at 0, 2, 4 weeks then monthly; 200 mg SC weekly",
              route: "IV infusion / SC",
              notes: "Systemic lupus erythematosus (SLE) with active disease despite standard therapy; do not use in severe active lupus nephritis or CNS lupus; screen for TB, hepatitis B before starting",
              sideEffects: "Infusion/injection-site reactions, serious infections, depression/suicidal ideation (monitor), nausea, diarrhoea, hypersensitivity reactions, progressive multifocal leukoencephalopathy (PML — rare)",
              contraindications: "Active or prior history of PML, severe active lupus nephritis or CNS lupus (excluded from trials), active serious infection, live vaccines within 30 days",
              renalDosing: "No dose adjustment recommended (limited data in severe renal impairment)",
              hepaticDosing: "No dose adjustment (not hepatically cleared)",
              monitoring: "Disease activity scores (SLEDAI); full blood count; renal function; complement (C3, C4, dsDNA) every 3–6 months; depression screening; TB screening before starting"),

        .init(name: "Cyclophosphamide (Cytoxan/Endoxan)", category: "Immunosuppressant / Alkylating Agent",
              commonDoses: "IV pulse: 500–1000 mg/m² every 4 weeks (lupus nephritis — Euro-Lupus: 500 mg fortnightly × 6 doses); PO: 1–2 mg/kg/day",
              route: "IV/PO",
              notes: "Lupus nephritis (induction); vasculitis; oncology; always use MESNA for haemorrhagic cystitis prophylaxis (IV doses); adequate hydration essential; teratogen — contraception mandatory",
              sideEffects: "Haemorrhagic cystitis (MESNA prevents — mandatory with IV doses), myelosuppression, nausea/vomiting (use 5-HT3 antiemetic), alopecia, infertility (consider egg/sperm banking), bladder cancer (long-term), immunosuppression, SIADH",
              contraindications: "Pregnancy (teratogen), breastfeeding, active infections, severe myelosuppression, haemorrhagic cystitis, severe renal/hepatic impairment",
              renalDosing: "eGFR 10–50: 75% dose. eGFR <10: 50% dose; avoid if possible",
              hepaticDosing: "Reduce dose in hepatic impairment (prodrug — requires hepatic conversion to active metabolite)",
              monitoring: "FBC and U&E before each pulse; urinalysis (haematuria); LFTs; pregnancy test before treatment; urine cytology annually (bladder cancer); fertility counselling"),

        .init(name: "Rituximab (MabThera/Rituxan)", category: "Immunosuppressant — Anti-CD20 (Biologic)",
              commonDoses: "SLE/vasculitis: 375 mg/m² weekly × 4 or 1 g × 2 (2 weeks apart); lymphoma: 375 mg/m² OD × 4–8 cycles",
              route: "IV infusion",
              notes: "Refractory SLE/lupus nephritis; ANCA vasculitis (licensed); RA; B-cell lymphoma; always pre-medicate with paracetamol + antihistamine + methylprednisolone; screen for hepatitis B/TB before starting",
              sideEffects: "Infusion reactions (first infusion — pre-medicate), progressive multifocal leukoencephalopathy (PML — rare), serious infections, hypogammaglobulinaemia, hepatitis B reactivation, tumour lysis syndrome (lymphoma)",
              contraindications: "Active severe infection; hepatitis B surface antigen positivity without prophylaxis; live vaccines within 4 weeks; pregnancy (avoid)",
              renalDosing: "No dose adjustment; monitor for tumour lysis syndrome in haematological disease",
              hepaticDosing: "No formal dose adjustment; monitor for hepatitis B reactivation (prophylax if coreAb positive)",
              monitoring: "FBC and immunoglobulins; hepatitis B serology before treatment; PML screening (JC virus antibodies); infection screening; CD19/CD20 B cell counts"),

        // ─── DERMATOLOGY / SKIN ───────────────────────────────────────────────
        .init(name: "Isotretinoin (Roaccutane/Accutane)", category: "Retinoid — Systemic",
              commonDoses: "0.5–1 mg/kg/day PO in 1–2 divided doses; cumulative dose 120–150 mg/kg total course",
              route: "PO",
              notes: "Severe nodulocystic/scarring acne; teratogen — mandatory pregnancy prevention programme (iPLEDGE/pregnancy test monthly); with food (fat-enhanced absorption); course typically 4–6 months",
              sideEffects: "Teratogenicity (Category X — mandatory contraception), cheilitis/dry lips (very common — use emollient), dry skin, photosensitivity, elevated triglycerides/LFTs, mood changes/depression (monitor), myalgia, night blindness, pseudotumour cerebri (with tetracyclines)",
              contraindications: "Pregnancy (Category X — ABSOLUTE), breastfeeding, concurrent tetracyclines (pseudotumour cerebri), liver disease, hyperlipidaemia",
              renalDosing: "Use with caution; no formal renal dose adjustment",
              hepaticDosing: "Contraindicated in significant hepatic impairment; avoid if LFTs >3× upper limit normal",
              monitoring: "Pregnancy test monthly (female); LFTs and fasting lipids at baseline, 6–8 weeks, then 3-monthly; mood assessment; ophthalmic review if night blindness"),

        .init(name: "Permethrin 5% cream (Lyclear)", category: "Antiparasitic — Topical",
              commonDoses: "Scabies: apply from neck down, leave 8–12h, wash off; repeat after 1 week. Head lice: apply to scalp 10 min, rinse",
              route: "Topical",
              notes: "Scabies (first-line); head lice; crusted/Norwegian scabies requires systemic ivermectin in addition; treat all household contacts simultaneously; wash/bag all clothing/bedding",
              sideEffects: "Local burning/stinging/pruritus on application (common — not allergy), temporary worsening of itch (post-scabicide reaction lasts 2–4 weeks — do not re-treat immediately), rarely contact dermatitis",
              contraindications: "Hypersensitivity to pyrethrins/chrysanthemums; avoid mucosal surfaces and eyes",
              renalDosing: "Not applicable (topical; negligible systemic absorption)",
              hepaticDosing: "Not applicable (topical)",
              monitoring: "Clinical resolution at 4 weeks (itch may persist 4 weeks after successful treatment — do not retreat unless new lesions); treat all contacts"),

        .init(name: "Ivermectin (Stromectol)", category: "Antiparasitic — Systemic",
              commonDoses: "Scabies: 200 mcg/kg PO single dose, repeat in 2 weeks; Crusted scabies: multiple doses (specialist guidance); Strongyloides: 200 mcg/kg OD × 2 days",
              route: "PO",
              notes: "Crusted/Norwegian scabies (systemic required alongside topical); strongyloidiasis; filariasis; Caribbean-relevant (filariasis, strongyloides endemic); take fasting",
              sideEffects: "Mazzotti reaction (fever, rash, pruritus, oedema — from dying microfilariae, especially filariasis treatment), dizziness, headache, GI upset, transient visual disturbances",
              contraindications: "Pregnancy (teratogen — use permethrin topically); CNS conditions (blood-brain barrier disruption — drugs increasing BBB permeability); children <15 kg",
              renalDosing: "No dose adjustment required",
              hepaticDosing: "Use with caution in severe hepatic impairment",
              monitoring: "Clinical resolution; microfilaria counts (filariasis); Mazzotti reaction monitoring; repeat stool examination (strongyloides)"),

        .init(name: "Tacrolimus 0.1% ointment (Protopic)", category: "Topical Immunomodulator",
              commonDoses: "Apply BD to affected skin until clear; use minimum effective amount; reduce to OD or PRN as symptoms improve",
              route: "Topical",
              notes: "Atopic dermatitis (moderate–severe, adults; steroid-sparing); face/flexures where topical steroids cause atrophy; does NOT cause skin atrophy (unlike steroids); FDA black-box: theoretical malignancy risk (not confirmed in humans)",
              sideEffects: "Burning/stinging/pruritus on application (common, improves after first few days), increased risk of infections (local), photosensitivity; theoretical lymphoma risk (Black Box Warning — not confirmed in humans at recommended doses)",
              contraindications: "Active skin infections (bacterial/viral/fungal — treat first), immunocompromised patients (relative), active malignancy at site, Netherton syndrome",
              renalDosing: "Not applicable (topical; minimal systemic absorption)",
              hepaticDosing: "Not applicable (topical; caution in severe hepatic impairment — increased systemic exposure)",
              monitoring: "Skin response; use minimum effective dose; sun protection (photosensitivity); review every 3–6 months; reassess if not responding at 6 weeks"),

        .init(name: "Terbinafine (Lamisil)", category: "Antifungal — Allylamine",
              commonDoses: "Onychomycosis: 250 mg OD × 6 weeks (fingernails), 12 weeks (toenails); Tinea: 250 mg OD × 2–6 weeks PO; Cream/gel: apply OD–BD × 1–2 weeks",
              route: "PO/topical",
              notes: "Dermatophyte fungal infections (tinea pedis/corporis/capitis/unguium); NOT effective against Candida; hepatotoxicity risk with systemic — liver function test recommended",
              sideEffects: "GI upset, headache, rash, taste/smell disturbance (may be prolonged or permanent — WARN patient), hepatotoxicity (rare but serious), bone marrow suppression (rare)",
              contraindications: "Active hepatic disease, taste/smell disorders (worsens), avoid in hepatic/renal impairment without monitoring",
              renalDosing: "eGFR <50: 50% dose (PO); avoid if severe renal impairment",
              hepaticDosing: "Avoid in chronic or active hepatic disease — hepatotoxicity risk; no dose adjustment if using topical form",
              monitoring: "LFTs before starting (PO systemic courses); repeat at 6 weeks if prolonged course; taste/smell — warn before prescribing; culture/sensitivity before starting"),

        .init(name: "Clotrimazole 1% cream/pessary (Canesten)", category: "Antifungal — Topical Azole",
              commonDoses: "Skin: apply BD–TDS × 2–4 weeks. Vaginal: 500 mg pessary single dose or 200 mg × 3 days; 1% cream intravaginally × 6 nights",
              route: "Topical/intravaginal",
              notes: "Superficial dermatophyte and candidal infections; vaginal candidiasis (thrush); oral candidiasis (lozenges — Canesten Oral); safe in pregnancy (topical/vaginal)",
              sideEffects: "Local burning/stinging/erythema (mild); contact dermatitis (rare); systemic absorption negligible",
              contraindications: "Hypersensitivity to imidazoles; avoid eyes; vaginal pessaries may damage condoms/diaphragms",
              renalDosing: "Not applicable (topical)",
              hepaticDosing: "Not applicable (topical)",
              monitoring: "Clinical response at 2 weeks; consider oral fluconazole for recurrent vaginal candidiasis; diabetes screening if recurrent"),

        // ─── EYE MEDICATIONS ─────────────────────────────────────────────────
        .init(name: "Chloramphenicol eye drops 0.5%", category: "Ophthalmic Antibiotic",
              commonDoses: "1 drop every 2h (acute infection — reduce to QDS once improving); ointment 1% apply at night × 5 days",
              route: "Ophthalmic (topical)",
              notes: "Bacterial conjunctivitis (first-line OTC/primary care); blepharitis; broad-spectrum including Staphylococci, H. influenzae; systemic absorption minimal but aplastic anaemia reported (idiosyncratic — extremely rare)",
              sideEffects: "Local stinging/burning on instillation, hypersensitivity reactions; aplastic anaemia (extremely rare — reported with topical eye drops, mechanism unclear)",
              contraindications: "Known hypersensitivity; contact lens wearers (remove lenses before instillation — reinsert 15 min later); avoid in pregnancy (1st trimester)",
              renalDosing: "Not applicable (ophthalmic topical)",
              hepaticDosing: "Not applicable (ophthalmic topical)",
              monitoring: "Clinical response in 48h; no improvement → culture and sensitivity; contact lens advice"),

        .init(name: "Fusidic acid 1% eye drops (Fucithalmic)", category: "Ophthalmic Antibiotic",
              commonDoses: "1 drop BD (viscous gel vehicle — prolongs contact time) × 7 days",
              route: "Ophthalmic (topical)",
              notes: "Bacterial conjunctivitis (especially staphylococcal); BD dosing advantage (viscous gel); less broad-spectrum than chloramphenicol but targeted for Gram-positive organisms",
              sideEffects: "Transient blurred vision after instillation (gel vehicle — temporary), local stinging/burning, hypersensitivity (rare)",
              contraindications: "Hypersensitivity to fusidic acid; contact lens wearers (remove before instillation)",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "Clinical response; blurred vision is expected transiently after instillation (advise patient)"),

        .init(name: "Latanoprost 0.005% eye drops (Xalatan)", category: "Ophthalmic — Prostaglandin Analogue",
              commonDoses: "1 drop OD in affected eye(s), preferably in the evening",
              route: "Ophthalmic (topical)",
              notes: "Open-angle glaucoma; ocular hypertension (first-line); increases uveoscleral outflow; irreversible iris pigmentation change — warn patients; evening dosing more effective",
              sideEffects: "Iris pigmentation change (permanent brownish discolouration — warn before prescribing), increased eyelash growth (hypertrichosis), conjunctival hyperaemia, periorbital skin darkening, macular oedema (aphakic/pseudophakic eyes)",
              contraindications: "Aphakic eyes without posterior lens capsule (macular oedema risk); uveitis/anterior segment inflammation; contact lens wearers (instill without lenses — wait 15 min before reinserting)",
              renalDosing: "Not applicable (ophthalmic topical)",
              hepaticDosing: "Not applicable (ophthalmic topical)",
              monitoring: "IOP at 4–6 weeks (response assessment); iris colour at each visit; annual optic disc and visual field; systemic absorption can cause bradycardia — caution with systemic beta-blockers"),

        .init(name: "Timolol 0.25%/0.5% eye drops (Timoptol)", category: "Ophthalmic — Beta-blocker",
              commonDoses: "1 drop BD (0.25% initially — increase to 0.5% if needed); once-daily formulation (gel) available",
              route: "Ophthalmic (topical)",
              notes: "Open-angle glaucoma; ocular hypertension; reduces aqueous humour production; systemic absorption occurs — cardiac/respiratory side effects possible despite topical use",
              sideEffects: "Bronchospasm (contraindicated in asthma/COPD), bradycardia, hypotension, masking of hypoglycaemia symptoms, corneal anaesthesia, dry eyes, contact dermatitis",
              contraindications: "Asthma, COPD, severe bradycardia, 2nd/3rd degree AV block, cardiogenic shock; caution in diabetes mellitus (hypoglycaemia masking); use lacrimal punctal occlusion to minimise systemic absorption",
              renalDosing: "Not applicable (topical); however systemic effects accumulate in renal failure",
              hepaticDosing: "Not applicable (topical); systemic effects more pronounced in hepatic impairment",
              monitoring: "IOP; pulse and BP (systemic absorption); respiratory function; advise nasolacrimal occlusion after instillation to reduce systemic absorption"),

        .init(name: "Prednisolone sodium phosphate 0.5% eye drops", category: "Ophthalmic Corticosteroid",
              commonDoses: "1 drop QDS–hourly (acute inflammation); taper as response occurs; post-operative: QDS × 4 weeks then taper",
              route: "Ophthalmic (topical)",
              notes: "Post-operative ocular inflammation (cataract/vitreoretinal surgery); uveitis; anterior segment inflammation; DO NOT use for infective conjunctivitis (worsens); ophthalmologist supervision for prolonged use",
              sideEffects: "Raised IOP (steroid-induced glaucoma — especially with prolonged use), posterior subcapsular cataract (prolonged use), secondary infections (masked symptoms), delayed wound healing, corneal thinning",
              contraindications: "Ocular viral infections (herpes simplex — dangerous, fungal, bacterial — unless covered), untreated glaucoma (raises IOP), acute purulent conjunctivitis; avoid without ophthalmologist supervision beyond 2 weeks",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "IOP at 2–4 weeks (steroid responders can develop dangerous rise); slit-lamp exam; clinical response; taper slowly; ophthalmology follow-up"),

        .init(name: "Hypromellose 0.3% eye drops (artificial tears)", category: "Ophthalmic — Lubricant",
              commonDoses: "1–2 drops PRN as needed (typically 4–6× daily or more); no maximum dose",
              route: "Ophthalmic (topical)",
              notes: "Dry eye syndrome (keratoconjunctivitis sicca); post-operative lubrication; preservative-free formulations preferred for frequent use or contact lens wear; safe in pregnancy",
              sideEffects: "Transient blurred vision immediately after instillation; preservative (benzalkonium chloride) toxicity with very frequent use (prefer preservative-free unit doses)",
              contraindications: "Hypersensitivity to components; preservative-containing drops: avoid contact lens wear (wait 15 min)",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "Use preservative-free formulation if >4× daily or contact lens wear; Schirmer's test for dry eye diagnosis"),

        // ─── NEBULISER MEDICATIONS — Additional ───────────────────────────────
        .init(name: "Tobramycin nebulised (TOBI/Bramitob)", category: "Antibiotic — Inhaled Aminoglycoside",
              commonDoses: "300 mg nebulised BD (28 days on, 28 days off cycling); administer with jet nebuliser (not ultrasonic)",
              route: "Nebulised",
              notes: "Cystic fibrosis with chronic Pseudomonas aeruginosa colonisation; not for acute infections; alternating cycle reduces resistance emergence; use after airway clearance physiotherapy",
              sideEffects: "Tinnitus/hearing loss (monitor audiology), voice alteration/dysphonia, bronchospasm (pre-treat with SABA), cough, sputum increase (initially), renal toxicity (minimal with inhalation — less than IV)",
              contraindications: "Hypersensitivity to aminoglycosides; monitor for ototoxicity; not for acute exacerbations",
              renalDosing: "Minimal systemic absorption with inhalation; however, systemic levels should be checked if renal impairment pre-exists",
              hepaticDosing: "Not applicable (inhaled route)",
              monitoring: "Audiometry and vestibular function before each cycle and at 6 months; renal function and drug levels if impairment; lung function (FEV1)"),

        .init(name: "Ipratropium/salbutamol (Combivent)", category: "Bronchodilator — Combined SAMA+SABA",
              commonDoses: "1 unit dose (2.5 mL: salbutamol 2.5 mg + ipratropium 500 mcg) nebulised TDS–QDS; MDI: 2 puffs QDS",
              route: "Nebulised/MDI",
              notes: "Acute COPD exacerbation; severe acute asthma (add ipratropium to salbutamol); greater bronchodilation than either agent alone; more convenient than separate nebulisation",
              sideEffects: "Tachycardia, tremor, palpitations, hypokalaemia (salbutamol component), dry mouth, urinary retention (ipratropium component), paradoxical bronchospasm",
              contraindications: "Hypersensitivity to soya lecithin (MDI — contains soya); narrow-angle glaucoma (protect eyes during nebulisation); urinary retention (BPH)",
              renalDosing: "No dose adjustment",
              hepaticDosing: "No dose adjustment",
              monitoring: "SpO2 and respiratory rate; HR (tachycardia); serum potassium (hypokalaemia risk — especially with concurrent steroids/diuretics/xanthines)"),

        .init(name: "Dornase alfa (Pulmozyme/DNase)", category: "Mucolytic — Recombinant DNase",
              commonDoses: "2.5 mg nebulised OD (CF); some patients benefit from BD dosing; use jet nebuliser",
              route: "Nebulised",
              notes: "Cystic fibrosis (reduces sputum viscosity — cleaves extracellular DNA from neutrophils); use after airway clearance physiotherapy; keep refrigerated (2–8°C); bring to room temperature before use",
              sideEffects: "Voice alteration, pharyngitis, chest pain (pleuritic), rash, conjunctivitis, rhinitis; generally well tolerated",
              contraindications: "Hypersensitivity to dornase alfa or CHO cell-derived products",
              renalDosing: "Not applicable (inhaled — no systemic effect)",
              hepaticDosing: "Not applicable",
              monitoring: "FEV1 and FVC (lung function); pulmonary exacerbation frequency; microbiological cultures"),

        // ─── VACCINES ─────────────────────────────────────────────────────────
        .init(name: "Yellow Fever vaccine (Stamaril)", category: "Vaccine — Live Attenuated",
              commonDoses: "0.5 mL SC single dose (lifelong immunity from 2017 WHO update); booster if at ongoing risk; minimum age 9 months",
              route: "SC",
              notes: "Required for entry to many endemic countries (incl. parts of Caribbean, South/Central America, Africa); administered ONLY at designated Yellow Fever vaccination centres; valid 10 days after vaccination",
              sideEffects: "Injection-site reactions, headache, myalgia, mild fever; viscerotropic disease (rare but potentially fatal — avoid in immunocompromised/elderly/thymus disorders); neurotropic disease (encephalitis — rare in infants)",
              contraindications: "Immunocompromised (HIV CD4 <200, chemotherapy), age <6 months (absolute), 6–9 months (generally avoid), thymus disorders (thymoma, myasthenia), age >60 years (elevated viscerotropic disease risk — weigh risk/benefit), pregnancy (relative — vaccinate if travel unavoidable)",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable; avoid in severe hepatic impairment",
              monitoring: "Observe 30 min post-vaccination (anaphylaxis); issue international certificate of vaccination; record batch number; enquire re thymus/immune status before administration"),

        .init(name: "Hepatitis B vaccine (Engerix-B/HBvaxPRO)", category: "Vaccine — Recombinant",
              commonDoses: "Primary: 3 doses at 0, 1, 6 months (standard); accelerated: 0, 1, 2 months + booster 12 months; rapid: 0, 7, 21 days + booster 12 months (travel). HBvaxPRO 40 mcg for haemodialysis",
              route: "IM (deltoid)",
              notes: "Prevention of hepatitis B; part of childhood immunisation schedule (most countries); occupational (healthcare workers); post-exposure prophylaxis (with HBIG); check anti-HBs at 4–8 weeks post-primary course",
              sideEffects: "Injection-site reactions, mild fever, headache, fatigue; anaphylaxis (rare)",
              contraindications: "Hypersensitivity to yeast or any vaccine component; defer if febrile illness (mild illness not a contraindication)",
              renalDosing: "Standard schedule; however, immunocompromised/CKD patients may need double dose or additional booster (check anti-HBs titre); 40 mcg formulation for haemodialysis patients",
              hepaticDosing: "Not applicable",
              monitoring: "Anti-HBs titre 4–8 weeks after completing primary course (target >10 mIU/mL); repeat 3-dose course if non-responder; annual anti-HBs in haemodialysis patients"),

        .init(name: "Hepatitis A vaccine (Havrix/Avaxim)", category: "Vaccine — Inactivated",
              commonDoses: "Primary: 2 doses at 0 and 6–12 months; single dose gives protection from 2 weeks onwards (14 days before travel)",
              route: "IM (deltoid)",
              notes: "Travellers to endemic areas; post-exposure prophylaxis (within 14 days of exposure); long-lasting immunity after 2-dose course (potentially lifelong after booster); combined with Hep B (Twinrix) available",
              sideEffects: "Injection-site reactions, mild fever, headache, fatigue; anaphylaxis (rare)",
              contraindications: "Hypersensitivity to vaccine components or formaldehyde; defer in febrile illness",
              renalDosing: "No dose adjustment; immunocompromised patients may have reduced immune response",
              hepaticDosing: "Not applicable",
              monitoring: "Serological testing not routine (high seroconversion rate); check if immunocompromised (may need additional dose)"),

        .init(name: "Typhoid vaccine (Typherix/Typhim Vi)", category: "Vaccine — Polysaccharide",
              commonDoses: "0.5 mL IM single dose; booster every 3 years if ongoing exposure. Oral: Vivotif 1 capsule alternate days × 3 doses (give 3 days before travel)",
              route: "IM (injected) / PO (oral live)",
              notes: "Caribbean travel prophylaxis; also relevant to food handlers, laboratory workers; oral vaccine (live) requires refrigeration; oral vaccine reduces adherence to antibiotics after taking",
              sideEffects: "IM: injection-site pain, mild fever, myalgia; oral (live): GI upset (nausea, abdominal pain, diarrhoea)",
              contraindications: "Oral live: immunocompromised, antibiotics within 24h of oral dose, antimalarials (proguanil/mefloquine — reduces efficacy; take ≥3 days apart). IM: hypersensitivity",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "No post-vaccination serology required; oral vaccine — ensure cold chain compliance; spacing of antimalarials"),

        .init(name: "HPV vaccine (Gardasil-9/Cervarix)", category: "Vaccine — Recombinant VLP",
              commonDoses: "9–14 years: 2 doses 6–12 months apart; 15–26 years: 3 doses at 0, 2, 6 months; 27–45 years: shared decision-making",
              route: "IM (deltoid)",
              notes: "Prevention of HPV-related cervical/anal/oropharyngeal/penile/vulval/vaginal cancers and genital warts (Gardasil-9: 9 strains); most effective before sexual debut; males and females",
              sideEffects: "Injection-site reactions (pain, swelling — most common), syncope (post-vaccination — observe 15 min), fever, headache, dizziness",
              contraindications: "Hypersensitivity to yeast (Gardasil) or any component; pregnancy (defer until after — no evidence of harm but not routinely given)",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "Observe 15 min (syncope risk — especially adolescents); no serology required; does not replace cervical screening"),

        .init(name: "Pneumococcal vaccine — Conjugate (Prevenar 13/PCV15/PCV20)", category: "Vaccine — Conjugate",
              commonDoses: "Single dose IM (adults at risk/≥65 yrs); infant schedule varies by national programme (primary 2/3 doses + booster); immunocompromised: 2 doses of PCV13 then PPSV23 (8 weeks later)",
              route: "IM",
              notes: "High-risk adults: asplenia, CKD, immunocompromised, diabetes, chronic liver/heart/lung disease, CSF leaks; post-splenectomy mandatory; may require PPSV23 sequentially",
              sideEffects: "Injection-site reactions, mild fever, myalgia; anaphylaxis (rare)",
              contraindications: "Hypersensitivity to diphtheria toxoid (conjugate carrier); febrile illness (defer)",
              renalDosing: "No dose adjustment; CKD is an indication for vaccination",
              hepaticDosing: "No dose adjustment; cirrhosis/chronic liver disease is an indication",
              monitoring: "High-risk patients: consider anti-pneumococcal antibody levels after vaccination to confirm response; PPSV23 5 years after PCV13 in asplenic patients"),

        .init(name: "Tetanus/Diphtheria/Pertussis (Td/IPV or Tdap — Boostrix/Adacel)", category: "Vaccine — Inactivated Combination",
              commonDoses: "Booster: single dose IM/SC every 10 years (or when wound management requires); pregnancy: 1 dose each pregnancy (27–36 weeks gestation for infant pertussis protection)",
              route: "IM",
              notes: "Tetanus prophylaxis in wounds (assess last vaccination; consider HTIG if >10 years or high-risk wound); pertussis booster in pregnancy (cocoon strategy for neonate); diphtheria prophylaxis",
              sideEffects: "Injection-site reactions (pain, redness, swelling), fever, myalgia, headache; arthus reaction (severe local reaction if too many boosters — avoid giving >1 tetanus-containing vaccine in 5 years)",
              contraindications: "Previous anaphylaxis to this vaccine or components; severe local reaction (arthus) within 10 years: postpone tetanus boosters; encephalopathy within 7 days of pertussis component",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "Document date of all tetanus doses; assess wound characteristics (clean/tetanus-prone); consider HTIG if >10 years since last dose for contaminated wounds; avoid >1 tetanus dose in 5-year window"),

        .init(name: "Meningococcal ACWY vaccine (Menveo/Nimenrix)", category: "Vaccine — Conjugate",
              commonDoses: "Single dose IM (adolescents, travellers, asplenic/complement deficiency); booster every 5 years for ongoing high-risk (asplenia, meningitis belt travel)",
              route: "IM",
              notes: "Meningococcal disease prevention; mandatory for Hajj/Umrah; sub-Saharan Africa travel (meningitis belt); asplenia/complement deficiency; adolescent programme in many countries; add MenB (Bexsero) for comprehensive cover",
              sideEffects: "Injection-site reactions, headache, mild fever, myalgia, fatigue; anaphylaxis (rare)",
              contraindications: "Hypersensitivity to diphtheria toxoid or any component; defer if febrile illness",
              renalDosing: "Not applicable",
              hepaticDosing: "Not applicable",
              monitoring: "Ensure conjugate (not plain polysaccharide) for long-term protection; post-splenectomy: give ≥2 weeks before elective splenectomy if possible; document on patient's record"),
    ]

    // ─── ONCOLOGY / CHEMOTHERAPY ─────────────────────────────────────────────

}
