/**
 * Clinical Vademecum — Chief Complaint matrices for AMISE MedFlow EMR
 *
 * Each entry defines:
 *  - SOCRATES-structured prompts for ChiefComplaintStrip
 *  - Matrix: which tabs are visible for this CC
 *  - DDx, suggested labs, imaging, algorithms, ICD-10 hints
 *
 * This is the single data source that drives the "minimatrices" UX:
 * selecting a CC collapses the UI to only the sections that matter for
 * that presentation, pre-wired with the relevant clinical tools.
 */

import type { Section, EncounterType } from '@/context/AppContext';

// ── Type definitions ──────────────────────────────────────────────────────────

export interface CCPromptField {
  key: string;
  label: string;
  hint: string;
}

export type CCUrgency = 'emergency' | 'urgent' | 'soon' | 'routine';

export type CCCategory =
  | 'Acute Abdomen'
  | 'GI / Hepatobiliary'
  | 'Colorectal / Lower GI'
  | 'Hernia & Abdominal Wall'
  | 'Breast & Endocrine'
  | 'Endoscopy & ERCP'
  | 'Anorectal / Perianal'
  | 'Vascular & Soft Tissue'
  | 'Post-op / Follow-up'
  | 'Other Surgical';

export interface CCTemplate {
  id: string;
  name: string;
  icon: string;
  category: CCCategory;
  rank: number;             // 1 = most common in practice
  urgency: CCUrgency;
  encounterType: EncounterType;
  prompts: CCPromptField[];
  sections: Section[];
  ddx: string[];
  labs: string[];
  imaging: string[];
  algorithms?: string[];    // IDs matching ClinicalAlgorithmPanel tools
  icd10Hint?: string;
  pearl?: string;
}

// ── Reusable section sets ─────────────────────────────────────────────────────

const S_EMERGENCY: Section[] = [
  'triage', 'hpi', 'pmh', 'medications', 'allergies',
  'examination', 'wounds',
  'investigations', 'blood_gas', 'radiology', 'attachments',
  'assessment', 'plan', 'dosing', 'fluid_nutrition',
  'prescriptions', 'progress', 'monitoring',
];

const S_SURGICAL: Section[] = [
  'hpi', 'pmh', 'surgical', 'medications', 'allergies',
  'examination', 'investigations', 'radiology', 'attachments',
  'assessment', 'plan', 'procedures',
  'prescriptions', 'referring_providers',
  'progress', 'monitoring', 'tasks',
];

const S_QUICK: Section[] = [
  'hpi', 'pmh', 'medications', 'allergies',
  'examination', 'assessment', 'plan',
  'prescriptions', 'progress', 'tasks',
];

const S_ENDOSCOPY: Section[] = [
  'hpi', 'pmh', 'surgical', 'medications', 'allergies',
  'investigations', 'procedures', 'attachments',
  'assessment', 'plan', 'prescriptions',
  'referring_providers', 'progress', 'tasks',
];

const S_MALIGNANCY: Section[] = [
  'pmh', 'surgical', 'medications', 'allergies', 'family_hx',
  'examination', 'investigations', 'radiology', 'attachments',
  'assessment', 'plan', 'procedures',
  'referring_providers', 'progress', 'monitoring', 'tasks',
];

const S_URGENT_SURGICAL: Section[] = [
  'triage', 'hpi', 'pmh', 'surgical', 'medications', 'allergies',
  'examination', 'investigations', 'radiology',
  'assessment', 'plan', 'dosing',
  'prescriptions', 'referring_providers', 'progress', 'monitoring',
];

// ── CC Templates (ranked by frequency in practice) ───────────────────────────

export const CC_TEMPLATES: CCTemplate[] = [

  // ══ ACUTE ABDOMEN ═══════════════════════════════════════════════════════════

  {
    id: 'acute_abdominal_pain',
    name: 'Acute abdominal pain',
    icon: '🫃',
    category: 'Acute Abdomen',
    rank: 1,
    urgency: 'urgent',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'site',      label: 'Site & radiation',   hint: 'RUQ · Epigastric · Periumbilical → RIF · LIF · Generalised · Back · Shoulder tip' },
      { key: 'onset',     label: 'Onset',              hint: 'Sudden (perforation) · Gradual (inflammation/ischaemia)' },
      { key: 'duration',  label: 'Duration',           hint: '< 6 hours · 6–24 hours · 1–3 days · > 3 days · Episodic / recurrent' },
      { key: 'character', label: 'Character',          hint: 'Colicky · Constant · Burning · Sharp · Dull ache · Cramping' },
      { key: 'timing',    label: 'Timing & pattern',   hint: 'Continuous · Intermittent / colicky · Post-meal · Nocturnal · Worsening over time' },
      { key: 'severity',  label: 'Severity (0–10)',    hint: '' },
      { key: 'assoc',     label: 'Associated',         hint: 'Nausea · Vomiting · Fever · Jaundice · Anorexia · PR bleeding · Distension · Rigors' },
      { key: 'triggers',  label: 'Aggravating',        hint: 'Movement · Deep breathing · Eating / drinking · Lying flat · Palpation · Coughing' },
      { key: 'relief',    label: 'Relieving',          hint: 'Analgesia · Rest · Nil by mouth · Antacids · Fetal position · Leaning forward · Vomiting' },
      { key: 'lmp',       label: 'LMP / pregnancy',    hint: 'Female: last menstrual period — exclude ectopic' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Acute appendicitis', 'Acute cholecystitis', 'Biliary colic', 'Acute pancreatitis', 'Bowel obstruction', 'Peptic ulcer disease', 'Perforated viscus', 'Renal colic', 'Mesenteric ischaemia', 'Ectopic pregnancy', 'Ovarian torsion', 'Diverticulitis'],
    labs: ['FBC', 'CRP', 'U&E', 'LFTs', 'Amylase / Lipase', 'Lactate', 'Coagulation', 'Group & Screen', 'Urinalysis', 'Serum βHCG'],
    imaging: ['Erect CXR', 'AXR', 'USS abdomen', 'CT abdomen/pelvis (contrast)'],
    icd10Hint: 'R10',
    pearl: 'Do not give analgesia before assessment — myth. Adequate analgesia improves examination accuracy.',
  },
  {
    id: 'acute_appendicitis',
    name: 'Acute appendicitis',
    icon: '⚡',
    category: 'Acute Abdomen',
    rank: 2,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'onset',    label: 'Onset & migration',  hint: 'Periumbilical → RIF — McBurney progression over hours' },
      { key: 'anorexia', label: 'Anorexia / nausea',  hint: 'Classic feature — present in >90%' },
      { key: 'fever',    label: 'Fever',              hint: 'Low grade initially · High fever suggests perforation' },
      { key: 'signs',    label: 'Clinical signs',     hint: "Rovsing's · Psoas · Obturator — retrocaecal / pelvic appendix" },
      { key: 'alvarado', label: 'Alvarado features',  hint: 'Score ≥7 = likely; ≥9 = certain. M-A-N-T-R-E-L-S' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Mesenteric adenitis', 'Ovarian cyst / torsion', 'Ectopic pregnancy', 'Pelvic inflammatory disease', 'Crohn\'s disease (terminal ileitis)', 'Meckel\'s diverticulum', 'Caecal carcinoma', 'Renal colic'],
    labs: ['FBC (leucocytosis)', 'CRP', 'U&E', 'βHCG', 'Urinalysis', 'Amylase', 'Lactate'],
    imaging: ['USS RIF (first-line if equivocal)', 'CT abdomen/pelvis (diagnostic in adults)', 'MRI (pregnancy)'],
    icd10Hint: 'K35',
    pearl: 'Alvarado score ≥7 in a male = immediate surgery. USS first in children/pregnancy. CT is standard in adults.',
  },
  {
    id: 'acute_cholecystitis',
    name: 'Acute cholecystitis',
    icon: '💛',
    category: 'Acute Abdomen',
    rank: 3,
    urgency: 'urgent',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'site',     label: 'Site',              hint: 'RUQ · Epigastric · Radiation to right shoulder tip / scapula' },
      { key: 'onset',    label: 'Onset',             hint: 'After fatty meal · Duration · Previous similar attacks' },
      { key: 'murphy',   label: "Murphy's sign",     hint: 'Inspiratory arrest on deep RUQ palpation' },
      { key: 'fever',    label: 'Fever / rigors',    hint: "Charcot's triad (+ jaundice) = cholangitis" },
      { key: 'jaundice', label: 'Jaundice',          hint: 'CBD stone / Mirizzi — get LFTs urgently' },
    ],
    sections: S_URGENT_SURGICAL,
    ddx: ['Biliary colic', 'Acute cholangitis', 'Choledocholithiasis', 'Pancreatitis', 'Peptic ulcer disease', 'Hepatitis', 'Right lower lobe pneumonia', 'Mirizzi syndrome'],
    labs: ['FBC', 'LFTs (ALP · GGT · Bilirubin)', 'CRP', 'Amylase', 'U&E', 'Coagulation', 'Blood cultures (if febrile)'],
    imaging: ['USS abdomen — gallstones · wall thickening · pericholecystic fluid · CBD diameter', 'CT (if USS equivocal)', 'MRCP (if CBD dilation)'],
    icd10Hint: 'K81.0',
    pearl: 'Tokyo Guidelines 2018: Grade I = early cholecystectomy within 72 h. Grade II–III = initial antibiotics + interval cholecystectomy or percutaneous drainage.',
  },
  {
    id: 'bowel_obstruction',
    name: 'Bowel obstruction',
    icon: '🔴',
    category: 'Acute Abdomen',
    rank: 4,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'onset',    label: 'Onset',                 hint: 'Colicky (SBO) · Gradual (LBO) · Duration · Absolute constipation' },
      { key: 'vomiting', label: 'Vomiting',              hint: 'Bilious (SBO) · Faeculent (late / LBO) · Haematemesis' },
      { key: 'prev',     label: 'Previous abdomen',      hint: 'Prior surgery (adhesions) · Hernia · Malignancy · IBD' },
      { key: 'hernia',   label: 'Hernia check',          hint: 'Inguinal · Femoral · Umbilical — strangulation risk' },
      { key: 'last',     label: 'Last bowel motion / flatus', hint: 'Absolute constipation (complete obstruction)' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Adhesional SBO', 'Hernial obstruction', 'Colorectal malignancy (LBO)', 'Sigmoid volvulus', 'Caecal volvulus', 'Diverticular stricture', 'Ileus', 'Crohn\'s stricture'],
    labs: ['FBC', 'U&E (dehydration)', 'Lactate (ischaemia)', 'LFTs', 'Amylase', 'Group & Screen', 'ABG'],
    imaging: ['Erect CXR (free air)', 'AXR (ladder pattern SBO · coffee bean LBO)', 'CT abdomen/pelvis (diagnostic — identifies cause & level)', 'Water-soluble contrast enema (LBO)'],
    icd10Hint: 'K56',
    pearl: 'CT is now the standard. Drip-and-suck for SBO (NGT + IV fluids). LBO with sigmoid volvulus → rigid sigmoidoscopy and flatus tube first.',
  },
  {
    id: 'perforated_viscus',
    name: 'Perforated viscus',
    icon: '💥',
    category: 'Acute Abdomen',
    rank: 5,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'onset',    label: 'Onset',            hint: 'Sudden onset — board-like rigidity suggests perforation' },
      { key: 'site',     label: 'Site',             hint: 'Epigastric (PUD) · Generalised (delayed presentation)' },
      { key: 'history',  label: 'History',          hint: 'NSAID / steroid use · Known PUD · Diverticular disease · Malignancy' },
      { key: 'sepsis',   label: 'Sepsis signs',     hint: 'Tachycardia · Fever · Hypotension · Peritonism' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Perforated peptic ulcer', 'Perforated diverticular disease', 'Perforated appendicitis', 'Perforated colorectal malignancy', 'Perforated Meckel\'s'],
    labs: ['FBC', 'CRP', 'U&E', 'LFTs', 'Amylase', 'Lactate', 'Coagulation', 'Group & Screen', 'Blood cultures'],
    imaging: ['Erect CXR (free air under diaphragm — 80% sensitive)', 'CT abdomen/pelvis (free air · free fluid · cause)'],
    icd10Hint: 'K25.1',
    pearl: 'Free air under diaphragm = surgery. Start IV antibiotics, IV fluids, analgesia, NGT, urinary catheter immediately.',
  },
  {
    id: 'acute_pancreatitis',
    name: 'Acute pancreatitis',
    icon: '🔥',
    category: 'Acute Abdomen',
    rank: 6,
    urgency: 'urgent',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'onset',    label: 'Onset & radiation',  hint: 'Epigastric → back ("bandlike") · Worse lying flat · Better sitting forward' },
      { key: 'cause',    label: 'Aetiology',          hint: 'Alcohol (how much?) · Gallstones · Hypertriglyceridaemia · Post-ERCP · Drugs' },
      { key: 'vomiting', label: 'Vomiting',           hint: 'Persistent retching without relief' },
      { key: 'severity', label: 'Severity features',  hint: 'Tachycardia · Hypotension · Fever · Grey Turner / Cullen (haemorrhagic)' },
      { key: 'ranson',   label: 'Ranson criteria',    hint: 'Age · WBC · Glucose · LDH · AST at admission; haematocrit · urea · Ca · PO2 · base deficit · fluid sequestration at 48 h' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Perforated peptic ulcer', 'Acute cholecystitis', 'Mesenteric ischaemia', 'Myocardial infarction', 'Aortic dissection', 'Diabetic ketoacidosis'],
    labs: ['Serum amylase / lipase (≥3× ULN)', 'LFTs (gallstone cause)', 'FBC', 'U&E', 'Calcium', 'Glucose', 'Triglycerides', 'CRP', 'LDH', 'ABG'],
    imaging: ['USS abdomen (gallstones · CBD)', 'CT abdomen (contrast-enhanced ≥48 h if severe — Balthazar / CTSI scoring)', 'MRCP if CBD dilation'],
    icd10Hint: 'K85',
    pearl: 'Aggressive IV fluids (250–500 mL/h crystalloid) in first 24 h — most important intervention. MRCP/ERCP within 72 h if biliary aetiology + cholangitis.',
  },
  {
    id: 'strangulated_hernia',
    name: 'Strangulated / irreducible hernia',
    icon: '🔐',
    category: 'Acute Abdomen',
    rank: 7,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'site',     label: 'Site',             hint: 'Inguinal · Femoral (higher strangulation risk) · Umbilical · Incisional · Paraumbilical' },
      { key: 'duration', label: 'Duration',         hint: 'How long irreducible — hours/days matter for viability' },
      { key: 'obstruct', label: 'Obstruction',      hint: 'Vomiting · Absolute constipation · Distension' },
      { key: 'colour',   label: 'Overlying skin',   hint: 'Erythema · Warmth · Tenderness = strangulation' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Incarcerated hernia (no vascular compromise)', 'Strangulated hernia (ischaemia)', 'Obstruction at hernia site', 'Lymphadenopathy (groin)', 'Saphenous varix'],
    labs: ['FBC', 'U&E', 'Lactate', 'Group & Screen', 'Coagulation'],
    imaging: ['USS if unclear diagnosis', 'CT abdomen/pelvis (if obstruction)'],
    icd10Hint: 'K40.30',
    pearl: 'Femoral hernias have the highest strangulation risk — repair within 2 h once strangulation confirmed.',
  },
  {
    id: 'gi_bleed_upper',
    name: 'Upper GI bleed (haematemesis / melaena)',
    icon: '🩸',
    category: 'Acute Abdomen',
    rank: 8,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'character', label: 'Character',        hint: 'Haematemesis (bright / coffee grounds) · Melaena · Haematochezia (brisk UGIB)' },
      { key: 'amount',    label: 'Estimated volume', hint: 'Teaspoons · Cups · Haemodynamic compromise' },
      { key: 'history',   label: 'Risk factors',     hint: 'NSAIDs · Aspirin/anticoagulants · Alcohol · PUD · Varices (cirrhosis)' },
      { key: 'haemodynamic', label: 'Haemodynamics', hint: 'Tachycardia · Hypotension · Syncope · Active shock' },
      { key: 'blatchford', label: 'Blatchford score', hint: 'Hb · Urea · SBP · HR · Melaena · Syncope · Hepatic/cardiac disease' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Peptic ulcer disease', 'Oesophageal varices', 'Mallory-Weiss tear', 'Oesophagitis / GORD', 'Gastric erosions (NSAID)', 'Gastric malignancy', 'Dieulafoy lesion', 'Angiodysplasia'],
    labs: ['FBC (Hb)', 'U&E (elevated urea:creatinine ratio)', 'LFTs', 'Coagulation / INR', 'Group & Crossmatch', 'Lactate', 'ABG'],
    imaging: ['CXR (perforation excluded)', 'OGD within 24 h (Blatchford ≥1) — resuscitate first'],
    icd10Hint: 'K92.0',
    pearl: 'Resuscitate first — target Hb 70–90 g/L (80–100 g/L if ACS or varices). OGD within 24 h; within 12 h if active haemorrhage + haemodynamic instability.',
  },
  {
    id: 'mesenteric_ischaemia',
    name: 'Mesenteric ischaemia',
    icon: '⚠️',
    category: 'Acute Abdomen',
    rank: 9,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'onset',    label: 'Onset',           hint: 'Sudden (embolus) · Gradual (thrombosis) · "Pain out of proportion to examination"' },
      { key: 'risk',     label: 'Risk factors',    hint: 'AF · Recent MI · Peripheral vascular disease · Hypertension · Hypercoagulable state' },
      { key: 'postprand', label: 'Postprandial pain', hint: 'Chronic mesenteric ischaemia — fear of eating · weight loss' },
      { key: 'sepsis',   label: 'Sepsis / shock',  hint: 'Late sign — indicates bowel infarction. High mortality.' },
    ],
    sections: S_EMERGENCY,
    ddx: ['SMA embolism', 'SMA thrombosis', 'Non-occlusive mesenteric ischaemia', 'MVT (mesenteric vein thrombosis)', 'Aortic dissection', 'Acute pancreatitis'],
    labs: ['FBC', 'Lactate (high)', 'ABG (acidosis)', 'U&E', 'LFTs', 'Amylase', 'Coagulation', 'D-dimer', 'Group & Screen'],
    imaging: ['CT mesenteric angiography (diagnostic standard — sensitivity >90%)', 'CXR (exclude perforation)'],
    icd10Hint: 'K55.0',
    pearl: '"Pain out of proportion to physical findings" in a patient with AF or recent MI = mesenteric ischaemia until proven otherwise. Immediate CT angiography.',
  },
  {
    id: 'acute_cholangitis',
    name: 'Acute cholangitis',
    icon: '🟡',
    category: 'Acute Abdomen',
    rank: 10,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'charcot',  label: "Charcot's triad",  hint: 'RUQ pain + Jaundice + Fever — classic triad (all 3 in <50%)' },
      { key: 'reynolds', label: "Reynolds' pentad", hint: '+ Altered consciousness + Shock — severe cholangitis' },
      { key: 'lft',      label: 'LFT pattern',      hint: 'Obstructive: ALP/GGT/bilirubin elevated' },
      { key: 'cause',    label: 'Underlying cause',  hint: 'CBD stones · Biliary stricture · PSC · Malignancy' },
    ],
    sections: S_URGENT_SURGICAL,
    ddx: ['Acute cholecystitis', 'Choledocholithiasis', 'Biliary stricture', 'PSC', 'Cholangiocarcinoma', 'Hepatitis', 'Liver abscess'],
    labs: ['LFTs (bilirubin · ALP · GGT · AST · ALT)', 'FBC (leucocytosis)', 'CRP', 'Blood cultures (x2)', 'Coagulation', 'U&E'],
    imaging: ['USS abdomen (CBD diameter · stones)', 'MRCP (if USS equivocal)', 'CT (if USS non-diagnostic · exclude malignancy)'],
    icd10Hint: 'K83.0',
    pearl: 'Tokyo Guidelines Grade III (Reynolds pentad / organ failure) = urgent ERCP within 12 h + ICU. Antibiotics immediately.',
  },

  // ══ GI / HEPATOBILIARY ═══════════════════════════════════════════════════════

  {
    id: 'biliary_colic',
    name: 'Biliary colic',
    icon: '💛',
    category: 'GI / Hepatobiliary',
    rank: 11,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'onset',   label: 'Onset',          hint: 'After fatty meal · Episodic · Duration (biliary colic = <6 h; cholecystitis = >6 h)' },
      { key: 'site',    label: 'Site',           hint: 'RUQ / epigastric · Radiation right shoulder / back' },
      { key: 'prevep',  label: 'Previous episodes', hint: 'How many · Increasing frequency suggests progression' },
      { key: 'jaundice', label: 'Jaundice', hint: 'Any yellow discolouration — CBD stone?' },
    ],
    sections: S_SURGICAL,
    ddx: ['Acute cholecystitis', 'Choledocholithiasis', 'GORD', 'Peptic ulcer disease', 'IBS', 'Right lower lobe pneumonia'],
    labs: ['LFTs', 'FBC', 'Amylase', 'CRP'],
    imaging: ['USS abdomen (gallstones — sensitivity >95%)'],
    icd10Hint: 'K80.2',
    pearl: 'Symptomatic gallstones = laparoscopic cholecystectomy. Asymptomatic gallstones in general surgery practice do not need routine removal.',
  },
  {
    id: 'obstructive_jaundice',
    name: 'Obstructive jaundice',
    icon: '🟡',
    category: 'GI / Hepatobiliary',
    rank: 12,
    urgency: 'urgent',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'onset',   label: 'Onset',         hint: 'Progressive (malignancy) · Fluctuating (stones)' },
      { key: 'pain',    label: 'Pain',          hint: 'RUQ pain + jaundice (stones) · Painless jaundice (Courvoisier = malignancy)' },
      { key: 'urine',   label: 'Dark urine / pale stools', hint: 'Obstructive pattern' },
      { key: 'weight',  label: 'Weight loss',   hint: 'Malignant jaundice — pancreas / cholangiocarcinoma / ampullary Ca' },
      { key: 'pruritus', label: 'Pruritus',     hint: 'Cholestasis' },
      { key: 'courvoisier', label: "Courvoisier's sign", hint: 'Palpable non-tender gallbladder + jaundice → carcinoma until proven otherwise' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Choledocholithiasis', 'Pancreatic head adenocarcinoma', 'Cholangiocarcinoma', 'Ampullary carcinoma', 'PSC', 'Mirizzi syndrome', 'Hepatitis', 'Biliary stricture (benign)', 'Gallbladder carcinoma'],
    labs: ['LFTs (bilirubin · ALP · GGT · AST · ALT)', 'CA 19-9', 'CEA', 'AFP', 'FBC', 'Coagulation (vit K deficiency)', 'U&E'],
    imaging: ['USS abdomen', 'CT triple-phase abdomen/pelvis', 'MRCP', 'PET-CT (staging)', 'EUS (pancreas head / CBD)'],
    icd10Hint: 'K83.1',
    pearl: 'Painless progressive jaundice + palpable gallbladder (Courvoisier) = malignancy (pancreatic head Ca / ampullary Ca / cholangiocarcinoma) until proven otherwise. Urgent triple-phase CT.',
  },
  {
    id: 'pancreatic_mass',
    name: 'Pancreatic mass / malignancy',
    icon: '🫁',
    category: 'GI / Hepatobiliary',
    rank: 13,
    urgency: 'urgent',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'discovery',  label: 'Discovery',        hint: 'Incidental on imaging · Symptoms (jaundice · weight loss · new DM · back pain)' },
      { key: 'symptoms',   label: 'Symptom complex',  hint: 'Epigastric pain → back · Painless jaundice · Anorexia · Steatorrhoea' },
      { key: 'new_dm',     label: 'New-onset DM',     hint: 'New-onset T2DM in >50 years = pancreatic cancer red flag' },
      { key: 'weight',     label: 'Weight loss',      hint: 'Significant unintentional weight loss over months' },
      { key: 'family',     label: 'Family history',   hint: 'BRCA2 · Lynch syndrome · Peutz-Jeghers · Hereditary pancreatitis' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Pancreatic ductal adenocarcinoma', 'Pancreatic neuroendocrine tumour', 'IPMN (cystic)', 'Ampullary carcinoma', 'Distal cholangiocarcinoma', 'Autoimmune pancreatitis', 'Metastatic disease to pancreas'],
    labs: ['CA 19-9', 'CEA', 'LFTs', 'Amylase', 'FBC', 'U&E', 'Glucose / HbA1c', 'AFP', 'Chromogranin A (NET)'],
    imaging: ['CT pancreatic protocol (triple-phase)', 'MRCP', 'EUS + FNA (tissue diagnosis)', 'PET-CT (staging)', 'Bone scan (mets)'],
    icd10Hint: 'C25',
    pearl: 'EUS-FNA is the preferred tissue biopsy for localised pancreatic mass. Whipple procedure (pancreaticoduodenectomy) is only for resectable head-of-pancreas disease.',
  },
  {
    id: 'dysphagia',
    name: 'Dysphagia',
    icon: '🍽️',
    category: 'GI / Hepatobiliary',
    rank: 14,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'level',        label: 'Level',           hint: 'Solids only → solids + liquids (progressive malignancy) · Intermittent (motility)' },
      { key: 'progression',  label: 'Progression',     hint: 'Progressive (malignancy) · Intermittent (achalasia · stricture) · Sudden onset (foreign body)' },
      { key: 'duration',     label: 'Duration',        hint: 'Weeks (alarming) · Months (structural) · Years (motility)' },
      { key: 'odynophagia',  label: 'Odynophagia',     hint: 'Pain on swallowing — oesophagitis · infective (candida) · malignancy' },
      { key: 'weightloss',   label: 'Weight loss',     hint: 'Significant red flag — oesophageal / GOJ malignancy' },
      { key: 'regurgitation', label: 'Regurgitation',  hint: 'Undigested food (pharyngeal pouch / achalasia) · Acidic (GORD)' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Oesophageal carcinoma', 'GOJ adenocarcinoma', 'Achalasia', 'Oesophageal stricture (peptic)', 'Pharyngeal pouch (Zenker)', 'Oesophageal web / ring', 'Eosinophilic oesophagitis', 'Extrinsic compression', 'Motility disorder'],
    labs: ['FBC (anaemia)', 'LFTs', 'U&E', 'Albumin', 'CEA', 'CA 19-9'],
    imaging: ['OGD (first-line — biopsy)', 'Barium swallow (motility / pharyngeal pouch)', 'CT chest/abdomen (staging)', 'EUS (T-staging)', 'PET-CT (staging)'],
    icd10Hint: 'R13',
    pearl: 'Any progressive dysphagia to solids aged >55 years is oesophageal/GOJ malignancy until proven otherwise. Urgent OGD + biopsies.',
  },
  {
    id: 'gord_heartburn',
    name: 'GORD / heartburn',
    icon: '🔥',
    category: 'GI / Hepatobiliary',
    rank: 15,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'duration',   label: 'Duration',         hint: 'How long · Daily or intermittent' },
      { key: 'triggers',   label: 'Triggers',         hint: 'Postprandial · Lying flat · Alcohol · Fatty food · Pregnancy' },
      { key: 'response',   label: 'PPI response',     hint: 'Complete · Partial · None (consider Barrett\'s / malignancy)' },
      { key: 'alarm',      label: 'Alarm features',   hint: 'Dysphagia · Weight loss · Haematemesis · Anaemia — OGD needed' },
      { key: 'barrettsx',  label: "Barrett's risk",   hint: 'Male · >50 yr · Obese · >5 yr symptoms · White ethnicity' },
    ],
    sections: S_QUICK,
    ddx: ['GORD', 'Barrett\'s oesophagus', 'Peptic ulcer disease', 'Achalasia', 'Eosinophilic oesophagitis', 'Non-cardiac chest pain', 'Hiatal hernia'],
    labs: ['H pylori breath test / stool antigen'],
    imaging: ['OGD (if alarm features or PPI failure ≥4 weeks or Barrett\'s risk factors)'],
    icd10Hint: 'K21',
    pearl: 'Alarm features (dysphagia, weight loss, haematemesis, anaemia) = OGD. NICE: all patients ≥55 with dyspepsia + weight loss = urgent (2-week wait) OGD.',
  },
  {
    id: 'liver_mass',
    name: 'Liver mass / hepatocellular carcinoma',
    icon: '🫀',
    category: 'GI / Hepatobiliary',
    rank: 16,
    urgency: 'urgent',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'discovery',  label: 'Discovery',        hint: 'Surveillance USS (cirrhosis) · Incidental · Symptomatic (RUQ pain · weight loss)' },
      { key: 'liver_dz',   label: 'Liver disease',    hint: 'HBV · HCV · Cirrhosis (alcoholic · NASH) · Haemochromatosis' },
      { key: 'symptoms',   label: 'Symptoms',         hint: 'RUQ pain · Hepatomegaly · Ascites · Weight loss · Jaundice' },
      { key: 'afp',        label: 'AFP level',        hint: 'AFP >400 in cirrhotic patient with mass = HCC (diagnostic)' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Hepatocellular carcinoma (HCC)', 'Cholangiocarcinoma (intrahepatic)', 'Metastatic disease to liver', 'Hepatic adenoma', 'Focal nodular hyperplasia (FNH)', 'Haemangioma', 'Simple cyst', 'Hydatid cyst'],
    labs: ['AFP', 'LFTs', 'Coagulation (Child-Pugh / MELD)', 'HBsAg · anti-HCV', 'FBC', 'CEA', 'CA 19-9'],
    imaging: ['Dynamic 4-phase CT or gadoxetate MRI (LI-RADS scoring)', 'USS (surveillance)', 'Chest CT (staging)'],
    icd10Hint: 'C22.0',
    pearl: 'EASL/AASLD criteria: cirrhotic patient with lesion >1 cm showing arterial enhancement + washout on CT/MRI = HCC (no biopsy needed). MELD-Na for transplant assessment.',
  },

  // ══ COLORECTAL / LOWER GI ════════════════════════════════════════════════════

  {
    id: 'colorectal_cancer',
    name: 'Colorectal malignancy',
    icon: '🔵',
    category: 'Colorectal / Lower GI',
    rank: 17,
    urgency: 'urgent',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'symptoms',   label: 'Presenting symptoms', hint: 'Rectal bleeding · Change in bowel habit · Weight loss · Abdominal mass · Iron deficiency anaemia' },
      { key: 'duration',   label: 'Duration',            hint: 'How long — weeks to months' },
      { key: 'family',     label: 'Family history',      hint: 'Lynch syndrome · FAP · CRC in first-degree relative <50 years' },
      { key: 'surveillance', label: 'Previous colonoscopy', hint: 'Any polyps removed — when · histology · risk stratification' },
      { key: 'staging',    label: 'Staging symptoms',    hint: 'Weight loss · Bone pain · Hepatomegaly (metastatic)' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Colorectal adenocarcinoma', 'Rectal carcinoma', 'Diverticular disease', 'IBD', 'Haemorrhoids', 'Colonic polyp (adenoma)', 'Anal carcinoma'],
    labs: ['FBC (iron deficiency anaemia)', 'CEA', 'LFTs', 'U&E', 'CA 19-9', 'Coagulation'],
    imaging: ['Colonoscopy + biopsy (diagnostic)', 'CT chest/abdomen/pelvis (staging — TNM)', 'MRI pelvis (rectal cancer — T-staging · CRM)', 'PET-CT (metastatic / recurrence)', 'USS liver (mets)'],
    icd10Hint: 'C18',
    pearl: 'MDT discussion mandatory before treatment. Low rectal cancer: MRI identifies CRM status — predicts R0 resection. APER vs LAR vs TEM depends on tumour level and sphincter function.',
  },
  {
    id: 'rectal_bleeding',
    name: 'Rectal bleeding',
    icon: '🩸',
    category: 'Colorectal / Lower GI',
    rank: 18,
    urgency: 'soon',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'colour',   label: 'Colour',          hint: 'Bright red (anorectal) · Dark / mixed with stool (higher origin) · Melaena (upper GI)' },
      { key: 'amount',   label: 'Amount',          hint: 'Spots · Coating stool · Mixed · Profuse (lower GI emergency)' },
      { key: 'pain',     label: 'Pain',            hint: 'Painful (fissure · ischaemia) · Painless (haemorrhoids · Ca · polyp · angiodysplasia)' },
      { key: 'bowel',    label: 'Bowel habit',     hint: 'Constipation · Diarrhoea · Alternating — CRC red flag' },
      { key: 'weight',   label: 'Weight loss',     hint: 'Red flag — colorectal malignancy' },
      { key: 'age_risk', label: 'Age & risk',      hint: '>45 yr or any age with alarm features = colonoscopy' },
    ],
    sections: [...S_QUICK, 'investigations' as Section],
    ddx: ['Haemorrhoids', 'Anal fissure', 'Colorectal carcinoma', 'Diverticular disease', 'Colonic polyp', 'Angiodysplasia', 'IBD', 'Ischaemic colitis', 'Infective colitis'],
    labs: ['FBC (anaemia)', 'Iron studies', 'CEA', 'LFTs', 'Coagulation'],
    imaging: ['Flexible sigmoidoscopy / colonoscopy', 'CT colonography (if colonoscopy not feasible)'],
    icd10Hint: 'K92.1',
    pearl: 'Never attribute rectal bleeding to haemorrhoids without excluding colorectal carcinoma by colonoscopy, especially in >45 years or with alarm features.',
  },
  {
    id: 'change_bowel_habit',
    name: 'Change in bowel habit',
    icon: '🔄',
    category: 'Colorectal / Lower GI',
    rank: 19,
    urgency: 'soon',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'direction', label: 'Direction',     hint: 'Constipation · Diarrhoea · Alternating (IBS vs CRC)' },
      { key: 'duration',  label: 'Duration',      hint: 'How long — any preceding normal bowel habit' },
      { key: 'blood',     label: 'Blood / mucus', hint: 'Amount · Colour · Mixed with stool' },
      { key: 'tenesmus',  label: 'Tenesmus',      hint: 'Incomplete evacuation sensation — rectal lesion' },
      { key: 'weight',    label: 'Weight loss',   hint: 'Unintentional — malignancy until excluded' },
    ],
    sections: [...S_QUICK, 'investigations' as Section],
    ddx: ['Colorectal carcinoma', 'IBS', 'IBD', 'Diverticular disease', 'Coeliac disease', 'Thyroid disease', 'Medication effect'],
    labs: ['FBC', 'CRP / ESR', 'CEA', 'Thyroid function', 'Coeliac screen', 'Stool culture (if diarrhoea)'],
    imaging: ['Colonoscopy (gold standard for ≥45 yr or alarm features)', 'CT colonography'],
    icd10Hint: 'K59',
    pearl: 'Any change in bowel habit >6 weeks in patients ≥45 years requires colonoscopy to exclude CRC.',
  },
  {
    id: 'diverticular_disease',
    name: 'Diverticular disease / diverticulitis',
    icon: '💢',
    category: 'Colorectal / Lower GI',
    rank: 20,
    urgency: 'urgent',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'site',      label: 'Site of pain',    hint: 'LIF (sigmoid most common) · RIF (right-sided diverticulitis — can mimic appendicitis)' },
      { key: 'fever',     label: 'Fever',           hint: 'Inflammatory feature' },
      { key: 'changed_bh', label: 'Bowel habit change', hint: 'Constipation · Ribbon stool (obstruction)' },
      { key: 'haematuria', label: 'Haematuria',     hint: 'Colovesical fistula' },
      { key: 'cxr_us',    label: 'Prior episodes',  hint: 'Hinchey grade (previous attacks) — Hinchey IIb+ = surgical risk' },
    ],
    sections: S_SURGICAL,
    ddx: ['Acute diverticulitis', 'Colovesical fistula', 'Diverticular perforation (Hinchey grade)', 'CRC complicating diverticular disease', 'Appendicitis', 'IBD', 'Ovarian pathology'],
    labs: ['FBC', 'CRP', 'U&E', 'Blood cultures (if febrile)'],
    imaging: ['CT abdomen/pelvis (Hinchey grading · free air · abscess)', 'USS (if mild · abscess)'],
    icd10Hint: 'K57',
    pearl: 'Hinchey III/IV (purulent/faecal peritonitis) = emergency Hartmann\'s procedure or laparoscopic washout ± resection. Hinchey I/II = IV antibiotics ± CT-guided drainage.',
  },
  {
    id: 'ibd_surgical',
    name: 'Inflammatory bowel disease (surgical)',
    icon: '🌿',
    category: 'Colorectal / Lower GI',
    rank: 21,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'diagnosis',  label: 'Diagnosis',         hint: 'Crohn\'s / UC / indeterminate colitis · Year of diagnosis' },
      { key: 'indication', label: 'Surgical indication', hint: 'Perforation · Obstruction · Fistula · Malignancy · Dysplasia · Medically refractory · Toxic megacolon' },
      { key: 'meds',       label: 'Current medications', hint: 'Biologics (infliximab · adalimumab) · Steroids · Immunosuppressants — peroperative risk' },
      { key: 'prev_surg',  label: 'Previous surgery',  hint: 'Resections — bowel length remaining · Short bowel syndrome risk' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Crohn\'s disease (fistulising · stricturing · penetrating)', 'Ulcerative colitis (pancolitis · proctitis)', 'Toxic megacolon', 'Colorectal malignancy in IBD'],
    labs: ['FBC', 'CRP', 'ESR', 'Albumin', 'U&E', 'LFTs', 'Iron studies', 'B12 / folate', 'Coagulation'],
    imaging: ['CT abdomen/pelvis (acute / fistula / obstruction)', 'MRI pelvis (perianal Crohn\'s)', 'Colonoscopy (quiescent phase)'],
    icd10Hint: 'K50',
    pearl: 'Stop anti-TNF biologics ≥8 weeks pre-elective surgery. Rectal-sparing in UC with ileal pouch-anal anastomosis (IPAA = J-pouch) when technically feasible.',
  },

  // ══ HERNIA & ABDOMINAL WALL ══════════════════════════════════════════════════

  {
    id: 'inguinal_hernia',
    name: 'Inguinal / groin hernia',
    icon: '🦵',
    category: 'Hernia & Abdominal Wall',
    rank: 22,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'side',   label: 'Side',          hint: 'R / L · Bilateral' },
      { key: 'type',   label: 'Type',          hint: 'Inguinal (above inguinal ligament) · Femoral (below — higher risk in female)' },
      { key: 'reduc',  label: 'Reducibility',  hint: 'Reducible · Irreducible · Painful (obstructed) · Skin changes (strangulated)' },
      { key: 'onset',  label: 'Onset',         hint: 'Sudden · Gradual · Precipitant (cough · straining)' },
      { key: 'pain',   label: 'Pain',          hint: 'Aching on exertion · At rest · Sharp (nerve entrapment)' },
    ],
    sections: S_QUICK,
    ddx: ['Direct inguinal hernia', 'Indirect inguinal hernia', 'Femoral hernia', 'Lymphadenopathy', 'Spermatic cord lipoma', 'Hydrocele', 'Undescended testis', 'Varicocele'],
    labs: [],
    imaging: ['USS groin (if diagnosis unclear)', 'CT hernia protocol (bilateral / recurrent / obese)'],
    icd10Hint: 'K40',
    pearl: 'All symptomatic inguinal hernias should be repaired electively (laparoscopic TAPP/TEP preferred). Femoral hernias have higher strangulation risk — expedited repair.',
  },
  {
    id: 'umbilical_hernia',
    name: 'Umbilical / paraumbilical hernia',
    icon: '🔵',
    category: 'Hernia & Abdominal Wall',
    rank: 23,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'size',   label: 'Defect size',   hint: 'Fingerbreadth estimate · Ultrasound measurement' },
      { key: 'reduc',  label: 'Reducibility',  hint: 'Reducible · Irreducible · Tender (obstruction risk)' },
      { key: 'onset',  label: 'Onset',         hint: 'Congenital (child) · Acquired (obesity · pregnancy · ascites · post-op)' },
      { key: 'ascites', label: 'Ascites',       hint: 'Underlying cirrhosis — high anaesthetic risk; recurrence rate high' },
    ],
    sections: S_QUICK,
    ddx: ['Umbilical hernia', 'Paraumbilical hernia', 'Umbilical granuloma', 'Patent urachus'],
    labs: [],
    imaging: ['USS (defect size · content)'],
    icd10Hint: 'K42',
    pearl: 'Defect ≥2 cm in symptomatic adults = repair. Ascitic patients need ascites controlled before hernia repair.',
  },
  {
    id: 'incisional_hernia',
    name: 'Incisional / ventral hernia',
    icon: '🏗️',
    category: 'Hernia & Abdominal Wall',
    rank: 24,
    urgency: 'routine',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'site',    label: 'Site',           hint: 'Midline · Flank · Previous stoma site · Trocar site' },
      { key: 'defect',  label: 'Defect size',    hint: 'Small (<2 cm) · Medium (2–4 cm) · Large (>4 cm) — determines mesh requirement' },
      { key: 'prev',    label: 'Previous repair', hint: 'Recurrence — mesh type · technique' },
      { key: 'sympt',   label: 'Symptoms',        hint: 'Intermittent reduction pain · Bowel symptoms · Bulge size' },
    ],
    sections: S_SURGICAL,
    ddx: ['Incisional hernia', 'Recurrent incisional hernia', 'Trocar site hernia', 'Diastasis recti'],
    labs: [],
    imaging: ['CT abdominal wall (defect dimensions · bowel content · overlap needed for mesh)'],
    icd10Hint: 'K43',
    pearl: 'Laparoscopic IPOM or open component separation with mesh for large defects. Botox injection can facilitate fascial closure in complex abdominal wall reconstruction.',
  },

  // ══ BREAST & ENDOCRINE ═══════════════════════════════════════════════════════

  {
    id: 'breast_lump',
    name: 'Breast lump',
    icon: '🎯',
    category: 'Breast & Endocrine',
    rank: 25,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'site',      label: 'Site',              hint: 'Quadrant · Subareolar · R/L' },
      { key: 'duration',  label: 'Duration',          hint: 'When first noticed · Growing · Fluctuating with cycle' },
      { key: 'character', label: 'Character',         hint: 'Hard · Soft · Mobile · Fixed · Tethered to skin · Irregular' },
      { key: 'discharge', label: 'Nipple discharge',  hint: 'Bloody (malignancy) · Serous · Purulent' },
      { key: 'nodes',     label: 'Axillary nodes',    hint: 'Palpable axillary lymphadenopathy' },
      { key: 'famhx',     label: 'Family history',    hint: 'BRCA1/2 · First-degree relatives — breast / ovarian cancer' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Breast carcinoma', 'Fibroadenoma', 'Fibrocystic change', 'Phyllodes tumour', 'Mastitis / abscess', 'Fat necrosis', 'DCIS', 'Duct ectasia'],
    labs: ['FBC', 'LFTs', 'CA 125 (if ovarian concern)', 'Tumour markers (not routine)'],
    imaging: ['Mammogram + USS (triple assessment)', 'Core needle biopsy (CNB) or FNAC', 'MRI breast (BRCA carriers · equivocal imaging)'],
    icd10Hint: 'N63',
    pearl: 'Triple assessment: clinical examination + mammogram/USS + FNAC or core biopsy. All three must agree. Discordance = excision.',
  },
  {
    id: 'thyroid_nodule',
    name: 'Thyroid nodule / goitre',
    icon: '🔵',
    category: 'Breast & Endocrine',
    rank: 26,
    urgency: 'routine',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'discovery',  label: 'Discovery',        hint: 'Incidental on USS · Self-palpated · Symptomatic (dysphagia · hoarse voice)' },
      { key: 'duration',   label: 'Duration',         hint: 'Long-standing (benign) · Rapid growth (malignancy)' },
      { key: 'compressive', label: 'Compressive symptoms', hint: 'Dysphagia · Hoarseness (RLN) · Dyspnoea (tracheal)' },
      { key: 'function',   label: 'Thyroid function', hint: 'Hyperthyroid (toxic) · Hypothyroid · Euthyroid' },
      { key: 'riskfactors', label: 'Risk factors',    hint: 'Previous head/neck irradiation · Family history MEN2 / thyroid Ca' },
    ],
    sections: S_SURGICAL,
    ddx: ['Benign colloid nodule', 'Follicular adenoma', 'Papillary thyroid carcinoma', 'Follicular carcinoma', 'Medullary thyroid carcinoma (check calcitonin)', 'Anaplastic carcinoma', 'Multinodular goitre', 'Hashimoto\'s thyroiditis'],
    labs: ['TSH / T4 / T3', 'Calcitonin (if MTC suspected)', 'Anti-TPO', 'CEA (if MTC)', 'RET mutation (if MEN2)'],
    imaging: ['USS neck (TIRADS scoring)', 'FNAC / ultrasound-guided CNB (TIRADS 4–5)', 'CT neck/chest (retrosternal extension)', 'Radionuclide scan (if TSH low — cold/hot nodule)'],
    icd10Hint: 'E04',
    pearl: 'TIRADS 4–5 or USS features (microcalcifications · taller-than-wide · irregular margins · hypoechoic) = FNAC. Bethesda VI = thyroidectomy. Calcitonin screening for MTC.',
  },
  {
    id: 'neck_lump',
    name: 'Neck lump',
    icon: '🔵',
    category: 'Breast & Endocrine',
    rank: 27,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'site',      label: 'Site',         hint: 'Anterior / posterior triangle · Midline · Submandibular · Submental · Supraclavicular' },
      { key: 'duration',  label: 'Duration',     hint: 'Tender (reactive / infective) · Painless progressive (malignancy)' },
      { key: 'character', label: 'Character',    hint: 'Hard · Rubbery · Cystic · Pulsatile · Mobile · Fixed to deep structures' },
      { key: 'assoc',     label: 'Associated',   hint: 'Hoarseness · Dysphagia · B symptoms (lymphoma) · Weight loss · Primary site symptoms' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Reactive lymphadenopathy', 'Lymphoma (Hodgkin\'s / NHL)', 'Metastatic SCC (head & neck primary)', 'Thyroid nodule', 'Branchial cyst', 'Cystic hygroma', 'Dermoid cyst', 'Parotid tumour', 'Submandibular salivary gland', 'Carotid body tumour'],
    labs: ['FBC', 'CRP / ESR', 'LDH (lymphoma)', 'EBV / CMV serology', 'FNAC (cytology)'],
    imaging: ['USS neck + FNAC', 'CT neck/chest (staging)', 'PET-CT (lymphoma / unknown primary)', 'MRI neck (soft tissue characterisation)', 'Panendoscopy (exclude primary)'],
    icd10Hint: 'R22.1',
    pearl: 'Supraclavicular lymphadenopathy = Virchow\'s node (Troisier\'s sign) — thoracic/abdominal malignancy. Any neck lump >3 cm or >4 weeks = urgent FNAC.',
  },
  {
    id: 'weight_loss',
    name: 'Unexplained weight loss',
    icon: '⚖️',
    category: 'Other Surgical',
    rank: 28,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'amount',   label: 'Amount',       hint: 'kg over what time period · >5% of body weight = significant' },
      { key: 'anorexia', label: 'Anorexia',     hint: 'Reduced appetite · Early satiety (gastric Ca)' },
      { key: 'gi',       label: 'GI symptoms',  hint: 'Dysphagia · Abdominal pain · Bowel habit change · PR bleeding' },
      { key: 'systemic', label: 'B symptoms',   hint: 'Fever · Night sweats · Fatigue (lymphoma / TB)' },
      { key: 'risk',     label: 'Risk factors',  hint: 'Smoking · Alcohol · Family history · Previous malignancy' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Upper GI malignancy', 'Colorectal carcinoma', 'Lymphoma', 'Pancreatic cancer', 'Lung cancer', 'Hyperthyroidism', 'Diabetes', 'Addison\'s disease', 'TB', 'HIV', 'Depression'],
    labs: ['FBC', 'CRP / ESR', 'U&E', 'LFTs', 'TFTs', 'CEA', 'CA 19-9', 'AFP', 'PSA', 'CA 125', 'LDH', 'SPEP', 'HIV', 'TB screening'],
    imaging: ['CT chest/abdomen/pelvis (staging / primary identification)', 'OGD + colonoscopy', 'PET-CT (if CT negative)'],
    icd10Hint: 'R63.4',
    pearl: 'A red flag is unintentional loss >5% over 6–12 months — systematic workup mandatory. Start with CT chest/abdomen/pelvis + tumour markers + OGD/colonoscopy.',
  },

  // ══ ENDOSCOPY & ERCP ════════════════════════════════════════════════════════

  {
    id: 'ogd_diagnostic',
    name: 'OGD (diagnostic upper endoscopy)',
    icon: '🔭',
    category: 'Endoscopy & ERCP',
    rank: 29,
    urgency: 'soon',
    encounterType: 'endoscopy',
    prompts: [
      { key: 'indication', label: 'Indication',      hint: 'Dysphagia · Upper GI bleed · PPI failure · Anaemia · Surveillance Barrett\'s / oesophageal Ca' },
      { key: 'prev',       label: 'Previous OGD',    hint: 'When · Findings' },
      { key: 'anticoag',   label: 'Anticoagulants',  hint: 'Warfarin · DOAC · Aspirin · Clopidogrel — bridging / hold?' },
      { key: 'allergies',  label: 'Sedation allergies', hint: 'Midazolam · Fentanyl · Propofol' },
    ],
    sections: S_ENDOSCOPY,
    ddx: [],
    labs: ['FBC', 'Coagulation (if therapeutic planned)', 'U&E'],
    imaging: ['OGD procedure + biopsy'],
    icd10Hint: 'Z12.11',
    pearl: 'Nil by mouth ≥6 h (solids) / ≥4 h (clear fluids). Stop aspirin 5 days + clopidogrel 7 days pre-therapeutic OGD.',
  },
  {
    id: 'colonoscopy',
    name: 'Colonoscopy (diagnostic / surveillance)',
    icon: '🔭',
    category: 'Endoscopy & ERCP',
    rank: 30,
    urgency: 'soon',
    encounterType: 'endoscopy',
    prompts: [
      { key: 'indication', label: 'Indication',       hint: 'Rectal bleeding · Change in bowel habit · Polyp surveillance · CRC screening · IBD surveillance' },
      { key: 'prev',       label: 'Previous colonoscopy', hint: 'When · Findings · Bowel prep adequacy (BBPS score)' },
      { key: 'anticoag',   label: 'Anticoagulants',   hint: 'Hold per protocol — polypectomy risk' },
      { key: 'prep',       label: 'Bowel prep',       hint: 'Split-dose PEG · Sodium picosulphate · Low-residue diet' },
    ],
    sections: S_ENDOSCOPY,
    ddx: [],
    labs: ['FBC', 'Coagulation (if polypectomy planned)', 'U&E'],
    imaging: ['Colonoscopy'],
    icd10Hint: 'Z12.11',
    pearl: 'BSG 2020: high-quality colonoscopy requires BBPS ≥6 and adenoma detection rate >25% in population screening.',
  },
  {
    id: 'ercp_stones',
    name: 'ERCP — choledocholithiasis',
    icon: '⚡',
    category: 'Endoscopy & ERCP',
    rank: 31,
    urgency: 'urgent',
    encounterType: 'endoscopy',
    prompts: [
      { key: 'indication', label: 'Indication',   hint: 'CBD stones on USS/MRCP · Cholangitis · Post-cholecystectomy bile leak' },
      { key: 'cbd_size',   label: 'CBD diameter', hint: 'USS or MRCP measured CBD diameter (>8 mm suspicious)' },
      { key: 'lft',        label: 'LFT pattern',  hint: 'ALP/GGT/bilirubin elevation — obstructive pattern' },
      { key: 'cholangitis', label: 'Cholangitis',  hint: 'Tokyo severity grade — timing of ERCP (Grade III = emergent)' },
    ],
    sections: S_ENDOSCOPY,
    ddx: [],
    labs: ['LFTs', 'FBC', 'Coagulation', 'Amylase (pre + 4 h post-ERCP)'],
    imaging: ['MRCP (pre-ERCP road map)', 'USS abdomen', 'EUS (if equivocal)'],
    icd10Hint: 'K80.5',
    pearl: 'Post-ERCP pancreatitis (3–5%) is the commonest complication. Rectal indomethacin 100 mg pre-procedure reduces risk. Consider prophylactic pancreatic duct stent if high risk.',
  },
  {
    id: 'ercp_stricture',
    name: 'ERCP — biliary stricture',
    icon: '🔭',
    category: 'Endoscopy & ERCP',
    rank: 32,
    urgency: 'urgent',
    encounterType: 'endoscopy',
    prompts: [
      { key: 'cause',      label: 'Aetiology',      hint: 'Malignant (CCA · pancreatic Ca) · Benign (post-op · PSC · IgG4 cholangiopathy)' },
      { key: 'lft',        label: 'LFT pattern',    hint: 'Degree of cholestasis' },
      { key: 'previous',   label: 'Previous stent',  hint: 'Plastic (3 months) · Metal (SEMS — malignant, 6–12 months)' },
      { key: 'biopsy',     label: 'Brush cytology',  hint: 'Planned — sensitivity ~50% for malignant stricture' },
    ],
    sections: S_ENDOSCOPY,
    ddx: [],
    labs: ['LFTs', 'CA 19-9', 'CEA', 'IgG4 (PSC/autoimmune)'],
    imaging: ['MRCP', 'CT (staging)', 'EUS + FNA'],
    icd10Hint: 'K83.1',
    pearl: 'Metal stents (SEMS) for unresectable malignant strictures. Plastic stents for benign or pre-resection. Cholangioscopy (SpyGlass) + biopsy for indeterminate strictures.',
  },
  {
    id: 'barrett_surveillance',
    name: "Barrett's oesophagus surveillance",
    icon: '🔭',
    category: 'Endoscopy & ERCP',
    rank: 33,
    urgency: 'routine',
    encounterType: 'endoscopy',
    prompts: [
      { key: 'prev_ogd',   label: 'Previous OGD',      hint: 'When diagnosed · Prague C&M classification · Grade of dysplasia' },
      { key: 'dysplasia',  label: 'Prior dysplasia',    hint: 'Indefinite · LGD (12-monthly) · HGD (endoscopic therapy)' },
      { key: 'reflux',     label: 'Reflux control',     hint: 'On PPI · Symptoms controlled' },
      { key: 'therapy',    label: 'Prior endotherapy',  hint: 'RFA · EMR · Cryotherapy' },
    ],
    sections: S_ENDOSCOPY,
    ddx: [],
    labs: [],
    imaging: ['OGD with Seattle protocol biopsies (4 quadrant every 2 cm throughout Barrett\'s segment)'],
    icd10Hint: 'K22.7',
    pearl: 'BSG 2015: no dysplasia + <3 cm = 3–5 yearly surveillance. ≥3 cm = 2–3 yearly. HGD = EMR + RFA (endoscopic eradication). Confirmed LGD = 6-monthly + consider RFA.',
  },

  // ══ ANORECTAL / PERIANAL ════════════════════════════════════════════════════

  {
    id: 'haemorrhoids',
    name: 'Haemorrhoids',
    icon: '🩹',
    category: 'Anorectal / Perianal',
    rank: 34,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'grade',    label: 'Grade',           hint: 'I (non-prolapse) · II (prolapse with reduction) · III (manual reduction) · IV (irreducible)' },
      { key: 'bleeding', label: 'Bleeding',        hint: 'Bright red · Post-defaecation · Dripping · Amount' },
      { key: 'prolapse', label: 'Prolapse',        hint: 'When does it prolapse — defaecation only · walking' },
      { key: 'pain',     label: 'Pain',            hint: 'Haemorrhoids per se are painless — pain suggests thrombosis · fissure · abscess' },
    ],
    sections: S_QUICK,
    ddx: ['Internal haemorrhoids', 'External haemorrhoids', 'Anal fissure', 'Perianal abscess', 'Rectal prolapse', 'Colorectal malignancy (must exclude)'],
    labs: ['FBC (exclude anaemia)'],
    imaging: ['Flexible sigmoidoscopy / colonoscopy (if ≥45 yr or alarm features)'],
    icd10Hint: 'K64',
    pearl: 'Grade I–II: rubber band ligation. Grade III: banding or haemorrhoidopexy. Grade IV: haemorrhoidectomy. Always colonoscopy if any alarm features.',
  },
  {
    id: 'anal_fissure',
    name: 'Anal fissure',
    icon: '⚡',
    category: 'Anorectal / Perianal',
    rank: 35,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'site',     label: 'Site',            hint: 'Posterior midline (90%) · Anterior midline · Lateral (Crohn\'s · TB · syphilis · HIV)' },
      { key: 'pain',     label: 'Pain',            hint: 'Severe tearing pain during and after defaecation (minutes to hours)' },
      { key: 'bleed',    label: 'Bleeding',        hint: 'Streaking on paper · Dripping' },
      { key: 'chronic',  label: 'Chronic features', hint: 'Sentinel pile · Hypertrophied papilla · Fibrotic base = chronic fissure' },
    ],
    sections: S_QUICK,
    ddx: ['Acute anal fissure', 'Chronic anal fissure', 'Crohn\'s perianal disease', 'Anal ulcer (STI — syphilis · HSV · HIV)'],
    labs: [],
    imaging: ['Flexible sigmoidoscopy (if lateral or atypical)'],
    icd10Hint: 'K60.0',
    pearl: 'Lateral fissure = secondary cause until proven otherwise (Crohn\'s / STI). GTN 0.4% or diltiazem 2% cream first-line (chronic). Botox injection. LIS (lateral internal sphincterotomy) if medical failure.',
  },
  {
    id: 'perianal_abscess',
    name: 'Perianal abscess / fistula',
    icon: '🔴',
    category: 'Anorectal / Perianal',
    rank: 36,
    urgency: 'urgent',
    encounterType: 'office_procedure',
    prompts: [
      { key: 'site',    label: 'Site',           hint: 'Perianal · Ischiorectal · Inter-sphincteric · Supralevator · Horseshoe' },
      { key: 'duration', label: 'Duration',      hint: 'Hours to days · Recurrent (suggests fistula)' },
      { key: 'fistula', label: 'External opening', hint: 'External fistula opening — track (Goodsall\'s rule)' },
      { key: 'crohns',  label: "Crohn's screen",  hint: 'Diarrhoea · Abdominal symptoms — perianal disease in 25% of Crohn\'s' },
    ],
    sections: [...S_QUICK, 'investigations' as Section],
    ddx: ['Perianal abscess', 'Ischiorectal abscess', 'Supralevator abscess', 'Anal fistula (inter-sphincteric · trans-sphincteric · suprasphincteric · extrasphincteric)', 'Crohn\'s perianal disease', 'Hidradenitis suppurativa'],
    labs: ['FBC', 'CRP', 'Blood glucose (diabetes)'],
    imaging: ['MRI pelvis (fistula mapping — Parks classification)', 'EUS (sphincter anatomy)'],
    icd10Hint: 'K61',
    pearl: 'Abscess = incision and drainage urgently. Fistula track: simple = lay-open / fistulotomy; complex (involves sphincter) = seton placement ± advancement flap.',
  },
  {
    id: 'pilonidal_disease',
    name: 'Pilonidal disease',
    icon: '🩹',
    category: 'Anorectal / Perianal',
    rank: 37,
    urgency: 'routine',
    encounterType: 'office_procedure',
    prompts: [
      { key: 'presentation', label: 'Presentation', hint: 'Acute abscess (fluctuant · tender) · Recurrent · Chronic sinus · Post-op' },
      { key: 'pits',         label: 'Pits',         hint: 'Midline natal cleft pits — number · secondary openings' },
      { key: 'prev',         label: 'Previous surgery', hint: 'Prior incision/drainage · Excision technique — recurrence' },
    ],
    sections: S_QUICK,
    ddx: ['Pilonidal abscess', 'Pilonidal sinus (chronic)', 'Perianal abscess', 'Hidradenitis suppurativa'],
    labs: [],
    imaging: [],
    icd10Hint: 'L05',
    pearl: 'Acute abscess: incision and drainage (not excision). Chronic sinus: excision. Off-midline (Karydakis/Bascom) procedures have lower recurrence than midline excision.',
  },

  // ══ VASCULAR & SOFT TISSUE ═══════════════════════════════════════════════════

  {
    id: 'varicose_veins',
    name: 'Varicose veins',
    icon: '🫀',
    category: 'Vascular & Soft Tissue',
    rank: 38,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'symptoms',   label: 'Symptoms',        hint: 'Aching · Heaviness · Swelling · Cramps · Itching · Thrombophlebitis' },
      { key: 'distribution', label: 'Distribution', hint: 'GSV (medial) · SSV (posterior) · Pattern · Recurrent (prev surgery)' },
      { key: 'skin',       label: 'Skin changes',    hint: 'Lipodermatosclerosis · Haemosiderin · Active / healed ulcer (CEAP C5/C6)' },
      { key: 'dvt',        label: 'DVT history',     hint: 'Prior DVT — deep system patency' },
    ],
    sections: S_QUICK,
    ddx: ['Primary varicose veins (GSV/SSV incompetence)', 'Secondary VV (post-DVT)', 'Recurrent varicose veins', 'Pelvic congestion syndrome'],
    labs: [],
    imaging: ['Duplex USS (reflux mapping — GSV/SSV/perforator incompetence)'],
    icd10Hint: 'I83',
    pearl: 'NICE NG168: EVLA or RFA first-line for GSV truncal incompetence (not foam sclerotherapy as first-line). Foam sclerotherapy for residual/recurrent veins.',
  },
  {
    id: 'skin_lesion',
    name: 'Skin lesion',
    icon: '🔵',
    category: 'Vascular & Soft Tissue',
    rank: 39,
    urgency: 'soon',
    encounterType: 'office_procedure',
    prompts: [
      { key: 'site',      label: 'Site',             hint: 'Sun-exposed area (SCC · BCC · melanoma) vs. trunk/back' },
      { key: 'duration',  label: 'Duration',         hint: 'Long-standing (benign) · Recent · Growing · Bleeding' },
      { key: 'character', label: 'Character',        hint: 'ABCDE: Asymmetry · Border · Colour · Diameter >6 mm · Evolution' },
      { key: 'famhx',     label: 'Family history',   hint: 'Melanoma · Atypical mole syndrome · Skin malignancy' },
      { key: 'risk',      label: 'UV exposure / fair skin', hint: 'Fitzpatrick type · Prior skin cancer · Immunosuppression' },
    ],
    sections: S_QUICK,
    ddx: ['Melanoma', 'Squamous cell carcinoma', 'Basal cell carcinoma', 'Sebaceous cyst', 'Seborrhoeic keratosis', 'Dermatofibroma', 'Lipoma', 'Pyogenic granuloma', 'Kaposi sarcoma'],
    labs: ['Sentinel node biopsy (melanoma ≥T1b)'],
    imaging: ['Dermoscopy', 'Wide local excision + histology (diagnostic + therapeutic)', 'CT chest/abdomen/pelvis (staging for melanoma)'],
    icd10Hint: 'L98.9',
    pearl: 'Any pigmented lesion with ABCDE features = excision biopsy. Melanoma staging: Breslow thickness + sentinel node biopsy (>T1b). 1 cm margin for T1, 2 cm for T2–T4.',
  },
  {
    id: 'soft_tissue_mass',
    name: 'Soft tissue mass',
    icon: '🔵',
    category: 'Vascular & Soft Tissue',
    rank: 40,
    urgency: 'soon',
    encounterType: 'office_procedure',
    prompts: [
      { key: 'site',      label: 'Site',            hint: 'Subcutaneous · Deep to fascia (sarcoma risk)' },
      { key: 'size',      label: 'Size',            hint: '> 5 cm or deep to fascia = sarcoma workup' },
      { key: 'character', label: 'Character',       hint: 'Soft (lipoma) · Firm · Hard (fibrosarcoma) · Transilluminates (cyst)' },
      { key: 'duration',  label: 'Duration / growth', hint: 'Rapid growth = sarcoma concern' },
    ],
    sections: S_SURGICAL,
    ddx: ['Lipoma', 'Sebaceous cyst (epidermoid)', 'Ganglion', 'Desmoid tumour', 'Sarcoma (liposarcoma · leiomyosarcoma · STS)'],
    labs: [],
    imaging: ['USS (first-line for superficial)', 'MRI (deep to fascia or >5 cm — sarcoma protocol)', 'Core needle biopsy (sarcoma workup)'],
    icd10Hint: 'M79.89',
    pearl: 'Any deep (below fascia) soft tissue mass > 5 cm = MRI + core needle biopsy before excision. Excision biopsy of a sarcoma can compromise curative surgery.',
  },

  // ══ POST-OP / FOLLOW-UP ═══════════════════════════════════════════════════════

  {
    id: 'postop_wound',
    name: 'Post-op wound concern',
    icon: '🏥',
    category: 'Post-op / Follow-up',
    rank: 41,
    urgency: 'soon',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'procedure', label: 'Procedure & date',   hint: '' },
      { key: 'concern',   label: 'Nature of concern',  hint: 'Erythema · Discharge · Swelling · Dehiscence · Fever · Pain' },
      { key: 'onset',     label: 'Onset post-op',      hint: 'Days post-surgery when problem started' },
      { key: 'systemic',  label: 'Systemic features',  hint: 'Fever · Malaise · Rigors · Nausea' },
    ],
    sections: [...S_QUICK, 'wounds' as Section],
    ddx: ['Surgical site infection (SSI)', 'Seroma', 'Haematoma', 'Dehiscence', 'Anastomotic leak (systemic features)', 'DVT / PE', 'Incisional hernia'],
    labs: ['FBC', 'CRP', 'Wound swab (MC&S)'],
    imaging: ['USS wound (collection)', 'CT abdomen (if deep collection / leak suspected)'],
    icd10Hint: 'T81',
    pearl: 'Wound erythema + fever on day 5–7 = SSI until proven otherwise. Superficial SSI = open wound + antibiotics. Deep or organ-space = CT + IR drainage + antibiotics.',
  },
  {
    id: 'postop_followup',
    name: 'Post-op follow-up (routine)',
    icon: '✅',
    category: 'Post-op / Follow-up',
    rank: 42,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'procedure', label: 'Procedure & date', hint: '' },
      { key: 'recovery',  label: 'Recovery',         hint: 'Tolerating diet · Bowel function · Pain control · Wound status' },
      { key: 'concerns',  label: 'Any concerns',     hint: 'Drain output · Swelling · Fever · Expected vs actual recovery' },
      { key: 'histology', label: 'Histology result', hint: 'Available — discuss findings with patient' },
    ],
    sections: S_QUICK,
    ddx: [],
    labs: ['Review operative specimen histology'],
    imaging: [],
    icd10Hint: 'Z09',
    pearl: 'Review histology results before appointment. Malignancy confirmed = MDT referral; tumour margins + adjuvant therapy discussion.',
  },
  {
    id: 'anastomotic_leak',
    name: 'Anastomotic leak / intra-abdominal collection',
    icon: '⚠️',
    category: 'Post-op / Follow-up',
    rank: 43,
    urgency: 'emergency',
    encounterType: 'major_emergency',
    prompts: [
      { key: 'procedure',  label: 'Procedure & date',    hint: '' },
      { key: 'presentation', label: 'Presentation',     hint: 'Fever · Tachycardia · Ileus · Peritonitis · Feculent drain' },
      { key: 'onset',      label: 'Day post-op',         hint: 'Day 5–7 most common for anastomotic leak' },
      { key: 'drain',      label: 'Drain output',        hint: 'Turbid · Feculent · Blood · Volume change' },
    ],
    sections: S_EMERGENCY,
    ddx: ['Anastomotic leak', 'Intra-abdominal abscess', 'Wound infection', 'DVT / PE', 'UTI (catheter-associated)', 'Aspiration pneumonia'],
    labs: ['FBC', 'CRP', 'U&E', 'LFTs', 'Blood cultures', 'Lactate'],
    imaging: ['CT abdomen/pelvis (oral contrast — leak site · collection)', 'CXR'],
    icd10Hint: 'K91.3',
    pearl: 'Grade A leak (radiological only) = conservative + antibiotics. Grade B = CT-guided drainage. Grade C (peritonitis) = return to theatre (Hartmann\'s / washout / diverting stoma).',
  },

  // ══ OTHER SURGICAL ════════════════════════════════════════════════════════════

  {
    id: 'rectal_prolapse',
    name: 'Rectal prolapse',
    icon: '🩸',
    category: 'Colorectal / Lower GI',
    rank: 44,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'type',     label: 'Type',          hint: 'Full-thickness (all rectal wall layers) · Mucosal only · Internal intussusception' },
      { key: 'reducible', label: 'Reducibility', hint: 'Spontaneous reduction · Manual reduction required · Irreducible (emergency)' },
      { key: 'symptoms', label: 'Symptoms',      hint: 'Faecal incontinence · Constipation · Mucous discharge · Bleeding · Difficulty with hygiene' },
      { key: 'obstetric', label: 'Obstetric history', hint: 'Female: vaginal deliveries · Pelvic floor damage' },
    ],
    sections: S_SURGICAL,
    ddx: ['Full-thickness rectal prolapse', 'Mucosal prolapse', 'Haemorrhoids (prolapsed)', 'Solitary rectal ulcer syndrome', 'Internal intussusception'],
    labs: ['FBC'],
    imaging: ['Defaecating proctography / MRI proctogram', 'Anorectal manometry', 'Colonoscopy (if bleeding / cancer excluded)'],
    icd10Hint: 'K62.3',
    pearl: 'Young fit patient: abdominal rectopexy (laparoscopic). Elderly / high-risk: perineal approach (Altemeier/Delorme). Faecal incontinence: concurrent sphincteroplasty or SNS assessment.',
  },
  {
    id: 'diabetic_foot',
    name: 'Diabetic foot / infected foot',
    icon: '🦶',
    category: 'Vascular & Soft Tissue',
    rank: 45,
    urgency: 'urgent',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'site',      label: 'Wound site',      hint: 'Toe · Heel · Sole · Ankle' },
      { key: 'grade',     label: 'Wagner grade',    hint: '0 (intact) · 1 (superficial) · 2 (deep tendon/capsule) · 3 (deep abscess/osteomyelitis) · 4 (forefoot gangrene) · 5 (foot gangrene)' },
      { key: 'infection', label: 'Infection signs', hint: 'Cellulitis · Purulence · Crepitus (gas) · Systemic sepsis' },
      { key: 'vascularity', label: 'Vascular status', hint: 'Foot pulses · ABPI · Prior PVD symptoms / revascularisation' },
      { key: 'dm_control', label: 'DM control',     hint: 'HbA1c · Current insulin / oral hypoglycaemics' },
    ],
    sections: S_URGENT_SURGICAL,
    ddx: ['Diabetic foot infection', 'Charcot foot', 'Osteomyelitis', 'Peripheral arterial disease', 'Venous ulcer', 'Necrotising fasciitis (surgical emergency)'],
    labs: ['FBC', 'CRP', 'ESR', 'U&E', 'HbA1c', 'Blood cultures', 'Wound swab MC&S', 'Bone biopsy (if osteomyelitis)'],
    imaging: ['X-ray foot (osteomyelitis · Charcot)', 'MRI foot (osteomyelitis · soft tissue extent)', 'CT angio / duplex (vascular — revascularisation feasibility)'],
    icd10Hint: 'E11.621',
    pearl: 'Crepitus on palpation + systemic sepsis = necrotising fasciitis — immediate theatre. Osteomyelitis: 6-week IV antibiotics + bone débridement. Ischaemic: revascularise before debride.',
  },
  {
    id: 'nausea_vomiting',
    name: 'Nausea / vomiting',
    icon: '🤢',
    category: 'GI / Hepatobiliary',
    rank: 46,
    urgency: 'soon',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'onset',    label: 'Onset & frequency', hint: 'Acute (days) · Chronic (weeks-months) · Constant · Episodic' },
      { key: 'character',label: 'Character',         hint: 'Bilious (obstruction) · Faeculent · Blood-stained · Undigested food (motility/achalasia)' },
      { key: 'timing',   label: 'Timing re meals',   hint: 'Immediately post-meal · Delayed hours (gastroparesis · obstruction)' },
      { key: 'assoc',    label: 'Associated',        hint: 'Abdominal pain · Fever · Diarrhoea · Weight loss · Headache' },
    ],
    sections: [...S_QUICK, 'investigations' as Section],
    ddx: ['Gastroenteritis', 'Gastroparesis (DM)', 'Bowel obstruction', 'Peptic ulcer disease', 'Acute pancreatitis', 'GORD', 'Pregnancy', 'Intracranial pathology', 'Medication-induced'],
    labs: ['U&E', 'LFTs', 'Amylase', 'βHCG', 'Blood glucose'],
    imaging: ['AXR / USS (if obstruction or abdominal pathology)'],
    icd10Hint: 'R11',
    pearl: 'Vomiting undigested food hours after eating = delayed gastric emptying (gastroparesis) or pyloric obstruction. Nuclear gastric emptying study or barium swallow.',
  },
  {
    id: 'abdominal_mass',
    name: 'Abdominal mass (incidental / new)',
    icon: '🔵',
    category: 'GI / Hepatobiliary',
    rank: 47,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'discovery', label: 'Discovery',        hint: 'Incidental on imaging · Self-palpated · Found on examination' },
      { key: 'site',      label: 'Site',             hint: 'RUQ · Epigastric · LUQ · RIF · LIF · Suprapubic · Central' },
      { key: 'character', label: 'Character',        hint: 'Mobile · Fixed · Hard · Tender · Pulsatile (AAA!)' },
      { key: 'pulsatile', label: 'Pulsatile',        hint: 'Pulsatile EXPANSILE = AAA — urgent vascular assessment' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Colorectal carcinoma', 'Ovarian mass', 'Lymphoma', 'Pancreatic mass', 'Renal mass', 'Splenic mass', 'AAA', 'Metastatic disease'],
    labs: ['FBC', 'CEA', 'CA 19-9', 'CA 125', 'AFP', 'LFTs', 'U&E'],
    imaging: ['USS abdomen', 'CT abdomen/pelvis (contrast)', 'CT angio if pulsatile (AAA)'],
    icd10Hint: 'R19.0',
    pearl: 'Pulsatile expansile abdominal mass = AAA until proven otherwise. Urgent CT angiography and urgent vascular referral.',
  },
  {
    id: 'nipple_discharge',
    name: 'Nipple discharge',
    icon: '🎯',
    category: 'Breast & Endocrine',
    rank: 48,
    urgency: 'soon',
    encounterType: 'surgical_consult',
    prompts: [
      { key: 'character',  label: 'Character',     hint: 'Bloody (malignancy) · Serous · Milky (galactorrhoea) · Purulent · Green-brown (duct ectasia)' },
      { key: 'unilateral', label: 'Unilateral',    hint: 'Unilateral single duct = higher malignancy risk than bilateral' },
      { key: 'spontaneous', label: 'Spontaneous', hint: 'Spontaneous (significant) vs. expressible only' },
      { key: 'assoc',      label: 'Associated',    hint: 'Lump · Skin change · Prolactin medication / pituitary' },
    ],
    sections: S_MALIGNANCY,
    ddx: ['Intraductal papilloma', 'DCIS', 'Breast carcinoma', 'Duct ectasia', 'Galactorrhoea (prolactinoma)', 'Mastitis'],
    labs: ['Prolactin', 'TFTs', 'Cytology of discharge'],
    imaging: ['Mammogram + USS', 'MRI breast (if equivocal)', 'Ductoscopy / galactography'],
    icd10Hint: 'N64.52',
    pearl: 'Bloody unilateral single-duct discharge = surgical exploration (Hadfield\'s / microdochectomy). Always send discharge for cytology.',
  },
  {
    id: 'rectal_prolapse_2',
    name: 'Faecal incontinence',
    icon: '🩹',
    category: 'Colorectal / Lower GI',
    rank: 49,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'type',     label: 'Type',          hint: 'Passive (gas/liquid) · Urge · Mixed' },
      { key: 'cause',    label: 'Aetiology',     hint: 'Obstetric injury · Haemorrhoidectomy · Sphincter trauma · Neurogenic · Rectal prolapse' },
      { key: 'severity', label: 'Wexner score',  hint: '0 = normal · 20 = complete incontinence' },
      { key: 'qol',      label: 'QoL impact',    hint: 'Social isolation · Pad use · Work / relationships' },
    ],
    sections: S_SURGICAL,
    ddx: ['Sphincter defect (obstetric / post-surgical)', 'Neurogenic faecal incontinence', 'Rectal prolapse', 'Rectovaginal fistula', 'IBD', 'Overflow incontinence'],
    labs: [],
    imaging: ['Anorectal manometry', 'EUS / MRI pelvis (sphincter defect characterisation)', 'Defaecating proctogram (prolapse / intussusception)'],
    icd10Hint: 'R15',
    pearl: 'Sacral nerve stimulation (SNS) is first-line for sphincter incontinence without major structural defect. Sphincteroplasty for isolated anterior defect. LARS score post-anterior resection.',
  },
  {
    id: 'other_surgical',
    name: 'Other / general surgical',
    icon: '✏️',
    category: 'Other Surgical',
    rank: 50,
    urgency: 'routine',
    encounterType: 'quick_consult',
    prompts: [
      { key: 'site',      label: 'Site',             hint: 'Central abdomen · RUQ · RIF · LIF · Epigastric · Back · Chest · Groin · Limb · Head · Other' },
      { key: 'onset',     label: 'Onset',            hint: 'Sudden · Gradual · < 24 hours · 1–7 days · > 1 week · Episodic / recurrent' },
      { key: 'character', label: 'Character',        hint: 'Constant · Intermittent · Sharp · Dull ache · Burning · Cramping · Pressure · Throbbing' },
      { key: 'radiation', label: 'Radiation',        hint: 'No radiation · Back · Right shoulder tip · Left arm · Groin · Down leg · Generalised' },
      { key: 'assoc',     label: 'Associated',       hint: 'Nausea · Vomiting · Fever · Diarrhoea · Constipation · Weight loss · Fatigue · Sweating · Bleeding' },
      { key: 'timing',    label: 'Timing / pattern', hint: 'Continuous · Episodic · Post-meal · Nocturnal · Worsening over time · Improving' },
      { key: 'triggers',  label: 'Aggravating',      hint: 'Movement · Eating · Deep breathing · Lying flat · Stress · Palpation' },
      { key: 'relief',    label: 'Relieving',        hint: 'Analgesia · Rest · Heat · Antacids · Fetal position · Nothing helps' },
      { key: 'severity',  label: 'Severity (0–10)',  hint: '1 · 2 · 3 · 4 · 5 · 6 · 7 · 8 · 9 · 10' },
    ],
    sections: S_SURGICAL,
    ddx: [],
    labs: ['As clinically indicated'],
    imaging: ['As clinically indicated'],
    icd10Hint: '',
    pearl: '',
  },
];

// ── Helper functions ──────────────────────────────────────────────────────────

/** Lookup by template ID. */
export function getMatrix(id: string): CCTemplate | undefined {
  return CC_TEMPLATES.find(t => t.id === id);
}

/** Case-insensitive name match — falls back to 'other_surgical'. */
export function getMatrixByName(name: string): CCTemplate {
  const lower = name.toLowerCase();
  return (
    CC_TEMPLATES.find(t => t.name.toLowerCase() === lower) ??
    CC_TEMPLATES.find(t => lower.includes(t.name.toLowerCase().split(' ')[0]!)) ??
    CC_TEMPLATES.find(t => t.id === 'other_surgical')!
  );
}

/** Sorted by rank ascending. */
export const CC_BY_FREQUENCY = [...CC_TEMPLATES].sort((a, b) => a.rank - b.rank);

/** Group by category. */
export const CC_BY_CATEGORY: Record<CCCategory, CCTemplate[]> = CC_TEMPLATES.reduce(
  (acc, t) => {
    if (!acc[t.category]) acc[t.category] = [];
    acc[t.category].push(t);
    return acc;
  },
  {} as Record<CCCategory, CCTemplate[]>,
);
