import React, {useEffect, useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { UploadCloud, CheckCircle, AlertTriangle, FileText, BarChart3, Settings, Receipt, Trash2 } from 'lucide-react';
import './style.css';
const API='/api';
function money(n){return `XCD ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function App(){
 const [tab,setTab]=useState('Dashboard'), [state,setState]=useState(null), [busy,setBusy]=useState(false);
 const load=()=>fetch(API+'/state').then(r=>r.json()).then(setState); useEffect(()=>{load()},[]);
 const expenses=state?.expenses||[], settings=state?.settings||{};
 const approved=expenses.filter(e=>e.status==='approved'), pending=expenses.filter(e=>['pending','ready'].includes(e.status));
 const totals=useMemo(()=>{let business=0,personal=0,capital=0; approved.forEach(e=>{ if(e.is_capital) capital+=+e.amount_xcd; else if(e.classification==='business') business+=+e.amount_xcd; else personal+=+e.amount_xcd; }); return {business,personal,capital,deductible:approved.reduce((s,e)=>s+(+e.deductible_amount||0),0)}},[expenses]);
 async function upload(files){setBusy(true); const fd=new FormData(); [...files].forEach(f=>fd.append('files',f)); await fetch(API+'/upload',{method:'POST',body:fd}); setBusy(false); load(); setTab('Review Inbox');}
 async function updateExpense(id, patch){await fetch(`${API}/expenses/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)}); load();}
 async function bulk(){await fetch(API+'/expenses/bulk-approve-ready',{method:'POST'}); load();}
 if(!state) return <div className="loading">Loading Amise Tax Planner...</div>
 return <div className="app"><aside><h1>Amise<br/><span>Tax Planner</span></h1>{['Dashboard','Upload','Review Inbox','Expenses','Reports','Tax Summary','Settings'].map(x=><button className={tab===x?'on':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside><main><header><div><b>Tax Year</b> {settings.taxYear} · <b>Base</b> {settings.baseCurrency}</div><div className="pill">{pending.length} review items</div></header>{tab==='Dashboard'&&<Dashboard totals={totals} expenses={approved} settings={settings}/>} {tab==='Upload'&&<Upload upload={upload} busy={busy}/>} {tab==='Review Inbox'&&<Review expenses={pending} state={state} update={updateExpense} bulk={bulk}/>} {tab==='Expenses'&&<Expenses expenses={expenses} update={updateExpense}/>} {tab==='Reports'&&<Reports expenses={approved}/>} {tab==='Tax Summary'&&<TaxSummary totals={totals} settings={settings}/>} {tab==='Settings'&&<SettingsPage state={state} reload={load}/>}</main></div>
}
function Dashboard({totals,expenses,settings}){ const months=Array.from({length:12},(_,i)=>expenses.filter(e=>new Date(e.date).getMonth()===i).reduce((s,e)=>s+(+e.deductible_amount||0),0)); const max=settings.maximumLimit||1, cons=settings.conservativeLimit||1, pmax=settings.personalMaximumLimit||1, pcons=settings.personalConservativeLimit||1; return <section><h2><BarChart3/> Dashboard</h2><div className="cards"><Card t="Business deductible" v={money(totals.deductible)}/><Card t="Personal approved" v={money(totals.personal)}/><Card t="Capital held separately" v={money(totals.capital)}/></div><h3>Business expenses</h3><Progress label="Conservative limit" val={totals.deductible} max={cons}/><Progress label="Maximum limit" val={totals.deductible} max={max}/><h3>Personal allowances</h3><Progress label="Conservative limit" val={totals.personal} max={pcons}/><Progress label="Maximum limit" val={totals.personal} max={pmax}/><h3>Monthly breakdown</h3><div className="months">{months.map((m,i)=><div key={i}><span>{new Date(2026,i,1).toLocaleString('default',{month:'short'})}</span><b>{money(m)}</b></div>)}</div></section>}
function Card({t,v}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function Progress({label,val,max}){let p=Math.min(100,Math.round((val/max)*100)); return <div className="progress"><div><b>{label}</b><span>{money(val)} / {money(max)} · {p}%</span></div><i><em style={{width:p+'%'}}/></i></div>}
function Upload({upload,busy}){return <section><h2><UploadCloud/> Upload</h2><label className="drop"><input type="file" multiple accept="image/*,.heic,.pdf" onChange={e=>upload(e.target.files)}/><UploadCloud size={50}/><b>Select up to 20+ receipt photos, screenshots, HEIC, files, or PDFs</b><span>Each document becomes a Review Inbox card before posting.</span></label>{busy&&<p className="notice">Extracting documents...</p>}<EmailStub/></section>}
function EmailStub(){ const [from,setFrom]=useState('receipts@vendor.com'), [total,setTotal]=useState('0'); async function send(){ await fetch(API+'/email-ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from,total,body:'Forwarded receipt body'})}); location.reload();} return <div className="panel"><h3>Email forwarding MVP test</h3><input value={from} onChange={e=>setFrom(e.target.value)}/><input value={total} onChange={e=>setTotal(e.target.value)} placeholder="Total XCD"/><button onClick={send}>Simulate forwarded receipt</button></div> }
function Review({expenses,state,update,bulk}){return <section><h2><Receipt/> Review Inbox</h2><button onClick={bulk}>Bulk approve all Ready</button><div className="grid">{expenses.map(e=><ReviewCard key={e.id} e={e} state={state} update={update}/>)}</div></section>}
function ReviewCard({e,state,update}){const doc=state.documents.find(d=>d.id===e.source_document_id); const [x,setX]=useState(e); const needs=e.status==='pending'||e.is_capital||e.duplicate||e.confidence<.75; const cats=state.settings.categories[x.classification==='personal'?'personal':'business']; return <div className={'review '+(needs?'needs':'ready')}><div className="thumb">{doc?.file_url?<a href={doc.file_url} target="_blank"><FileText/></a>:<FileText/>}</div><b>{e.vendor}</b><small>{needs?'Needs review':'Ready'} · confidence {Math.round((e.confidence||0)*100)}%</small>{e.duplicate&&<p className="warn">Duplicate detected</p>}{e.near_duplicate&&<p className="warn">Near match detected</p>}{e.is_capital&&<p className="warn">Capital item: not counted in deductible total</p>}<input value={x.vendor||''} onChange={ev=>setX({...x,vendor:ev.target.value})}/><input type="date" value={x.date||''} onChange={ev=>setX({...x,date:ev.target.value})}/><select value={x.classification} onChange={ev=>setX({...x,classification:ev.target.value})}><option>business</option><option>personal</option></select><select value={x.category} onChange={ev=>setX({...x,category:ev.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select><select value={x.entity_id} onChange={ev=>setX({...x,entity_id:ev.target.value})}>{state.settings.entities.map(c=><option key={c}>{c}</option>)}</select><div className="row"><input value={x.currency} onChange={ev=>setX({...x,currency:ev.target.value})}/><input type="number" value={x.amount_original} onChange={ev=>setX({...x,amount_original:+ev.target.value})}/></div><p>{money(x.amount_xcd)} · FX {x.fx_rate} on {x.fx_date}</p><label><input type="checkbox" checked={!!x.is_capital} onChange={ev=>setX({...x,is_capital:ev.target.checked})}/> Capital item</label><textarea value={x.notes||''} onChange={ev=>setX({...x,notes:ev.target.value})}/><div className="actions"><button onClick={()=>update(e.id,{...x,status:'approved'})}><CheckCircle/>Approve</button><button onClick={()=>update(e.id,x)}>Save edit</button><button className="danger" onClick={()=>update(e.id,{status:'rejected'})}><Trash2/>Reject</button></div></div>}
function Expenses({expenses, update}){return <section><h2>Expenses</h2><table><thead><tr><th>Date</th><th>Vendor</th><th>Entity</th><th>Category</th><th>Class</th><th>Original</th><th>XCD</th><th>Status</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.vendor}</td><td>{e.entity_id}</td><td>{e.category}</td><td>{e.classification}</td><td>{e.currency} {e.amount_original}</td><td>{money(e.amount_xcd)}</td><td>{e.status}</td></tr>)}</tbody></table></section>}
function Reports({expenses}){return <section><h2>Reports</h2><table><tbody>{Object.entries(expenses.reduce((a,e)=>{a[e.category]=(a[e.category]||0)+(+e.deductible_amount||0);return a},{})).map(([k,v])=><tr key={k}><td>{k}</td><td>{money(v)}</td></tr>)}</tbody></table></section>}
function TaxSummary({totals,settings}){return <section><h2>Tax Summary</h2><Card t="Deductible business expenses" v={money(totals.deductible)}/><Card t="Personal allowances used" v={money(totals.personal)}/><Card t="Capital items excluded" v={money(totals.capital)}/><p className="notice">Capital items are flagged separately for capital allowance review and do not auto-post into the deductible total.</p><h3>Business expenses</h3><Progress label="Conservative" val={totals.deductible} max={settings.conservativeLimit}/><Progress label="Maximum" val={totals.deductible} max={settings.maximumLimit}/><h3>Personal allowances</h3><Progress label="Conservative" val={totals.personal} max={settings.personalConservativeLimit}/><Progress label="Maximum" val={totals.personal} max={settings.personalMaximumLimit}/></section>}
function SettingsPage({state,reload}){const [s,setS]=useState(state.settings); async function save(){await fetch(API+'/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)}); reload();} return <section><h2><Settings/> Settings</h2><label>Business conservative limit<input type="number" value={s.conservativeLimit} onChange={e=>setS({...s,conservativeLimit:+e.target.value})}/></label><label>Business maximum limit<input type="number" value={s.maximumLimit} onChange={e=>setS({...s,maximumLimit:+e.target.value})}/></label><label>Personal conservative limit<input type="number" value={s.personalConservativeLimit} onChange={e=>setS({...s,personalConservativeLimit:+e.target.value})}/></label><label>Personal maximum limit<input type="number" value={s.personalMaximumLimit} onChange={e=>setS({...s,personalMaximumLimit:+e.target.value})}/></label><label>Entities<textarea value={s.entities.join('\n')} onChange={e=>setS({...s,entities:e.target.value.split('\n').filter(Boolean)})}/></label><label>Business categories<textarea value={s.categories.business.join('\n')} onChange={e=>setS({...s,categories:{...s.categories,business:e.target.value.split('\n').filter(Boolean)}})}/></label><label>Personal categories<textarea value={s.categories.personal.join('\n')} onChange={e=>setS({...s,categories:{...s.categories,personal:e.target.value.split('\n').filter(Boolean)}})}/></label><button onClick={save}>Save settings</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
